window.SHOW = {
  id: "NewAlfredHitchcockPresents",
  title: "The New Alfred Hitchcock Presents",
  art: "NewAlfredHitchcockPresents.jpg",
  storageProgressKey: "newalfredhitchcockpresents-progress",
  storageSettingsKey: "newalfredhitchcockpresents-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E00A - Incident In A Small Jail",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E00A Incident In A Small Jail.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E00B - Man From The South",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E00B Man From The South.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E00C - Bang! You're Dead!",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E00C Bang! You're Dead!.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E00D - An Unlocked Window",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E00D An Unlocked Window.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E01 - Revenge",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E01 Revenge.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E02 - Night Fever",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E02 Night Fever.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E03 - Wake Me When I'm Dead",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E03 Wake Me When I'm Dead.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E04 - Final Escape",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E04 Final Escape.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E05 - Night Caller",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E05 Night Caller.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E06 - Method Actor",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E06 Method Actor.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E07 - The Human Interest Story",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E07 The Human Interest Story.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E08 - Breakdown",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E08 Breakdown.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E09 - Prisoners",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E09 Prisoners.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E10 - Gigolo",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E10 Gigolo.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E11 - The Gloating Place",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E11 The Gloating Place.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E12 - The Right Kind Of Medicine",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E12 The Right Kind Of Medicine.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E13 - Beast In View",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E13 Beast In View.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E14 - A Very Happy Ending",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E14 A Very Happy Ending.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E15 - The Canary Sedan",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E15 The Canary Sedan.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E16 - Enough Rope For Two",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E16 Enough Rope For Two.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E17 - The Creeper",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E17 The Creeper.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E18 - Happy Birthday",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E18 Happy Birthday.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E19 - The Jar",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E19 The Jar.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E20 - Deadly Honeymoon",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E20 Deadly Honeymoon.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E21 - Four O'Clock",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E21 Four O'Clock.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S01E22 - Road Hog",
    "The New Alfred Hitchcock Presents (1985)/Season 1/S01E22 Road Hog.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E01 - The Initiation",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E01 The Initiation.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E02 - Conversation Over A Corpse",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E02 Conversation Over A Corpse.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E03 - Man On The Edge",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E03 Man On The Edge.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E04 - If The Shoe Fits",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E04 If The Shoe Fits.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E05 - The Mole",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E05 The Mole.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E06 - Anniversary Gift",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E06 Anniversary Gift.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E07 - The Impatient Patient",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E07 The Impatient Patient.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E08 - When This Man Dies",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E08 When This Man Dies.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E09 - The Specialty Of The House",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E09 The Specialty Of The House.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E10 - The Final Twist",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E10 The Final Twist.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E11 - Tragedy Tonight",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E11 Tragedy Tonight.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E12 - World's Oldest Motive",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E12 World's Oldest Motive.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S02E13 - Deathmate",
    "The New Alfred Hitchcock Presents (1985)/Season 2/S02E13 Deathmate.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E01 - VCR - Very Careful Rape",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E01 VCR - Very Careful Rape.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E02 - Animal Lovers",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E02 Animal Lovers.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E03 - Prism",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E03 Prism.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E04 - A Stolen Heart",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E04 A Stolen Heart.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E05 - Houdini On Channel 4",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E05 Houdini On Channel 4.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E06 - Killer Takes All",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E06 Killer Takes All.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E07 - Hippocritic Oath",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E07 Hippocritic Oath.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E08 - Prosecuter",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E08 Prosecuter.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E09 - If Looks Could Kill",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E09 If Looks Could Kill.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E10 - You'll Die Laughing",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E10 You'll Die Laughing.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E11 - Murder Party",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E11 Murder Party.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E12 - Twist",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E12 Twist.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E13 - User Deadly",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E13 User Deadly.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E14 - Career Move",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E14 Career Move.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E15 - Full Disclosure",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E15 Full Disclosure.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E16 - Kandinsky's Vault",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E16 Kandinsky's Vault.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E17 - There Was A Little Girl...",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E17 There Was A Little Girl....mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E18 - Twisted Sisters",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E18 Twisted Sisters.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E19 - The 13th Floor",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E19 The 13th Floor.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E20 - Hunted Part One",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E20 Hunted Part One.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S03E21 - Hunted Part Two",
    "The New Alfred Hitchcock Presents (1985)/Season 3/S03E21 Hunted Part Two.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E01 - Fogbound",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E01 Fogbound.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E02 - Pen Pal",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E02 Pen Pal.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E03 - Ancient Voices",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E03 Ancient Voices.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E04 - Survival Of The Fittest",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E04 Survival Of The Fittest.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E05 - The Big Spin",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E05 The Big Spin.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E06 - Don't Sell Yourself Short",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E06 Don't Sell Yourself Short.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E07 - For Art's Sake",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E07 For Art's Sake.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E08 - Murder In Mind",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E08 Murder In Mind.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E09 - Mirror Mirror",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E09 Mirror Mirror.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E10 - Skeleton In The Closet",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E10 Skeleton In The Closet.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E11 - In The Driver's Seat",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E11 In The Driver's Seat.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E12 - Driving Under The Influence",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E12 Driving Under The Influence.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E13 - In The Name Of Science",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E13 In The Name Of Science.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E14 - Romance Machine",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E14 Romance Machine.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E15 - Diamonds Aren't Forever",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E15 Diamonds Aren't Forever.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E16 - My Dear Watson",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E16 My Dear Watson.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E17 - Night Creatures",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E17 Night Creatures.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E18 - The Man Who Knew Too Little",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E18 The Man Who Knew Too Little.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E19 - Reunion",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E19 Reunion.mp4"],
  ['the-new-alfred-hitchcock-presents-complete', "THE NEW ALFRED HITCHCOCK PRESENTS - S04E20 - South By Southeast",
    "The New Alfred Hitchcock Presents (1985)/Season 4/S04E20 South By Southeast.mp4"],
],
  durations: {
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E00A Incident In A Small Jail.mp4": 1407,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E00B Man From The South.mp4": 1434,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E00C Bang! You're Dead!.mp4": 1413,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E00D An Unlocked Window.mp4": 1579,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E01 Revenge.mp4": 1428,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E02 Night Fever.mp4": 1425,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E03 Wake Me When I'm Dead.mp4": 1429,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E04 Final Escape.mp4": 1418,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E05 Night Caller.mp4": 1405,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E06 Method Actor.mp4": 1394,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E07 The Human Interest Story.mp4": 1344,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E08 Breakdown.mp4": 1417,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E09 Prisoners.mp4": 1421,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E10 Gigolo.mp4": 1428,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E11 The Gloating Place.mp4": 1419,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E12 The Right Kind Of Medicine.mp4": 1420,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E13 Beast In View.mp4": 1397,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E14 A Very Happy Ending.mp4": 1418,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E15 The Canary Sedan.mp4": 1416,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E16 Enough Rope For Two.mp4": 1424,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E17 The Creeper.mp4": 1423,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E18 Happy Birthday.mp4": 1424,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E19 The Jar.mp4": 1426,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E20 Deadly Honeymoon.mp4": 1428,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E21 Four O'Clock.mp4": 1421,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 1/S01E22 Road Hog.mp4": 1412,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E01 The Initiation.mp4": 1379,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E02 Conversation Over A Corpse.mp4": 1376,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E03 Man On The Edge.mp4": 1373,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E04 If The Shoe Fits.mp4": 1413,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E05 The Mole.mp4": 1396,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E06 Anniversary Gift.mp4": 1410,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E07 The Impatient Patient.mp4": 1378,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E08 When This Man Dies.mp4": 1396,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E09 The Specialty Of The House.mp4": 1407,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E10 The Final Twist.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E11 Tragedy Tonight.mp4": 1401,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E12 World's Oldest Motive.mp4": 1382,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 2/S02E13 Deathmate.mp4": 1398,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E01 VCR - Very Careful Rape.mp4": 1404,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E02 Animal Lovers.mp4": 1376,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E03 Prism.mp4": 1390,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E04 A Stolen Heart.mp4": 1395,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E05 Houdini On Channel 4.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E06 Killer Takes All.mp4": 1374,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E07 Hippocritic Oath.mp4": 1403,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E08 Prosecuter.mp4": 1395,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E09 If Looks Could Kill.mp4": 1403,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E10 You'll Die Laughing.mp4": 1395,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E11 Murder Party.mp4": 1406,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E12 Twist.mp4": 1394,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E13 User Deadly.mp4": 1400,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E14 Career Move.mp4": 1393,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E15 Full Disclosure.mp4": 1384,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E16 Kandinsky's Vault.mp4": 1405,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E17 There Was A Little Girl....mp4": 1374,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E18 Twisted Sisters.mp4": 1383,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E19 The 13th Floor.mp4": 1383,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E20 Hunted Part One.mp4": 1410,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 3/S03E21 Hunted Part Two.mp4": 1418,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E01 Fogbound.mp4": 1375,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E02 Pen Pal.mp4": 1376,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E03 Ancient Voices.mp4": 1397,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E04 Survival Of The Fittest.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E05 The Big Spin.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E06 Don't Sell Yourself Short.mp4": 1400,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E07 For Art's Sake.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E08 Murder In Mind.mp4": 1390,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E09 Mirror Mirror.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E10 Skeleton In The Closet.mp4": 1397,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E11 In The Driver's Seat.mp4": 1408,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E12 Driving Under The Influence.mp4": 1365,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E13 In The Name Of Science.mp4": 1404,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E14 Romance Machine.mp4": 1410,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E15 Diamonds Aren't Forever.mp4": 1409,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E16 My Dear Watson.mp4": 1410,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E17 Night Creatures.mp4": 1398,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E18 The Man Who Knew Too Little.mp4": 1375,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E19 Reunion.mp4": 1405,
  "the-new-alfred-hitchcock-presents-complete::The New Alfred Hitchcock Presents (1985)/Season 4/S04E20 South By Southeast.mp4": 1342,
},
};
