window.SHOW = {
  id: "NedAndStacey",
  title: "Ned and Stacey",
  art: "NedAndStacey.jpg",
  storageProgressKey: "nedandstacey-progress",
  storageSettingsKey: "nedandstacey-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['Ned_and_Stacey', "NED AND STACEY - S01E01 - Ned and Stacey (pilot)",
    "Ned and Stacey - S01E01 - Ned and Stacey (pilot).mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E02 - Portrait of a Marriage",
    "Ned and Stacey - S01E02 - Portrait of a Marriage.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E03 - Take My Wife, Please",
    "Ned and Stacey - S01E03 - Take My Wife, Please.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E04 - Cover Story",
    "Ned and Stacey - S01E04 - Cover Story.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E05 - Model Husband",
    "Ned and Stacey - S01E05 - Model Husband.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E06 - Saul and Ellen and Ned and Stacey",
    "Ned and Stacey - S01E06 - Saul and Ellen and Ned and Stacey.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E07 - Here's to You, Mrs. Binder",
    "Ned and Stacey - S01E07 - Here's to You, Mrs. Binder.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E08 - Halloween Story",
    "Ned and Stacey - S01E08 - Halloween Story.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E09 - Reality Check",
    "Ned and Stacey - S01E09 - Reality Check.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E10 - Thanksgiving Day Massacre",
    "Ned and Stacey - S01E10 - Thanksgiving Day Massacre.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E11 - Sleepless in Manhattan",
    "Ned and Stacey - S01E11 - Sleepless in Manhattan.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E12 - Threesome",
    "Ned and Stacey - S01E12 - Threesome.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E13 - Accountus Interruptus",
    "Ned and Stacey - S01E13 - Accountus Interruptus.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E14 - New Year's Eve",
    "Ned and Stacey - S01E14 - New Year's Eve.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E15 - Paranoia on the 47th Floor",
    "Ned and Stacey - S01E15 - Paranoia on the 47th Floor.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E16 - A Tender Trap",
    "Ned and Stacey - S01E16 - A Tender Trap.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E17 - Promotional Rescue",
    "Ned and Stacey - S01E17 - Promotional Rescue.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E18 - Friends and Lovers",
    "Ned and Stacey - S01E18 - Friends and Lovers.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E19 - The Gay Caballeros",
    "Ned and Stacey - S01E19 - The Gay Caballeros.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E20 - Gut Feeling",
    "Ned and Stacey - S01E20 - Gut Feeling.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E21 - Pals",
    "Ned and Stacey - S01E21 - Pals.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E22 - It Happened One Night",
    "Ned and Stacey - S01E22 - It Happened One Night.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E23 - You Bet Your Wife",
    "Ned and Stacey - S01E23 - You Bet Your Wife.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S01E24 - The End! (1)",
    "Ned and Stacey - S01E24 - The End! (1).mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E01 - The Other End (2)",
    "Ned and Stacey - S02E01 - The Other End (2).mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E02 - Dorsey vs. Dorsey",
    "Ned and Stacey - S02E02 - Dorsey vs. Dorsey.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E03 - The Muffins Take Manhattan",
    "Ned and Stacey - S02E03 - The Muffins Take Manhattan.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E04 - Computer Dating",
    "Ned and Stacey - S02E04 - Computer Dating.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E05 - Les is More or Less Moral-less",
    "Ned and Stacey - S02E05 - Les is More or Less Moral-less.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E06 - Loganberry's Run",
    "Ned and Stacey - S02E06 - Loganberry's Run.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E07 - It's a Mad, Mad, Mad, Mad Eric",
    "Ned and Stacey - S02E07 - It's a Mad, Mad, Mad, Mad Eric.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E08 - Fifteen A-Minutes",
    "Ned and Stacey - S02E08 - Fifteen A-Minutes.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E09 - Prom Night",
    "Ned and Stacey - S02E09 - Prom Night.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E10 - Saved by the Belvedere",
    "Ned and Stacey - S02E10 - Saved by the Belvedere.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E11 - Where My Third Nepal is Sheriff",
    "Ned and Stacey - S02E11 - Where My Third Nepal is Sheriff.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E12 - Sex, Lies and Commercials",
    "Ned and Stacey - S02E12 - Sex, Lies and Commercials.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E13 - Scenes From a Muffin Shop",
    "Ned and Stacey - S02E13 - Scenes From a Muffin Shop.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E14 - The Skyward's the Limit",
    "Ned and Stacey - S02E14 - The Skyward's the Limit.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E15 - The Errand Girl",
    "Ned and Stacey - S02E15 - The Errand Girl.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E16 - No Retreat, No Surrender",
    "Ned and Stacey - S02E16 - No Retreat, No Surrender.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E17 - The Truth Shall Set You Back",
    "Ned and Stacey - S02E17 - The Truth Shall Set You Back.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E18 - I Like Your Moxie",
    "Ned and Stacey - S02E18 - I Like Your Moxie.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E19 - Please Don't Squeeze the Eric",
    "Ned and Stacey - S02E19 - Please Don't Squeeze the Eric.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E20 - All That Chazz",
    "Ned and Stacey - S02E20 - All That Chazz.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E21 - Skippy's Revenge",
    "Ned and Stacey - S02E21 - Skippy's Revenge.mp4"],
  ['Ned_and_Stacey', "NED AND STACEY - S02E22 - Best of Luck on Future Projects",
    "Ned and Stacey - S02E22 - Best of Luck on Future Projects.mp4"],
],
  durations: {
  "Ned_and_Stacey::Ned and Stacey - S01E01 - Ned and Stacey (pilot).mp4": 1356,
  "Ned_and_Stacey::Ned and Stacey - S01E02 - Portrait of a Marriage.mp4": 1352,
  "Ned_and_Stacey::Ned and Stacey - S01E03 - Take My Wife, Please.mp4": 1353,
  "Ned_and_Stacey::Ned and Stacey - S01E04 - Cover Story.mp4": 1350,
  "Ned_and_Stacey::Ned and Stacey - S01E05 - Model Husband.mp4": 1353,
  "Ned_and_Stacey::Ned and Stacey - S01E06 - Saul and Ellen and Ned and Stacey.mp4": 1338,
  "Ned_and_Stacey::Ned and Stacey - S01E07 - Here's to You, Mrs. Binder.mp4": 1350,
  "Ned_and_Stacey::Ned and Stacey - S01E08 - Halloween Story.mp4": 1337,
  "Ned_and_Stacey::Ned and Stacey - S01E09 - Reality Check.mp4": 1353,
  "Ned_and_Stacey::Ned and Stacey - S01E10 - Thanksgiving Day Massacre.mp4": 1383,
  "Ned_and_Stacey::Ned and Stacey - S01E11 - Sleepless in Manhattan.mp4": 1356,
  "Ned_and_Stacey::Ned and Stacey - S01E12 - Threesome.mp4": 1352,
  "Ned_and_Stacey::Ned and Stacey - S01E13 - Accountus Interruptus.mp4": 1353,
  "Ned_and_Stacey::Ned and Stacey - S01E14 - New Year's Eve.mp4": 1339,
  "Ned_and_Stacey::Ned and Stacey - S01E15 - Paranoia on the 47th Floor.mp4": 1339,
  "Ned_and_Stacey::Ned and Stacey - S01E16 - A Tender Trap.mp4": 1340,
  "Ned_and_Stacey::Ned and Stacey - S01E17 - Promotional Rescue.mp4": 1337,
  "Ned_and_Stacey::Ned and Stacey - S01E18 - Friends and Lovers.mp4": 1337,
  "Ned_and_Stacey::Ned and Stacey - S01E19 - The Gay Caballeros.mp4": 1321,
  "Ned_and_Stacey::Ned and Stacey - S01E20 - Gut Feeling.mp4": 1337,
  "Ned_and_Stacey::Ned and Stacey - S01E21 - Pals.mp4": 1336,
  "Ned_and_Stacey::Ned and Stacey - S01E22 - It Happened One Night.mp4": 1337,
  "Ned_and_Stacey::Ned and Stacey - S01E23 - You Bet Your Wife.mp4": 1336,
  "Ned_and_Stacey::Ned and Stacey - S01E24 - The End! (1).mp4": 1335,
  "Ned_and_Stacey::Ned and Stacey - S02E01 - The Other End (2).mp4": 1323,
  "Ned_and_Stacey::Ned and Stacey - S02E02 - Dorsey vs. Dorsey.mp4": 1326,
  "Ned_and_Stacey::Ned and Stacey - S02E03 - The Muffins Take Manhattan.mp4": 1325,
  "Ned_and_Stacey::Ned and Stacey - S02E04 - Computer Dating.mp4": 1326,
  "Ned_and_Stacey::Ned and Stacey - S02E05 - Les is More or Less Moral-less.mp4": 1329,
  "Ned_and_Stacey::Ned and Stacey - S02E06 - Loganberry's Run.mp4": 1327,
  "Ned_and_Stacey::Ned and Stacey - S02E07 - It's a Mad, Mad, Mad, Mad Eric.mp4": 1325,
  "Ned_and_Stacey::Ned and Stacey - S02E08 - Fifteen A-Minutes.mp4": 1326,
  "Ned_and_Stacey::Ned and Stacey - S02E09 - Prom Night.mp4": 1296,
  "Ned_and_Stacey::Ned and Stacey - S02E10 - Saved by the Belvedere.mp4": 1325,
  "Ned_and_Stacey::Ned and Stacey - S02E11 - Where My Third Nepal is Sheriff.mp4": 1325,
  "Ned_and_Stacey::Ned and Stacey - S02E12 - Sex, Lies and Commercials.mp4": 1328,
  "Ned_and_Stacey::Ned and Stacey - S02E13 - Scenes From a Muffin Shop.mp4": 1324,
  "Ned_and_Stacey::Ned and Stacey - S02E14 - The Skyward's the Limit.mp4": 1325,
  "Ned_and_Stacey::Ned and Stacey - S02E15 - The Errand Girl.mp4": 1324,
  "Ned_and_Stacey::Ned and Stacey - S02E16 - No Retreat, No Surrender.mp4": 1325,
  "Ned_and_Stacey::Ned and Stacey - S02E17 - The Truth Shall Set You Back.mp4": 1323,
  "Ned_and_Stacey::Ned and Stacey - S02E18 - I Like Your Moxie.mp4": 1324,
  "Ned_and_Stacey::Ned and Stacey - S02E19 - Please Don't Squeeze the Eric.mp4": 1326,
  "Ned_and_Stacey::Ned and Stacey - S02E20 - All That Chazz.mp4": 1324,
  "Ned_and_Stacey::Ned and Stacey - S02E21 - Skippy's Revenge.mp4": 1327,
  "Ned_and_Stacey::Ned and Stacey - S02E22 - Best of Luck on Future Projects.mp4": 1326,
},
};
