window.SHOW = {
  id: "USAUpAllNight",
  title: "USA Up All Night",
  art: "USAUpAllNight.jpg",
  storageProgressKey: "usaupallnight-progress",
  storageSettingsKey: "usaupallnight-settings",
  nestedPaths: false,
  grouping: "flat",
  segments: "film",
  episodes: [
  ['usa-up-all-night-pom-pom-girls-6-30-89', "USA UP ALL NIGHT - 06/30/1989",
    "USA Up All Night Pom-Pom Girls 6-30-89.mp4"],
  ['july-28th-1989-usa-up-all-night-iron-eagle', "USA UP ALL NIGHT - 07/28/1989",
    "July 28th, 1989 USA Up All Night Iron Eagle.ia.mp4"],
  ['usa-up-all-night-school-for-sex-maybe-08-11-1989', "USA UP ALL NIGHT - 08/11/1989",
    "USA Up All Night - School For Sex - maybe 08-11-1989.ia.mp4"],
  ['usa-up-all-night-sweet-sugar-01-13-1990', "USA UP ALL NIGHT - 01/13/1990",
    "USA Up All Night - Sweet Sugar - 01-13-1990.ia.mp4"],
  ['usa-up-all-night-return-of-the-killer-tomatoes-3-31-90', "USA UP ALL NIGHT - 03/31/1990",
    "USA Up All Night Return of the Killer Tomatoes 3-31-90.mp4"],
  ['usa-up-all-night-partial-august-25-1990-broadcast', "USA UP ALL NIGHT - 08/25/1990",
    "USA Up All Night Partial August 25, 1990 Broadcast.mp4"],
  ['usa-up-all-night-nothern-kicks-southern-fists-1990', "USA UP ALL NIGHT - 1990",
    "USA Up All NIght - Nothern Kicks, Southern Fists - 1990.ia.mp4"],
  ['usa-up-all-night-the-girl-i-want-1-5-91', "USA UP ALL NIGHT - 01/05/1991",
    "USA Up All Night The Girl I Want 1-5-91.mp4"],
  ['usa-up-all-night-mankillers-recreaction-nov-22-1991', "USA UP ALL NIGHT - 11/22/1991",
    "USA Up All Night - Mankillers (Recreaction) - Nov, 22, 1991.ia.mp4"],
  ['basket-case-usa-up-all-night-1992', "USA UP ALL NIGHT - 1992",
    "Basket Case USA Up All Night 1992.mp4"],
  ['usa-up-all-night-hot-chili-06-06-1992', "USA UP ALL NIGHT - 06/06/1992",
    "Usa Up All Night - Hot Chili - 06-06-1992.ia.mp4"],
  ['state-park-usa-up-all-night-08-01-1992', "USA UP ALL NIGHT - 08/01/1992",
    "StatePark_USAupAllNight_08-01-1992_WOC-(bd)-[60]-1.ia.mp4"],
  ['usa-up-all-night-with-rhonda-shear-beach-balls-09-25-1992', "USA UP ALL NIGHT - 09/25/1992",
    "USA Up All Night With Rhonda Shear - Beach Balls - 09-25-1992.ia.mp4"],
  ['usa-up-all-night-with-rhonda-shear-virgin-high-06-04-1993', "USA UP ALL NIGHT - 06/04/1993",
    "USA Up All Night With Rhonda Shear - Virgin High - 06-04-1993.ia.mp4"],
  ['usa-up-all-night-cheerleaders-wild-weekend-02-25-1994', "USA UP ALL NIGHT - 02/25/1994",
    "USA Up All Night - Cheerleaders Wild Weekend - 02-25-1994.ia.mp4"],
  ['20220508-154728', "USA UP ALL NIGHT - 1994",
    "20220508-154728.mp4"],
  ['usa-up-all-night-return-to-horror-high-10-18-96', "USA UP ALL NIGHT - 10/18/1996",
    "USA Up All Night Return to Horror High 10-18-96.mp4"],
  ['usa-up-all-night-night-of-the-living-dead-1997', "USA UP ALL NIGHT - 1997",
    "USA Up All Night - Night Of The Living Dead 1997.ia.mp4"],
  ['usa-up-all-night-howling-3', "USA UP ALL NIGHT - Howling III: The Marsupials",
    "USA Up All Night - Howling 3.ia.mp4"],
  ['usa-up-all-night-lifeforce', "USA UP ALL NIGHT - Lifeforce",
    "USA Up All Night - Lifeforce.ia.mp4"],
  ['usa-up-all-night-fright-night', "USA UP ALL NIGHT - Fright Night",
    "USA Up All Night - Fright Night.ia.mp4"],
  ['usa-up-all-night-killer-klowns-from-outer-space-10-00', "USA UP ALL NIGHT - Killer Klowns from Outer Space",
    "USA Up All Night - Killer Klowns From Outer Space - 10-00.mp4"],
  ['usa-up-all-night-porkys-2', "USA UP ALL NIGHT - Porky's II: The Next Day",
    "USA Up All Night - Porky's 2.ia.mp4"],
  ['usa-up-all-night-friday-the-13th-part-vii-jason-takes-manhattan-1989-vhs-woc', "USA UP ALL NIGHT - Friday the 13th Part VIII: Jason Takes Manhattan",
    "USA Up All Night - Friday the 13th Part VII Jason Takes Manhattan (1989) VHS WOC.mp4"],
  ['usa-up-all-night-hell-comes-to-frogtown-with-gilbert-gottfried', "USA UP ALL NIGHT - Hell Comes to Frogtown",
    "USA Up All Night Hell Comes To Frogtown with Gilbert Gottfried.ia.mp4"],
  ['usa-up-all-night-beach-babes-from-beyond-with-rhonda-shear', "USA UP ALL NIGHT - Beach Babes from Beyond",
    "USA Up All Night Beach Babes From Beyond with Rhonda Shear.ia.mp4"],
  ['cgi-95-usa-up-all-night', "USA UP ALL NIGHT - Beach Babes 2: Cave Girl Island",
    "CGI95 - USA UP ALL NIGHT.mp4"],
  ['usa-up-all-night-with-rhonda-shear-vice-academy-4', "USA UP ALL NIGHT - Vice Academy 4",
    "USA Up All Night With Rhonda Shear - Vice Academy 4.ia.mp4"],
  ['usa-up-all-night-vampire-on-bikini-beach', "USA UP ALL NIGHT - Vampire on Bikini Beach",
    "USA Up All Night - Vampire On Bikini Beach.ia.mp4"],
  ['usa-up-all-night-wild-malibu-weekend', "USA UP ALL NIGHT - Wild Malibu Weekend",
    "USA Up All Night - Wild Malibu Weekend.ia.mp4"],
  ['usa-up-all-night-slammer-girls', "USA UP ALL NIGHT - Slammer Girls",
    "USA Up All Night - Slammer Girls.ia.mp4"],
  ['usa-up-all-night-the-vals', "USA UP ALL NIGHT - The Vals",
    "USA Up All Night - The Vals.ia.mp4"],
  ['usa-up-all-night-lovers-lovers', "USA UP ALL NIGHT - Lovers, Lovers",
    "USA Up All Night - Lovers, Lovers.ia.mp4"],
  ['usa-up-all-night-lunchbox', "USA UP ALL NIGHT - Lunch Box",
    "USA Up All Night - Lunchbox.ia.mp4"],
  ['usa-up-all-night-nightshift', "USA UP ALL NIGHT - Night Shift",
    "USA Up All Night - Nightshift.ia.mp4"],
  ['usa-up-all-night-sorority-babes-in-the-slimeball-bowl-o-rama', "USA UP ALL NIGHT - Sorority Babes in the Slimeball Bowl-O-Rama",
    "USA Up All Night - Sorority Babes In The Slimeball Bowl-O-Rama.ia.mp4"],
  ['usa-up-all-night-dream-a-little-evil-missing-end-august-6-1993', "USA UP ALL NIGHT - Dream a Little Evil (ends early)",
    "USA Up All Night - Dream A Little Evil - missing end - August 6, 1993.ia.mp4"],
  ['dvd-video-recording-1_202604', "USA UP ALL NIGHT - Attack of the Killer Tomatoes",
    "Dvd Video Recording(1).ia.mp4"],
  ['01.-usa-up-all-night-hot-times-at-montclair-high', "USA UP ALL NIGHT - Hot Times at Montclair High",
    "01. USA Up All Night - Hot Times At Montclair High.ia.mp4"],
  ['nve-dvd-0', "USA UP ALL NIGHT - Monster High / Witch Academy",
    "Nve Dvd(1).ia.mp4"],
],
  durations: {
  "usa-up-all-night-pom-pom-girls-6-30-89::USA Up All Night Pom-Pom Girls 6-30-89.mp4": 6244,
  "july-28th-1989-usa-up-all-night-iron-eagle::July 28th, 1989 USA Up All Night Iron Eagle.ia.mp4": 8858,
  "usa-up-all-night-school-for-sex-maybe-08-11-1989::USA Up All Night - School For Sex - maybe 08-11-1989.ia.mp4": 7236,
  "usa-up-all-night-sweet-sugar-01-13-1990::USA Up All Night - Sweet Sugar - 01-13-1990.ia.mp4": 7262,
  "usa-up-all-night-return-of-the-killer-tomatoes-3-31-90::USA Up All Night Return of the Killer Tomatoes 3-31-90.mp4": 7433,
  "usa-up-all-night-partial-august-25-1990-broadcast::USA Up All Night Partial August 25, 1990 Broadcast.mp4": 14969,
  "usa-up-all-night-nothern-kicks-southern-fists-1990::USA Up All NIght - Nothern Kicks, Southern Fists - 1990.ia.mp4": 7267,
  "usa-up-all-night-the-girl-i-want-1-5-91::USA Up All Night The Girl I Want 1-5-91.mp4": 5466,
  "usa-up-all-night-mankillers-recreaction-nov-22-1991::USA Up All Night - Mankillers (Recreaction) - Nov, 22, 1991.ia.mp4": 6851,
  "basket-case-usa-up-all-night-1992::Basket Case USA Up All Night 1992.mp4": 6908,
  "usa-up-all-night-hot-chili-06-06-1992::Usa Up All Night - Hot Chili - 06-06-1992.ia.mp4": 6693,
  "state-park-usa-up-all-night-08-01-1992::StatePark_USAupAllNight_08-01-1992_WOC-(bd)-[60]-1.ia.mp4": 7499,
  "usa-up-all-night-with-rhonda-shear-beach-balls-09-25-1992::USA Up All Night With Rhonda Shear - Beach Balls - 09-25-1992.ia.mp4": 6485,
  "usa-up-all-night-with-rhonda-shear-virgin-high-06-04-1993::USA Up All Night With Rhonda Shear - Virgin High - 06-04-1993.ia.mp4": 7310,
  "usa-up-all-night-cheerleaders-wild-weekend-02-25-1994::USA Up All Night - Cheerleaders Wild Weekend - 02-25-1994.ia.mp4": 7188,
  "20220508-154728::20220508-154728.mp4": 6517,
  "usa-up-all-night-return-to-horror-high-10-18-96::USA Up All Night Return to Horror High 10-18-96.mp4": 7043,
  "usa-up-all-night-night-of-the-living-dead-1997::USA Up All Night - Night Of The Living Dead 1997.ia.mp4": 7764,
  "usa-up-all-night-howling-3::USA Up All Night - Howling 3.ia.mp4": 9366,
  "usa-up-all-night-lifeforce::USA Up All Night - Lifeforce.ia.mp4": 7206,
  "usa-up-all-night-fright-night::USA Up All Night - Fright Night.ia.mp4": 6843,
  "usa-up-all-night-killer-klowns-from-outer-space-10-00::USA Up All Night - Killer Klowns From Outer Space - 10-00.mp4": 7044,
  "usa-up-all-night-porkys-2::USA Up All Night - Porky's 2.ia.mp4": 7619,
  "usa-up-all-night-friday-the-13th-part-vii-jason-takes-manhattan-1989-vhs-woc::USA Up All Night - Friday the 13th Part VII Jason Takes Manhattan (1989) VHS WOC.mp4": 7359,
  "usa-up-all-night-hell-comes-to-frogtown-with-gilbert-gottfried::USA Up All Night Hell Comes To Frogtown with Gilbert Gottfried.ia.mp4": 7082,
  "usa-up-all-night-beach-babes-from-beyond-with-rhonda-shear::USA Up All Night Beach Babes From Beyond with Rhonda Shear.ia.mp4": 7015,
  "cgi-95-usa-up-all-night::CGI95 - USA UP ALL NIGHT.mp4": 4979,
  "usa-up-all-night-with-rhonda-shear-vice-academy-4::USA Up All Night With Rhonda Shear - Vice Academy 4.ia.mp4": 6169,
  "usa-up-all-night-vampire-on-bikini-beach::USA Up All Night - Vampire On Bikini Beach.ia.mp4": 6420,
  "usa-up-all-night-wild-malibu-weekend::USA Up All Night - Wild Malibu Weekend.ia.mp4": 6537,
  "usa-up-all-night-slammer-girls::USA Up All Night - Slammer Girls.ia.mp4": 7272,
  "usa-up-all-night-the-vals::USA Up All Night - The Vals.ia.mp4": 7787,
  "usa-up-all-night-lovers-lovers::USA Up All Night - Lovers, Lovers.ia.mp4": 7439,
  "usa-up-all-night-lunchbox::USA Up All Night - Lunchbox.ia.mp4": 5785,
  "usa-up-all-night-nightshift::USA Up All Night - Nightshift.ia.mp4": 6613,
  "usa-up-all-night-sorority-babes-in-the-slimeball-bowl-o-rama::USA Up All Night - Sorority Babes In The Slimeball Bowl-O-Rama.ia.mp4": 5168,
  "usa-up-all-night-dream-a-little-evil-missing-end-august-6-1993::USA Up All Night - Dream A Little Evil - missing end - August 6, 1993.ia.mp4": 5272,
  "dvd-video-recording-1_202604::Dvd Video Recording(1).ia.mp4": 5087,
  "01.-usa-up-all-night-hot-times-at-montclair-high::01. USA Up All Night - Hot Times At Montclair High.ia.mp4": 6638,
  "nve-dvd-0::Nve Dvd(1).ia.mp4": 6088,
},
  film: {
  "usa-up-all-night-pom-pom-girls-6-30-89::USA Up All Night Pom-Pom Girls 6-30-89.mp4": "The Pom Pom Girls",
  "july-28th-1989-usa-up-all-night-iron-eagle::July 28th, 1989 USA Up All Night Iron Eagle.ia.mp4": "Iron Eagle",
  "usa-up-all-night-school-for-sex-maybe-08-11-1989::USA Up All Night - School For Sex - maybe 08-11-1989.ia.mp4": "School for Sex, Maybe",
  "usa-up-all-night-sweet-sugar-01-13-1990::USA Up All Night - Sweet Sugar - 01-13-1990.ia.mp4": "Sweet Sugar",
  "usa-up-all-night-return-of-the-killer-tomatoes-3-31-90::USA Up All Night Return of the Killer Tomatoes 3-31-90.mp4": "Return of the Killer Tomatoes",
  "usa-up-all-night-partial-august-25-1990-broadcast::USA Up All Night Partial August 25, 1990 Broadcast.mp4": "August 25, 1990 (partial capture)",
  "usa-up-all-night-nothern-kicks-southern-fists-1990::USA Up All NIght - Nothern Kicks, Southern Fists - 1990.ia.mp4": "Northern Kicks, Southern Fists",
  "usa-up-all-night-the-girl-i-want-1-5-91::USA Up All Night The Girl I Want 1-5-91.mp4": "The Girl I Want",
  "usa-up-all-night-mankillers-recreaction-nov-22-1991::USA Up All Night - Mankillers (Recreaction) - Nov, 22, 1991.ia.mp4": "Mankillers",
  "basket-case-usa-up-all-night-1992::Basket Case USA Up All Night 1992.mp4": "Basket Case",
  "usa-up-all-night-hot-chili-06-06-1992::Usa Up All Night - Hot Chili - 06-06-1992.ia.mp4": "Hot Chili",
  "state-park-usa-up-all-night-08-01-1992::StatePark_USAupAllNight_08-01-1992_WOC-(bd)-[60]-1.ia.mp4": "State Park",
  "usa-up-all-night-with-rhonda-shear-beach-balls-09-25-1992::USA Up All Night With Rhonda Shear - Beach Balls - 09-25-1992.ia.mp4": "Beach Balls",
  "usa-up-all-night-with-rhonda-shear-virgin-high-06-04-1993::USA Up All Night With Rhonda Shear - Virgin High - 06-04-1993.ia.mp4": "Virgin High",
  "usa-up-all-night-cheerleaders-wild-weekend-02-25-1994::USA Up All Night - Cheerleaders Wild Weekend - 02-25-1994.ia.mp4": "Cheerleaders' Wild Weekend",
  "20220508-154728::20220508-154728.mp4": "Mankillers",
  "usa-up-all-night-return-to-horror-high-10-18-96::USA Up All Night Return to Horror High 10-18-96.mp4": "Return to Horror High",
  "usa-up-all-night-night-of-the-living-dead-1997::USA Up All Night - Night Of The Living Dead 1997.ia.mp4": "Night of the Living Dead",
  "usa-up-all-night-howling-3::USA Up All Night - Howling 3.ia.mp4": "Howling III: The Marsupials",
  "usa-up-all-night-lifeforce::USA Up All Night - Lifeforce.ia.mp4": "Lifeforce",
  "usa-up-all-night-fright-night::USA Up All Night - Fright Night.ia.mp4": "Fright Night",
  "usa-up-all-night-killer-klowns-from-outer-space-10-00::USA Up All Night - Killer Klowns From Outer Space - 10-00.mp4": "Killer Klowns from Outer Space",
  "usa-up-all-night-porkys-2::USA Up All Night - Porky's 2.ia.mp4": "Porky's II: The Next Day",
  "usa-up-all-night-friday-the-13th-part-vii-jason-takes-manhattan-1989-vhs-woc::USA Up All Night - Friday the 13th Part VII Jason Takes Manhattan (1989) VHS WOC.mp4": "Friday the 13th Part VIII: Jason Takes Manhattan",
  "usa-up-all-night-hell-comes-to-frogtown-with-gilbert-gottfried::USA Up All Night Hell Comes To Frogtown with Gilbert Gottfried.ia.mp4": "Hell Comes to Frogtown",
  "usa-up-all-night-beach-babes-from-beyond-with-rhonda-shear::USA Up All Night Beach Babes From Beyond with Rhonda Shear.ia.mp4": "Beach Babes from Beyond",
  "cgi-95-usa-up-all-night::CGI95 - USA UP ALL NIGHT.mp4": "Beach Babes 2: Cave Girl Island",
  "usa-up-all-night-with-rhonda-shear-vice-academy-4::USA Up All Night With Rhonda Shear - Vice Academy 4.ia.mp4": "Vice Academy 4",
  "usa-up-all-night-vampire-on-bikini-beach::USA Up All Night - Vampire On Bikini Beach.ia.mp4": "Vampire on Bikini Beach",
  "usa-up-all-night-wild-malibu-weekend::USA Up All Night - Wild Malibu Weekend.ia.mp4": "Wild Malibu Weekend",
  "usa-up-all-night-slammer-girls::USA Up All Night - Slammer Girls.ia.mp4": "Slammer Girls",
  "usa-up-all-night-the-vals::USA Up All Night - The Vals.ia.mp4": "The Vals",
  "usa-up-all-night-lovers-lovers::USA Up All Night - Lovers, Lovers.ia.mp4": "Lovers, Lovers",
  "usa-up-all-night-lunchbox::USA Up All Night - Lunchbox.ia.mp4": "Lunch Box",
  "usa-up-all-night-nightshift::USA Up All Night - Nightshift.ia.mp4": "Night Shift",
  "usa-up-all-night-sorority-babes-in-the-slimeball-bowl-o-rama::USA Up All Night - Sorority Babes In The Slimeball Bowl-O-Rama.ia.mp4": "Sorority Babes in the Slimeball Bowl-O-Rama",
  "usa-up-all-night-dream-a-little-evil-missing-end-august-6-1993::USA Up All Night - Dream A Little Evil - missing end - August 6, 1993.ia.mp4": "Dream a Little Evil (ends early)",
  "dvd-video-recording-1_202604::Dvd Video Recording(1).ia.mp4": "Attack of the Killer Tomatoes",
  "01.-usa-up-all-night-hot-times-at-montclair-high::01. USA Up All Night - Hot Times At Montclair High.ia.mp4": "Hot Times at Montclair High",
},
  shows: {
  "nve-dvd-0::Nve Dvd(1).ia.mp4": ["Monster High", "Witch Academy"],
},
};
