window.SHOW = {
  id: "Wishbone",
  title: "Wishbone",
  storageProgressKey: "wishbone-progress",
  storageSettingsKey: "wishbone-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['wishbonefullseriesremastered', "WISHBONE - S01E01 - A Tail In Twain, Part 1!",
    "Season 1/Wishbone S01E01 A Tail In Twain, Part 1!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E02 - A Tail In Twain, Part 2!",
    "Season 1/Wishbone S01E02 A Tail In Twain, Part 2!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E03 - Twisted Tail!",
    "Season 1/Wishbone S01E03 Twisted Tail!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E04 - Rosie, Oh, Rosie, Oh!",
    "Season 1/Wishbone S01E04 Rosie, Oh, Rosie, Oh!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E05 - Homer Sweet Homer!",
    "Season 1/Wishbone S01E05 Homer Sweet Homer!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E06 - Bark That Bark!",
    "Season 1/Wishbone S01E06 Bark That Bark!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E07 - Cyranose!",
    "Season 1/Wishbone S01E07 Cyranose!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E08 - The Slobbery Hound!",
    "Season 1/Wishbone S01E08 The Slobbery Hound!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E09 - Digging Up The Past!",
    "Season 1/Wishbone S01E09 Digging Up The Past!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E10 - Bone Of Arc!",
    "Season 1/Wishbone S01E10 Bone Of Arc!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E11 - Impawssible Dream!",
    "Season 1/Wishbone S01E11 Impawssible Dream!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E12 - Fleabitten Bargain!",
    "Season 1/Wishbone S01E12 Fleabitten Bargain!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E13 - Sniffing The Gauntlet!",
    "Season 1/Wishbone S01E13 Sniffing The Gauntlet!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E14 - Hunchdog of Notre Dame!",
    "Season 1/Wishbone S01E14 Hunchdog of Notre Dame!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E15 - Golden Retrieved!",
    "Season 1/Wishbone S01E15 Golden Retrieved!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E16 - A Tale Of Two Sitters!",
    "Season 1/Wishbone S01E16 A Tale Of Two Sitters!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E17 - Frankenbone!",
    "Season 1/Wishbone S01E17 Frankenbone!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E18 - Hot Diggety Dawg!",
    "Season 1/Wishbone S01E18 Hot Diggety Dawg!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E19 - One Thousand And One Tails!",
    "Season 1/Wishbone S01E19 One Thousand And One Tails!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E20 - Mixed Breeds!",
    "Season 1/Wishbone S01E20 Mixed Breeds!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E21 - Canine Cure!",
    "Season 1/Wishbone S01E21 Canine Cure!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E22 - The Pawioined Paper!",
    "Season 1/Wishbone S01E22 The Pawioined Paper!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E23 - Bark To The Future!",
    "Season 1/Wishbone S01E23 Bark To The Future!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E24 - Paw Prints Of Thieves!",
    "Season 1/Wishbone S01E24 Paw Prints Of Thieves!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E25 - Furst Impressions!",
    "Season 1/Wishbone S01E25 Furst Impressions!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E26 - Prince And The Pooch!",
    "Season 1/Wishbone S01E26 Prince And The Pooch!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E27 - The Count's Account!",
    "Season 1/Wishbone S01E27 The Count's Account!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E28 - Salty Dog!",
    "Season 1/Wishbone S01E28 Salty Dog!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E29 - Little Big Dog!",
    "Season 1/Wishbone S01E29 Little Big Dog!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E30 - A Dogged Expose!",
    "Season 1/Wishbone S01E30 A Dogged Expose!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E31 - Terrified Terrier!",
    "Season 1/Wishbone S01E31 Terrified Terrier!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E32 - Shakespaw!",
    "Season 1/Wishbone S01E32 Shakespaw!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E33 - Muttketeer!",
    "Season 1/Wishbone S01E33 Muttketeer!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E34 - Hercules Unleashed!",
    "Season 1/Wishbone S01E34 Hercules Unleashed!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E35 - Viva Wishbone!",
    "Season 1/Wishbone S01E35 Viva Wishbone!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E36 - The Entrepawneur!",
    "Season 1/Wishbone S01E36 The Entrepawneur!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E37 - Pantin' At The Opera!",
    "Season 1/Wishbone S01E37 Pantin' At The Opera!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E38 - Dances With Dogs!",
    "Season 1/Wishbone S01E38 Dances With Dogs!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E39 - Persiguiendo Al Hueso!",
    "Season 1/Wishbone S01E39 Persiguiendo Al Hueso!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S01E40 - Picks Of The Litter!",
    "Season 1/Wishbone S01E40 Picks Of The Litter!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E01-02 - Halloween Hound, The Legend of the Creepy Collars (Part 1 and Part 2!)",
    "Season 2/Wishbone S02E01-E02 Halloween Hound, The Legend of the Creepy Collars (Part 1 and Part 2!).mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E03 - The Prince of Wags!",
    "Season 2/Wishbone S02E03 The Prince of Wags!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E04 - Groomed for Greatness!",
    "Season 2/Wishbone S02E04 Groomed for Greatness!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E05 - A Bone of Contention!",
    "Season 2/Wishbone S02E05 A Bone of Contention!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E06 - War of the Noses!",
    "Season 2/Wishbone S02E06 War of the Noses!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E07 - Moonbone!",
    "Season 2/Wishbone S02E07 Moonbone!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E08 - Barking At Buddha!",
    "Season 2/Wishbone S02E08 Barking At Buddha!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E09 - Pup Fiction!",
    "Season 2/Wishbone S02E09 Pup Fiction!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S02E10 - The Roamin' Nose!",
    "Season 2/Wishbone S02E10 The Roamin' Nose!.mp4"],
  ['wishbonefullseriesremastered', "WISHBONE - S03E01 - Dog Days Of The West (TV Movie)",
    "Dog Days Of The West (1998).mp4"],
],
  durations: {
  "wishbonefullseriesremastered::Season 1/Wishbone S01E01 A Tail In Twain, Part 1!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E02 A Tail In Twain, Part 2!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E03 Twisted Tail!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E04 Rosie, Oh, Rosie, Oh!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E05 Homer Sweet Homer!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E06 Bark That Bark!.mp4": 1621,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E07 Cyranose!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E08 The Slobbery Hound!.mp4": 1644,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E09 Digging Up The Past!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E10 Bone Of Arc!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E11 Impawssible Dream!.mp4": 1692,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E12 Fleabitten Bargain!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E13 Sniffing The Gauntlet!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E14 Hunchdog of Notre Dame!.mp4": 1680,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E15 Golden Retrieved!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E16 A Tale Of Two Sitters!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E17 Frankenbone!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E18 Hot Diggety Dawg!.mp4": 1679,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E19 One Thousand And One Tails!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E20 Mixed Breeds!.mp4": 1615,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E21 Canine Cure!.mp4": 1671,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E22 The Pawioined Paper!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E23 Bark To The Future!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E24 Paw Prints Of Thieves!.mp4": 1678,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E25 Furst Impressions!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E26 Prince And The Pooch!.mp4": 1614,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E27 The Count's Account!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E28 Salty Dog!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E29 Little Big Dog!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E30 A Dogged Expose!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E31 Terrified Terrier!.mp4": 1675,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E32 Shakespaw!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E33 Muttketeer!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E34 Hercules Unleashed!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E35 Viva Wishbone!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E36 The Entrepawneur!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E37 Pantin' At The Opera!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E38 Dances With Dogs!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E39 Persiguiendo Al Hueso!.mp4": 1616,
  "wishbonefullseriesremastered::Season 1/Wishbone S01E40 Picks Of The Litter!.mp4": 1616,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E01-E02 Halloween Hound, The Legend of the Creepy Collars (Part 1 and Part 2!).mp4": 3292,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E03 The Prince of Wags!.mp4": 1616,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E04 Groomed for Greatness!.mp4": 1605,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E05 A Bone of Contention!.mp4": 1605,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E06 War of the Noses!.mp4": 1605,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E07 Moonbone!.mp4": 1605,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E08 Barking At Buddha!.mp4": 1604,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E09 Pup Fiction!.mp4": 1604,
  "wishbonefullseriesremastered::Season 2/Wishbone S02E10 The Roamin' Nose!.mp4": 1605,
  "wishbonefullseriesremastered::Dog Days Of The West (1998).mp4": 5698,
},
};
