window.SHOW = {
  id: "FreddysNightmares",
  title: "Freddy's Nightmares",
  art: "FreddysNightmares.png",
  storageProgressKey: "freddysnightmares-progress",
  storageSettingsKey: "freddysnightmares-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E01 - No More Mr. Nice Guy",
    "Freddy's Nightmares S01E01 No More Mr. Nice Guy.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E02 - It's a Miserable Life",
    "Freddy's Nightmares S01E02 It's a Miserable Life.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E03 - Killer Instinct",
    "Freddy's Nightmares S01E03 Killer Instinct.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E04 - Freddy's Tricks and Treats",
    "Freddy's Nightmares S01E04 Freddy's Tricks and Treats.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E05 - Judy Miller, Come On Down",
    "Freddy's Nightmares S01E05 Judy Miller, Come On Down.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E06 - Saturday Night Special",
    "Freddy's Nightmares S01E06 Saturday Night Special.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E07 - Sister's Keeper",
    "Freddy's Nightmares S01E07 Sister's Keeper.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E08 - Mother's Day",
    "Freddy's Nightmares S01E08 Mother's Day.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E09 - Rebel Without a Car",
    "Freddy's Nightmares S01E09 Rebel Without a Car.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E10 - The Bride Wore Red",
    "Freddy's Nightmares S01E10 The Bride Wore Red.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E11 - Do Dreams Bleed",
    "Freddy's Nightmares S01E11 Do Dreams Bleed.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E12 - The End of the World",
    "Freddy's Nightmares S01E12 The End of the World.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E13 - Deadline",
    "Freddy's Nightmares S01E13 Deadline.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E14 - Black Tickets",
    "Freddy's Nightmares S01E14 Black Tickets.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E15 - School Daze",
    "Freddy's Nightmares S01E15 School Daze.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E16 - Cabin Fever",
    "Freddy's Nightmares S01E16 Cabin Fever.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E17 - Love Stinks",
    "Freddy's Nightmares S01E17 Love Stinks.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E18 - The Art of Death",
    "Freddy's Nightmares S01E18 The Art of Death.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E19 - Missing Persons",
    "Freddy's Nightmares S01E19 Missing Persons.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E20 - The Light At the End of the Tunnel",
    "Freddy's Nightmares S01E20 The Light At the End of the Tunnel.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E21 - Identity Crisis",
    "Freddy's Nightmares S01E21 Identity Crisis.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S01E22 - Safe Sex",
    "Freddy's Nightmares S01E22 Safe Sex.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E01 - Dream Come True",
    "Freddy's Nightmares S02E01 Dream Come True.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E02 - Heartbreak Hotel",
    "Freddy's Nightmares S02E02 Heartbreak Hotel.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E03 - Welcome to Springwood",
    "Freddy's Nightmares S02E03 Welcome to Springwood.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E04 - Photo Finish",
    "Freddy's Nightmares S02E04 Photo Finish.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E05 - Memory Overload",
    "Freddy's Nightmares S02E05 Memory Overload.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E06 - Lucky Stiff",
    "Freddy's Nightmares S02E06 Lucky Stiff.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E07 - Silence is Golden",
    "Freddy's Nightmares S02E07 Silence is Golden.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E08 - Bloodlines",
    "Freddy's Nightmares S02E08 Bloodlines.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E09 - Monkey Dreams",
    "Freddy's Nightmares S02E09 Monkey Dreams.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E10 - Do You Know Where Your Kids Are",
    "Freddy's Nightmares S02E10 Do You Know Where Your Kids Are.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E11 - Dreams That Kill",
    "Freddy's Nightmares S02E11 Dreams That Kill.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E12 - It's My Party and You'll Die If I Want You To",
    "Freddy's Nightmares S02E12 It's My Party and You'll Die If I Want You To.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E13 - What You Don't Know Can Kill You",
    "Freddy's Nightmares S02E13 What You Don't Know Can Kill You.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E14 - Easy Come, Easy Go",
    "Freddy's Nightmares S02E14 Easy Come, Easy Go.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E15 - Prime Cut",
    "Freddy's Nightmares S02E15 Prime Cut.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E16 - Interior Loft",
    "Freddy's Nightmares S02E16 Interior Loft.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E17 - Interior Loft-Later",
    "Freddy's Nightmares S02E17 Interior Loft-Later.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E18 - Funhouse",
    "Freddy's Nightmares S02E18 Funhouse.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E19 - A Family Affair",
    "Freddy's Nightmares S02E19 A Family Affair.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E20 - Dust To Dust",
    "Freddy's Nightmares S02E20 Dust To Dust.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E21 - Prisoner of Love",
    "Freddy's Nightmares S02E21 Prisoner of Love.mp4"],
  ['freddys-nightmares-complete-tv-series', "FREDDY'S NIGHTMARES - S02E22 - Life Sentence",
    "Freddy's Nightmares S02E22 Life Sentence.mp4"],
],
  durations: {
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E01 No More Mr. Nice Guy.mp4": 2805,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E02 It's a Miserable Life.mp4": 2811,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E03 Killer Instinct.mp4": 2803,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E04 Freddy's Tricks and Treats.mp4": 2805,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E05 Judy Miller, Come On Down.mp4": 2759,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E06 Saturday Night Special.mp4": 2777,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E07 Sister's Keeper.mp4": 2776,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E08 Mother's Day.mp4": 2777,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E09 Rebel Without a Car.mp4": 2777,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E10 The Bride Wore Red.mp4": 2768,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E11 Do Dreams Bleed.mp4": 2897,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E12 The End of the World.mp4": 2777,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E13 Deadline.mp4": 2777,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E14 Black Tickets.mp4": 2884,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E15 School Daze.mp4": 2902,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E16 Cabin Fever.mp4": 2870,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E17 Love Stinks.mp4": 2778,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E18 The Art of Death.mp4": 2780,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E19 Missing Persons.mp4": 2794,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E20 The Light At the End of the Tunnel.mp4": 2792,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E21 Identity Crisis.mp4": 2833,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S01E22 Safe Sex.mp4": 2757,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E01 Dream Come True.mp4": 2736,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E02 Heartbreak Hotel.mp4": 2758,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E03 Welcome to Springwood.mp4": 2782,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E04 Photo Finish.mp4": 2779,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E05 Memory Overload.mp4": 2756,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E06 Lucky Stiff.mp4": 2754,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E07 Silence is Golden.mp4": 2768,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E08 Bloodlines.mp4": 2768,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E09 Monkey Dreams.mp4": 2758,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E10 Do You Know Where Your Kids Are.mp4": 2735,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E11 Dreams That Kill.mp4": 2630,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E12 It's My Party and You'll Die If I Want You To.mp4": 2723,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E13 What You Don't Know Can Kill You.mp4": 2756,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E14 Easy Come, Easy Go.mp4": 2777,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E15 Prime Cut.mp4": 2768,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E16 Interior Loft.mp4": 2756,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E17 Interior Loft-Later.mp4": 2766,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E18 Funhouse.mp4": 2754,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E19 A Family Affair.mp4": 2781,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E20 Dust To Dust.mp4": 2762,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E21 Prisoner of Love.mp4": 2756,
  "freddys-nightmares-complete-tv-series::Freddy's Nightmares S02E22 Life Sentence.mp4": 2759,
},
};
