window.SHOW = {
  id: "SpiderManTAS",
  title: "Spider-Man: The Animated Series",
  storageProgressKey: "spidermantas-progress",
  storageSettingsKey: "spidermantas-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E01 - Night of the Lizard",
    "01x01 Night of the Lizard.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E02 - The Spider Slayer",
    "01x02 The Spider Slayer.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E03 - Return of the Spider Slayers",
    "01x03 Return of the Spider Slayers.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E04 - Doctor Octopus - Armed and Dangerous",
    "01x04 Doctor Octopus - Armed and Dangerous.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E05 - The Menace of Mysterio",
    "01x05 The Menace of Mysterio.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E06 - The Sting of the Scorpion",
    "01x06 The Sting of the Scorpion.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E07 - Kraven The Hunter",
    "01x07 Kraven The Hunter.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E08 - The Alien Costume (Part 1)",
    "01x08 The Alien Costume (Part 1).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E09 - The Alien Costume (Part 2)",
    "01x09 The Alien Costume (Part 2).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E10 - The Alien Costume (Part 3)",
    "01x10 The Alien Costume (Part 3).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E11 - The Hobgoblin (Part 1)",
    "01x11 The Hobgoblin (Part 1).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E12 - The Hobgoblin (Part 2)",
    "01x12 The Hobgoblin (Part 2).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S01E13 - Day of the Chameleon",
    "01x13 Day of the Chameleon.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E01 - The Insidious Six",
    "02x01 The Insidious Six.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E02 - Battle of the Insidious Six",
    "02x02 Battle of the Insidious Six.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E03 - Hydro-Man",
    "02x03 Hydro-Man.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E04 - The Mutant Agenda",
    "02x04 The Mutant Agenda.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E05 - Mutants' Revenge",
    "02x05 Mutants' Revenge.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E06 - Morbius",
    "02x06 Morbius.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E07 - Enter the Punisher",
    "02x07 Enter the Punisher.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E08 - Duel of the Hunters",
    "02x08 Duel of the Hunters.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E09 - Blade, The Vampire Hunter",
    "02x09 Blade, The Vampire Hunter.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E10 - The Immortal Vampire",
    "02x10 The Immortal Vampire.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E11 - Tablet of Time",
    "02x11 Tablet of Time.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E12 - Ravages of Time",
    "02x12 Ravages of Time.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E13 - Shriek of the Vulture",
    "02x13 Shriek of the Vulture.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S02E14 - The Final Nightmare",
    "02x14 The Final Nightmare.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E01 - Doctor Strange",
    "03x01 Doctor Strange.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E02 - Make A Wish",
    "03x02 Make A Wish.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E03 - Attack of the Octobot",
    "03x03 Attack of the Octobot.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E04 - Enter the Green Goblin",
    "03x04 Enter the Green Goblin.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E05 - The Rocket Racer",
    "03x05 The Rocket Racer.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E06 - Framed",
    "03x06 Framed.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E07 - The Man Without Fear",
    "03x07 The Man Without Fear.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E08 - The Ultimate Slayer",
    "03x08 The Ultimate Slayer.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E09 - Tombstone",
    "03x09 Tombstone.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E10 - Venom Returns",
    "03x10 Venom Returns.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E11 - Carnage",
    "03x11 Carnage.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E12 - The Spot",
    "03x12 The Spot.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E13 - Goblin War",
    "03x13 Goblin War.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S03E14 - Turning Point",
    "03x14 Turning Point.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E01 - Guilty",
    "04x01 Guilty.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E02 - The Cat",
    "04x02 The Cat.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E03 - The Black Cat",
    "04x03 The Black Cat.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E04 - The Return of Kraven",
    "04x04 The Return of Kraven.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E05 - Partners",
    "04x05 Partners.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E06 - The Awakening",
    "04x06 The Awakening.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E07 - The Vampire Queen",
    "04x07 The Vampire Queen.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E08 - The Return of the Green Goblin",
    "04x08 The Return of the Green Goblin.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E09 - The Haunting of Mary Jane Watson",
    "04x09 The Haunting of Mary Jane Watson.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E10 - The Lizard King",
    "04x10 The Lizard King.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S04E11 - The Prowler",
    "04x11 The Prowler.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E01 - The Wedding",
    "05x01 The Wedding.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E02 - Six Forgotten Warriors",
    "05x02 Six Forgotten Warriors.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E03 - Unclaimed Legacy",
    "05x03 Unclaimed Legacy.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E04 - Secrets of the Six",
    "05x04 Secrets of the Six.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E05 - The Six Fight Again",
    "05x05 The Six Fight Again.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E06 - The Price of Heroism",
    "05x06 The Price of Heroism.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E07 - The Return of Hydro-Man (Part 1)",
    "05x07 The Return of Hydro-Man (Part 1).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E08 - The Return of Hydro-Man (Part 2)",
    "05x08 The Return of Hydro-Man (Part 2).mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E09 - Arrival",
    "05x09 Arrival.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E10 - The Gauntlet of the Red Skull",
    "05x10 The Gauntlet of the Red Skull.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E11 - Doom",
    "05x11 Doom.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E12 - I Really, Really Hate Clones",
    "05x12 I Really, Really Hate Clones.mp4"],
  ['spider-mantheanimatedseries', "SPIDER-MAN: THE ANIMATED SERIES - S05E13 - Farewell, Spider-Man",
    "05x13 Farewell, Spider-Man.mp4"],
],
  durations: {
  "spider-mantheanimatedseries::01x01 Night of the Lizard.mp4": 1149,
  "spider-mantheanimatedseries::01x02 The Spider Slayer.mp4": 1197,
  "spider-mantheanimatedseries::01x03 Return of the Spider Slayers.mp4": 1195,
  "spider-mantheanimatedseries::01x04 Doctor Octopus - Armed and Dangerous.mp4": 1186,
  "spider-mantheanimatedseries::01x05 The Menace of Mysterio.mp4": 1155,
  "spider-mantheanimatedseries::01x06 The Sting of the Scorpion.mp4": 1193,
  "spider-mantheanimatedseries::01x07 Kraven The Hunter.mp4": 1134,
  "spider-mantheanimatedseries::01x08 The Alien Costume (Part 1).mp4": 1213,
  "spider-mantheanimatedseries::01x09 The Alien Costume (Part 2).mp4": 1196,
  "spider-mantheanimatedseries::01x10 The Alien Costume (Part 3).mp4": 1192,
  "spider-mantheanimatedseries::01x11 The Hobgoblin (Part 1).mp4": 1221,
  "spider-mantheanimatedseries::01x12 The Hobgoblin (Part 2).mp4": 1224,
  "spider-mantheanimatedseries::01x13 Day of the Chameleon.mp4": 1192,
  "spider-mantheanimatedseries::02x01 The Insidious Six.mp4": 1220,
  "spider-mantheanimatedseries::02x02 Battle of the Insidious Six.mp4": 1191,
  "spider-mantheanimatedseries::02x03 Hydro-Man.mp4": 1191,
  "spider-mantheanimatedseries::02x04 The Mutant Agenda.mp4": 1153,
  "spider-mantheanimatedseries::02x05 Mutants' Revenge.mp4": 1218,
  "spider-mantheanimatedseries::02x06 Morbius.mp4": 1221,
  "spider-mantheanimatedseries::02x07 Enter the Punisher.mp4": 1220,
  "spider-mantheanimatedseries::02x08 Duel of the Hunters.mp4": 1221,
  "spider-mantheanimatedseries::02x09 Blade, The Vampire Hunter.mp4": 1202,
  "spider-mantheanimatedseries::02x10 The Immortal Vampire.mp4": 1222,
  "spider-mantheanimatedseries::02x11 Tablet of Time.mp4": 1224,
  "spider-mantheanimatedseries::02x12 Ravages of Time.mp4": 1221,
  "spider-mantheanimatedseries::02x13 Shriek of the Vulture.mp4": 1222,
  "spider-mantheanimatedseries::02x14 The Final Nightmare.mp4": 1218,
  "spider-mantheanimatedseries::03x01 Doctor Strange.mp4": 1193,
  "spider-mantheanimatedseries::03x02 Make A Wish.mp4": 1222,
  "spider-mantheanimatedseries::03x03 Attack of the Octobot.mp4": 1222,
  "spider-mantheanimatedseries::03x04 Enter the Green Goblin.mp4": 1221,
  "spider-mantheanimatedseries::03x05 The Rocket Racer.mp4": 1222,
  "spider-mantheanimatedseries::03x06 Framed.mp4": 1222,
  "spider-mantheanimatedseries::03x07 The Man Without Fear.mp4": 1222,
  "spider-mantheanimatedseries::03x08 The Ultimate Slayer.mp4": 1221,
  "spider-mantheanimatedseries::03x09 Tombstone.mp4": 1220,
  "spider-mantheanimatedseries::03x10 Venom Returns.mp4": 1216,
  "spider-mantheanimatedseries::03x11 Carnage.mp4": 1222,
  "spider-mantheanimatedseries::03x12 The Spot.mp4": 1183,
  "spider-mantheanimatedseries::03x13 Goblin War.mp4": 1222,
  "spider-mantheanimatedseries::03x14 Turning Point.mp4": 1223,
  "spider-mantheanimatedseries::04x01 Guilty.mp4": 1192,
  "spider-mantheanimatedseries::04x02 The Cat.mp4": 1194,
  "spider-mantheanimatedseries::04x03 The Black Cat.mp4": 1220,
  "spider-mantheanimatedseries::04x04 The Return of Kraven.mp4": 1198,
  "spider-mantheanimatedseries::04x05 Partners.mp4": 1220,
  "spider-mantheanimatedseries::04x06 The Awakening.mp4": 1220,
  "spider-mantheanimatedseries::04x07 The Vampire Queen.mp4": 1221,
  "spider-mantheanimatedseries::04x08 The Return of the Green Goblin.mp4": 1220,
  "spider-mantheanimatedseries::04x09 The Haunting of Mary Jane Watson.mp4": 1222,
  "spider-mantheanimatedseries::04x10 The Lizard King.mp4": 1222,
  "spider-mantheanimatedseries::04x11 The Prowler.mp4": 1193,
  "spider-mantheanimatedseries::05x01 The Wedding.mp4": 1221,
  "spider-mantheanimatedseries::05x02 Six Forgotten Warriors.mp4": 1222,
  "spider-mantheanimatedseries::05x03 Unclaimed Legacy.mp4": 1220,
  "spider-mantheanimatedseries::05x04 Secrets of the Six.mp4": 1222,
  "spider-mantheanimatedseries::05x05 The Six Fight Again.mp4": 1221,
  "spider-mantheanimatedseries::05x06 The Price of Heroism.mp4": 1221,
  "spider-mantheanimatedseries::05x07 The Return of Hydro-Man (Part 1).mp4": 1221,
  "spider-mantheanimatedseries::05x08 The Return of Hydro-Man (Part 2).mp4": 1222,
  "spider-mantheanimatedseries::05x09 Arrival.mp4": 1192,
  "spider-mantheanimatedseries::05x10 The Gauntlet of the Red Skull.mp4": 1221,
  "spider-mantheanimatedseries::05x11 Doom.mp4": 1221,
  "spider-mantheanimatedseries::05x12 I Really, Really Hate Clones.mp4": 1221,
  "spider-mantheanimatedseries::05x13 Farewell, Spider-Man.mp4": 1221,
},
};
