window.SHOW = {
  id: "JimHensonHour",
  title: "The Jim Henson Hour",
  art: "JimHensonHour.jpg",
  storageProgressKey: "jimhensonhour-progress",
  storageSettingsKey: "jimhensonhour-settings",
  nestedPaths: false,
  grouping: "season",
  segments: "none",
  episodes: [
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E00 - (Inner Tube) The Jim Henson Hour Test Pilot",
    "00 - (Inner Tube) The Jim Henson Hour Test Pilot.mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E00 - The Jim Henson Hour (Pitch Reel)",
    "00 - The Jim Henson Hour (Pitch Reel).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E01 - The Jim Henson Hour (Outer Space:The Heartless Giant)",
    "01 - The Jim Henson Hour (Outer Space:The Heartless Giant).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E02 - The Jim Henson Hour (Oceans:Lighthouse Island)",
    "02 - The Jim Henson Hour (Oceans:Lighthouse Island).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E03 - The Jim Henson Hour (Power:The Soldier and Death)",
    "03 - The Jim Henson Hour (Power:The Soldier and Death).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E04 - The Jim Henson Hour (Dog City)",
    "04 - The Jim Henson Hour (Dog City).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E05a - The Jim Henson Hour (First Show)",
    "05a - The Jim Henson Hour (First Show).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E05b - The Jim Henson Hour (Miss Piggys Hollywood)",
    "05b - The Jim Henson Hour (Miss Piggys Hollywood).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E06 - The Jim Henson Hour (Monster Maker)",
    "06 - The Jim Henson Hour (Monster Maker).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E07 - The Jim Henson Hour (Fitness:Song of the Cloud Forest)",
    "07 - The Jim Henson Hour (Fitness:Song of the Cloud Forest).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E08 - The Jim Henson Hour (Videotape:The True Bride)",
    "08 - The Jim Henson Hour (Videotape:The True Bride).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E09 - The Jim Henson Hour (Garbage:Sapsorrow)",
    "09 - The Jim Henson Hour (Garbage:Sapsorrow).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E10 - The Jim Henson Hour (Secrets of the Muppets)",
    "10 - The Jim Henson Hour (Secrets of the Muppets).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E11 - The Jim Henson Hour (Living with Dinosaurs)",
    "11 - The Jim Henson Hour (Living with Dinosaurs).mp4"],
  ['04TheJimHensonHourDogCity', "THE JIM HENSON HOUR - S01E12 - The Jim Henson Hour (Food:The Three Ravens)",
    "12 - The Jim Henson Hour (Food:The Three Ravens).mp4"],
],
  durations: {
  "04TheJimHensonHourDogCity::00 - (Inner Tube) The Jim Henson Hour Test Pilot.mp4": 608,
  "04TheJimHensonHourDogCity::00 - The Jim Henson Hour (Pitch Reel).mp4": 756,
  "04TheJimHensonHourDogCity::01 - The Jim Henson Hour (Outer Space:The Heartless Giant).mp4": 2836,
  "04TheJimHensonHourDogCity::02 - The Jim Henson Hour (Oceans:Lighthouse Island).mp4": 2910,
  "04TheJimHensonHourDogCity::03 - The Jim Henson Hour (Power:The Soldier and Death).mp4": 2911,
  "04TheJimHensonHourDogCity::04 - The Jim Henson Hour (Dog City).mp4": 2910,
  "04TheJimHensonHourDogCity::05a - The Jim Henson Hour (First Show).mp4": 1591,
  "04TheJimHensonHourDogCity::05b - The Jim Henson Hour (Miss Piggys Hollywood).mp4": 1385,
  "04TheJimHensonHourDogCity::06 - The Jim Henson Hour (Monster Maker).mp4": 2897,
  "04TheJimHensonHourDogCity::07 - The Jim Henson Hour (Fitness:Song of the Cloud Forest).mp4": 2914,
  "04TheJimHensonHourDogCity::08 - The Jim Henson Hour (Videotape:The True Bride).mp4": 2904,
  "04TheJimHensonHourDogCity::09 - The Jim Henson Hour (Garbage:Sapsorrow).mp4": 2914,
  "04TheJimHensonHourDogCity::10 - The Jim Henson Hour (Secrets of the Muppets).mp4": 2846,
  "04TheJimHensonHourDogCity::11 - The Jim Henson Hour (Living with Dinosaurs).mp4": 2913,
  "04TheJimHensonHourDogCity::12 - The Jim Henson Hour (Food:The Three Ravens).mp4": 2863,
},
};
