window.SHOW = {
  id: "DragonBallZKai",
  title: "Dragon Ball Z Kai",
  art: "DragonBallZKai.jpg",
  storageProgressKey: "dragonballzkai-progress",
  storageSettingsKey: "dragonballzkai-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  seasonNames: {
    1: "Saiyan Saga",
    2: "Frieza Saga",
    3: "Androids and Cell Saga",
    4: "Cell Games Saga",
  },
  episodes: [
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E01 - The Curtain Rises for Battle! The Return of Son Goku",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 01 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E02 - The Enemy is Goku's Brother?! The Secret of the Mighty Saiyan Warriors!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 02 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E03 - Life or Death Battle! Goku and Piccolo's Fierce Suicidal Attack",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 03 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E04 - Son Goku Runs in the Afterlife! The Million Kilometer Serpent Road",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 04 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E05 - Wilderness Survival! A Moonlit Night Awakens Gohan!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 05 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E06 - Finally Arriving at the End! Kaio-sama's Playful Test",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 06 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E07 - Battle with 10-Fold Gravity! Goku, Your Training is a Footrace",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 07 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E08 - Come Forth, Shenlong! The Saiyans Finally Arrive on Earth",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 08 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E09 - Yamucha's Struggle! The Terrifying Saibaimen",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 09 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E10 - Wait, Chaozu! Tenshinhan's Screaming Kikōhō",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 10 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E11 - Will Son Goku Make It?! The Battle Resumes in 3 Hours",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 11 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E12 - The Tears Piccolo Shed... Son Goku's Furious Counterattack!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 12 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E13 - This is the Kaio-Ken!! A Battle to the Limit of Goku vs. Vegeta",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 13 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E14 - Kamehameha Clash! Vegeta's Tenacious Transformation",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 14 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E15 - Goku in Absolute Peril! Entrust Your Wishes to the Genki-Dama",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 15 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E16 - The Invincible Vegeta Defeated! Son Gohan Summons a Miracle",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 16 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E17 - Dawn of a Fierce Battle! The Star of Hope is Piccolo's Homeland!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 17 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S01E18 - The Ship Resting in Yunzabit! Time to Blast Off for Planet Namek!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 18 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E01 - A Formidable New Enemy! Emperor of the Universe, Freeza",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 19 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E02 - Rebellion Against Freeza! Vegeta, Burning with Ambition",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 20 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E03 - Protect the Dragon Balls! The Namekian Offensive",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 21 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E04 - Dodoria in Terrifying Hot Pursuit! Vegeta Learns the Truth",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 22 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E05 - Vegeta's Secret Maneuvering! The Tragic Attack Upon the Namekians",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 23 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E06 - Resurrected Comrades! The Handsome Warrior Zarbon's Devilish Transformation",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 24 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E07 - Power Up for Kuririn! Freeza's Nagging Premonition",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 25 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E08 - The Conspiracy Shatters! The Counterattack of Vegeta vs. Zarbon",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 26 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E09 - A Hair-Trigger Pinch! Gohan, Protect the Four-Star Ball",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 27 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E10 - The Super Decisive Battle Draws Near! The Ginyu Special Squadron Has Arrived!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 28 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E11 - The Special Squadron's Frontline Man! Break Gurd's Spell",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 29 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E12 - The Hellish Recoome! Keep Me Entertained Vegeta-chan",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 30 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E13 - Son Goku Finally Arrives! Knock the Ginyu Special Squadron Around",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 31 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E14 - The Star Performer Takes the Stage!? Captain Ginyu vs. Son Goku",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 32 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E15 - Son Goku at Full Power! The Terrified Ginyu Has Something Up His Sleeve!?",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 33 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E16 - Surprise! Goku is Ginyu and Ginyu is Goku?!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 34 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E17 - A Great Turnabout for Goku!? Super Shenlong, Come Out Right Now!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 35 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E18 - An Enraged Freeza Draws Near! Polunga... Grant This Wish!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 36 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E19 - A Nightmarish Super Transformation! Freeza's Battle Power Reaches 1-Million",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 37 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E20 - Freeza Bares His Fangs! Gohan's Transcendent Power Attacks",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 38 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E21 - The Reborn Piccolo Arrives! A Furious Freeza's 2nd Transformation",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 39 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E22 - Freeza's Final Super Transformation! The Terror Greater than Hell Begins",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 40 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E23 - The Moment We've Waited For! Son Goku is Revived",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 41 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E24 - Defeat Freeza, Son Goku! The Proud Vegeta's Tears",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 42 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E25 - Son Goku vs. Freeza! The Curtain Opens on the Super Decisive Battle!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 43 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E26 - A Physical War That Exceeds All Limits! Goku and Freeza and Ginyu Again!?",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 44 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E27 - It's a 20-Fold Kaiō-ken! A Kamehameha With Everything on the Line",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 45 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E28 - This is the Last Trump Card! Goku's Extra-Large Genki-Dama",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 46 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E29 - Awaken Warrior of Legend... Super Saiyan, Son Goku!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 47 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E30 - The Angry Super Saiyan! Throw Your Hat in the Ring, Son Goku!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 48 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E31 - Exact Vengeance, Son Goku! Countdown to the Planet's Collapse",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 49 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E32 - Freeza's Do-or-Die Full Power! Shenlong, Heed This Wish",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 50 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E33 - Goku's Furious Battle Cry! Make It in Time... The Resurrection Wish!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 51 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E34 - Two Remain on a Vanishing Planet! This is the Final Showdown",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 52 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E35 - The Final Blow, Son Goku... Planet Namek Scatters Throughout Space",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 53 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S02E36 - Goku Vanishes in Space... Return to Life! Super Warriors",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 54 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E01 - That's Earth, Papa... Freeza and His Father Strike Back",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 55 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E02 - I'll Defeat Freeza! Another Super Saiyan",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 56 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E03 - Welcome Back Son Goku! The Confession of the Mysterious Young Boy Trunks",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 57 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E04 - New Technique of Goku, Instant Movement! Special Training Staked on 3 Years From Now",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 58 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E05 - The Pair Who Don't Leave a Trace! The Artificial Humans Appear",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 59 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E06 - Attacked on Both Sides by an Internal Enemy?! Son Goku vs Artificial Human #19",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 60 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E07 - No Chance of Victory Against #19! Super Vegeta Arrives Late",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 61 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E08 - Piccolo's Assault! The Missing #20 and the Future Gone Askew",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 62 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E09 - Pursue! Doctor Gero... The Search for the Mysterious Laboratory!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 63 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E10 - #17 and #18, and...! The Artificial Humans Awaken",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 64 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E11 - A Cute Face and Super Power?! #18 vs Vegeta",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 65 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E12 - The Time has Come to Become One Again... Piccolo's Decision for Ultimate Power!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 66 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E13 - One More Time Machine?! Bulma Unveils a Mystery",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 67 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E14 - And So the Monster Makes its Move... Take Off! It's the Super Namekian!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 68 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E15 - I am Your Sibling! The Monster with the Ki of Goku",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 69 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E16 - Escape Tactic, Taiyoken! Chase after the Artificial Human Cell",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 70 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E17 - Attack the Elusive Cell! Son Goku, Finally Revived!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 71 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E18 - Surpass Super Saiyan! Now, Into the Room of Spirit and Time",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 72 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E19 - This is the Power of a Super-Namekian! #17 vs. Piccolo!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 73 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E20 - Run #17! Piccolo, A Battle for Suicidal Resistance",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 74 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E21 - Unmeasured Power! The Silent Warrior #16, Makes his Move",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 75 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E22 - Tenshinhan's Do-or-Die Shin Kikoho! Save Your Brother-in-Arms, Son Goku",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 76 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E23 - Super Saiyan Surpassed! The Daring Vegeta Strikes Cell",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 77 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E24 - The Surging Resentment of Cell! Kuririn, Destroy #18",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 78 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E25 - And So the Situation Takes a Turn for the Worst... Cell Attacks #18!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 79 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E26 - The Tables Have Turned! Perfect Form Cell, Finally Goes into Action",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 80 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E27 - Full-Power Strike of Vegeta! But the Terror of Cell Grows and Grows",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 81 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S03E28 - Super Power Awakening! Trunks Surpasses his Father",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 82 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E01 - The Television Has Been Hijacked! A Live Broadcast of the Cell Games Press Conference",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 83 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E02 - Training Completed! Goku, Does he have the Composure to Defeat Cell?!",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 84 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E03 - An Interrupted Rest! The Self-Defense Army, Launches a General Offensive Against Cell",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 85 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E04 - A New God! The Dragon Balls are Finally Revived",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 86 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E05 - Satan's Legion Runs Wild! The Curtain Rises on the Cell Games",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 87 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E06 - Decisive Battle! Cell vs Son Goku",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 88 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E07 - A Battle of the Highest Level! Defeat Cell, Son Goku",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 89 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E08 - Conclusion to the Death Match! Time for Goku's Decision",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 90 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E09 - Get Angry Gohan! Release Your Dormant Power",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 91 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E10 - The Tears that Disappeared into the Sky! The Angry Super Awakening of Gohan",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 92 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E11 - Fighting Spirit Free from Hesitation! Gohan, Pulverizes the Cell Juniors",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 93 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E12 - The Perfect Form Breaks Down! Explosion, the Super Iron Fist of Rage",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 94 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E13 - Bye-Bye Everyone! This is the Only Way to Save the Earth",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 95 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E14 - Combine Our Power! The Mightiest Final Kamehameha",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 96 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E15 - Farewell with a Smile! Heading for New Days...",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 97 [Cut][C-W].avi"],
  ['dbz-kai-nick', "DRAGON BALL Z KAI - S04E16 - Bring Peace to the Future! Goku's Spirit is Eternal",
    "[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 98 [Uncut BD Version][C-W].avi"],
],
  durations: {
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 01 [Cut][C-W].avi": 1276,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 02 [Cut][C-W].avi": 1325,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 03 [Cut][C-W].avi": 1304,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 04 [Cut][C-W].avi": 1312,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 05 [Cut][C-W].avi": 1289,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 06 [Cut][C-W].avi": 1259,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 07 [Cut][C-W].avi": 1236,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 08 [Cut][C-W].avi": 1250,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 09 [Cut][C-W].avi": 1288,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 10 [Cut][C-W].avi": 1273,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 11 [Cut][C-W].avi": 1263,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 12 [Cut][C-W].avi": 1255,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 13 [Cut][C-W].avi": 1254,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 14 [Cut][C-W].avi": 1255,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 15 [Cut][C-W].avi": 1250,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 16 [Cut][C-W].avi": 1267,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 17 [Cut][C-W].avi": 1268,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 18 [Cut][C-W].avi": 1289,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 19 [Cut][C-W].avi": 1257,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 20 [Cut][C-W].avi": 1287,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 21 [Cut][C-W].avi": 1311,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 22 [Cut][C-W].avi": 1297,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 23 [Cut][C-W].avi": 1326,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 24 [Cut][C-W].avi": 1310,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 25 [Cut][C-W].avi": 1296,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/1 - Season One/Dragon Ball Z Kai - 26 [Cut][C-W].avi": 1297,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 27 [Cut][C-W].avi": 1318,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 28 [Cut][C-W].avi": 1304,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 29 [Cut][C-W].avi": 1289,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 30 [Cut][C-W].avi": 1281,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 31 [Cut][C-W].avi": 1266,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 32 [Cut][C-W].avi": 1317,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 33 [Cut][C-W].avi": 1306,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 34 [Cut][C-W].avi": 1302,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 35 [Cut][C-W].avi": 1318,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 36 [Cut][C-W].avi": 1308,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 37 [Cut][C-W].avi": 1305,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 38 [Cut][C-W].avi": 1224,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 39 [Cut][C-W].avi": 1246,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 40 [Cut][C-W].avi": 1310,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 41 [Cut][C-W].avi": 1222,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 42 [Cut][C-W].avi": 1169,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 43 [Cut][C-W].avi": 1326,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 44 [Cut][C-W].avi": 1255,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 45 [Cut][C-W].avi": 1269,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 46 [Cut][C-W].avi": 1269,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 47 [Cut][C-W].avi": 1319,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 48 [Cut][C-W].avi": 1322,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 49 [Cut][C-W].avi": 1309,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 50 [Cut][C-W].avi": 1304,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 51 [Cut][C-W].avi": 1320,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/2 - Season Two/Dragon Ball Z Kai - 52 [Cut][C-W].avi": 1223,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 53 [Cut][C-W].avi": 1273,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 54 [Cut][C-W].avi": 1326,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 55 [Cut][C-W].avi": 1287,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 56 [Cut][C-W].avi": 1273,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 57 [Cut][C-W].avi": 1276,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 58 [Cut][C-W].avi": 1263,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 59 [Cut][C-W].avi": 1241,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 60 [Cut][C-W].avi": 1240,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 61 [Cut][C-W].avi": 1255,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 62 [Cut][C-W].avi": 1282,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 63 [Cut][C-W].avi": 1284,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 64 [Cut][C-W].avi": 1266,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 65 [Cut][C-W].avi": 1267,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 66 [Cut][C-W].avi": 1288,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 67 [Cut][C-W].avi": 1286,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 68 [Cut][C-W].avi": 1248,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 69 [Cut][C-W].avi": 1228,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 70 [Cut][C-W].avi": 1280,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 71 [Cut][C-W].avi": 1287,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 72 [Cut][C-W].avi": 1286,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 73 [Cut][C-W].avi": 1199,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 74 [Cut][C-W].avi": 1240,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 75 [Cut][C-W].avi": 1281,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 76 [Cut][C-W].avi": 1284,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/3 - Season Three/Dragon Ball Z Kai - 77 [Cut][C-W].avi": 1283,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 78 [Cut][C-W].avi": 1281,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 79 [Cut][C-W].avi": 1281,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 80 [Cut][C-W].avi": 1288,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 81 [Cut][C-W].avi": 1254,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 82 [Cut][C-W].avi": 1286,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 83 [Cut][C-W].avi": 1270,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 84 [Cut][C-W].avi": 1247,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 85 [Cut][C-W].avi": 1265,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 86 [Cut][C-W].avi": 1288,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 87 [Cut][C-W].avi": 1252,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 88 [Cut][C-W].avi": 1276,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 89 [Cut][C-W].avi": 1192,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 90 [Cut][C-W].avi": 1279,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 91 [Cut][C-W].avi": 1221,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 92 [Cut][C-W].avi": 1253,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 93 [Cut][C-W].avi": 1240,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 94 [Cut][C-W].avi": 1239,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 95 [Cut][C-W].avi": 1252,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 96 [Cut][C-W].avi": 1245,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 97 [Cut][C-W].avi": 1258,
  "dbz-kai-nick::[TC] [SoM] Dragon Ball Z Kai [Nicktoons] [Tv Rip]/4 - Season Four/Dragon Ball Z Kai - 98 [Uncut BD Version][C-W].avi": 1352,
},
};
