window.SHOW = {
  id: "WonderYears",
  title: "The Wonder Years",
  storageProgressKey: "wonderyears-progress",
  storageSettingsKey: "wonderyears-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S01E01 - Pilot",
    "The Wonder Years S01E01 - Pilot.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S01E02 - Swingers",
    "The Wonder Years S01E02 - Swingers.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S01E03 - My Father's Office",
    "The Wonder Years S01E03 - My Father's Office.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S01E04 - Angel",
    "The Wonder Years S01E04 - Angel.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S01E05 - The Phone Call",
    "The Wonder Years S01E05 - The Phone Call.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S01E06 - Dance with Me",
    "The Wonder Years S01E06 - Dance with Me.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E01 - Heart of Darkness",
    "The Wonder Years S02E01 - Heart of Darkness.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E02 - Our Miss White",
    "The Wonder Years S02E02 - Our Miss White.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E03 - Christmas",
    "The Wonder Years S02E03 - Christmas.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E04 - Steady as She Goes",
    "The Wonder Years S02E04 - Steady as She Goes.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E05 - Just Between Me and You and Kirk and Paul and Carla and Becky",
    "The Wonder Years S02E05 - Just Between Me and You and Kirk and Paul and Carla and Becky.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E06 - Pottery Will Get You Nowhere",
    "The Wonder Years S02E06 - Pottery Will Get You Nowhere.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E07 - Coda",
    "The Wonder Years S02E07 - Coda.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E08 - Hiroshima, Mon Frere",
    "The Wonder Years S02E08 - Hiroshima, Mon Frere.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E09 - Loosiers",
    "The Wonder Years S02E09 - Loosiers.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E10 - Walk Out",
    "The Wonder Years S02E10 - Walk Out.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E11 - Nemesis",
    "The Wonder Years S02E11 - Nemesis.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E12 - Fate",
    "The Wonder Years S02E12 - Fate.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E13 - Birthday Boy",
    "The Wonder Years S02E13 - Birthday Boy.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E14 - Brightwing",
    "The Wonder Years S02E14 - Brightwing.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E15 - Square Dance",
    "The Wonder Years S02E15 - Square Dance.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E16 - Whose Woods Are These",
    "The Wonder Years S02E16 - Whose Woods Are These.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S02E17 - How I'm Spending My Summer Vacation",
    "The Wonder Years S02E17 - How I'm Spending My Summer Vacation.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E01 - Summer Song",
    "The Wonder Years S03E01 - Summer Song.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E02 - Math Class",
    "The Wonder Years S03E02 - Math Class.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E03 - Wayne on Wheels",
    "The Wonder Years S03E03 - Wayne on Wheels.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E04 - Mom Wars",
    "The Wonder Years S03E04 - Mom Wars.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E05 - On The Spot",
    "The Wonder Years S03E05 - On The Spot.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E06 - Odd Man Out",
    "The Wonder Years S03E06 - Odd Man Out.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E07 - The Family Car",
    "The Wonder Years S03E07 - The Family Car.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E08 - The Pimple",
    "The Wonder Years S03E08 - The Pimple.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E09 - Math Class Squared",
    "The Wonder Years S03E09 - Math Class Squared.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E10 - Rock 'n Roll",
    "The Wonder Years S03E10 - Rock 'n Roll.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E11 - Don't You Know Anything About Women",
    "The Wonder Years S03E11 - Don't You Know Anything About Women.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E12 - The Powers That Be",
    "The Wonder Years S03E12 - The Powers That Be.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E13 - She, My Friend and I",
    "The Wonder Years S03E13 - She, My Friend and I.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E14 - The St. Valentine's Day Massacre",
    "The Wonder Years S03E14 - The St. Valentine's Day Massacre.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E15 - The Tree House",
    "The Wonder Years S03E15 - The Tree House.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E16 - The Glee Club",
    "The Wonder Years S03E16 - The Glee Club.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E17 - Night Out",
    "The Wonder Years S03E17 - Night Out.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E18 - Faith",
    "The Wonder Years S03E18 - Faith.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E19 - The Unnatural",
    "The Wonder Years S03E19 - The Unnatural.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E20 - Goodbye",
    "The Wonder Years S03E20 - Goodbye.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E21 - Cocoa and Sympathy",
    "The Wonder Years S03E21 - Cocoa and Sympathy.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E22 - Daddy's Little Girl",
    "The Wonder Years S03E22 - Daddy's Little Girl.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S03E23 - Moving",
    "The Wonder Years S03E23 - Moving.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E01 - Growing Up",
    "The Wonder Years S04E01 - Growing Up.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E02 - Ninth Grade Man",
    "The Wonder Years S04E02 - Ninth Grade Man.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E03 - The Journey",
    "The Wonder Years S04E03 - The Journey.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E04 - The Cost of Living",
    "The Wonder Years S04E04 - The Cost of Living.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E05 - It's A Mad, Mad, Madeline World",
    "The Wonder Years S04E05 - It's A Mad, Mad, Madeline World.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E06 - Little Debbie",
    "The Wonder Years S04E06 - Little Debbie.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E07 - The Ties That Bind",
    "The Wonder Years S04E07 - The Ties That Bind.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E08 - The Sixth Man",
    "The Wonder Years S04E08 - The Sixth Man.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E09 - A Very Cutlip Christmas",
    "The Wonder Years S04E09 - A Very Cutlip Christmas.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E10 - The Candidate",
    "The Wonder Years S04E10 - The Candidate.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E11 - Heartbreak",
    "The Wonder Years S04E11 - Heartbreak.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E12 - Denial",
    "The Wonder Years S04E12 - Denial.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E13 - Who's Aunt Rose",
    "The Wonder Years S04E13 - Who's Aunt Rose.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E14 - Courage",
    "The Wonder Years S04E14 - Courage.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E15 - Buster",
    "The Wonder Years S04E15 - Buster.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E16 - Road Trip",
    "The Wonder Years S04E16 - Road Trip.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E17 - When Worlds Collide",
    "The Wonder Years S04E17 - When Worlds Collide.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E18 - Separate Rooms",
    "The Wonder Years S04E18 - Separate Rooms.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E19 - The Yearbook",
    "The Wonder Years S04E19 - The Yearbook.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E20 - The Accident",
    "The Wonder Years S04E20 - The Accident.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E21 - The House That Jack Built",
    "The Wonder Years S04E21 - The House That Jack Built.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E22 - Graduation",
    "The Wonder Years S04E22 - Graduation.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S04E23 - The Wonder Years",
    "The Wonder Years S04E23 - The Wonder Years.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E01 - The Lake",
    "The Wonder Years S05E01 - The Lake.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E02 - Day One",
    "The Wonder Years S05E02 - Day One.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E03 - The Hardware Store",
    "The Wonder Years S05E03 - The Hardware Store.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E04 - Frank and Denise",
    "The Wonder Years S05E04 - Frank and Denise.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E05 - Full Moon Rising",
    "The Wonder Years S05E05 - Full Moon Rising.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E06 - Triangle",
    "The Wonder Years S05E06 - Triangle.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E07 - Soccer",
    "The Wonder Years S05E07 - Soccer.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E08 - Dinner Out",
    "The Wonder Years S05E08 - Dinner Out.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E09 - Christmas Party",
    "The Wonder Years S05E09 - Christmas Party.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E10 - Pfeiffer's Choice",
    "The Wonder Years S05E10 - Pfeiffer's Choice.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E11 - Road Test",
    "The Wonder Years S05E11 - Road Test.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E12 - Grandpa's Car",
    "The Wonder Years S05E12 - Grandpa's Car.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E13 - Kodachrome",
    "The Wonder Years S05E13 - Kodachrome.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E14 - Private Butthead",
    "The Wonder Years S05E14 - Private Butthead.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E15 - Of Mastodons and Men",
    "The Wonder Years S05E15 - Of Mastodons and Men.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E16 - Double Double Date",
    "The Wonder Years S05E16 - Double Double Date.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E17 - Hero",
    "The Wonder Years S05E17 - Hero.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E18 - Lunch Stories",
    "The Wonder Years S05E18 - Lunch Stories.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E19 - Carnal Knowledge",
    "The Wonder Years S05E19 - Carnal Knowledge.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E20 - The Lost Weekend",
    "The Wonder Years S05E20 - The Lost Weekend.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E21 - Stormy Weather",
    "The Wonder Years S05E21 - Stormy Weather.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E22 - The Wedding",
    "The Wonder Years S05E22 - The Wedding.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E23 - Back to The Lake",
    "The Wonder Years S05E23 - Back to The Lake.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S05E24 - Broken Hearts and Burgers",
    "The Wonder Years S05E24 - Broken Hearts and Burgers.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E01 - Homecoming",
    "The Wonder Years S06E01 - Homecoming.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E02 - Fishing",
    "The Wonder Years S06E02 - Fishing.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E03 - Scenes from A Wedding",
    "The Wonder Years S06E03 - Scenes from A Wedding.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E04 - Sex and Economics",
    "The Wonder Years S06E04 - Sex and Economics.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E05 - Politics as Usual",
    "The Wonder Years S06E05 - Politics as Usual.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E06 - White Lies",
    "The Wonder Years S06E06 - White Lies.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E07 - Wayne and Bonnie",
    "The Wonder Years S06E07 - Wayne and Bonnie.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E08 - Kevin Delivers",
    "The Wonder Years S06E08 - Kevin Delivers.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E09 - The Test",
    "The Wonder Years S06E09 - The Test.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E10 - Let Nothing You Dismay",
    "The Wonder Years S06E10 - Let Nothing You Dismay.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E11 - New Years",
    "The Wonder Years S06E11 - New Years.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E12 - Alice in Autoland",
    "The Wonder Years S06E12 - Alice in Autoland.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E13 - Ladies and Gentlemen... The Rolling Stones",
    "The Wonder Years S06E13 - Ladies and Gentlemen... The Rolling Stones.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E14 - Unpacking",
    "The Wonder Years S06E14 - Unpacking.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E15 - Hulk Arnold",
    "The Wonder Years S06E15 - Hulk Arnold.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E16 - Nose",
    "The Wonder Years S06E16 - Nose.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E17 - Eclipse",
    "The Wonder Years S06E17 - Eclipse.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E18 - Poker",
    "The Wonder Years S06E18 - Poker.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E19 - The Little Women",
    "The Wonder Years S06E19 - The Little Women.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E20 - Reunion",
    "The Wonder Years S06E20 - Reunion.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E21 - Summer",
    "The Wonder Years S06E21 - Summer.mp4"],
  ['the-wonder-years-complete-series', "THE WONDER YEARS - S06E22 - Independence Day",
    "The Wonder Years S06E22 - Independence Day.mp4"],
],
  durations: {
  "the-wonder-years-complete-series::The Wonder Years S01E01 - Pilot.mp4": 1481,
  "the-wonder-years-complete-series::The Wonder Years S01E02 - Swingers.mp4": 1406,
  "the-wonder-years-complete-series::The Wonder Years S01E03 - My Father's Office.mp4": 1432,
  "the-wonder-years-complete-series::The Wonder Years S01E04 - Angel.mp4": 1421,
  "the-wonder-years-complete-series::The Wonder Years S01E05 - The Phone Call.mp4": 1431,
  "the-wonder-years-complete-series::The Wonder Years S01E06 - Dance with Me.mp4": 1426,
  "the-wonder-years-complete-series::The Wonder Years S02E01 - Heart of Darkness.mp4": 1414,
  "the-wonder-years-complete-series::The Wonder Years S02E02 - Our Miss White.mp4": 1436,
  "the-wonder-years-complete-series::The Wonder Years S02E03 - Christmas.mp4": 1375,
  "the-wonder-years-complete-series::The Wonder Years S02E04 - Steady as She Goes.mp4": 1432,
  "the-wonder-years-complete-series::The Wonder Years S02E05 - Just Between Me and You and Kirk and Paul and Carla and Becky.mp4": 1418,
  "the-wonder-years-complete-series::The Wonder Years S02E06 - Pottery Will Get You Nowhere.mp4": 1368,
  "the-wonder-years-complete-series::The Wonder Years S02E07 - Coda.mp4": 1401,
  "the-wonder-years-complete-series::The Wonder Years S02E08 - Hiroshima, Mon Frere.mp4": 1401,
  "the-wonder-years-complete-series::The Wonder Years S02E09 - Loosiers.mp4": 1387,
  "the-wonder-years-complete-series::The Wonder Years S02E10 - Walk Out.mp4": 1394,
  "the-wonder-years-complete-series::The Wonder Years S02E11 - Nemesis.mp4": 1400,
  "the-wonder-years-complete-series::The Wonder Years S02E12 - Fate.mp4": 1370,
  "the-wonder-years-complete-series::The Wonder Years S02E13 - Birthday Boy.mp4": 1392,
  "the-wonder-years-complete-series::The Wonder Years S02E14 - Brightwing.mp4": 1347,
  "the-wonder-years-complete-series::The Wonder Years S02E15 - Square Dance.mp4": 1332,
  "the-wonder-years-complete-series::The Wonder Years S02E16 - Whose Woods Are These.mp4": 1388,
  "the-wonder-years-complete-series::The Wonder Years S02E17 - How I'm Spending My Summer Vacation.mp4": 1396,
  "the-wonder-years-complete-series::The Wonder Years S03E01 - Summer Song.mp4": 1402,
  "the-wonder-years-complete-series::The Wonder Years S03E02 - Math Class.mp4": 1387,
  "the-wonder-years-complete-series::The Wonder Years S03E03 - Wayne on Wheels.mp4": 1366,
  "the-wonder-years-complete-series::The Wonder Years S03E04 - Mom Wars.mp4": 1365,
  "the-wonder-years-complete-series::The Wonder Years S03E05 - On The Spot.mp4": 1388,
  "the-wonder-years-complete-series::The Wonder Years S03E06 - Odd Man Out.mp4": 1391,
  "the-wonder-years-complete-series::The Wonder Years S03E07 - The Family Car.mp4": 1396,
  "the-wonder-years-complete-series::The Wonder Years S03E08 - The Pimple.mp4": 1376,
  "the-wonder-years-complete-series::The Wonder Years S03E09 - Math Class Squared.mp4": 1395,
  "the-wonder-years-complete-series::The Wonder Years S03E10 - Rock 'n Roll.mp4": 1360,
  "the-wonder-years-complete-series::The Wonder Years S03E11 - Don't You Know Anything About Women.mp4": 1371,
  "the-wonder-years-complete-series::The Wonder Years S03E12 - The Powers That Be.mp4": 1396,
  "the-wonder-years-complete-series::The Wonder Years S03E13 - She, My Friend and I.mp4": 1374,
  "the-wonder-years-complete-series::The Wonder Years S03E14 - The St. Valentine's Day Massacre.mp4": 1387,
  "the-wonder-years-complete-series::The Wonder Years S03E15 - The Tree House.mp4": 1385,
  "the-wonder-years-complete-series::The Wonder Years S03E16 - The Glee Club.mp4": 1366,
  "the-wonder-years-complete-series::The Wonder Years S03E17 - Night Out.mp4": 1394,
  "the-wonder-years-complete-series::The Wonder Years S03E18 - Faith.mp4": 1392,
  "the-wonder-years-complete-series::The Wonder Years S03E19 - The Unnatural.mp4": 1361,
  "the-wonder-years-complete-series::The Wonder Years S03E20 - Goodbye.mp4": 1411,
  "the-wonder-years-complete-series::The Wonder Years S03E21 - Cocoa and Sympathy.mp4": 1390,
  "the-wonder-years-complete-series::The Wonder Years S03E22 - Daddy's Little Girl.mp4": 1396,
  "the-wonder-years-complete-series::The Wonder Years S03E23 - Moving.mp4": 1381,
  "the-wonder-years-complete-series::The Wonder Years S04E01 - Growing Up.mp4": 1391,
  "the-wonder-years-complete-series::The Wonder Years S04E02 - Ninth Grade Man.mp4": 1395,
  "the-wonder-years-complete-series::The Wonder Years S04E03 - The Journey.mp4": 1397,
  "the-wonder-years-complete-series::The Wonder Years S04E04 - The Cost of Living.mp4": 1402,
  "the-wonder-years-complete-series::The Wonder Years S04E05 - It's A Mad, Mad, Madeline World.mp4": 1380,
  "the-wonder-years-complete-series::The Wonder Years S04E06 - Little Debbie.mp4": 1393,
  "the-wonder-years-complete-series::The Wonder Years S04E07 - The Ties That Bind.mp4": 1386,
  "the-wonder-years-complete-series::The Wonder Years S04E08 - The Sixth Man.mp4": 1368,
  "the-wonder-years-complete-series::The Wonder Years S04E09 - A Very Cutlip Christmas.mp4": 1387,
  "the-wonder-years-complete-series::The Wonder Years S04E10 - The Candidate.mp4": 1357,
  "the-wonder-years-complete-series::The Wonder Years S04E11 - Heartbreak.mp4": 1356,
  "the-wonder-years-complete-series::The Wonder Years S04E12 - Denial.mp4": 1383,
  "the-wonder-years-complete-series::The Wonder Years S04E13 - Who's Aunt Rose.mp4": 1386,
  "the-wonder-years-complete-series::The Wonder Years S04E14 - Courage.mp4": 1363,
  "the-wonder-years-complete-series::The Wonder Years S04E15 - Buster.mp4": 1373,
  "the-wonder-years-complete-series::The Wonder Years S04E16 - Road Trip.mp4": 1385,
  "the-wonder-years-complete-series::The Wonder Years S04E17 - When Worlds Collide.mp4": 1383,
  "the-wonder-years-complete-series::The Wonder Years S04E18 - Separate Rooms.mp4": 1378,
  "the-wonder-years-complete-series::The Wonder Years S04E19 - The Yearbook.mp4": 1376,
  "the-wonder-years-complete-series::The Wonder Years S04E20 - The Accident.mp4": 1384,
  "the-wonder-years-complete-series::The Wonder Years S04E21 - The House That Jack Built.mp4": 1368,
  "the-wonder-years-complete-series::The Wonder Years S04E22 - Graduation.mp4": 1415,
  "the-wonder-years-complete-series::The Wonder Years S04E23 - The Wonder Years.mp4": 1396,
  "the-wonder-years-complete-series::The Wonder Years S05E01 - The Lake.mp4": 1390,
  "the-wonder-years-complete-series::The Wonder Years S05E02 - Day One.mp4": 1381,
  "the-wonder-years-complete-series::The Wonder Years S05E03 - The Hardware Store.mp4": 1378,
  "the-wonder-years-complete-series::The Wonder Years S05E04 - Frank and Denise.mp4": 1392,
  "the-wonder-years-complete-series::The Wonder Years S05E05 - Full Moon Rising.mp4": 1369,
  "the-wonder-years-complete-series::The Wonder Years S05E06 - Triangle.mp4": 1386,
  "the-wonder-years-complete-series::The Wonder Years S05E07 - Soccer.mp4": 1386,
  "the-wonder-years-complete-series::The Wonder Years S05E08 - Dinner Out.mp4": 1386,
  "the-wonder-years-complete-series::The Wonder Years S05E09 - Christmas Party.mp4": 1385,
  "the-wonder-years-complete-series::The Wonder Years S05E10 - Pfeiffer's Choice.mp4": 1389,
  "the-wonder-years-complete-series::The Wonder Years S05E11 - Road Test.mp4": 1368,
  "the-wonder-years-complete-series::The Wonder Years S05E12 - Grandpa's Car.mp4": 1384,
  "the-wonder-years-complete-series::The Wonder Years S05E13 - Kodachrome.mp4": 1380,
  "the-wonder-years-complete-series::The Wonder Years S05E14 - Private Butthead.mp4": 1429,
  "the-wonder-years-complete-series::The Wonder Years S05E15 - Of Mastodons and Men.mp4": 1386,
  "the-wonder-years-complete-series::The Wonder Years S05E16 - Double Double Date.mp4": 1389,
  "the-wonder-years-complete-series::The Wonder Years S05E17 - Hero.mp4": 1408,
  "the-wonder-years-complete-series::The Wonder Years S05E18 - Lunch Stories.mp4": 1392,
  "the-wonder-years-complete-series::The Wonder Years S05E19 - Carnal Knowledge.mp4": 1382,
  "the-wonder-years-complete-series::The Wonder Years S05E20 - The Lost Weekend.mp4": 1392,
  "the-wonder-years-complete-series::The Wonder Years S05E21 - Stormy Weather.mp4": 1414,
  "the-wonder-years-complete-series::The Wonder Years S05E22 - The Wedding.mp4": 1392,
  "the-wonder-years-complete-series::The Wonder Years S05E23 - Back to The Lake.mp4": 1406,
  "the-wonder-years-complete-series::The Wonder Years S05E24 - Broken Hearts and Burgers.mp4": 1326,
  "the-wonder-years-complete-series::The Wonder Years S06E01 - Homecoming.mp4": 1422,
  "the-wonder-years-complete-series::The Wonder Years S06E02 - Fishing.mp4": 1400,
  "the-wonder-years-complete-series::The Wonder Years S06E03 - Scenes from A Wedding.mp4": 1407,
  "the-wonder-years-complete-series::The Wonder Years S06E04 - Sex and Economics.mp4": 1401,
  "the-wonder-years-complete-series::The Wonder Years S06E05 - Politics as Usual.mp4": 1402,
  "the-wonder-years-complete-series::The Wonder Years S06E06 - White Lies.mp4": 1400,
  "the-wonder-years-complete-series::The Wonder Years S06E07 - Wayne and Bonnie.mp4": 1433,
  "the-wonder-years-complete-series::The Wonder Years S06E08 - Kevin Delivers.mp4": 1401,
  "the-wonder-years-complete-series::The Wonder Years S06E09 - The Test.mp4": 1409,
  "the-wonder-years-complete-series::The Wonder Years S06E10 - Let Nothing You Dismay.mp4": 1399,
  "the-wonder-years-complete-series::The Wonder Years S06E11 - New Years.mp4": 1382,
  "the-wonder-years-complete-series::The Wonder Years S06E12 - Alice in Autoland.mp4": 1404,
  "the-wonder-years-complete-series::The Wonder Years S06E13 - Ladies and Gentlemen... The Rolling Stones.mp4": 1404,
  "the-wonder-years-complete-series::The Wonder Years S06E14 - Unpacking.mp4": 1405,
  "the-wonder-years-complete-series::The Wonder Years S06E15 - Hulk Arnold.mp4": 1368,
  "the-wonder-years-complete-series::The Wonder Years S06E16 - Nose.mp4": 1383,
  "the-wonder-years-complete-series::The Wonder Years S06E17 - Eclipse.mp4": 1399,
  "the-wonder-years-complete-series::The Wonder Years S06E18 - Poker.mp4": 1385,
  "the-wonder-years-complete-series::The Wonder Years S06E19 - The Little Women.mp4": 1389,
  "the-wonder-years-complete-series::The Wonder Years S06E20 - Reunion.mp4": 1409,
  "the-wonder-years-complete-series::The Wonder Years S06E21 - Summer.mp4": 1367,
  "the-wonder-years-complete-series::The Wonder Years S06E22 - Independence Day.mp4": 1515,
},
};
