window.SHOW = {
  id: "BenStillerShow",
  title: "The Ben Stiller Show",
  art: "BenStillerShow.png",
  storageProgressKey: "benstillershow-progress",
  storageSettingsKey: "benstillershow-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E01 - Pilot",
    "Episode 1 - Pilot.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E02 - With Bobcat Goldthwait",
    "Episode 2 - With Bobcat Goldthwait.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E03 - With James Doohan",
    "Episode 3 - With James Doohan.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E04 - On Melrose Avenue",
    "Episode 4 - On Melrose Avenue.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E05 - With Colin Quinn",
    "Episode 5 - With Colin Quinn.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E06 - With Sarah Jessica Parker",
    "Episode 6 - With Sarah Jessica Parker.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E07 - With Rob Morrow",
    "Episode 7 - With Rob Morrow.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E08 - With Flea",
    "Episode 8 - With Flea.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E09 - With Garry Shandling",
    "Episode 9 - With Garry Shandling.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E10 - With Dennis Miller",
    "Episode 10 - With Dennis Miller.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E11 - At the Beach",
    "Episode 11 - At the Beach.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E12 - A Few Good Scouts",
    "Episode 12 - A Few Good Scouts.mp4"],
  ['the-ben-stiller-show-complete-series', "THE BEN STILLER SHOW - S01E13 - ZooTV at Night",
    "Episode 13 - ZooTV at Night.mp4"],
],
  durations: {
  "the-ben-stiller-show-complete-series::Episode 1 - Pilot.mp4": 1367,
  "the-ben-stiller-show-complete-series::Episode 2 - With Bobcat Goldthwait.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 3 - With James Doohan.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 4 - On Melrose Avenue.mp4": 1380,
  "the-ben-stiller-show-complete-series::Episode 5 - With Colin Quinn.mp4": 1380,
  "the-ben-stiller-show-complete-series::Episode 6 - With Sarah Jessica Parker.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 7 - With Rob Morrow.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 8 - With Flea.mp4": 1380,
  "the-ben-stiller-show-complete-series::Episode 9 - With Garry Shandling.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 10 - With Dennis Miller.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 11 - At the Beach.mp4": 1380,
  "the-ben-stiller-show-complete-series::Episode 12 - A Few Good Scouts.mp4": 1381,
  "the-ben-stiller-show-complete-series::Episode 13 - ZooTV at Night.mp4": 1381,
},
};
