window.SHOW = {
  id: "MonsterVision",
  title: "MonsterVision",
  art: "MonsterVision.jpg",
  storageProgressKey: "monstervision-progress",
  storageSettingsKey: "monstervision-settings",
  nestedPaths: false,
  grouping: "flat",
  segments: "film",
  episodes: [
  ['joe-bob-briggs-monstervision', "MONSTERVISION - 2020 Texas Gladiators",
    "JoeBobBriggs_2020_Texas_Gladiators.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Beastmaster",
    "JoeBobBriggs_Beastmaster.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Beastmaster 2",
    "JoeBobBriggs_Beastmaster_2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Beyond Thunderdome",
    "JoeBobBriggs_Beyond_Thunderdome.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Big Trouble in Little China",
    "JoeBobBriggs_Big Trouble in Little China.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Carrie",
    "JoeBobBriggs_Carrie.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Children of the Corn 2",
    "JoeBobBriggs_Children_of_the_Corn_2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Childs Play 2",
    "JoeBobBriggs_Childs_Play_2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Christine",
    "JoeBobBriggs_Christine.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Clash of the Titans (TV)",
    "JoeBobBriggs_Clash of the Titans (TV).mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Conan the Barbarian",
    "JoeBobBriggs_Conan_the_Barbarian.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Conan the Destroyer",
    "JoeBobBriggs_Conan_the_Destroyer.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Critters (TV)",
    "JoeBobBriggs_Critters (TV).mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - DamnationAlley",
    "JoeBobBriggs_DamnationAlley.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - DeliberateStrangerPart1",
    "JoeBobBriggs_DeliberateStrangerPart1.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - DeliberateStrangerPart2",
    "JoeBobBriggs_DeliberateStrangerPart2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Dolores Claiborne",
    "JoeBobBriggs_Dolores_Claiborne.mp4"],
  ['monstervision-duel', "MONSTERVISION - Duel",
    "Duel (TV).mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - EmbraceOfTheVampire",
    "JoeBobBriggs_EmbraceOfTheVampire.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Escape Planet of the Apes",
    "JoeBobBriggs_Escape_Planet_of_the_Apes.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Forbidden Planet",
    "JoeBobBriggs_Forbidden_Planet.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Friday the 13th 6",
    "JoeBobBriggs_Friday_the_13th_6.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Funhouse",
    "JoeBobBriggs_Funhouse.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - FutureHunters",
    "JoeBobBriggs_FutureHunters.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Ghoulies",
    "JoeBobBriggs_Ghoulies.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Ghoulies 2",
    "JoeBobBriggs_Ghoulies_2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Godzilla",
    "JoeBobBriggs_Godzilla.mp4"],
  ['godzilla-vs.-mothra-tnt-full', "MONSTERVISION - Godzilla vs. Mothra",
    "Godzilla vs. Mothra TNT full.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Hairspray",
    "JoeBobBriggs_Hairspray.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Halloween 2",
    "JoeBobBriggs_Halloween 2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Halloween III Season of the Witch (TV)",
    "JoeBobBriggs_Halloween III_Season of the Witch (TV).mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Highlander",
    "JoeBobBriggs_Highlander.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Howling 3",
    "JoeBobBriggs_Howling_3.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Howling 7",
    "JoeBobBriggs_Howling_7.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - IceCreamMan",
    "JoeBobBriggs_IceCreamMan.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - ImmortalCombat",
    "JoeBobBriggs_ImmortalCombat.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - In Mouth of Madness",
    "JoeBobBriggs_In_Mouth_of_Madness.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - ItLivesAgain",
    "JoeBobBriggs_ItLivesAgain.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - ItsAlive",
    "JoeBobBriggs_ItsAlive.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Jaws 2",
    "JoeBobBriggs_Jaws_2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Mars Attacks",
    "JoeBobBriggs_Mars_Attacks.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Mary Shelleys Frankenstein",
    "JoeBobBriggs_Mary_Shelleys_Frankenstein.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - MaximumOverdrive",
    "JoeBobBriggs_MaximumOverdrive.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Metalbeast audiofixed",
    "JoeBobBriggs_Metalbeast_audiofixed.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - National Lampoons European Vacation",
    "JoeBobBriggs_National Lampoons European Vacation.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Pee Wees Big Adventure",
    "JoeBobBriggs_Pee_Wees_Big_Adventure.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - People Under the Stairs",
    "JoeBobBriggs_People_Under_the_Stairs.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Pet Shop",
    "JoeBobBriggs_Pet Shop.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Phantasm",
    "JoeBobBriggs_Phantasm.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Phantasm 2",
    "JoeBobBriggs_Phantasm_2.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - PlanetOfTheApes",
    "JoeBobBriggs_PlanetOfTheApes.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Poltergeist",
    "JoeBobBriggs_Poltergeist.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - ReturnOfTheLivingDead",
    "JoeBobBriggs_ReturnOfTheLivingDead.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Road Warrior",
    "JoeBobBriggs_Road_Warrior.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Stepfather",
    "JoeBobBriggs_Stepfather.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Swamp Thing",
    "JoeBobBriggs_Swamp_Thing.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Teen Wolf",
    "JoeBobBriggs_Teen Wolf.mp4"],
  ['joe-bob-briggs-presents-the-dev-ills-reign-with-commercials', "MONSTERVISION - The Devil's Rain",
    "Joe Bob Briggs presents The Dev Ills Reign (with commercials!).mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Exorcist",
    "JoeBobBriggs_The Exorcist.mp4"],
  ['monstervision-the-fear', "MONSTERVISION - The Fear",
    "MonstervisionTheFear.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Fog",
    "JoeBobBriggs_The_Fog.mp4"],
  ['monstervision-the-horror-at-37000-feet', "MONSTERVISION - The Horror at 37,000 Feet",
    "MonstervisionTheHorrorAt37000Feet.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Kiss",
    "JoeBobBriggs_The_Kiss.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Lost Boys",
    "JoeBobBriggs_The Lost Boys.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Seventh Sign",
    "JoeBobBriggs_The_Seventh_Sign.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Surgeon",
    "JoeBobBriggs_The_Surgeon.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Time Machine",
    "JoeBobBriggs_The_Time_Machine.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Ultimate Warrior",
    "JoeBobBriggs_The_Ultimate_Warrior.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - The Wasp Woman (1959)",
    "JoeBobBriggs_The Wasp Woman (1959).mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - TheBirds",
    "JoeBobBriggs_TheBirds.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - TheyLive",
    "JoeBobBriggs_TheyLive.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Time After Time",
    "JoeBobBriggs_Time_After_Time.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Time Runner",
    "JoeBobBriggs_Time_Runner.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - ToTheLimit",
    "JoeBobBriggs_ToTheLimit.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Willy Wonka Chocolate Factory",
    "JoeBobBriggs_Willy_Wonka_Chocolate_Factory.mp4"],
  ['joe-bob-briggs-monstervision', "MONSTERVISION - Xmas Part1 Gremlins",
    "JoeBobBriggs_Xmas_Part1_Gremlins.mp4"],
],
  durations: {
  "joe-bob-briggs-monstervision::JoeBobBriggs_2020_Texas_Gladiators.mp4": 6437,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Beastmaster.mp4": 9364,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Beastmaster_2.mp4": 8161,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Beyond_Thunderdome.mp4": 7799,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Big Trouble in Little China.mp4": 7951,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Carrie.mp4": 6895,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Children_of_the_Corn_2.mp4": 6478,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Childs_Play_2.mp4": 6277,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Christine.mp4": 8359,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Clash of the Titans (TV).mp4": 10807,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Conan_the_Barbarian.mp4": 5381,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Conan_the_Destroyer.mp4": 7537,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Critters (TV).mp4": 6179,
  "joe-bob-briggs-monstervision::JoeBobBriggs_DamnationAlley.mp4": 6712,
  "joe-bob-briggs-monstervision::JoeBobBriggs_DeliberateStrangerPart1.mp4": 6964,
  "joe-bob-briggs-monstervision::JoeBobBriggs_DeliberateStrangerPart2.mp4": 6978,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Dolores_Claiborne.mp4": 9543,
  "monstervision-duel::Duel (TV).mp4": 9311,
  "joe-bob-briggs-monstervision::JoeBobBriggs_EmbraceOfTheVampire.mp4": 5830,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Escape_Planet_of_the_Apes.mp4": 7373,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Forbidden_Planet.mp4": 7822,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Friday_the_13th_6.mp4": 5897,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Funhouse.mp4": 6983,
  "joe-bob-briggs-monstervision::JoeBobBriggs_FutureHunters.mp4": 7115,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Ghoulies.mp4": 6245,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Ghoulies_2.mp4": 6461,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Godzilla.mp4": 6170,
  "godzilla-vs.-mothra-tnt-full::Godzilla vs. Mothra TNT full.mp4": 7063,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Hairspray.mp4": 7572,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Halloween 2.mp4": 7012,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Halloween III_Season of the Witch (TV).mp4": 8067,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Highlander.mp4": 8342,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Howling_3.mp4": 6979,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Howling_7.mp4": 6621,
  "joe-bob-briggs-monstervision::JoeBobBriggs_IceCreamMan.mp4": 7043,
  "joe-bob-briggs-monstervision::JoeBobBriggs_ImmortalCombat.mp4": 7909,
  "joe-bob-briggs-monstervision::JoeBobBriggs_In_Mouth_of_Madness.mp4": 6603,
  "joe-bob-briggs-monstervision::JoeBobBriggs_ItLivesAgain.mp4": 6699,
  "joe-bob-briggs-monstervision::JoeBobBriggs_ItsAlive.mp4": 6880,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Jaws_2.mp4": 8406,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Mars_Attacks.mp4": 8418,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Mary_Shelleys_Frankenstein.mp4": 9627,
  "joe-bob-briggs-monstervision::JoeBobBriggs_MaximumOverdrive.mp4": 7203,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Metalbeast_audiofixed.mp4": 6421,
  "joe-bob-briggs-monstervision::JoeBobBriggs_National Lampoons European Vacation.mp4": 9655,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Pee_Wees_Big_Adventure.mp4": 6911,
  "joe-bob-briggs-monstervision::JoeBobBriggs_People_Under_the_Stairs.mp4": 6656,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Pet Shop.mp4": 6774,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Phantasm.mp4": 6110,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Phantasm_2.mp4": 6457,
  "joe-bob-briggs-monstervision::JoeBobBriggs_PlanetOfTheApes.mp4": 8581,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Poltergeist.mp4": 8250,
  "joe-bob-briggs-monstervision::JoeBobBriggs_ReturnOfTheLivingDead.mp4": 7042,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Road_Warrior.mp4": 7246,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Stepfather.mp4": 6376,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Swamp_Thing.mp4": 6265,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Teen Wolf.mp4": 7256,
  "joe-bob-briggs-presents-the-dev-ills-reign-with-commercials::Joe Bob Briggs presents The Dev Ills Reign (with commercials!).mp4": 8396,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The Exorcist.mp4": 8507,
  "monstervision-the-fear::MonstervisionTheFear.mp4": 7433,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Fog.mp4": 6404,
  "monstervision-the-horror-at-37000-feet::MonstervisionTheHorrorAt37000Feet.mp4": 5173,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Kiss.mp4": 7043,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The Lost Boys.mp4": 7080,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Seventh_Sign.mp4": 7219,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Surgeon.mp4": 7840,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Time_Machine.mp4": 7681,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Ultimate_Warrior.mp4": 7107,
  "joe-bob-briggs-monstervision::JoeBobBriggs_The Wasp Woman (1959).mp4": 4341,
  "joe-bob-briggs-monstervision::JoeBobBriggs_TheBirds.mp4": 9461,
  "joe-bob-briggs-monstervision::JoeBobBriggs_TheyLive.mp4": 7571,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Time_After_Time.mp4": 7898,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Time_Runner.mp4": 6678,
  "joe-bob-briggs-monstervision::JoeBobBriggs_ToTheLimit.mp4": 6007,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Willy_Wonka_Chocolate_Factory.mp4": 7853,
  "joe-bob-briggs-monstervision::JoeBobBriggs_Xmas_Part1_Gremlins.mp4": 8200,
},
  film: {
  "joe-bob-briggs-monstervision::JoeBobBriggs_2020_Texas_Gladiators.mp4": "2020 Texas Gladiators",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Beastmaster.mp4": "Beastmaster",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Beastmaster_2.mp4": "Beastmaster 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Beyond_Thunderdome.mp4": "Beyond Thunderdome",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Big Trouble in Little China.mp4": "Big Trouble in Little China",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Carrie.mp4": "Carrie",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Children_of_the_Corn_2.mp4": "Children of the Corn 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Childs_Play_2.mp4": "Childs Play 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Christine.mp4": "Christine",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Clash of the Titans (TV).mp4": "Clash of the Titans (TV)",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Conan_the_Barbarian.mp4": "Conan the Barbarian",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Conan_the_Destroyer.mp4": "Conan the Destroyer",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Critters (TV).mp4": "Critters (TV)",
  "joe-bob-briggs-monstervision::JoeBobBriggs_DamnationAlley.mp4": "DamnationAlley",
  "joe-bob-briggs-monstervision::JoeBobBriggs_DeliberateStrangerPart1.mp4": "DeliberateStrangerPart1",
  "joe-bob-briggs-monstervision::JoeBobBriggs_DeliberateStrangerPart2.mp4": "DeliberateStrangerPart2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Dolores_Claiborne.mp4": "Dolores Claiborne",
  "monstervision-duel::Duel (TV).mp4": "Duel",
  "joe-bob-briggs-monstervision::JoeBobBriggs_EmbraceOfTheVampire.mp4": "EmbraceOfTheVampire",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Escape_Planet_of_the_Apes.mp4": "Escape Planet of the Apes",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Forbidden_Planet.mp4": "Forbidden Planet",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Friday_the_13th_6.mp4": "Friday the 13th 6",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Funhouse.mp4": "Funhouse",
  "joe-bob-briggs-monstervision::JoeBobBriggs_FutureHunters.mp4": "FutureHunters",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Ghoulies.mp4": "Ghoulies",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Ghoulies_2.mp4": "Ghoulies 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Godzilla.mp4": "Godzilla",
  "godzilla-vs.-mothra-tnt-full::Godzilla vs. Mothra TNT full.mp4": "Godzilla vs. Mothra",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Hairspray.mp4": "Hairspray",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Halloween 2.mp4": "Halloween 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Halloween III_Season of the Witch (TV).mp4": "Halloween III Season of the Witch (TV)",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Highlander.mp4": "Highlander",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Howling_3.mp4": "Howling 3",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Howling_7.mp4": "Howling 7",
  "joe-bob-briggs-monstervision::JoeBobBriggs_IceCreamMan.mp4": "IceCreamMan",
  "joe-bob-briggs-monstervision::JoeBobBriggs_ImmortalCombat.mp4": "ImmortalCombat",
  "joe-bob-briggs-monstervision::JoeBobBriggs_In_Mouth_of_Madness.mp4": "In Mouth of Madness",
  "joe-bob-briggs-monstervision::JoeBobBriggs_ItLivesAgain.mp4": "ItLivesAgain",
  "joe-bob-briggs-monstervision::JoeBobBriggs_ItsAlive.mp4": "ItsAlive",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Jaws_2.mp4": "Jaws 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Mars_Attacks.mp4": "Mars Attacks",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Mary_Shelleys_Frankenstein.mp4": "Mary Shelleys Frankenstein",
  "joe-bob-briggs-monstervision::JoeBobBriggs_MaximumOverdrive.mp4": "MaximumOverdrive",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Metalbeast_audiofixed.mp4": "Metalbeast audiofixed",
  "joe-bob-briggs-monstervision::JoeBobBriggs_National Lampoons European Vacation.mp4": "National Lampoons European Vacation",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Pee_Wees_Big_Adventure.mp4": "Pee Wees Big Adventure",
  "joe-bob-briggs-monstervision::JoeBobBriggs_People_Under_the_Stairs.mp4": "People Under the Stairs",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Pet Shop.mp4": "Pet Shop",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Phantasm.mp4": "Phantasm",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Phantasm_2.mp4": "Phantasm 2",
  "joe-bob-briggs-monstervision::JoeBobBriggs_PlanetOfTheApes.mp4": "PlanetOfTheApes",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Poltergeist.mp4": "Poltergeist",
  "joe-bob-briggs-monstervision::JoeBobBriggs_ReturnOfTheLivingDead.mp4": "ReturnOfTheLivingDead",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Road_Warrior.mp4": "Road Warrior",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Stepfather.mp4": "Stepfather",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Swamp_Thing.mp4": "Swamp Thing",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Teen Wolf.mp4": "Teen Wolf",
  "joe-bob-briggs-presents-the-dev-ills-reign-with-commercials::Joe Bob Briggs presents The Dev Ills Reign (with commercials!).mp4": "The Devil's Rain",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The Exorcist.mp4": "The Exorcist",
  "monstervision-the-fear::MonstervisionTheFear.mp4": "The Fear",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Fog.mp4": "The Fog",
  "monstervision-the-horror-at-37000-feet::MonstervisionTheHorrorAt37000Feet.mp4": "The Horror at 37,000 Feet",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Kiss.mp4": "The Kiss",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The Lost Boys.mp4": "The Lost Boys",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Seventh_Sign.mp4": "The Seventh Sign",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Surgeon.mp4": "The Surgeon",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Time_Machine.mp4": "The Time Machine",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The_Ultimate_Warrior.mp4": "The Ultimate Warrior",
  "joe-bob-briggs-monstervision::JoeBobBriggs_The Wasp Woman (1959).mp4": "The Wasp Woman (1959)",
  "joe-bob-briggs-monstervision::JoeBobBriggs_TheBirds.mp4": "TheBirds",
  "joe-bob-briggs-monstervision::JoeBobBriggs_TheyLive.mp4": "TheyLive",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Time_After_Time.mp4": "Time After Time",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Time_Runner.mp4": "Time Runner",
  "joe-bob-briggs-monstervision::JoeBobBriggs_ToTheLimit.mp4": "ToTheLimit",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Willy_Wonka_Chocolate_Factory.mp4": "Willy Wonka Chocolate Factory",
  "joe-bob-briggs-monstervision::JoeBobBriggs_Xmas_Part1_Gremlins.mp4": "Xmas Part1 Gremlins",
},
};
