window.SHOW = {
  id: "DragonBallZMovies",
  title: "Dragon Ball Z Movies & Specials",
  art: "DragonBallZMovies.jpg",
  storageProgressKey: "dragonballzmovies-progress",
  storageSettingsKey: "dragonballzmovies-settings",
  nestedPaths: true,
  grouping: "flat",
  segments: "film",
  episodes: [
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Dead Zone (1989)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M01 - Dead Zone.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - The World's Strongest (1990)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M02 - The World's Strongest.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - The Tree of Might (1990)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M03 - The Tree of Might.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Lord Slug (1991)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M04 - Lord Slug.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Cooler's Revenge (1991)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M05 - Cooler's Revenge.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - The Return of Cooler (1992)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M06 - The Return of Cooler.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Super Android 13! (1992)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M07 - Super Android 13.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Broly: The Legendary Super Saiyan (1993)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M08 - Broly - The Legendary Super Saiyan.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Bojack Unbound (1993)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M09 - Bojack Unbound.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Broly: Second Coming (1994)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M10 - Broly - Second Coming.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Bio-Broly (1994)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M11 - Bio Broly.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Fusion Reborn (1995)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M12 - Fusion Reborn.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Wrath of the Dragon (1995)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M13 - Wrath of the Dragon.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Dead Zone (Ocean dub)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 01 - Dead Zone (Ocean Dub).mp4"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - The World's Strongest (Ocean dub)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 02 - The World's Strongest (Ocean Dub).mp4"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - The Tree of Might (Ocean dub)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 03 - The Tree Of Might (Ocean Dub).mp4"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Bardock: The Father of Goku (TV special, 1990)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Specials/Dragon Ball Z - Bardock - The Father of Goku.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - The History of Trunks (TV special, 1993)",
    "Dragon Ball Complete/(2) Dragon Ball Z/Specials/Dragon Ball Z - The History of Trunks.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Plan to Eradicate the Saiyans, Part 1 (OVA)",
    "Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball Z Side Story - OVA1 - Plan to Eradicate the Saiyans - Part 1.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Plan to Eradicate the Saiyans, Part 2 (OVA)",
    "Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball Z Side Story - OVA1 - Plan to Eradicate the Saiyans - Part 2.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Yo! Son Goku and His Friends Return!! (OVA, 2008)",
    "Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA2 - Yo! Son Goku and His Friends Return!!.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Plan to Eradicate the Super Saiyans (OVA, 2010)",
    "Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA3 - Plan to Eradicate the Super Saiyans.mkv"],
  ['dragon-ball-movie-4-the-path-to-power_202508', "DRAGON BALL Z - Episode of Bardock (OVA, 2011)",
    "Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA4 - Episode of Bardock.mkv"],
],
  durations: {
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M01 - Dead Zone.mkv": 2480,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M02 - The World's Strongest.mkv": 3574,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M03 - The Tree of Might.mkv": 3659,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M04 - Lord Slug.mkv": 3095,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M05 - Cooler's Revenge.mkv": 2818,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M06 - The Return of Cooler.mkv": 2739,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M07 - Super Android 13.mkv": 2757,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M08 - Broly - The Legendary Super Saiyan.mkv": 4310,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M09 - Bojack Unbound.mkv": 3033,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M10 - Broly - Second Coming.mkv": 3133,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M11 - Bio Broly.mkv": 2806,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M12 - Fusion Reborn.mkv": 3050,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M13 - Wrath of the Dragon.mkv": 3115,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 01 - Dead Zone (Ocean Dub).mp4": 2494,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 02 - The World's Strongest (Ocean Dub).mp4": 3591,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 03 - The Tree Of Might (Ocean Dub).mp4": 3669,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Specials/Dragon Ball Z - Bardock - The Father of Goku.mkv": 2885,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Specials/Dragon Ball Z - The History of Trunks.mkv": 2898,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball Z Side Story - OVA1 - Plan to Eradicate the Saiyans - Part 1.mkv": 1812,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball Z Side Story - OVA1 - Plan to Eradicate the Saiyans - Part 2.mkv": 1769,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA2 - Yo! Son Goku and His Friends Return!!.mkv": 2086,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA3 - Plan to Eradicate the Super Saiyans.mkv": 1763,
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA4 - Episode of Bardock.mkv": 1194,
},
  film: {
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M01 - Dead Zone.mkv": "Dead Zone (1989)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M02 - The World's Strongest.mkv": "The World's Strongest (1990)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M03 - The Tree of Might.mkv": "The Tree of Might (1990)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M04 - Lord Slug.mkv": "Lord Slug (1991)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M05 - Cooler's Revenge.mkv": "Cooler's Revenge (1991)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M06 - The Return of Cooler.mkv": "The Return of Cooler (1992)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M07 - Super Android 13.mkv": "Super Android 13! (1992)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M08 - Broly - The Legendary Super Saiyan.mkv": "Broly: The Legendary Super Saiyan (1993)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M09 - Bojack Unbound.mkv": "Bojack Unbound (1993)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M10 - Broly - Second Coming.mkv": "Broly: Second Coming (1994)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M11 - Bio Broly.mkv": "Bio-Broly (1994)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M12 - Fusion Reborn.mkv": "Fusion Reborn (1995)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Dragon Ball Z - M13 - Wrath of the Dragon.mkv": "Wrath of the Dragon (1995)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 01 - Dead Zone (Ocean Dub).mp4": "Dead Zone (Ocean dub)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 02 - The World's Strongest (Ocean Dub).mp4": "The World's Strongest (Ocean dub)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Movies/Ocean Dub/Dragon Ball Z Movie 03 - The Tree Of Might (Ocean Dub).mp4": "The Tree of Might (Ocean dub)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Specials/Dragon Ball Z - Bardock - The Father of Goku.mkv": "Bardock: The Father of Goku (TV special, 1990)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/Specials/Dragon Ball Z - The History of Trunks.mkv": "The History of Trunks (TV special, 1993)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball Z Side Story - OVA1 - Plan to Eradicate the Saiyans - Part 1.mkv": "Plan to Eradicate the Saiyans, Part 1 (OVA)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball Z Side Story - OVA1 - Plan to Eradicate the Saiyans - Part 2.mkv": "Plan to Eradicate the Saiyans, Part 2 (OVA)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA2 - Yo! Son Goku and His Friends Return!!.mkv": "Yo! Son Goku and His Friends Return!! (OVA, 2008)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA3 - Plan to Eradicate the Super Saiyans.mkv": "Plan to Eradicate the Super Saiyans (OVA, 2010)",
  "dragon-ball-movie-4-the-path-to-power_202508::Dragon Ball Complete/(2) Dragon Ball Z/OVAs/Dragon Ball - OVA4 - Episode of Bardock.mkv": "Episode of Bardock (OVA, 2011)",
},
};
