window.SHOW = {
  id: "GetSmart",
  title: "Get Smart",
  storageProgressKey: "getsmart-progress",
  storageSettingsKey: "getsmart-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['get-smart', "GET SMART - S01E01 - Mr. Big",
    "Get Smart S01E01 (Mr. Big).ia.mp4"],
  ['get-smart', "GET SMART - S01E02 - Diplomat's Daughter",
    "Get Smart S01E02 (Diplomat's Daughter).ia.mp4"],
  ['get-smart', "GET SMART - S01E03 - School Days",
    "Get Smart S01E03 (School Days).ia.mp4"],
  ['get-smart', "GET SMART - S01E04 - Our Man in Toyland",
    "Get Smart S01E04 (Our Man in Toyland).ia.mp4"],
  ['get-smart', "GET SMART - S01E05 - Now You See Him... Now You Don't",
    "Get Smart S01E05 (Now You See Him... Now You Don't).ia.mp4"],
  ['get-smart', "GET SMART - S01E06 - Washington 4, Indians 3",
    "Get Smart S01E06 (Washington 4, Indians 3).ia.mp4"],
  ['get-smart', "GET SMART - S01E07 - KAOS in CONTROL",
    "Get Smart S01E07 (KAOS in CONTROL).ia.mp4"],
  ['get-smart', "GET SMART - S01E08 - The Day Smart Turned Chicken",
    "Get Smart S01E08 (The Day Smart Turned Chicken).ia.mp4"],
  ['get-smart', "GET SMART - S01E09 - Satan Place",
    "Get Smart S01E09 (Satan Place).ia.mp4"],
  ['get-smart', "GET SMART - S01E10 - Our Man in Leotards",
    "Get Smart S01E10 (Our Man in Leotards).ia.mp4"],
  ['get-smart', "GET SMART - S01E11 - Too Many Chiefs",
    "Get Smart S01E11 (Too Many Chiefs).ia.mp4"],
  ['get-smart', "GET SMART - S01E12 - My Nephew the Spy",
    "Get Smart S01E12 (My Nephew the Spy).ia.mp4"],
  ['get-smart', "GET SMART - S01E13 - Aboard the Orient Express",
    "Get Smart S01E13 (Aboard the Orient Express).ia.mp4"],
  ['get-smart', "GET SMART - S01E14 - Weekend Vampire",
    "Get Smart S01E14 (Weekend Vampire).ia.mp4"],
  ['get-smart', "GET SMART - S01E15 - Survival of the Fattest",
    "Get Smart S01E15 (Survival of the Fattest).ia.mp4"],
  ['get-smart', "GET SMART - S01E16 - Double Agent",
    "Get Smart S01E16 (Double Agent).ia.mp4"],
  ['get-smart', "GET SMART - S01E17 - Kisses for KAOS",
    "Get Smart S01E17 (Kisses for KAOS).ia.mp4"],
  ['get-smart', "GET SMART - S01E18 - The Dead Spy Scrawls",
    "Get Smart S01E18 (The Dead Spy Scrawls).ia.mp4"],
  ['get-smart', "GET SMART - S01E19 - Back to the Old Drawing Board",
    "Get Smart S01E19 (Back to the Old Drawing Board).ia.mp4"],
  ['get-smart', "GET SMART - S01E20 - All in the Mind",
    "Get Smart S01E20 (All in the Mind).ia.mp4"],
  ['get-smart', "GET SMART - S01E21 - Dear Diary",
    "Get Smart S01E21 (Dear Diary).ia.mp4"],
  ['get-smart', "GET SMART - S01E22 - Smart, the Assassin",
    "Get Smart S01E22 (Smart, the Assassin).ia.mp4"],
  ['get-smart', "GET SMART - S01E23 - I'm Only Human",
    "Get Smart S01E23 (I'm Only Human).ia.mp4"],
  ['get-smart', "GET SMART - S01E24 - Stakeout on Blue Mist Mountain",
    "Get Smart S01E24 (Stakeout on Blue Mist Mountain).ia.mp4"],
  ['get-smart', "GET SMART - S01E25 - The Amazing Harry Hoo",
    "Get Smart S01E25 (The Amazing Harry Hoo).ia.mp4"],
  ['get-smart', "GET SMART - S01E26 - Hubert's Unfinished Symphony",
    "Get Smart S01E26 (Hubert's Unfinished Symphony).ia.mp4"],
  ['get-smart', "GET SMART - S01E27 - Ship of Spies - Pt1",
    "Get Smart S01E27 (Ship of Spies - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S01E28 - Ship of Spies - Pt2",
    "Get Smart S01E28 (Ship of Spies - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S01E29 - Shipment to Beirut",
    "Get Smart S01E29 (Shipment to Beirut).ia.mp4"],
  ['get-smart', "GET SMART - S01E30 - The Last One in is a Rotten Spy",
    "Get Smart S01E30 (The Last One in is a Rotten Spy).ia.mp4"],
  ['get-smart', "GET SMART - S02E01 - Anatomy of a Lover",
    "Get Smart S02E01 (Anatomy of a Lover).ia.mp4"],
  ['get-smart', "GET SMART - S02E02 - Strike While the Agent is Hot",
    "Get Smart S02E02 (Strike While the Agent is Hot).ia.mp4"],
  ['get-smart', "GET SMART - S02E03 - A Spy for a Spy",
    "Get Smart S02E03 (A Spy for a Spy).ia.mp4"],
  ['get-smart', "GET SMART - S02E04 - The Only Way to Die",
    "Get Smart S02E04 (The Only Way to Die).ia.mp4"],
  ['get-smart', "GET SMART - S02E05 - Maxwell Smart, Alias Jimmy Ballantine",
    "Get Smart S02E05 (Maxwell Smart, Alias Jimmy Ballantine).ia.mp4"],
  ['get-smart', "GET SMART - S02E06 - Casablanca",
    "Get Smart S02E06 (Casablanca).ia.mp4"],
  ['get-smart', "GET SMART - S02E07 - The Decoy",
    "Get Smart S02E07 (The Decoy).ia.mp4"],
  ['get-smart', "GET SMART - S02E08 - Hoo Done It",
    "Get Smart S02E08 (Hoo Done It).ia.mp4"],
  ['get-smart', "GET SMART - S02E09 - Rub-a-Dub-Dub... Three Spies in a Sub",
    "Get Smart S02E09 (Rub-a-Dub-Dub... Three Spies in a Sub).ia.mp4"],
  ['get-smart', "GET SMART - S02E10 - The Greatest Spy on Earth",
    "Get Smart S02E10 (The Greatest Spy on Earth).ia.mp4"],
  ['get-smart', "GET SMART - S02E11 - Island of the Darned",
    "Get Smart S02E11 (Island of the Darned).ia.mp4"],
  ['get-smart', "GET SMART - S02E12 - Bronzefinger",
    "Get Smart S02E12 (Bronzefinger).ia.mp4"],
  ['get-smart', "GET SMART - S02E13 - Perils in a Pet Shop",
    "Get Smart S02E13 (Perils in a Pet Shop).ia.mp4"],
  ['get-smart', "GET SMART - S02E14 - The Whole Tooth and...",
    "Get Smart S02E14 (The Whole Tooth and...).ia.mp4"],
  ['get-smart', "GET SMART - S02E15 - Kiss of Death",
    "Get Smart S02E15 (Kiss of Death).ia.mp4"],
  ['get-smart', "GET SMART - S02E16 - It takes One to Know One",
    "Get Smart S02E16 (It takes One to Know One).ia.mp4"],
  ['get-smart', "GET SMART - S02E17 - Someone Down Here Hates Me",
    "Get Smart S02E17 (Someone Down Here Hates Me).ia.mp4"],
  ['get-smart', "GET SMART - S02E18 - Cutback at CONTROL",
    "Get Smart S02E18 (Cutback at CONTROL).ia.mp4"],
  ['get-smart', "GET SMART - S02E19 - The Man from YENTA",
    "Get Smart S02E19 (The Man from YENTA).ia.mp4"],
  ['get-smart', "GET SMART - S02E20 - The Mummy",
    "Get Smart S02E20 (The Mummy).ia.mp4"],
  ['get-smart', "GET SMART - S02E21 - The Girls from KAOS",
    "Get Smart S02E21 (The Girls from KAOS).ia.mp4"],
  ['get-smart', "GET SMART - S02E22 - Smart Fit the Battle of Jericho",
    "Get Smart S02E22 (Smart Fit the Battle of Jericho).ia.mp4"],
  ['get-smart', "GET SMART - S02E23 - Where-What-How-Who Am I",
    "Get Smart S02E23 (Where-What-How-Who Am I).ia.mp4"],
  ['get-smart', "GET SMART - S02E24 - The Expendable Agent",
    "Get Smart S02E24 (The Expendable Agent).ia.mp4"],
  ['get-smart', "GET SMART - S02E25 - How to Succeed in the Spy Business without Really Trying",
    "Get Smart S02E25 (How to Succeed in the Spy Business without Really Trying).ia.mp4"],
  ['get-smart', "GET SMART - S02E26 - Appointment in Sahara",
    "Get Smart S02E26 (Appointment in Sahara).ia.mp4"],
  ['get-smart', "GET SMART - S02E27 - Pussycats Galore",
    "Get Smart S02E27 (Pussycats Galore).ia.mp4"],
  ['get-smart', "GET SMART - S02E28 - A Man Called Smart - Pt1",
    "Get Smart S02E28 (A Man Called Smart - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S02E29 - A Man Called Smart - Pt2",
    "Get Smart S02E29 (A Man Called Smart - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S02E30 - A Man Called Smart - Pt3",
    "Get Smart S02E30 (A Man Called Smart - Pt3).ia.mp4"],
  ['get-smart', "GET SMART - S03E01 - The Spy Who Met Himself",
    "Get Smart S03E01 (The Spy Who Met Himself).ia.mp4"],
  ['get-smart', "GET SMART - S03E02 - Viva Smart",
    "Get Smart S03E02 (Viva Smart).ia.mp4"],
  ['get-smart', "GET SMART - S03E03 - Witness for the Persecution",
    "Get Smart S03E03 (Witness for the Persecution).ia.mp4"],
  ['get-smart', "GET SMART - S03E04 - The Spirit Is Willing",
    "Get Smart S03E04 (The Spirit Is Willing).ia.mp4"],
  ['get-smart', "GET SMART - S03E05 - Maxwell Smart, Private Eye",
    "Get Smart S03E05 (Maxwell Smart, Private Eye).ia.mp4"],
  ['get-smart', "GET SMART - S03E06 - Supersonic Boom",
    "Get Smart S03E06 (Supersonic Boom).ia.mp4"],
  ['get-smart', "GET SMART - S03E07 - One of Our Olives is Missing",
    "Get Smart S03E07 (One of Our Olives is Missing).ia.mp4"],
  ['get-smart', "GET SMART - S03E08 - When Good Fellows Get Together",
    "Get Smart S03E08 (When Good Fellows Get Together).ia.mp4"],
  ['get-smart', "GET SMART - S03E09 - Dr. Yes",
    "Get Smart S03E09 (Dr. Yes).ia.mp4"],
  ['get-smart', "GET SMART - S03E10 - That Old Gang of Mine",
    "Get Smart S03E10 (That Old Gang of Mine).ia.mp4"],
  ['get-smart', "GET SMART - S03E11 - The Mild Ones",
    "Get Smart S03E11 (The Mild Ones).ia.mp4"],
  ['get-smart', "GET SMART - S03E12 - Classification Dead",
    "Get Smart S03E12 (Classification Dead).ia.mp4"],
  ['get-smart', "GET SMART - S03E13 - The Mysterious Dr. T",
    "Get Smart S03E13 (The Mysterious Dr. T).ia.mp4"],
  ['get-smart', "GET SMART - S03E14 - The King Lives",
    "Get Smart S03E14 (The King Lives).ia.mp4"],
  ['get-smart', "GET SMART - S03E15 - The Groovy Guru",
    "Get Smart S03E15 (The Groovy Guru).ia.mp4"],
  ['get-smart', "GET SMART - S03E16 - The Little Black Book - Pt1",
    "Get Smart S03E16 (The Little Black Book - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S03E17 - The Little Black Book - Pt2",
    "Get Smart S03E17 (The Little Black Book - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S03E18 - Don't Look Back",
    "Get Smart S03E18 (Don't Look Back).ia.mp4"],
  ['get-smart', "GET SMART - S03E19 - 99 Loses CONTROL",
    "Get Smart S03E19 (99 Loses CONTROL).ia.mp4"],
  ['get-smart', "GET SMART - S03E20 - The Wax Max",
    "Get Smart S03E20 (The Wax Max).ia.mp4"],
  ['get-smart', "GET SMART - S03E21 - Operation Ridiculous",
    "Get Smart S03E21 (Operation Ridiculous).ia.mp4"],
  ['get-smart', "GET SMART - S03E22 - Spy, Spy, Birdie",
    "Get Smart S03E22 (Spy, Spy, Birdie).ia.mp4"],
  ['get-smart', "GET SMART - S03E23 - Run, Robot, Run",
    "Get Smart S03E23 (Run, Robot, Run).ia.mp4"],
  ['get-smart', "GET SMART - S03E24 - The Hot Line",
    "Get Smart S03E24 (The Hot Line).ia.mp4"],
  ['get-smart', "GET SMART - S03E25 - Die Spy",
    "Get Smart S03E25 (Die Spy).ia.mp4"],
  ['get-smart', "GET SMART - S03E26 - The Reluctant Redhead",
    "Get Smart S03E26 (The Reluctant Redhead).ia.mp4"],
  ['get-smart', "GET SMART - S04E01 - The Impossible Mission",
    "Get Smart S04E01 (The Impossible Mission).ia.mp4"],
  ['get-smart', "GET SMART - S04E02 - Snoopy Smart vs. the Red Baron",
    "Get Smart S04E02 (Snoopy Smart vs. the Red Baron).ia.mp4"],
  ['get-smart', "GET SMART - S04E03 - Closely Watched Planes",
    "Get Smart S04E03 (Closely Watched Planes).ia.mp4"],
  ['get-smart', "GET SMART - S04E04 - The Secret of Sam Vittorio",
    "Get Smart S04E04 (The Secret of Sam Vittorio).ia.mp4"],
  ['get-smart', "GET SMART - S04E05 - Diamonds Are a Spy's Best Friend",
    "Get Smart S04E05 (Diamonds Are a Spy's Best Friend).ia.mp4"],
  ['get-smart', "GET SMART - S04E06 - The Worst Best Man",
    "Get Smart S04E06 (The Worst Best Man).ia.mp4"],
  ['get-smart', "GET SMART - S04E07 - A Tale of Two Tails",
    "Get Smart S04E07 (A Tale of Two Tails).ia.mp4"],
  ['get-smart', "GET SMART - S04E08 - The Return of the Ancient Mariner",
    "Get Smart S04E08 (The Return of the Ancient Mariner).ia.mp4"],
  ['get-smart', "GET SMART - S04E09 - With Love and Twitches",
    "Get Smart S04E09 (With Love and Twitches).ia.mp4"],
  ['get-smart', "GET SMART - S04E10 - The Laser Blazer",
    "Get Smart S04E10 (The Laser Blazer).ia.mp4"],
  ['get-smart', "GET SMART - S04E11 - The Farkas Fracas",
    "Get Smart S04E11 (The Farkas Fracas).ia.mp4"],
  ['get-smart', "GET SMART - S04E12 - Temporarily Out of CONTROL",
    "Get Smart S04E12 (Temporarily Out of CONTROL).ia.mp4"],
  ['get-smart', "GET SMART - S04E13 - Schwartz's Island",
    "Get Smart S04E13 (Schwartz's Island).ia.mp4"],
  ['get-smart', "GET SMART - S04E14 - One Nation Invisible",
    "Get Smart S04E14 (One Nation Invisible).ia.mp4"],
  ['get-smart', "GET SMART - S04E15 - Hurray for Hollywood",
    "Get Smart S04E15 (Hurray for Hollywood).ia.mp4"],
  ['get-smart', "GET SMART - S04E16 - The Day They Raided the Knights",
    "Get Smart S04E16 (The Day They Raided the Knights).ia.mp4"],
  ['get-smart', "GET SMART - S04E17 - Tequila Mockingbird",
    "Get Smart S04E17 (Tequila Mockingbird).ia.mp4"],
  ['get-smart', "GET SMART - S04E18 - I Shot 86 Today",
    "Get Smart S04E18 (I Shot 86 Today).ia.mp4"],
  ['get-smart', "GET SMART - S04E19 - Absorb the Greek",
    "Get Smart S04E19 (Absorb the Greek).ia.mp4"],
  ['get-smart', "GET SMART - S04E20 - To Sire, with Love - Pt1",
    "Get Smart S04E20 (To Sire, with Love - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S04E21 - To Sire, with Love - Pt2",
    "Get Smart S04E21 (To Sire, with Love - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S04E22 - Shock it to Me",
    "Get Smart S04E22 (Shock it to Me).ia.mp4"],
  ['get-smart', "GET SMART - S04E23 - Leadside",
    "Get Smart S04E23 (Leadside).ia.mp4"],
  ['get-smart', "GET SMART - S04E24 - Greer Windows",
    "Get Smart S04E24 (Greer Windows).ia.mp4"],
  ['get-smart', "GET SMART - S04E25 - The Not-So-Great Escape - Pt1",
    "Get Smart S04E25 (The Not-So-Great Escape - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S04E26 - The Not-So-Great Escape - Pt2",
    "Get Smart S04E26 (The Not-So-Great Escape - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S05E01 - Pheasant Under Glass",
    "Get Smart S05E01 (Pheasant Under Glass).ia.mp4"],
  ['get-smart', "GET SMART - S05E02 - Ironhand",
    "Get Smart S05E02 (Ironhand).ia.mp4"],
  ['get-smart', "GET SMART - S05E03 - Valerie of the Dolls",
    "Get Smart S05E03 (Valerie of the Dolls).ia.mp4"],
  ['get-smart', "GET SMART - S05E04 - Window often Annie",
    "Get Smart S05E04 (Window often Annie).ia.mp4"],
  ['get-smart', "GET SMART - S05E05 - The Treasure of C. Errol Madre",
    "Get Smart S05E05 (The Treasure of C. Errol Madre).ia.mp4"],
  ['get-smart', "GET SMART - S05E06 - Smart Fell on Alabama",
    "Get Smart S05E06 (Smart Fell on Alabama).ia.mp4"],
  ['get-smart', "GET SMART - S05E07 - And Baby makes Four - Pt1",
    "Get Smart S05E07 (And Baby makes Four - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S05E08 - And Baby makes Four - Pt2",
    "Get Smart S05E08 (And Baby makes Four - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S05E09 - Physician Impossible",
    "Get Smart S05E09 (Physician Impossible).ia.mp4"],
  ['get-smart', "GET SMART - S05E10 - The Apes of Rath",
    "Get Smart S05E10 (The Apes of Rath).ia.mp4"],
  ['get-smart', "GET SMART - S05E11 - Age Before Duty",
    "Get Smart S05E11 (Age Before Duty).ia.mp4"],
  ['get-smart', "GET SMART - S05E12 - Is this Trip Necessary",
    "Get Smart S05E12 (Is this Trip Necessary).ia.mp4"],
  ['get-smart', "GET SMART - S05E13 - Ice Station Siegfried",
    "Get Smart S05E13 (Ice Station Siegfried).ia.mp4"],
  ['get-smart', "GET SMART - S05E14 - Moonlighting Becomes You",
    "Get Smart S05E14 (Moonlighting Becomes You).ia.mp4"],
  ['get-smart', "GET SMART - S05E15 - House of Max - Pt1",
    "Get Smart S05E15 (House of Max - Pt1).ia.mp4"],
  ['get-smart', "GET SMART - S05E16 - House of Max - Pt2",
    "Get Smart S05E16 (House of Max - Pt2).ia.mp4"],
  ['get-smart', "GET SMART - S05E17 - Rebecca of Funny-Folk Farm",
    "Get Smart S05E17 (Rebecca of Funny-Folk Farm).ia.mp4"],
  ['get-smart', "GET SMART - S05E18 - The Mess of Adrian Listenger",
    "Get Smart S05E18 (The Mess of Adrian Listenger).ia.mp4"],
  ['get-smart', "GET SMART - S05E19 - Witness for the Execution",
    "Get Smart S05E19 (Witness for the Execution).ia.mp4"],
  ['get-smart', "GET SMART - S05E20 - How Green was my Valet",
    "Get Smart S05E20 (How Green was my Valet).ia.mp4"],
  ['get-smart', "GET SMART - S05E21 - And Only Two Ninety-Nine",
    "Get Smart S05E21 (And Only Two Ninety-Nine).ia.mp4"],
  ['get-smart', "GET SMART - S05E22 - Smartacus",
    "Get Smart S05E22 (Smartacus).ia.mp4"],
  ['get-smart', "GET SMART - S05E23 - What's It All About, Algie",
    "Get Smart S05E23 (What's It All About, Algie).ia.mp4"],
  ['get-smart', "GET SMART - S05E24 - Hello, Columbus – Goodbye, America",
    "Get Smart S05E24 (Hello, Columbus – Goodbye, America).mp4"],
  ['get-smart', "GET SMART - S05E25 - Do I Hear a Vaults",
    "Get Smart S05E25 (Do I Hear a Vaults).ia.mp4"],
  ['get-smart', "GET SMART - S05E26 - I Am Curiously Yellow",
    "Get Smart S05E26 (I Am Curiously Yellow).ia.mp4"],
],
  durations: {
  "get-smart::Get Smart S01E01 (Mr. Big).ia.mp4": 1535,
  "get-smart::Get Smart S01E02 (Diplomat's Daughter).ia.mp4": 1521,
  "get-smart::Get Smart S01E03 (School Days).ia.mp4": 1522,
  "get-smart::Get Smart S01E04 (Our Man in Toyland).ia.mp4": 1519,
  "get-smart::Get Smart S01E05 (Now You See Him... Now You Don't).ia.mp4": 1516,
  "get-smart::Get Smart S01E06 (Washington 4, Indians 3).ia.mp4": 1524,
  "get-smart::Get Smart S01E07 (KAOS in CONTROL).ia.mp4": 1515,
  "get-smart::Get Smart S01E08 (The Day Smart Turned Chicken).ia.mp4": 1516,
  "get-smart::Get Smart S01E09 (Satan Place).ia.mp4": 1525,
  "get-smart::Get Smart S01E10 (Our Man in Leotards).ia.mp4": 1525,
  "get-smart::Get Smart S01E11 (Too Many Chiefs).ia.mp4": 1515,
  "get-smart::Get Smart S01E12 (My Nephew the Spy).ia.mp4": 1520,
  "get-smart::Get Smart S01E13 (Aboard the Orient Express).ia.mp4": 1523,
  "get-smart::Get Smart S01E14 (Weekend Vampire).ia.mp4": 1518,
  "get-smart::Get Smart S01E15 (Survival of the Fattest).ia.mp4": 1525,
  "get-smart::Get Smart S01E16 (Double Agent).ia.mp4": 1521,
  "get-smart::Get Smart S01E17 (Kisses for KAOS).ia.mp4": 1525,
  "get-smart::Get Smart S01E18 (The Dead Spy Scrawls).ia.mp4": 1525,
  "get-smart::Get Smart S01E19 (Back to the Old Drawing Board).ia.mp4": 1521,
  "get-smart::Get Smart S01E20 (All in the Mind).ia.mp4": 1524,
  "get-smart::Get Smart S01E21 (Dear Diary).ia.mp4": 1525,
  "get-smart::Get Smart S01E22 (Smart, the Assassin).ia.mp4": 1525,
  "get-smart::Get Smart S01E23 (I'm Only Human).ia.mp4": 1513,
  "get-smart::Get Smart S01E24 (Stakeout on Blue Mist Mountain).ia.mp4": 1525,
  "get-smart::Get Smart S01E25 (The Amazing Harry Hoo).ia.mp4": 1524,
  "get-smart::Get Smart S01E26 (Hubert's Unfinished Symphony).ia.mp4": 1525,
  "get-smart::Get Smart S01E27 (Ship of Spies - Pt1).ia.mp4": 1524,
  "get-smart::Get Smart S01E28 (Ship of Spies - Pt2).ia.mp4": 1525,
  "get-smart::Get Smart S01E29 (Shipment to Beirut).ia.mp4": 1524,
  "get-smart::Get Smart S01E30 (The Last One in is a Rotten Spy).ia.mp4": 1526,
  "get-smart::Get Smart S02E01 (Anatomy of a Lover).ia.mp4": 1523,
  "get-smart::Get Smart S02E02 (Strike While the Agent is Hot).ia.mp4": 1529,
  "get-smart::Get Smart S02E03 (A Spy for a Spy).ia.mp4": 1529,
  "get-smart::Get Smart S02E04 (The Only Way to Die).ia.mp4": 1523,
  "get-smart::Get Smart S02E05 (Maxwell Smart, Alias Jimmy Ballantine).ia.mp4": 1522,
  "get-smart::Get Smart S02E06 (Casablanca).ia.mp4": 1527,
  "get-smart::Get Smart S02E07 (The Decoy).ia.mp4": 1527,
  "get-smart::Get Smart S02E08 (Hoo Done It).ia.mp4": 1526,
  "get-smart::Get Smart S02E09 (Rub-a-Dub-Dub... Three Spies in a Sub).ia.mp4": 1505,
  "get-smart::Get Smart S02E10 (The Greatest Spy on Earth).ia.mp4": 1495,
  "get-smart::Get Smart S02E11 (Island of the Darned).ia.mp4": 1525,
  "get-smart::Get Smart S02E12 (Bronzefinger).ia.mp4": 1520,
  "get-smart::Get Smart S02E13 (Perils in a Pet Shop).ia.mp4": 1515,
  "get-smart::Get Smart S02E14 (The Whole Tooth and...).ia.mp4": 1518,
  "get-smart::Get Smart S02E15 (Kiss of Death).ia.mp4": 1461,
  "get-smart::Get Smart S02E16 (It takes One to Know One).ia.mp4": 1516,
  "get-smart::Get Smart S02E17 (Someone Down Here Hates Me).ia.mp4": 1522,
  "get-smart::Get Smart S02E18 (Cutback at CONTROL).ia.mp4": 1518,
  "get-smart::Get Smart S02E19 (The Man from YENTA).ia.mp4": 1519,
  "get-smart::Get Smart S02E20 (The Mummy).ia.mp4": 1519,
  "get-smart::Get Smart S02E21 (The Girls from KAOS).ia.mp4": 1526,
  "get-smart::Get Smart S02E22 (Smart Fit the Battle of Jericho).ia.mp4": 1518,
  "get-smart::Get Smart S02E23 (Where-What-How-Who Am I).ia.mp4": 1516,
  "get-smart::Get Smart S02E24 (The Expendable Agent).ia.mp4": 1513,
  "get-smart::Get Smart S02E25 (How to Succeed in the Spy Business without Really Trying).ia.mp4": 1518,
  "get-smart::Get Smart S02E26 (Appointment in Sahara).ia.mp4": 1519,
  "get-smart::Get Smart S02E27 (Pussycats Galore).ia.mp4": 1521,
  "get-smart::Get Smart S02E28 (A Man Called Smart - Pt1).ia.mp4": 1523,
  "get-smart::Get Smart S02E29 (A Man Called Smart - Pt2).ia.mp4": 1525,
  "get-smart::Get Smart S02E30 (A Man Called Smart - Pt3).ia.mp4": 1525,
  "get-smart::Get Smart S03E01 (The Spy Who Met Himself).ia.mp4": 1527,
  "get-smart::Get Smart S03E02 (Viva Smart).ia.mp4": 1524,
  "get-smart::Get Smart S03E03 (Witness for the Persecution).ia.mp4": 1529,
  "get-smart::Get Smart S03E04 (The Spirit Is Willing).ia.mp4": 1518,
  "get-smart::Get Smart S03E05 (Maxwell Smart, Private Eye).ia.mp4": 1498,
  "get-smart::Get Smart S03E06 (Supersonic Boom).ia.mp4": 1531,
  "get-smart::Get Smart S03E07 (One of Our Olives is Missing).ia.mp4": 1528,
  "get-smart::Get Smart S03E08 (When Good Fellows Get Together).ia.mp4": 1529,
  "get-smart::Get Smart S03E09 (Dr. Yes).ia.mp4": 1495,
  "get-smart::Get Smart S03E10 (That Old Gang of Mine).ia.mp4": 1527,
  "get-smart::Get Smart S03E11 (The Mild Ones).ia.mp4": 1515,
  "get-smart::Get Smart S03E12 (Classification Dead).ia.mp4": 1527,
  "get-smart::Get Smart S03E13 (The Mysterious Dr. T).ia.mp4": 1523,
  "get-smart::Get Smart S03E14 (The King Lives).ia.mp4": 1530,
  "get-smart::Get Smart S03E15 (The Groovy Guru).ia.mp4": 1528,
  "get-smart::Get Smart S03E16 (The Little Black Book - Pt1).ia.mp4": 1527,
  "get-smart::Get Smart S03E17 (The Little Black Book - Pt2).ia.mp4": 1519,
  "get-smart::Get Smart S03E18 (Don't Look Back).ia.mp4": 1528,
  "get-smart::Get Smart S03E19 (99 Loses CONTROL).ia.mp4": 1528,
  "get-smart::Get Smart S03E20 (The Wax Max).ia.mp4": 1467,
  "get-smart::Get Smart S03E21 (Operation Ridiculous).ia.mp4": 1527,
  "get-smart::Get Smart S03E22 (Spy, Spy, Birdie).ia.mp4": 1467,
  "get-smart::Get Smart S03E23 (Run, Robot, Run).ia.mp4": 1525,
  "get-smart::Get Smart S03E24 (The Hot Line).ia.mp4": 1529,
  "get-smart::Get Smart S03E25 (Die Spy).ia.mp4": 1528,
  "get-smart::Get Smart S03E26 (The Reluctant Redhead).ia.mp4": 1529,
  "get-smart::Get Smart S04E01 (The Impossible Mission).ia.mp4": 1505,
  "get-smart::Get Smart S04E02 (Snoopy Smart vs. the Red Baron).ia.mp4": 1499,
  "get-smart::Get Smart S04E03 (Closely Watched Planes).ia.mp4": 1483,
  "get-smart::Get Smart S04E04 (The Secret of Sam Vittorio).ia.mp4": 1485,
  "get-smart::Get Smart S04E05 (Diamonds Are a Spy's Best Friend).ia.mp4": 1485,
  "get-smart::Get Smart S04E06 (The Worst Best Man).ia.mp4": 1486,
  "get-smart::Get Smart S04E07 (A Tale of Two Tails).ia.mp4": 1484,
  "get-smart::Get Smart S04E08 (The Return of the Ancient Mariner).ia.mp4": 1480,
  "get-smart::Get Smart S04E09 (With Love and Twitches).ia.mp4": 1479,
  "get-smart::Get Smart S04E10 (The Laser Blazer).ia.mp4": 1485,
  "get-smart::Get Smart S04E11 (The Farkas Fracas).ia.mp4": 1485,
  "get-smart::Get Smart S04E12 (Temporarily Out of CONTROL).ia.mp4": 1476,
  "get-smart::Get Smart S04E13 (Schwartz's Island).ia.mp4": 1478,
  "get-smart::Get Smart S04E14 (One Nation Invisible).ia.mp4": 1477,
  "get-smart::Get Smart S04E15 (Hurray for Hollywood).ia.mp4": 1484,
  "get-smart::Get Smart S04E16 (The Day They Raided the Knights).ia.mp4": 1483,
  "get-smart::Get Smart S04E17 (Tequila Mockingbird).ia.mp4": 1483,
  "get-smart::Get Smart S04E18 (I Shot 86 Today).ia.mp4": 1482,
  "get-smart::Get Smart S04E19 (Absorb the Greek).ia.mp4": 1484,
  "get-smart::Get Smart S04E20 (To Sire, with Love - Pt1).ia.mp4": 1484,
  "get-smart::Get Smart S04E21 (To Sire, with Love - Pt2).ia.mp4": 1483,
  "get-smart::Get Smart S04E22 (Shock it to Me).ia.mp4": 1486,
  "get-smart::Get Smart S04E23 (Leadside).ia.mp4": 1487,
  "get-smart::Get Smart S04E24 (Greer Windows).ia.mp4": 1484,
  "get-smart::Get Smart S04E25 (The Not-So-Great Escape - Pt1).ia.mp4": 1483,
  "get-smart::Get Smart S04E26 (The Not-So-Great Escape - Pt2).ia.mp4": 1482,
  "get-smart::Get Smart S05E01 (Pheasant Under Glass).ia.mp4": 1459,
  "get-smart::Get Smart S05E02 (Ironhand).ia.mp4": 1457,
  "get-smart::Get Smart S05E03 (Valerie of the Dolls).ia.mp4": 1457,
  "get-smart::Get Smart S05E04 (Window often Annie).ia.mp4": 1460,
  "get-smart::Get Smart S05E05 (The Treasure of C. Errol Madre).ia.mp4": 1456,
  "get-smart::Get Smart S05E06 (Smart Fell on Alabama).ia.mp4": 1457,
  "get-smart::Get Smart S05E07 (And Baby makes Four - Pt1).ia.mp4": 1458,
  "get-smart::Get Smart S05E08 (And Baby makes Four - Pt2).ia.mp4": 1454,
  "get-smart::Get Smart S05E09 (Physician Impossible).ia.mp4": 1456,
  "get-smart::Get Smart S05E10 (The Apes of Rath).ia.mp4": 1456,
  "get-smart::Get Smart S05E11 (Age Before Duty).ia.mp4": 1456,
  "get-smart::Get Smart S05E12 (Is this Trip Necessary).ia.mp4": 1457,
  "get-smart::Get Smart S05E13 (Ice Station Siegfried).ia.mp4": 1457,
  "get-smart::Get Smart S05E14 (Moonlighting Becomes You).ia.mp4": 1456,
  "get-smart::Get Smart S05E15 (House of Max - Pt1).ia.mp4": 1457,
  "get-smart::Get Smart S05E16 (House of Max - Pt2).ia.mp4": 1456,
  "get-smart::Get Smart S05E17 (Rebecca of Funny-Folk Farm).ia.mp4": 1457,
  "get-smart::Get Smart S05E18 (The Mess of Adrian Listenger).ia.mp4": 1456,
  "get-smart::Get Smart S05E19 (Witness for the Execution).ia.mp4": 1456,
  "get-smart::Get Smart S05E20 (How Green was my Valet).ia.mp4": 1457,
  "get-smart::Get Smart S05E21 (And Only Two Ninety-Nine).ia.mp4": 1452,
  "get-smart::Get Smart S05E22 (Smartacus).ia.mp4": 1456,
  "get-smart::Get Smart S05E23 (What's It All About, Algie).ia.mp4": 1457,
  "get-smart::Get Smart S05E24 (Hello, Columbus – Goodbye, America).mp4": 1457,
  "get-smart::Get Smart S05E25 (Do I Hear a Vaults).ia.mp4": 1397,
  "get-smart::Get Smart S05E26 (I Am Curiously Yellow).ia.mp4": 1457,
},
};
