window.SHOW = {
  id: "PetticoatJunction",
  title: "Petticoat Junction",
  art: "PetticoatJunction.jpg",
  storageProgressKey: "petticoatjunction-progress",
  storageSettingsKey: "petticoatjunction-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E01 - Spur Line to Shady Rest (Part 1 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E01 - Spur Lane to Shady Rest (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E02 - Quick, Hide the Railroad (Part 2 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E02 - Quick, Hide the Railroad (Part 2 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E03 - The President Who Came to Dinner (Part 1 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E03 - The President Who Came to Dinner (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E04 - Is There a Doctor in the Roundhouse (Part 2 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E04 - Is There a Doctor in the Roundhouse (Part 2 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E05 - The Courtship of Floyd Smoot",
    "Petticoat Junction - Season 1/Petticoat Junction S01E05 - The Courtship of Floyd Smoot.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E06 - Please Buy My Violets",
    "Petticoat Junction - Season 1/Petticoat Junction S01E06 - Please Buy My Violets.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E07 - The Ringer",
    "Petticoat Junction - Season 1/Petticoat Junction S01E07 - The Ringer.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E08 - Kate's Recipe for Hot Rhubarb",
    "Petticoat Junction - Season 1/Petticoat Junction S01E08 - Kate's Recipe for Hot Rhubarb.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E09 - The Little Train Robbery",
    "Petticoat Junction - Season 1/Petticoat Junction S01E09 - The Little Train Robbery.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E10 - Bedloe Strikes Again",
    "Petticoat Junction - Season 1/Petticoat Junction S01E10 - Bedloe Strikes Again.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E11 - Uncle Joe's Replacement",
    "Petticoat Junction - Season 1/Petticoat Junction S01E11 - Uncle Joe's Replacement.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E12 - Honeymoon Hotel",
    "Petticoat Junction - Season 1/Petticoat Junction S01E12 - Honeymoon Hotel.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E13 - A Night at the Hooterville Hilton",
    "Petticoat Junction - Season 1/Petticoat Junction S01E13 - A Night at the Hooterville Hilton.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E14 - Cannonball Christmas",
    "Petticoat Junction - Season 1/Petticoat Junction S01E14 - Cannonball Christmas.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E15 - Herby Gets Drafted",
    "Petticoat Junction - Season 1/Petticoat Junction S01E15 - Herby Gets Drafted.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E16 - Bobbie Jo and the Beatnik",
    "Petticoat Junction - Season 1/Petticoat Junction S01E16 - Bobbie Jo and the Beatnik.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E17 - My Daughter the Doctor (Part 1 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E17 - My Daughter the Doctor (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E18 - Hooterville vs. Hollywood (Part 2 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E18 - Hooterville vs. Hollywood (Part 2 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E19 - Visit from a Big Star",
    "Petticoat Junction - Season 1/Petticoat Junction S01E19 - Visit from a Big Star.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E20 - Last Chance Farm",
    "Petticoat Junction - Season 1/Petticoat Junction S01E20 - Last Chance Farm.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E21 - The Very Old Antique",
    "Petticoat Junction - Season 1/Petticoat Junction S01E21 - The Very Old Antique.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E22 - The Art Game",
    "Petticoat Junction - Season 1/Petticoat Junction S01E22 - The Art Game.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E23 - Betty Jo's First Love",
    "Petticoat Junction - Season 1/Petticoat Junction S01E23 - Betty Jo's First Love.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E24 - Behind All Silver, There's a Cloud Lining",
    "Petticoat Junction - Season 1/Petticoat Junction S01E24 - Behind All Silver, There's a Cloud Lining.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E25 - The Talent Contest",
    "Petticoat Junction - Season 1/Petticoat Junction S01E25 - The Talent Contest.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E26 - Kate and the Manpower Problem",
    "Petticoat Junction - Season 1/Petticoat Junction S01E26 - Kate and the Manpower Problem.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E27 - The Ladybugs (March 24, 1964)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E27 - The Ladybugs (March 24, 1964).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E28 - The Hooterville Flivverball",
    "Petticoat Junction - Season 1/Petticoat Junction S01E28 - The Hooterville Flivverball.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E29 - Kate the Stockholder",
    "Petticoat Junction - Season 1/Petticoat Junction S01E29 - Kate the Stockholder.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E30 - Kate and the Dowager",
    "Petticoat Junction - Season 1/Petticoat Junction S01E30 - Kate and the Dowager.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E31 - Charley Abandons the Cannonball",
    "Petticoat Junction - Season 1/Petticoat Junction S01E31 - Charley Abandons the Cannonball.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E32 - Dog Days at Shady Rest",
    "Petticoat Junction - Season 1/Petticoat Junction S01E32 - Dog Days at Shady Rest.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E33 - A Millionaire for Kate",
    "Petticoat Junction - Season 1/Petticoat Junction S01E33 - A Millionaire for Kate.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E34 - Bedloe and Son",
    "Petticoat Junction - Season 1/Petticoat Junction S01E34 - Bedloe and Son.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E35 - Local Girl Makes Good",
    "Petticoat Junction - Season 1/Petticoat Junction S01E35 - Local Girl Makes Good.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E36 - Cave Woman (Part 1 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E36 - Cave Woman (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E37 - Kate, Flat on Her Back (Part 2 of 2)",
    "Petticoat Junction - Season 1/Petticoat Junction S01E37 - Kate, Flat on Her Back (Part 2 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S01E38 - The Genghis Keane Story",
    "Petticoat Junction - Season 1/Petticoat Junction S01E38 - The Genghis Keane Story.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E01 - Betty Jo's Dog",
    "Petticoat Junction - Season 2/Petticoat Junction S02E01 - Betty Jo's Dog.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E02 - Race Against the Stork",
    "Petticoat Junction - Season 2/Petticoat Junction S02E02 - Race Against the Stork.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E03 - Have Library, Will Travel",
    "Petticoat Junction - Season 2/Petticoat Junction S02E03 - Have Library, Will Travel.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E04 - The Umquaw Strip",
    "Petticoat Junction - Season 2/Petticoat Junction S02E04 - The Umquaw Strip.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E05 - As Hooterville Goes",
    "Petticoat Junction - Season 2/Petticoat Junction S02E05 - As Hooterville Goes.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E06 - My Dog the Actor",
    "Petticoat Junction - Season 2/Petticoat Junction S02E06 - My Dog the Actor.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E07 - The Great Buffalo Hunt",
    "Petticoat Junction - Season 2/Petticoat Junction S02E07 - The Great Buffalo Hunt.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E08 - Betty Jo's Pen Pal",
    "Petticoat Junction - Season 2/Petticoat Junction S02E08 - Betty Jo's Pen Pal.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E09 - Bedloe's Nightmare",
    "Petticoat Junction - Season 2/Petticoat Junction S02E09 - Bedloe's Nightmare.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E10 - Kate's Bachelor Butter",
    "Petticoat Junction - Season 2/Petticoat Junction S02E10 - Kate's Bachelor Butter.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E11 - Mother of the Bride",
    "Petticoat Junction - Season 2/Petticoat Junction S02E11 - Mother of the Bride.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E12 - The Lost Patrol",
    "Petticoat Junction - Season 2/Petticoat Junction S02E12 - The Lost Patrol.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E13 - Smoke-Eaters",
    "Petticoat Junction - Season 2/Petticoat Junction S02E13 - Smoke-Eaters.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E14 - The Curse of Chester W. Farnsworth",
    "Petticoat Junction - Season 2/Petticoat Junction S02E14 - The Curse of Chester W. Farnsworth.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E15 - There's No Flame Like an Old Flame",
    "Petticoat Junction - Season 2/Petticoat Junction S02E15 - There's No Flame Like an Old Flame.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E16 - Billie Jo's First Job",
    "Petticoat Junction - Season 2/Petticoat Junction S02E16 - Billy Jo's First Job.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E17 - A Matter of Communication",
    "Petticoat Junction - Season 2/Petticoat Junction S02E17 - A Matter of Communication.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E18 - Kate Bradley, Girl Volunteer",
    "Petticoat Junction - Season 2/Petticoat Junction S02E18 - Kate Bradley, Girl Volunteer.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E19 - Hooterville Crime Wave",
    "Petticoat Junction - Season 2/Petticoat Junction S02E19 - Hooterville Crime Wave.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E20 - For the Birds",
    "Petticoat Junction - Season 2/Petticoat Junction S02E20 - For the Birds.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E21 - Modern Merchandising",
    "Petticoat Junction - Season 2/Petticoat Junction S02E21 - Modern Merchandising.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E22 - Visit From the Governor",
    "Petticoat Junction - Season 2/Petticoat Junction S02E22 - Visit From the Governor.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E23 - A Borderline Story",
    "Petticoat Junction - Season 2/Petticoat Junction S02E23 - A Borderline Story.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E24 - The Shady Rest Hotel Corporation",
    "Petticoat Junction - Season 2/Petticoat Junction S02E24 - The Shady Rest Hotel Corporation.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E25 - A Tale of Two Dogs",
    "Petticoat Junction - Season 2/Petticoat Junction S02E25 - A Tale of Two Dogs.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E26 - The Black Box",
    "Petticoat Junction - Season 2/Petticoat Junction S02E26 - The Black Box.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E27 - Bedloe's Most Fiendish Scheme (Part 1 of 2)",
    "Petticoat Junction - Season 2/Petticoat Junction S02E27 - Bedloe's Most Fiendish Scheme (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E28 - Bedloe Gets His Comeuppance (Part 2 of 2)",
    "Petticoat Junction - Season 2/Petticoat Junction S02E28 - Bedloe Gets His Comeuppance (Part 2 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E29 - The Mayor of Hooterville",
    "Petticoat Junction - Season 2/Petticoat Junction S02E29 - The Mayor of Hooterville.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E30 - Who's Afraid of the Big Bad Jinx",
    "Petticoat Junction - Season 2/Petticoat Junction S02E30 - Who's Afraid of the Big Bad Jinx.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E31 - The Chicken Killer",
    "Petticoat Junction - Season 2/Petticoat Junction S02E31 - The Chicken Killer.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E32 - Why Girls Leave Home",
    "Petticoat Junction - Season 2/Petticoat Junction S02E32 - Why Girls Leave Home.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E33 - There's No Stove Like an Old Stove",
    "Petticoat Junction - Season 2/Petticoat Junction S02E33 - There's No Stove Like an Old Stove.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E34 - The Brontosaurus Caper",
    "Petticoat Junction - Season 2/Petticoat Junction S02E34 - The Brontosaurus Caper.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E35 - The Hairbrained Scheme",
    "Petticoat Junction - Season 2/Petticoat Junction S02E35 - The Hairbrained Scheme.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S02E36 - There's No Business with Show Business",
    "Petticoat Junction - Season 2/Petticoat Junction S02E36 - There's No Business with Show Business.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E01 - Dear Minerva",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E01 - Dear Minerva.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E02 - The Baffling Raffle",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E02 - The Baffling Raffle.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E03 - The Dog Turns Playboy",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E03 - The Dog Turns Playboy.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E04 - The Good Luck Ring",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E04 - The Good Luck Ring.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E05 - Joe Carson, General Contractor",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E05 - Joe Carson, General Contractor.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E06 - Bobbie Jo's Sorority",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E06 - Bobbie Jo's Sorority.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E07 - A Doctor In The House",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E07 - A Doctor In The House.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E08 - Hooterville A-Go-Go",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E08 - Hooterville A-Go-Go.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E09 - Hooterville Hurricane",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E09 - Hooterville Hurricane.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E10 - Betty Jo Goes to New York",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E10 - Betty Jo Goes to New York.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E11 - Bedloe's Successor",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E11 - Bedloe's Successor.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E12 - The Crowded Wedding Ring",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E12 - The Crowded Wedding Ring.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E13 - Uncle Joe Plays Post Office",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E13 - Uncle Joe Plays Post Office.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E14 - What's A Trajectory",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E14 - What's A Trajectory.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E15 - The Butler Did It",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E15 - The Butler Did It.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E16 - Better Never Than Late",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E16 - Better Never Than Late.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E17 - Betty Jo Catches The Bouquet",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E17 - Betty Jo Catches The Bouquet.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E18 - Billy Jo's Independence Day",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E18 - Billy Jo's Independence Day.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E19 - Yogurt, Anyone",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E19 - Yogurt, Anyone.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E20 - Only Boy In the Class",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E20 - Only Boy In the Class.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E21 - The County Fair",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E21 - The County Fair.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E22 - Jury at the Shady Rest",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E22 - Jury at the Shady Rest.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E23 - The Invisible Mr. Dobble",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E23 - The Invisible Mr. Dobble.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E24 - It's Not the Principle, It's the Money",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E24 - It's Not the Principle, It's the Money.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E25 - War of the Hotels",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E25 - War of the Hotels.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E26 - The Windfall",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E26 - The Windfall.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E27 - Second Honeymoon",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E27 - Second Honeymoon.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E28 - Kate Sells the Hotel",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E28 - Kate Sells the Hotel.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E29 - Kate Bradley, Peacemaker",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E29 - Kate Bradley, Peacemaker.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E30 - Whatever Happened to Betty Jo",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E30 - Whatever Happened to Betty Jo.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E31 - Every Bachelor Should Have a Family",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E31 - Every Bachelor Should Have a Family.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E32 - The Young Matchmakers",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E32 - The Young Matchmakers.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E33 - Hooterville Valley Project",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E33 - Hooterville Valley Project.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S03E34 - Betty Jo's Bike",
    "Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E34 - Betty Jo's Bike.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E01 - Young Love",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x01 - Young Love.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E02 - Birdman Of Shady Rest (Part 1 of 2)",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x02 - Birdman Of Shady Rest (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E03 - Hooterville, You're All Heart (Part 2 of 2)",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x03 - Hooterville, You're All Heart (Part 2 of 2) .mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E04 - He Loves Us, He Loves Us Not",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x04 - He Loves Us, He Loves Us Not.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E05 - The All-Night Party",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x05 - The All-Night Party.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E06 - Cannonball, Inc",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x06 - Cannonball, Inc.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E07 - Kate Grounds Selma Plout",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x07 - Kate Grounds Selma Plout.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E08 - The Almost Annual Charity Show",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x08 - The Almost Annual Charity Show.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E09 - How Bugged Was My Valley",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x09 - How Bugged Was My Valley.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E10 - Twenty-Five Years Too Late",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x10 - Twenty-Five Years Too Late.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E11 - The Runt Strikes Back",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x11 - The Runt Strikes Back.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E12 - Is There a Doctor in the Valley",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x12 - Is There a Doctor in the Valley.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E13 - The Santa Claus Special",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x13 - The Santa Claus Special.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E14 - My Daughter the Secretary",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x14 - My Daughter the Secretary.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E15 - The Rise and Fall of a Tycoon",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x15 - The Rise and Fall of a Tycoon.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E16 - His Highness the Dog",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x16 - His Highness the Dog.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E17 - Girls! Girls! Girls!",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x17 - Girls! Girls! Girls!.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E18 - Temperance, Temperance",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x18 - Termperance, Temperance.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E19 - A Star is Born",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x19 - A Star is Born.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E20 - Shoplifter at the Shady Rest",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x20 - Shoplifter at the Shady Rest.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E21 - Don't Call Us",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x21 - Don't Call Us.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E22 - Hey, Look Me Over",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x22 - Hey, Look Me Over.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E23 - That's Max",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x23 - That's Max.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E24 - The Fishing Derby",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x24 - The Fishing Derby.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E25 - Kate's Big Deal",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x25 - Kate's Big Deal.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E26 - Author! Author!",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x26 - Author! Author!.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E27 - Steve's Ol' Buddy",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x27 - Steve's Ol' Buddy.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E28 - That Was the Night That Was",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x28 - That Was the Night That Was.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E29 - The Eternal Rectangle",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x29 - The Eternal Rectangle.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E30 - Kate's Cousin Mae",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x30 - Kate's Cousin Mae.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E31 - A House Divided",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x31 - A House Divided.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S04E32 - Go Away, Fat",
    "Petticoat Junction - Season 4/Petticoat Junction - 4x32 - Go Away, Fat.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E01 - Is This My Daughter",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x01 - Is This My Daughter.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E02 - It's Not Easy to Be a Mother",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x02 - It's Not Easy to Be a Mother.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E03 - One Dozen Roses",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x03 - One Dozen Roses.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E04 - You Know I Can't Hear You When the Thunder is Clapping",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x04 - You Know I Can't Hear You When the Thunder is Clapping.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E05 - Pop Goes The Question",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x05 - Pop Goes The Question.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E06 - A Cottage For Two",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x06 - A Cottage For Two.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E07 - Mind If We Join Your Wedding",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x07 - Mind If We Join Your Wedding.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E08 - Meet the In-Laws",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x08 - Meet the In-Laws.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E09 - With This Gown I Thee Wed",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x09 - With This Gown I Thee Wed.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E10 - Hawaii Calling",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x10 - Hawaii Calling.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E11 - Kate's Birthday",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x11 - Kate's Birthday.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E12 - The Honeymoon is Over",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x12 - The Honeymoon is Over.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E13 - A Horse on You, Mr. Bedloe",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x13 - A Horse on You, Mr. Bedloe.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E14 - Kate's Day in Court",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x14 - Kate's Day in Court.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E15 - Uncle Joe and the Master Plan",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x15 - Uncle Joe and the Master Plan.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E16 - All That Buzzes Ain't Bees",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x16 - All That Buzzes Ain't Bees.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E17 - All Sales Final",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x17 - All Sales Final.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E18 - The Power of the Press",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x18 - The Power of the Press.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E19 - Steve, The Apple Polisher",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x19 - Steve, The Apple Polisher.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E20 - The Barber Shop Quartet",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x20 - The Barber Shop Quartet.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E21 - Come Home Higgins",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x21 - Come Home Higgins.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E22 - Girl of Our Dreams",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x22 - Girl of Our Dreams.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E23 - Uncle Joe Runs The Hotel",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x23 - Uncle Joe Runs The Hotel.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E24 - Billie Jo's First Record",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x24 - Billie Jo's First Record.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E25 - Mae's Helping Hand",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x25 - Mae's Helping Hand.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E26 - Bad Day at Shady Rest",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x26 - Bad Day at Shady Rest.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E27 - Cannonball for Sale",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x27 - Cannonball for Sale.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E28 - My Pal Sam",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x28 - My Pal Sam.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E29 - Ring-A-Ding-Ding",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x29 - Ring-A-Ding-Ding.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S05E30 - Kate's Homecoming",
    "Petticoat Junction - Season 5/Petticoat Junction - 5x30 - Kate's Homecoming.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E01 - Birthplace of a Future President",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x01 - Birthplace of a Future President.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E02 - The Singing Sweethearts",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x02 - The Singing Sweethearts.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E03 - Only a Husband",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x03 - Only a Husband.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E04 - The Valley Has a Baby",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x04 - The Valley Has a Baby.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E05 - Granny, The Baby Expert",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x05 - Granny, The Baby Expert.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E06 - Wings",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x06 - Wings.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E07 - The Lady Doctor",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x07 - The Lady Doctor.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E08 - The Sneaky Ways of a Woman Who is Both Beautiful and Smart",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x08 - The Sneaky Ways of a Woman Who is Both Beautiful and Smart.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E09 - The Strange Case of Joseph P. Carson",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x09 - The Strange Case of Joseph P. Carson.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E10 - Bye, Bye, Doctor",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x10 - Bye, Bye, Doctor.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E11 - First Night Out",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x11 - First Night Out.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E12 - A Cake from Granny",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x12 - A Cake from Granny.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E13 - The Feminine Mistake",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x13 - The Feminine Mistake.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E14 - The Ballad of the Everyday Housewife",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x14 - The Ballad of the Everyday Housewife.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E15 - The Christening",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x15 - The Christening.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E16 - Billie Jo and the Big, Big Star",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x16 - Billie Jo and the Big, Big Star.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E17 - Steve's New Job",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x17 - Steve's New Job.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E18 - The Cannonball Bookmobile",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x18 - The Cannonball Bookmobile.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E19 - A Man Called Cyrus Plout",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x19 - A Man Called Cyrus Plout.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E20 - Joe Saves the Post Office",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x20 - Joe Saves the Post Office.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E21 - I'm Allergic to Daddy",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x21 - I'm Allergic to Daddy.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E22 - Uncle Joe Retires",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x22 - Uncle Joe Retires.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E23 - The Organ Fund",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x23 - The Organ Fund.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E24 - The Great Race",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x24 - The Great Race.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E25 - Tune in Next Year",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x25 - Tune in Next Year.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S06E26 - By the Book",
    "Petticoat Junction - Season 6/Petticoat Junction - 6x26 - By the Book.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E01 - Make Room for Baby",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x01 - Make Room for Baby.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E02 - The Game Warden",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x02 - The Game Warden .mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E03 - The Other Woman",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x03 - The Other Woman .mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E04 - One of Our Chickens is Missing",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x04 - One of Our Chickens is Missing.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E05 - The Three Queens",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x05 - The Three Queens.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E06 - The Glen Tinker Caper",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x06 - The Glen Tinker Caper.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E07 - The Tenant",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x07 - The Tenant.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E08 - Sorry Doctor, I Ain't Takin' No Shots",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x08 - Sorry Doctor, I Ain't Takin' No Shots.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E09 - A Most Momentous Occasion",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x09 - A Most Momentous Occasion.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E10 - The Camping Trip",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x10 - The Camping Trip.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E11 - Kathy Jo's First Birthday (Part 1 of 2)",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x11 - Kathy Jo's First Birthday (Part 1 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E12 - Goodbye, Mr. Chimp (Part 2 of 2)",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x12 - Goodbye, Mr. Chimp (Part 2 of 2).mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E13 - The Golden Spike Ceremony",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x13 - The Golden Spike Ceremony.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E14 - But I've Never Been in Erie, PA",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x14 - But I've Never Been in Erie, PA.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E15 - How to Arrange a Marriage",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x15 - How to Arrange a Marriage.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E16 - Selma Plout's Plot",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x16 - Selma Plout's Plot.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E17 - With This Ring...",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x17 - With This Ring....mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E18 - The Valley's New Owner",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x18 - The Valley's New Owner.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E19 - Steve's Uncle George",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x19 - Steve's Uncle George.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E20 - Susan B. Anthony, I Love You",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x20 - Susan B. Anthony, I Love You.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E21 - Spare That Cottage",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x21 - Spare That Cottage.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E22 - Whiplash, Whiplash",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x22 - Whiplash, Whiplash.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E23 - Last Train to Pixley",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x23 - Last Train to Pixley.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E24 - Love Rears Its Ugly Head",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x24 - Love Rears Its Ugly Head.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E25 - No, No, You Can't Take Her Away",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x25 - No, No, You Can't Take Her Away.mp4"],
  ['Petticoat_Junction_Series', "PETTICOAT JUNCTION - S07E26 - Betty Jo's Business",
    "Petticoat Junction - Season 7/Petticoat Junction - 7x26 - Betty Jo's Business.mp4"],
],
  durations: {
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E01 - Spur Lane to Shady Rest (Part 1 of 2).mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E02 - Quick, Hide the Railroad (Part 2 of 2).mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E03 - The President Who Came to Dinner (Part 1 of 2).mp4": 1539,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E04 - Is There a Doctor in the Roundhouse (Part 2 of 2).mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E05 - The Courtship of Floyd Smoot.mp4": 1520,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E06 - Please Buy My Violets.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E07 - The Ringer.mp4": 1539,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E08 - Kate's Recipe for Hot Rhubarb.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E09 - The Little Train Robbery.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E10 - Bedloe Strikes Again.mp4": 1546,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E11 - Uncle Joe's Replacement.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E12 - Honeymoon Hotel.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E13 - A Night at the Hooterville Hilton.mp4": 1545,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E14 - Cannonball Christmas.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E15 - Herby Gets Drafted.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E16 - Bobbie Jo and the Beatnik.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E17 - My Daughter the Doctor (Part 1 of 2).mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E18 - Hooterville vs. Hollywood (Part 2 of 2).mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E19 - Visit from a Big Star.mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E20 - Last Chance Farm.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E21 - The Very Old Antique.mp4": 1545,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E22 - The Art Game.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E23 - Betty Jo's First Love.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E24 - Behind All Silver, There's a Cloud Lining.mp4": 1531,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E25 - The Talent Contest.mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E26 - Kate and the Manpower Problem.mp4": 1531,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E27 - The Ladybugs (March 24, 1964).mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E28 - The Hooterville Flivverball.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E29 - Kate the Stockholder.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E30 - Kate and the Dowager.mp4": 1536,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E31 - Charley Abandons the Cannonball.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E32 - Dog Days at Shady Rest.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E33 - A Millionaire for Kate.mp4": 1545,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E34 - Bedloe and Son.mp4": 1545,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E35 - Local Girl Makes Good.mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E36 - Cave Woman (Part 1 of 2).mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E37 - Kate, Flat on Her Back (Part 2 of 2).mp4": 1534,
  "Petticoat_Junction_Series::Petticoat Junction - Season 1/Petticoat Junction S01E38 - The Genghis Keane Story.mp4": 1548,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E01 - Betty Jo's Dog.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E02 - Race Against the Stork.mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E03 - Have Library, Will Travel.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E04 - The Umquaw Strip.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E05 - As Hooterville Goes.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E06 - My Dog the Actor.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E07 - The Great Buffalo Hunt.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E08 - Betty Jo's Pen Pal.mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E09 - Bedloe's Nightmare.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E10 - Kate's Bachelor Butter.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E11 - Mother of the Bride.mp4": 1528,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E12 - The Lost Patrol.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E13 - Smoke-Eaters.mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E14 - The Curse of Chester W. Farnsworth.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E15 - There's No Flame Like an Old Flame.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E16 - Billy Jo's First Job.mp4": 1545,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E17 - A Matter of Communication.mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E18 - Kate Bradley, Girl Volunteer.mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E19 - Hooterville Crime Wave.mp4": 1521,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E20 - For the Birds.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E21 - Modern Merchandising.mp4": 1542,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E22 - Visit From the Governor.mp4": 1531,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E23 - A Borderline Story.mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E24 - The Shady Rest Hotel Corporation.mp4": 1545,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E25 - A Tale of Two Dogs.mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E26 - The Black Box.mp4": 1540,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E27 - Bedloe's Most Fiendish Scheme (Part 1 of 2).mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E28 - Bedloe Gets His Comeuppance (Part 2 of 2).mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E29 - The Mayor of Hooterville.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E30 - Who's Afraid of the Big Bad Jinx.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E31 - The Chicken Killer.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E32 - Why Girls Leave Home.mp4": 1547,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E33 - There's No Stove Like an Old Stove.mp4": 1535,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E34 - The Brontosaurus Caper.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E35 - The Hairbrained Scheme.mp4": 1480,
  "Petticoat_Junction_Series::Petticoat Junction - Season 2/Petticoat Junction S02E36 - There's No Business with Show Business.mp4": 1541,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E01 - Dear Minerva.mp4": 1517,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E02 - The Baffling Raffle.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E03 - The Dog Turns Playboy.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E04 - The Good Luck Ring.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E05 - Joe Carson, General Contractor.mp4": 1535,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E06 - Bobbie Jo's Sorority.mp4": 1534,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E07 - A Doctor In The House.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E08 - Hooterville A-Go-Go.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E09 - Hooterville Hurricane.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E10 - Betty Jo Goes to New York.mp4": 1536,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E11 - Bedloe's Successor.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E12 - The Crowded Wedding Ring.mp4": 1524,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E13 - Uncle Joe Plays Post Office.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E14 - What's A Trajectory.mp4": 1535,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E15 - The Butler Did It.mp4": 1536,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E16 - Better Never Than Late.mp4": 1534,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E17 - Betty Jo Catches The Bouquet.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E18 - Billy Jo's Independence Day.mp4": 1533,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E19 - Yogurt, Anyone.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E20 - Only Boy In the Class.mp4": 1514,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E21 - The County Fair.mp4": 1502,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E22 - Jury at the Shady Rest.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E23 - The Invisible Mr. Dobble.mp4": 1535,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E24 - It's Not the Principle, It's the Money.mp4": 1536,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E25 - War of the Hotels.mp4": 1523,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E26 - The Windfall.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E27 - Second Honeymoon.mp4": 1536,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E28 - Kate Sells the Hotel.mp4": 1536,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E29 - Kate Bradley, Peacemaker.mp4": 1535,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E30 - Whatever Happened to Betty Jo.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E31 - Every Bachelor Should Have a Family.mp4": 1534,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E32 - The Young Matchmakers.mp4": 1527,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E33 - Hooterville Valley Project.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 3 (50th Anniversary Edition)/Petticoat Junction S03E34 - Betty Jo's Bike.mp4": 1523,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x01 - Young Love.mp4": 1512,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x02 - Birdman Of Shady Rest (Part 1 of 2).mp4": 1508,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x03 - Hooterville, You're All Heart (Part 2 of 2) .mp4": 1514,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x04 - He Loves Us, He Loves Us Not.mp4": 1524,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x05 - The All-Night Party.mp4": 1512,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x06 - Cannonball, Inc.mp4": 1524,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x07 - Kate Grounds Selma Plout.mp4": 1521,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x08 - The Almost Annual Charity Show.mp4": 1513,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x09 - How Bugged Was My Valley.mp4": 1506,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x10 - Twenty-Five Years Too Late.mp4": 1492,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x11 - The Runt Strikes Back.mp4": 1507,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x12 - Is There a Doctor in the Valley.mp4": 1458,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x13 - The Santa Claus Special.mp4": 1527,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x14 - My Daughter the Secretary.mp4": 1517,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x15 - The Rise and Fall of a Tycoon.mp4": 1511,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x16 - His Highness the Dog.mp4": 1512,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x17 - Girls! Girls! Girls!.mp4": 1502,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x18 - Termperance, Temperance.mp4": 1519,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x19 - A Star is Born.mp4": 1525,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x20 - Shoplifter at the Shady Rest.mp4": 1519,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x21 - Don't Call Us.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x22 - Hey, Look Me Over.mp4": 1514,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x23 - That's Max.mp4": 1517,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x24 - The Fishing Derby.mp4": 1512,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x25 - Kate's Big Deal.mp4": 1509,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x26 - Author! Author!.mp4": 1517,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x27 - Steve's Ol' Buddy.mp4": 1514,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x28 - That Was the Night That Was.mp4": 1500,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x29 - The Eternal Rectangle.mp4": 1512,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x30 - Kate's Cousin Mae.mp4": 1511,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x31 - A House Divided.mp4": 1513,
  "Petticoat_Junction_Series::Petticoat Junction - Season 4/Petticoat Junction - 4x32 - Go Away, Fat.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x01 - Is This My Daughter.mp4": 1491,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x02 - It's Not Easy to Be a Mother.mp4": 1522,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x03 - One Dozen Roses.mp4": 1516,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x04 - You Know I Can't Hear You When the Thunder is Clapping.mp4": 1521,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x05 - Pop Goes The Question.mp4": 1538,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x06 - A Cottage For Two.mp4": 1510,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x07 - Mind If We Join Your Wedding.mp4": 1463,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x08 - Meet the In-Laws.mp4": 1529,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x09 - With This Gown I Thee Wed.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x10 - Hawaii Calling.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x11 - Kate's Birthday.mp4": 1502,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x12 - The Honeymoon is Over.mp4": 1521,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x13 - A Horse on You, Mr. Bedloe.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x14 - Kate's Day in Court.mp4": 1513,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x15 - Uncle Joe and the Master Plan.mp4": 1513,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x16 - All That Buzzes Ain't Bees.mp4": 1476,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x17 - All Sales Final.mp4": 1511,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x18 - The Power of the Press.mp4": 1514,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x19 - Steve, The Apple Polisher.mp4": 1516,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x20 - The Barber Shop Quartet.mp4": 1526,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x21 - Come Home Higgins.mp4": 1529,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x22 - Girl of Our Dreams.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x23 - Uncle Joe Runs The Hotel.mp4": 1496,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x24 - Billie Jo's First Record.mp4": 1522,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x25 - Mae's Helping Hand.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x26 - Bad Day at Shady Rest.mp4": 1532,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x27 - Cannonball for Sale.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x28 - My Pal Sam.mp4": 1492,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x29 - Ring-A-Ding-Ding.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 5/Petticoat Junction - 5x30 - Kate's Homecoming.mp4": 1515,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x01 - Birthplace of a Future President.mp4": 1556,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x02 - The Singing Sweethearts.mp4": 1549,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x03 - Only a Husband.mp4": 1552,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x04 - The Valley Has a Baby.mp4": 1531,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x05 - Granny, The Baby Expert.mp4": 1568,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x06 - Wings.mp4": 1563,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x07 - The Lady Doctor.mp4": 1547,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x08 - The Sneaky Ways of a Woman Who is Both Beautiful and Smart.mp4": 1550,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x09 - The Strange Case of Joseph P. Carson.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x10 - Bye, Bye, Doctor.mp4": 1391,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x11 - First Night Out.mp4": 1409,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x12 - A Cake from Granny.mp4": 1562,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x13 - The Feminine Mistake.mp4": 1428,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x14 - The Ballad of the Everyday Housewife.mp4": 1553,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x15 - The Christening.mp4": 1591,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x16 - Billie Jo and the Big, Big Star.mp4": 1415,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x17 - Steve's New Job.mp4": 1426,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x18 - The Cannonball Bookmobile.mp4": 1550,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x19 - A Man Called Cyrus Plout.mp4": 1414,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x20 - Joe Saves the Post Office.mp4": 1556,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x21 - I'm Allergic to Daddy.mp4": 1462,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x22 - Uncle Joe Retires.mp4": 1401,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x23 - The Organ Fund.mp4": 1424,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x24 - The Great Race.mp4": 1417,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x25 - Tune in Next Year.mp4": 1554,
  "Petticoat_Junction_Series::Petticoat Junction - Season 6/Petticoat Junction - 6x26 - By the Book.mp4": 1693,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x01 - Make Room for Baby.mp4": 1548,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x02 - The Game Warden .mp4": 1552,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x03 - The Other Woman .mp4": 1550,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x04 - One of Our Chickens is Missing.mp4": 1552,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x05 - The Three Queens.mp4": 1543,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x06 - The Glen Tinker Caper.mp4": 1555,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x07 - The Tenant.mp4": 1547,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x08 - Sorry Doctor, I Ain't Takin' No Shots.mp4": 1552,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x09 - A Most Momentous Occasion.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x10 - The Camping Trip.mp4": 1390,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x11 - Kathy Jo's First Birthday (Part 1 of 2).mp4": 1317,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x12 - Goodbye, Mr. Chimp (Part 2 of 2).mp4": 1552,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x13 - The Golden Spike Ceremony.mp4": 1537,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x14 - But I've Never Been in Erie, PA.mp4": 1656,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x15 - How to Arrange a Marriage.mp4": 1606,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x16 - Selma Plout's Plot.mp4": 1544,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x17 - With This Ring....mp4": 1556,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x18 - The Valley's New Owner.mp4": 1551,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x19 - Steve's Uncle George.mp4": 1551,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x20 - Susan B. Anthony, I Love You.mp4": 1549,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x21 - Spare That Cottage.mp4": 1521,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x22 - Whiplash, Whiplash.mp4": 1633,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x23 - Last Train to Pixley.mp4": 1551,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x24 - Love Rears Its Ugly Head.mp4": 1550,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x25 - No, No, You Can't Take Her Away.mp4": 1546,
  "Petticoat_Junction_Series::Petticoat Junction - Season 7/Petticoat Junction - 7x26 - Betty Jo's Business.mp4": 1547,
},
};
