window.SHOW = {
  id: "MuppetBabies",
  title: "Muppet Babies",
  storageProgressKey: "muppetbabies-progress",
  storageSettingsKey: "muppetbabies-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['muppet_babies', "MUPPET BABIES - S01E01 - Noisy Neigbors",
    "S1E01 Noisy Neigbors.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E02 - Are You Afraid of the Big Bag Dark",
    "S1E02 Are You Afraid of the Big Bag Dark.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E03 - Dental Hyjinks",
    "S1E03 Dental Hyjinks.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E04 - Raiders of the Lost Muppet",
    "S1E04 Raiders of the Lost Muppet.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E05 - Scooter's Hidden Talent",
    "S1E05 Scooter's Hidden Talent.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E06 - The Case of the Missing Chicken",
    "S1E06 The Case of the Missing Chicken.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E07 - Eight Take Away One Equals Panic",
    "S1E07 Eight Take Away One Equals Panic.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E08 - What Do You Want To Be When You Grow Up",
    "S1E08 What Do You Want To Be When You Grow Up.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E09 - Close Encounters of the Frog Kind",
    "S1E09 Close Encounters of the Frog Kind.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E10 - Gonzo's Video Show",
    "S1E10 Gonzo's Video Show.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E11 - Fun Park Fantasies",
    "S1E11 Fun Park Fantasies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E12 - From a Galaxy Far, Far Away",
    "S1E12 From a Galaxy Far, Far Away.mp4"],
  ['muppet_babies', "MUPPET BABIES - S01E13 - Good Clean Fun",
    "S1E13 Good Clean Fun.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E01 - Once Upon an Egg Timer",
    "S2E01 Once Upon an Egg Timer.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E02 - Piggy's Hyper-Activity Book",
    "S2E02 Piggy's Hyper-Activity Book.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E03 - Fozzie's Last Laugh",
    "S2E03 Fozzie's Last Laugh.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E04 - The Great Cookie Robbery",
    "S2E04 The Great Cookie Robbery.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E05 - Out Of This World History",
    "S2E05 Out Of This World History.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E06 - Snow White and the Seven Muppets",
    "S2E06 Snow White and the Seven Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E07 - I Want My Muppet T.V.",
    "S2E07 I Want My Muppet T.V..mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E08 - Musical Muppets",
    "S2E08 Musical Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E09 - What's New at the Zoo",
    "S2E09 What's New at the Zoo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E10 - The Great Muppet Cartoon Show",
    "S2E10 The Great Muppet Cartoon Show.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E11 - The Muppet Museum of Art",
    "S2E11 The Muppet Museum of Art.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E12 - By the Book",
    "S2E12 By the Book.mp4"],
  ['muppet_babies', "MUPPET BABIES - S02E13 - When You Wish Upon a Muppet",
    "S2E13 When You Wish Upon a Muppet.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E01 - Pigerella",
    "S3E01 Pigerella.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E02 - The Best Friend I Never Had",
    "S3E02 The Best Friend I Never Had.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E03 - The Weirdo Zone",
    "S3E03 The Weirdo Zone.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E04 - Muppets in Toyland",
    "S3E04 Muppets in Toyland.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E05 - The Muppet Broadcasting Company",
    "S3E05 The Muppet Broadcasting Company.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E06 - Kermit Goes to Washington",
    "S3E06 Kermit Goes to Washington.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E07 - Fozzie’s Family Tree",
    "S3E07 Fozzie’s Family Tree.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E08 - The Daily Muppet",
    "S3E08 The Daily Muppet.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E09 - Scooter’s Uncommon Cold",
    "S3E09 Scooter’s Uncommon Cold.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E10 - Treasure Attic",
    "S3E10 Treasure Attic.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E11 - Around the Nursery in 80 Days",
    "S3E11 Around the Nursery in 80 Days.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E12 - Fine Feathered Enemies",
    "S3E12 Fine Feathered Enemies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E13 - Muppet Goose",
    "S3E13 Muppet Goose.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E14 - Bad Luck Bear",
    "S3E14 Bad Luck Bear.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E15 - Of Mice and Muppets",
    "S3E15 Of Mice and Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S03E16 - Back to the Nursery",
    "S3E16 Back to the Nursery.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E01 - Muppetland",
    "S4E01 Muppetland.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E02 - Water Babies",
    "S4E02 Water Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E03 - The Incredible Shrinking Weirdo",
    "S4E03 The Incredible Shrinking Weirdo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E04 - Where No Muppet Has Gone Before",
    "S4E04 Where No Muppet Has Gone Before.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E05 - Journey to the Center of the Nursery",
    "S4E05 Journey to the Center of the Nursery.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E06 - This Little Piggy Went to Hollywood",
    "S4E06 This Little Piggy Went to Hollywood.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E07 - My Muppet Valentine",
    "S4E07 My Muppet Valentine.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E08 - Invasion of the Muppet Snackers",
    "S4E08 Invasion of the Muppet Snackers.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E09 - Twinkle Toe Muppets",
    "S4E09 Twinkle Toe Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E10 - Weirdo for the Prosecution",
    "S4E10 Weirdo for the Prosecution.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E11 - Muppet Island",
    "S4E11 Muppet Island.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E12 - The Frog Who Knew Too Much",
    "S4E12 The Frog Who Knew Too Much.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E13 - Beach Blanket Babies",
    "S4E13 Beach Blanket Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E14 - Old MacKermit Had a Farm",
    "S4E14 Old MacKermit Had a Farm.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E15 - Adventures in Muppet-Sitting",
    "S4E15 Adventures in Muppet-Sitting.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E16 - The House That Muppets Built",
    "S4E16 The House That Muppets Built.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E17 - Masquerading Muppets",
    "S4E17 Masquerading Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S04E18 - Nanny’s Day Off",
    "S4E18 Nanny’s Day Off.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E01 - Muppets Not Included",
    "S5E01 Muppets Not Included.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E02 - Beauty and the Schnoz",
    "S5E02 Beauty and the Schnoz.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E03 - The Pig Who Would Be Queen",
    "S5E03 The Pig Who Would Be Queen.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E04 - Is There a Muppet in the House",
    "S5E04 Is There a Muppet in the House.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E05 - Slipping Beauty",
    "S5E05 Slipping Beauty.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E06 - Muppet Baby Boom",
    "S5E06 Muppet Baby Boom.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E07 - Scooter by Any Other Name",
    "S5E07 Scooter by Any Other Name.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E08 - He’s a Wonderful Frog",
    "S5E08 He’s a Wonderful Frog.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E09 - Elm Street Babies",
    "S5E09 Elm Street Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E10 - Plan 8 from Outer Space",
    "S5E10 Plan 8 from Outer Space.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E11 - Junkyard Muppets",
    "S5E11 Junkyard Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E12 - The Air Conditioner at the End of the Galaxy",
    "S5E12 The Air Conditioner at the End of the Galaxy.mp4"],
  ['muppet_babies', "MUPPET BABIES - S05E13 - Bug-Busting Babies",
    "S5E13 Bug-Busting Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E01 - This Old Nursery",
    "S6E01 This Old Nursery.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E02 - And Now a Word from Our Muppets",
    "S6E02 And Now a Word from Our Muppets.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E03 - Six-to-Eight Weeks",
    "S6E03 Six-to-Eight Weeks.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E04 - The Green Ranger",
    "S6E04 The Green Ranger.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E05 - Not Necessarily the Babies",
    "S6E05 Not Necessarily the Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E06 - Comic Capers",
    "S6E06 Comic Capers.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E07 - Faster Than a Speeding Weirdo",
    "S6E07 Faster Than a Speeding Weirdo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E08 - Skeeter and the Wolf",
    "S6E08 Skeeter and the Wolf.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E09 - Romancing the Weirdo",
    "S6E09 Romancing the Weirdo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E10 - The New Adventures of Kermo Polo",
    "S6E10 The New Adventures of Kermo Polo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S06E11 - Goosetown Babies",
    "S6E11 Goosetown Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E01 - It’s Only Pretendo",
    "S7E01 It’s Only Pretendo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E02 - Quoth the Weirdo",
    "S7E02 Quoth the Weirdo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E03 - Operators Are Standing by",
    "S7E03 Operators Are Standing by.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E04 - Babes in Troyland",
    "S7E04 Babes in Troyland.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E05 - Puss ‘n’ Boots ‘n’ Babies",
    "S7E05 Puss ‘n’ Boots ‘n’ Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E06 - Muppets of Invention",
    "S7E06 Muppets of Invention.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E07 - A Punch Line to the Tummy",
    "S7E07 A Punch Line to the Tummy.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E08 - Muppet Babies_The Next Generation",
    "S7E08 Muppet Babies_The Next Generation.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E09 - Buckskin Babies",
    "S7E09 Buckskin Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E10 - Sing a Song of Superheroes",
    "S7E10 Sing a Song of Superheroes.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E11 - Gonzee’s Playhouse Channel",
    "S7E11 Gonzee’s Playhouse Channel.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E12 - Kermit Pan",
    "S7E12 Kermit Pan.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E13 - Whose Tale Is It Anyway",
    "S7E13 Whose Tale Is It Anyway.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E14 - At The Movies",
    "S7E14 At The Movies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S07E15 - In Search of the Bronzed Beetle",
    "S7E15 In Search of the Bronzed Beetle.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E01 - The Transcontinental Whoo-Whoo",
    "S8E1 The Transcontinental Whoo-Whoo.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E02 - Get Me to the Perch on Time",
    "S8E2 Get Me to the Perch on Time.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E03 - Bearly Alone Babies",
    "S8E3 Bearly Alone Babies.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E04 - Remote Control Cornballs",
    "S8E4 Remote Control Cornballs.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E05 - Nice to Have Gnome",
    "S8E5 Nice to Have Gnome.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E06 - Happy Birthday Uncle Piggy",
    "S8E6 Happy Birthday Uncle Piggy.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E07 - Hats!, Hats!, Hats!",
    "S8E7 Hats!, Hats!, Hats!.mp4"],
  ['muppet_babies', "MUPPET BABIES - S08E08 - Eight Flags Over the Nursery",
    "S8E8 Eight Flags Over the Nursery.mp4"],
],
  durations: {
  "muppet_babies::S1E01 Noisy Neigbors.mp4": 1332,
  "muppet_babies::S1E02 Are You Afraid of the Big Bag Dark.mp4": 1450,
  "muppet_babies::S1E03 Dental Hyjinks.mp4": 1458,
  "muppet_babies::S1E04 Raiders of the Lost Muppet.mp4": 1407,
  "muppet_babies::S1E05 Scooter's Hidden Talent.mp4": 1461,
  "muppet_babies::S1E06 The Case of the Missing Chicken.mp4": 1459,
  "muppet_babies::S1E07 Eight Take Away One Equals Panic.mp4": 1459,
  "muppet_babies::S1E08 What Do You Want To Be When You Grow Up.mp4": 1459,
  "muppet_babies::S1E09 Close Encounters of the Frog Kind.mp4": 1387,
  "muppet_babies::S1E10 Gonzo's Video Show.mp4": 1463,
  "muppet_babies::S1E11 Fun Park Fantasies.mp4": 1337,
  "muppet_babies::S1E12 From a Galaxy Far, Far Away.mp4": 1458,
  "muppet_babies::S1E13 Good Clean Fun.mp4": 1471,
  "muppet_babies::S2E01 Once Upon an Egg Timer.mp4": 1474,
  "muppet_babies::S2E02 Piggy's Hyper-Activity Book.mp4": 1437,
  "muppet_babies::S2E03 Fozzie's Last Laugh.mp4": 1453,
  "muppet_babies::S2E04 The Great Cookie Robbery.mp4": 1474,
  "muppet_babies::S2E05 Out Of This World History.mp4": 1435,
  "muppet_babies::S2E06 Snow White and the Seven Muppets.mp4": 1474,
  "muppet_babies::S2E07 I Want My Muppet T.V..mp4": 1443,
  "muppet_babies::S2E08 Musical Muppets.mp4": 1349,
  "muppet_babies::S2E09 What's New at the Zoo.mp4": 1447,
  "muppet_babies::S2E10 The Great Muppet Cartoon Show.mp4": 1416,
  "muppet_babies::S2E11 The Muppet Museum of Art.mp4": 1415,
  "muppet_babies::S2E12 By the Book.mp4": 1456,
  "muppet_babies::S2E13 When You Wish Upon a Muppet.mp4": 1449,
  "muppet_babies::S3E01 Pigerella.mp4": 1442,
  "muppet_babies::S3E02 The Best Friend I Never Had.mp4": 1437,
  "muppet_babies::S3E03 The Weirdo Zone.mp4": 1441,
  "muppet_babies::S3E04 Muppets in Toyland.mp4": 1436,
  "muppet_babies::S3E05 The Muppet Broadcasting Company.mp4": 1435,
  "muppet_babies::S3E06 Kermit Goes to Washington.mp4": 1437,
  "muppet_babies::S3E07 Fozzie’s Family Tree.mp4": 1338,
  "muppet_babies::S3E08 The Daily Muppet.mp4": 1477,
  "muppet_babies::S3E09 Scooter’s Uncommon Cold.mp4": 1439,
  "muppet_babies::S3E10 Treasure Attic.mp4": 1136,
  "muppet_babies::S3E11 Around the Nursery in 80 Days.mp4": 1476,
  "muppet_babies::S3E12 Fine Feathered Enemies.mp4": 1438,
  "muppet_babies::S3E13 Muppet Goose.mp4": 1487,
  "muppet_babies::S3E14 Bad Luck Bear.mp4": 1429,
  "muppet_babies::S3E15 Of Mice and Muppets.mp4": 1483,
  "muppet_babies::S3E16 Back to the Nursery.mp4": 1422,
  "muppet_babies::S4E01 Muppetland.mp4": 1329,
  "muppet_babies::S4E02 Water Babies.mp4": 1405,
  "muppet_babies::S4E03 The Incredible Shrinking Weirdo.mp4": 1405,
  "muppet_babies::S4E04 Where No Muppet Has Gone Before.mp4": 1339,
  "muppet_babies::S4E05 Journey to the Center of the Nursery.mp4": 1411,
  "muppet_babies::S4E06 This Little Piggy Went to Hollywood.mp4": 1415,
  "muppet_babies::S4E07 My Muppet Valentine.mp4": 1473,
  "muppet_babies::S4E08 Invasion of the Muppet Snackers.mp4": 1337,
  "muppet_babies::S4E09 Twinkle Toe Muppets.mp4": 1335,
  "muppet_babies::S4E10 Weirdo for the Prosecution.mp4": 1405,
  "muppet_babies::S4E11 Muppet Island.mp4": 1400,
  "muppet_babies::S4E12 The Frog Who Knew Too Much.mp4": 1413,
  "muppet_babies::S4E13 Beach Blanket Babies.mp4": 1441,
  "muppet_babies::S4E14 Old MacKermit Had a Farm.mp4": 1398,
  "muppet_babies::S4E15 Adventures in Muppet-Sitting.mp4": 1332,
  "muppet_babies::S4E16 The House That Muppets Built.mp4": 1439,
  "muppet_babies::S4E17 Masquerading Muppets.mp4": 1438,
  "muppet_babies::S4E18 Nanny’s Day Off.mp4": 1350,
  "muppet_babies::S5E01 Muppets Not Included.mp4": 1441,
  "muppet_babies::S5E02 Beauty and the Schnoz.mp4": 1342,
  "muppet_babies::S5E03 The Pig Who Would Be Queen.mp4": 1455,
  "muppet_babies::S5E04 Is There a Muppet in the House.mp4": 1331,
  "muppet_babies::S5E05 Slipping Beauty.mp4": 1439,
  "muppet_babies::S5E06 Muppet Baby Boom.mp4": 1434,
  "muppet_babies::S5E07 Scooter by Any Other Name.mp4": 1379,
  "muppet_babies::S5E08 He’s a Wonderful Frog.mp4": 1379,
  "muppet_babies::S5E09 Elm Street Babies.mp4": 1409,
  "muppet_babies::S5E10 Plan 8 from Outer Space.mp4": 1412,
  "muppet_babies::S5E11 Junkyard Muppets.mp4": 1412,
  "muppet_babies::S5E12 The Air Conditioner at the End of the Galaxy.mp4": 1403,
  "muppet_babies::S5E13 Bug-Busting Babies.mp4": 1396,
  "muppet_babies::S6E01 This Old Nursery.mp4": 1396,
  "muppet_babies::S6E02 And Now a Word from Our Muppets.mp4": 1398,
  "muppet_babies::S6E03 Six-to-Eight Weeks.mp4": 1393,
  "muppet_babies::S6E04 The Green Ranger.mp4": 1400,
  "muppet_babies::S6E05 Not Necessarily the Babies.mp4": 1407,
  "muppet_babies::S6E06 Comic Capers.mp4": 1416,
  "muppet_babies::S6E07 Faster Than a Speeding Weirdo.mp4": 1436,
  "muppet_babies::S6E08 Skeeter and the Wolf.mp4": 1379,
  "muppet_babies::S6E09 Romancing the Weirdo.mp4": 1406,
  "muppet_babies::S6E10 The New Adventures of Kermo Polo.mp4": 1454,
  "muppet_babies::S6E11 Goosetown Babies.mp4": 1401,
  "muppet_babies::S7E01 It’s Only Pretendo.mp4": 1379,
  "muppet_babies::S7E02 Quoth the Weirdo.mp4": 1379,
  "muppet_babies::S7E03 Operators Are Standing by.mp4": 1403,
  "muppet_babies::S7E04 Babes in Troyland.mp4": 1411,
  "muppet_babies::S7E05 Puss ‘n’ Boots ‘n’ Babies.mp4": 1416,
  "muppet_babies::S7E06 Muppets of Invention.mp4": 1417,
  "muppet_babies::S7E07 A Punch Line to the Tummy.mp4": 1431,
  "muppet_babies::S7E08 Muppet Babies_The Next Generation.mp4": 1384,
  "muppet_babies::S7E09 Buckskin Babies.mp4": 1418,
  "muppet_babies::S7E10 Sing a Song of Superheroes.mp4": 1379,
  "muppet_babies::S7E11 Gonzee’s Playhouse Channel.mp4": 1371,
  "muppet_babies::S7E12 Kermit Pan.mp4": 1429,
  "muppet_babies::S7E13 Whose Tale Is It Anyway.mp4": 1424,
  "muppet_babies::S7E14 At The Movies.mp4": 1329,
  "muppet_babies::S7E15 In Search of the Bronzed Beetle.mp4": 1379,
  "muppet_babies::S8E1 The Transcontinental Whoo-Whoo.mp4": 1389,
  "muppet_babies::S8E2 Get Me to the Perch on Time.mp4": 1353,
  "muppet_babies::S8E3 Bearly Alone Babies.mp4": 1337,
  "muppet_babies::S8E4 Remote Control Cornballs.mp4": 1401,
  "muppet_babies::S8E5 Nice to Have Gnome.mp4": 1359,
  "muppet_babies::S8E6 Happy Birthday Uncle Piggy.mp4": 1379,
  "muppet_babies::S8E7 Hats!, Hats!, Hats!.mp4": 1399,
  "muppet_babies::S8E8 Eight Flags Over the Nursery.mp4": 1379,
},
};
