window.SHOW = {
  id: "ZoeDuncanJackJane",
  title: "Zoe, Duncan, Jack and Jane",
  art: "ZoeDuncanJackJane.jpg",
  storageProgressKey: "zoeduncanjackjane-progress",
  storageSettingsKey: "zoeduncanjackjane-settings",
  nestedPaths: false,
  grouping: "season",
  segments: "none",
  episodes: [
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E01 - Pilot",
    "Zoe, Duncan, Jack and Jane - 1x01 - Pilot.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E02 - Everything You Wanted to Know About Zoe",
    "Zoe, Duncan, Jack and Jane - 1x02 - Everything You Wanted to Know About Zoe.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E03 - When Zoe Met Johnny",
    "Zoe, Duncan, Jack and Jane - 1x03 - When Zoe Met Johnny.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E04 - To Jack, from Zoe",
    "Zoe, Duncan, Jack and Jane - 1x04 -To Jack, from Zoe.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E05 - Sympathy for Jack",
    "Zoe, Duncan, Jack and Jane - 1x05 - Sympathy for Jack.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E06 - Hard Cheese on Zoe",
    "Zoe, Duncan, Jack and Jane - 1x06 - Hard Cheese on Zoe.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E07 - The Trouble with Jane",
    "Zoe, Duncan, Jack and Jane - 1x07 - The Trouble with Jane.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E08 - A Good Man is Hard to Find",
    "Zoe, Duncan, Jack and Jane - 1x08 - A Good Man is Hard to Find.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E09 - The Advice",
    "Zoe, Duncan, Jack and Jane - 1x09 - The Advice.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E10 - Under Mom's Thumb",
    "Zoe, Duncan, Jack and Jane - 1x10 - Under Mom's Thumb.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E11 - Down and Out at Bleecker and Houston",
    "Zoe, Duncan, Jack and Jane - 1x11 - Down and Out at Bleecker and Houston.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E12 - Zoe Under the Influence",
    "Zoe, Duncan, Jack and Jane - 1x12 - Zoe Under the Influence.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S01E13 - Run, Man Ray, Run",
    "Zoe, Duncan, Jack and Jane - 1x13 - Run, Man Ray, Run.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E01 - No Good Deed",
    "Zoe, Duncan, Jack and Jane - 2x01 - No Good Deed.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E02 - The Customer Is Always Vic",
    "Zoe, Duncan, Jack and Jane - 2x02 - The Customer Is Always Vic.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E03 - I Don't Feel So Good",
    "Zoe, Duncan, Jack and Jane - 2x03 - I Don't Feel So Good.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E04 - Kiss of Death",
    "Zoe, Duncan, Jack and Jane - 2x04 - Kiss of Death.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E05 - The Feud",
    "Zoe, Duncan, Jack and Jane - 2x05 - The Feud.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E06 - A Midsummer Night's Nightmare",
    "Zoe, Duncan, Jack and Jane - 2x06 - A Midsummer Night's Nightmare.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E07 - Crossing the Line",
    "Zoe, Duncan, Jack and Jane - 2x07 - Crossing the Line.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E08 - Desperately Seeking Zoe",
    "Zoe, Duncan, Jack and Jane - 2x08 - Desperately Seeking Zoe.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E09 - Tall, Dark and Ducan's Boss",
    "Zoe, Duncan, Jack and Jane - 2x09 - Tall, Dark and Ducan's Boss.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E10 - My Dinner with Andy",
    "Zoe, Duncan, Jack and Jane - 2x10 - My Dinner with Andy.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E11 - Too Much Pressure",
    "Zoe, Duncan, Jack and Jane - 2x11 - Too Much Pressure.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E12 - Party Girls",
    "Zoe, Duncan, Jack and Jane - 2x12 - Party Girls.mp4"],
  ['zoe-duncan-jack-and-jane-complete-series', "ZOE, DUNCAN, JACK AND JANE - S02E13 - Three Years Later",
    "Zoe, Duncan, Jack and Jane - 2x13 - Three Years Later.mp4"],
],
  durations: {
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x01 - Pilot.mp4": 1416,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x02 - Everything You Wanted to Know About Zoe.mp4": 1293,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x03 - When Zoe Met Johnny.mp4": 1361,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x04 -To Jack, from Zoe.mp4": 1267,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x05 - Sympathy for Jack.mp4": 1279,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x06 - Hard Cheese on Zoe.mp4": 1308,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x07 - The Trouble with Jane.mp4": 1183,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x08 - A Good Man is Hard to Find.mp4": 1317,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x09 - The Advice.mp4": 1307,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x10 - Under Mom's Thumb.mp4": 1352,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x11 - Down and Out at Bleecker and Houston.mp4": 1335,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x12 - Zoe Under the Influence.mp4": 1327,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 1x13 - Run, Man Ray, Run.mp4": 1313,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x01 - No Good Deed.mp4": 1376,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x02 - The Customer Is Always Vic.mp4": 1314,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x03 - I Don't Feel So Good.mp4": 1263,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x04 - Kiss of Death.mp4": 1265,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x05 - The Feud.mp4": 1325,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x06 - A Midsummer Night's Nightmare.mp4": 1326,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x07 - Crossing the Line.mp4": 1319,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x08 - Desperately Seeking Zoe.mp4": 1338,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x09 - Tall, Dark and Ducan's Boss.mp4": 1320,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x10 - My Dinner with Andy.mp4": 1318,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x11 - Too Much Pressure.mp4": 1321,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x12 - Party Girls.mp4": 1296,
  "zoe-duncan-jack-and-jane-complete-series::Zoe, Duncan, Jack and Jane - 2x13 - Three Years Later.mp4": 1320,
},
};
