window.SHOW = {
  id: "ParkerLewis",
  title: "Parker Lewis Can't Lose",
  storageProgressKey: "parkerlewis-progress",
  storageSettingsKey: "parkerlewis-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E01 - Pilot",
    "Parker Lewis Can't Lose - S01E01 - Pilot.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E02 - Operation Kubiak",
    "Parker Lewis Can't Lose - S01E02 - Operation Kubiak.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E03 - Power Play",
    "Parker Lewis Can't Lose - S01E03 - Power Play.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E04 - Parker Lewis Must Lose",
    "Parker Lewis Can't Lose - S01E04 - Parker Lewis Must Lose.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E05 - Close, But No Guitar",
    "Parker Lewis Can't Lose - S01E05 - Close, But No Guitar.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E06 - G.A.G. Dance",
    "Parker Lewis Can't Lose - S01E06 - G.A.G. Dance.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E07 - Love's a Beast",
    "Parker Lewis Can't Lose - S01E07 - Love's a Beast.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E08 - Saving Grace",
    "Parker Lewis Can't Lose - S01E08 - Saving Grace.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E09 - Musso & Frank",
    "Parker Lewis Can't Lose - S01E09 - Musso & Frank.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E10 - Deja Dudes",
    "Parker Lewis Can't Lose - S01E10 - Deja Dudes.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E11 - Radio Free Flamingo",
    "Parker Lewis Can't Lose - S01E11 - Radio Free Flamingo.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E12 - Science Fair",
    "Parker Lewis Can't Lose - S01E12 - Science Fair.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E13 - Teacher, Teacher",
    "Parker Lewis Can't Lose - S01E13 - Teacher, Teacher.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E14 - Rent-a-Kube",
    "Parker Lewis Can't Lose - S01E14 - Rent-a-Kube.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E15 - Heather the Class",
    "Parker Lewis Can't Lose - S01E15 - Heather the Class.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E16 - Jerry Portrait of a Video Junkie",
    "Parker Lewis Can't Lose - S01E16 - Jerry Portrait of a Video Junkie.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E17 - Splendor in the Class",
    "Parker Lewis Can't Lose - S01E17 - Splendor in the Class.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E18 - The Human Grace",
    "Parker Lewis Can't Lose - S01E18 - The Human Grace.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E19 - Citizen Kube",
    "Parker Lewis Can't Lose - S01E19 - Citizen Kube.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E20 - Randall Without a Cause",
    "Parker Lewis Can't Lose - S01E20 - Randall Without a Cause.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E21 - Jerry's First Date",
    "Parker Lewis Can't Lose - S01E21 - Jerry's First Date.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E22 - Against the Norm",
    "Parker Lewis Can't Lose - S01E22 - Against the Norm.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E23 - King Kube",
    "Parker Lewis Can't Lose - S01E23 - King Kube.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E24 - Teens from a Mall",
    "Parker Lewis Can't Lose - S01E24 - Teens from a Mall.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E25 - My Fair Shelly",
    "Parker Lewis Can't Lose - S01E25 - My Fair Shelly.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S01E26 - Parker Lewis Can't Win",
    "Parker Lewis Can't Lose - S01E26 - Parker Lewis Can't Win.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E01 - Father Knows Less",
    "Parker Lewis Can't Lose - S02E01 - Father Knows Less.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E02 - A Walk on the Dark Side",
    "Parker Lewis Can't Lose - S02E02 - A Walk on the Dark Side.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E03 - Full Mental Jacket",
    "Parker Lewis Can't Lose - S02E03 - Full Mental Jacket.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E04 - Future Shock",
    "Parker Lewis Can't Lose - S02E04 - Future Shock.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E05 - The Undergraduate",
    "Parker Lewis Can't Lose - S02E05 - The Undergraduate.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E06 - Stormy Mikey",
    "Parker Lewis Can't Lose - S02E06 - Stormy Mikey.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E07 - Fat Boy and Little Man",
    "Parker Lewis Can't Lose - S02E07 - Fat Boy and Little Man.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E08 - Aging Gracefully",
    "Parker Lewis Can't Lose - S02E08 - Aging Gracefully.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E09 - The Parker Chronicles",
    "Parker Lewis Can't Lose - S02E09 - The Parker Chronicles.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E10 - Rock 'n' Roles",
    "Parker Lewis Can't Lose - S02E10 - Rock 'n' Roles.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E11 - Love Handles",
    "Parker Lewis Can't Lose - S02E11 - Love Handles.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E12 - Boy Meets Girl",
    "Parker Lewis Can't Lose - S02E12 - Boy Meets Girl.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E13 - Raging Kube",
    "Parker Lewis Can't Lose - S02E13 - Raging Kube.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E14 - Tower of Power",
    "Parker Lewis Can't Lose - S02E14 - Tower of Power.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E15 - Obscene and Not Heard",
    "Parker Lewis Can't Lose - S02E15 - Obscene and Not Heard.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E16 - Goodbye Mr. Rips",
    "Parker Lewis Can't Lose - S02E16 - Goodbye Mr. Rips.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E17 - Civil Wars",
    "Parker Lewis Can't Lose - S02E17 - Civil Wars.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E18 - Glory Daze",
    "Parker Lewis Can't Lose - S02E18 - Glory Daze.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E19 - Boy Meets Girl II",
    "Parker Lewis Can't Lose - S02E19 - Boy Meets Girl II.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E20 - Dance of Romance",
    "Parker Lewis Can't Lose - S02E20 - Dance of Romance.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E21 - When Jerry Met Shelly",
    "Parker Lewis Can't Lose - S02E21 - When Jerry Met Shelly.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E22 - Geek Tragedy",
    "Parker Lewis Can't Lose - S02E22 - Geek Tragedy.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E23 - Money Talks",
    "Parker Lewis Can't Lose - S02E23 - Money Talks.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E24 - Home Alone with Annie",
    "Parker Lewis Can't Lose - S02E24 - Home Alone with Annie.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S02E25 - Diner '75",
    "Parker Lewis Can't Lose - S02E25 - Diner '75.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E01 - Flamingo Graffiti",
    "Parker Lewis Can't Lose - S03E01 - Flamingo Graffiti.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E02 - Cape Flamingo",
    "Parker Lewis Can't Lose - S03E02 - Cape Flamingo.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E03 - The Kiss",
    "Parker Lewis Can't Lose - S03E03 - The Kiss.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E04 - Summer of '92",
    "Parker Lewis Can't Lose - S03E04 - Summer of '92.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E05 - Love is Hell",
    "Parker Lewis Can't Lose - S03E05 - Love is Hell.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E06 - Jerry's Journey",
    "Parker Lewis Can't Lose - S03E06 - Jerry's Journey.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E07 - Beauty and the Kube",
    "Parker Lewis Can't Lose - S03E07 - Beauty and the Kube.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E08 - Hungry Heart",
    "Parker Lewis Can't Lose - S03E08 - Hungry Heart.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E09 - Lewis and Son",
    "Parker Lewis Can't Lose - S03E09 - Lewis and Son.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E10 - Kohler Buys the Diner",
    "Parker Lewis Can't Lose - S03E10 - Kohler Buys the Diner.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E11 - Parker's Got a Brand New Car",
    "Parker Lewis Can't Lose - S03E11 - Parker's Got a Brand New Car.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E12 - An Unmarried Musso",
    "Parker Lewis Can't Lose - S03E12 - An Unmarried Musso.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E13 - Educating Brad",
    "Parker Lewis Can't Lose - S03E13 - Educating Brad.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E14 - The Love Bug",
    "Parker Lewis Can't Lose - S03E14 - The Love Bug.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E15 - Write or Die",
    "Parker Lewis Can't Lose - S03E15 - Write or Die.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E16 - The Bitch is Back",
    "Parker Lewis Can't Lose - S03E16 - The Bitch is Back.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E17 - Musso a Wedding",
    "Parker Lewis Can't Lose - S03E17 - Musso a Wedding.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E18 - A Night to Remember",
    "Parker Lewis Can't Lose - S03E18 - A Night to Remember.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E19 - Boys Night In",
    "Parker Lewis Can't Lose - S03E19 - Boys Night In.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E20 - Senior Jerry",
    "Parker Lewis Can't Lose - S03E20 - Senior Jerry.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E21 - The Rocky Kohler Picture Show",
    "Parker Lewis Can't Lose - S03E21 - The Rocky Kohler Picture Show.mp4"],
  ['parker-lewis-cant-lose-series', "PARKER LEWIS CAN'T LOSE - S03E22 - The Last Supper",
    "Parker Lewis Can't Lose - S03E22 - The Last Supper.mp4"],
],
  durations: {
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E01 - Pilot.mp4": 1404,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E02 - Operation Kubiak.mp4": 1370,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E03 - Power Play.mp4": 1396,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E04 - Parker Lewis Must Lose.mp4": 1335,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E05 - Close, But No Guitar.mp4": 1396,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E06 - G.A.G. Dance.mp4": 1398,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E07 - Love's a Beast.mp4": 1395,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E08 - Saving Grace.mp4": 1375,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E09 - Musso & Frank.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E10 - Deja Dudes.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E11 - Radio Free Flamingo.mp4": 1373,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E12 - Science Fair.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E13 - Teacher, Teacher.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E14 - Rent-a-Kube.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E15 - Heather the Class.mp4": 1368,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E16 - Jerry Portrait of a Video Junkie.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E17 - Splendor in the Class.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E18 - The Human Grace.mp4": 1373,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E19 - Citizen Kube.mp4": 1368,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E20 - Randall Without a Cause.mp4": 1368,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E21 - Jerry's First Date.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E22 - Against the Norm.mp4": 1373,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E23 - King Kube.mp4": 1358,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E24 - Teens from a Mall.mp4": 1357,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E25 - My Fair Shelly.mp4": 1357,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S01E26 - Parker Lewis Can't Win.mp4": 1373,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E01 - Father Knows Less.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E02 - A Walk on the Dark Side.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E03 - Full Mental Jacket.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E04 - Future Shock.mp4": 1380,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E05 - The Undergraduate.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E06 - Stormy Mikey.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E07 - Fat Boy and Little Man.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E08 - Aging Gracefully.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E09 - The Parker Chronicles.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E10 - Rock 'n' Roles.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E11 - Love Handles.mp4": 1376,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E12 - Boy Meets Girl.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E13 - Raging Kube.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E14 - Tower of Power.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E15 - Obscene and Not Heard.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E16 - Goodbye Mr. Rips.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E17 - Civil Wars.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E18 - Glory Daze.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E19 - Boy Meets Girl II.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E20 - Dance of Romance.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E21 - When Jerry Met Shelly.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E22 - Geek Tragedy.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E23 - Money Talks.mp4": 1378,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E24 - Home Alone with Annie.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S02E25 - Diner '75.mp4": 1379,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E01 - Flamingo Graffiti.mp4": 1365,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E02 - Cape Flamingo.mp4": 1343,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E03 - The Kiss.mp4": 1393,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E04 - Summer of '92.mp4": 1369,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E05 - Love is Hell.mp4": 1356,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E06 - Jerry's Journey.mp4": 1316,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E07 - Beauty and the Kube.mp4": 1380,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E08 - Hungry Heart.mp4": 1381,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E09 - Lewis and Son.mp4": 1377,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E10 - Kohler Buys the Diner.mp4": 1382,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E11 - Parker's Got a Brand New Car.mp4": 1374,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E12 - An Unmarried Musso.mp4": 1382,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E13 - Educating Brad.mp4": 1381,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E14 - The Love Bug.mp4": 1364,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E15 - Write or Die.mp4": 1341,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E16 - The Bitch is Back.mp4": 1372,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E17 - Musso a Wedding.mp4": 1367,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E18 - A Night to Remember.mp4": 1376,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E19 - Boys Night In.mp4": 1380,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E20 - Senior Jerry.mp4": 1366,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E21 - The Rocky Kohler Picture Show.mp4": 1375,
  "parker-lewis-cant-lose-series::Parker Lewis Can't Lose - S03E22 - The Last Supper.mp4": 1363,
},
};
