window.SHOW = {
  id: "JeffFoxworthyShow",
  title: "The Jeff Foxworthy Show",
  storageProgressKey: "jefffoxworthy-progress",
  storageSettingsKey: "jefffoxworthy-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E01 - Jeff's Life 101",
    "The Jeff Foxworthy Show - Season 1 Episode 01 - Jeff's Life 101.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E02 - A Non-Affair To Remember",
    "The Jeff Foxworthy Show - Season 1 Episode 02 - A Non-Affair To Remember.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E03 - The Gene Pool",
    "The Jeff Foxworthy Show - Season 1 Episode 03 - The Gene Pool.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E04 - Elliot And Victoria's Secret",
    "The Jeff Foxworthy Show - Season 1 Episode 04 - Elliot And Victoria's Secret.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E05 - Womb With A View",
    "The Jeff Foxworthy Show - Season 1 Episode 05 - Womb With A View.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E06 - With Two You Get Cow's Milk",
    "The Jeff Foxworthy Show - Season 1 Episode 06 - With Two You Get Cow's Milk.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E07 - Jeff & Ray & Rascal's Big Adventure",
    "The Jeff Foxworthy Show - Season 1 Episode 07 - Jeff & Ray & Rascal's Big Adventure.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E08 - A Sore Winter",
    "The Jeff Foxworthy Show - Season 1 Episode 08 - A Sore Winter.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E09 - He's Making A List, Checking It Twice",
    "The Jeff Foxworthy Show - Season 1 Episode 09 - He's Making A List, Checking It Twice.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E10 - Foxworthy Family Feud",
    "The Jeff Foxworthy Show - Season 1 Episode 10 - Foxworthy Family Feud.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E11 - Matt About You",
    "The Jeff Foxworthy Show - Season 1 Episode 11 - Matt About You.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E12 - Clan And The Bare Caves",
    "The Jeff Foxworthy Show - Season 1 Episode 12 - Clan And The Bare Caves.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E13 - Before You Say No",
    "The Jeff Foxworthy Show - Season 1 Episode 13 - Before You Say No.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E14 - Deede Day",
    "The Jeff Foxworthy Show - Season 1 Episode 14 - Deede Day.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E15 - He Ain't Heavy, He's Bully",
    "The Jeff Foxworthy Show - Season 1 Episode 15 - He Ain't Heavy, He's Bully.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E16 - Moonstruck",
    "The Jeff Foxworthy Show - Season 1 Episode 16 - Moonstruck.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E17 - Shootout At The Comedy Corral",
    "The Jeff Foxworthy Show - Season 1 Episode 17 - Shootout At The Comedy Corral.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S01E18 - 1 Wedding And A Baby",
    "The Jeff Foxworthy Show - Season 1 Episode 18 - 1 Wedding And A Baby.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E01 - The List Is Strife",
    "The Jeff Foxworthy Show - Season 2 Episode 01 - The List Is Strife.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E02 - Where The Doughnuts Are Good...Not Great",
    "The Jeff Foxworthy Show - Season 2 Episode 02 - Where The Doughnuts Are Good...Not Great.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E03 - The Gift",
    "The Jeff Foxworthy Show - Season 2 Episode 03 - The Gift.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E04 - My Dinner With Betty",
    "The Jeff Foxworthy Show - Season 2 Episode 04 - My Dinner With Betty.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E05 - The Poor Sportsmen Of The Apocalypse",
    "The Jeff Foxworthy Show - Season 2 Episode 05 - The Poor Sportsmen Of The Apocalypse.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E06 - Puppy Love Triangle",
    "The Jeff Foxworthy Show - Season 2 Episode 06 - Puppy Love Triangle.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E07 - The Practical Joke",
    "The Jeff Foxworthy Show - Season 2 Episode 07 - The Practical Joke.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E08 - Thanksgiving",
    "The Jeff Foxworthy Show - Season 2 Episode 08 - Thanksgiving.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E09 - Like Florus, Like Son",
    "The Jeff Foxworthy Show - Season 2 Episode 09 - Like Florus, Like Son.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E10 - Feud For A Thought",
    "The Jeff Foxworthy Show - Season 2 Episode 10 - Feud For A Thought.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E11 - Merry Christmas Y'All",
    "The Jeff Foxworthy Show - Season 2 Episode 11 - Merry Christmas Y'All.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E12 - Moose Face Loves Nuzzles",
    "The Jeff Foxworthy Show - Season 2 Episode 12 - Moose Face Loves Nuzzles.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E13 - You Cain't Teach A Dead Dog New Tricks",
    "The Jeff Foxworthy Show - Season 2 Episode 13 - You Cain't Teach A Dead Dog New Tricks.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E14 - The Briarton Syndrome",
    "The Jeff Foxworthy Show - Season 2 Episode 14 - The Briarton Syndrome.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E15 - Foxworthy Shall Rise Again",
    "The Jeff Foxworthy Show - Season 2 Episode 15 - Foxworthy Shall Rise Again.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E16 - Jeff, You The Man",
    "The Jeff Foxworthy Show - Season 2 Episode 16 - Jeff, You The Man.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E17 - The Dogs",
    "The Jeff Foxworthy Show - Season 2 Episode 17 - The Dogs.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E18 - Gone Fishin'",
    "The Jeff Foxworthy Show - Season 2 Episode 18 - Gone Fishin'.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E19 - Real Men",
    "The Jeff Foxworthy Show - Season 2 Episode 19 - Real Men.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E20 - The Good, The Bad And The Hairless",
    "The Jeff Foxworthy Show - Season 2 Episode 20 - The Good, The Bad And The Hairless.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E21 - Wrestling Opera",
    "The Jeff Foxworthy Show - Season 2 Episode 21 - Wrestling Opera.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E22 - Twister Of Fate",
    "The Jeff Foxworthy Show - Season 2 Episode 22 - Twister Of Fate.mp4"],
  ['JeffFoxworthyShow', "THE JEFF FOXWORTHY SHOW - S02E23 - Field Of Schemes",
    "The Jeff Foxworthy Show - Season 2 Episode 23 - Field Of Schemes.mp4"],
],
  durations: {
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 01 - Jeff's Life 101.mp4": 1381,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 02 - A Non-Affair To Remember.mp4": 1384,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 03 - The Gene Pool.mp4": 1365,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 04 - Elliot And Victoria's Secret.mp4": 1383,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 05 - Womb With A View.mp4": 1367,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 06 - With Two You Get Cow's Milk.mp4": 1384,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 07 - Jeff & Ray & Rascal's Big Adventure.mp4": 1364,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 08 - A Sore Winter.mp4": 1378,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 09 - He's Making A List, Checking It Twice.mp4": 1321,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 10 - Foxworthy Family Feud.mp4": 1367,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 11 - Matt About You.mp4": 1383,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 12 - Clan And The Bare Caves.mp4": 1382,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 13 - Before You Say No.mp4": 1383,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 14 - Deede Day.mp4": 1368,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 15 - He Ain't Heavy, He's Bully.mp4": 1256,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 16 - Moonstruck.mp4": 1314,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 17 - Shootout At The Comedy Corral.mp4": 1317,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 1 Episode 18 - 1 Wedding And A Baby.mp4": 1304,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 01 - The List Is Strife.mp4": 1347,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 02 - Where The Doughnuts Are Good...Not Great.mp4": 1367,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 03 - The Gift.mp4": 1346,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 04 - My Dinner With Betty.mp4": 1367,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 05 - The Poor Sportsmen Of The Apocalypse.mp4": 1366,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 06 - Puppy Love Triangle.mp4": 1366,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 07 - The Practical Joke.mp4": 1366,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 08 - Thanksgiving.mp4": 1345,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 09 - Like Florus, Like Son.mp4": 1364,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 10 - Feud For A Thought.mp4": 1364,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 11 - Merry Christmas Y'All.mp4": 1334,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 12 - Moose Face Loves Nuzzles.mp4": 1344,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 13 - You Cain't Teach A Dead Dog New Tricks.mp4": 1363,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 14 - The Briarton Syndrome.mp4": 1364,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 15 - Foxworthy Shall Rise Again.mp4": 1365,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 16 - Jeff, You The Man.mp4": 1360,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 17 - The Dogs.mp4": 1305,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 18 - Gone Fishin'.mp4": 1335,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 19 - Real Men.mp4": 1365,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 20 - The Good, The Bad And The Hairless.mp4": 1365,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 21 - Wrestling Opera.mp4": 1344,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 22 - Twister Of Fate.mp4": 1303,
  "JeffFoxworthyShow::The Jeff Foxworthy Show - Season 2 Episode 23 - Field Of Schemes.mp4": 1343,
},
};
