window.SHOW = {
  id: "VeronicasCloset",
  title: "Veronica's Closet",
  art: "VeronicasCloset.jpg",
  storageProgressKey: "veronicascloset-progress",
  storageSettingsKey: "veronicascloset-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
    ['veronicascloset', "VERONICA'S CLOSET - S01E01 - Pilot", "S01E01 - Pilot.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E02 - Veronica's Woman Friend", "S01E02 - Veronica's Woman Friend.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E03 - Veronica's Husband Won't Leave", "S01E03 - Veronica's Husband Won't Leave.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E04 - Veronica's Not Happy About the Book", "S01E04 - Veronica's Not Happy About the Book.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E05 - Veronica's First Date", "S01E05 - Veronica's First Date.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E06 - Veronica's Best Buddy", "S01E06 - Veronica's Best Buddy.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E07 - Veronica's a Doll", "S01E07 - Veronica's a Doll.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E08 - Veronica's First Thanksgiving", "S01E08 - Veronica's First Thanksgiving.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E09 - Veronica's Brotherly Love", "S01E09 - Veronica's Brotherly Love.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E10 - Veronica's Christmas Song", "S01E10 - Veronica's Christmas Song.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E11 - Veronica's Got a Secret", "S01E11 - Veronica's Got a Secret.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E12 - Veronica's Fun and Pirates Are Crazy", "S01E12 - Veronica's Fun and Pirates Are Crazy.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E13 - Veronica's Night Alone", "S01E13 - Veronica's Night Alone.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E14 - Veronica's $600,000 Pop", "S01E14 - Veronica's $600,000 Pop.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E15 - Veronica's a Drag", "S01E15 - Veronica's a Drag.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E16 - Veronica's Divorce Papers", "S01E16 - Veronica's Divorce Papers.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E17 - Veronica's Blackout", "S01E17 - Veronica's Blackout.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E18 - Veronica's Bridal Shower", "S01E18 - Veronica's Bridal Shower.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E19 - Veronica's Man in a Suitcase", "S01E19 - Veronica's Man in a Suitcase.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E20 - Veronica's All-Nighter", "S01E20 - Veronica's All-Nighter.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E21 - Veronica's Mole", "S01E21 - Veronica's Mole.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S01E22 - Veronica's Silent Partner", "S01E22 - Veronica's Silent Partner.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E01 - Veronica Gets Her Closet Back", "S02E01 - Veronica Gets Her Closet Back.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E02 - Veronica's a Partner Now", "S02E02 - Veronica's a Partner Now.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E03 - Veronica's Great Model Search", "S02E03 - Veronica's Great Model Search.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E04 - Veronica's Dog Day Afternoon", "S02E04 - Veronica's Dog Day Afternoon.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E05 - Veronica's Crushed", "S02E05 - Veronica's Crushed.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E06 - Veronica's on the Herb", "S02E06 - Veronica's on the Herb.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E07 - Veronica's Breast Effort", "S02E07 - Veronica's Breast Effort.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E08 - Veronica's Thanksgiving That Keeps on Giving", "S02E08 - Veronica's Thanksgiving That Keeps on Giving.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E09 - Veronica's Cheating Partners", "S02E09 - Veronica's Cheating Partners.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E10 - Veronica's Secret Santa", "S02E10 - Veronica's Secret Santa.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E11 - Veronica's From Venus; Josh's Parents are From Mars", "S02E11 - Veronica's From Venus; Josh's Parents are From Mars.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E12 - Veronica's Desk Job", "S02E12 - Veronica's Desk Job.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E13 - Veronica's Wedding Bell Blues", "S02E13 - Veronica's Wedding Bell Blues.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E14 - Veronica Plays House", "S02E14 - Veronica Plays House.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E15 - Veronica's Favorite Year", "S02E15 - Veronica's Favorite Year.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E16 - Veronica's Little Tribute", "S02E16 - Veronica's Little Tribute.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E17 - Veronica Falls Hard", "S02E17 - Veronica Falls Hard.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E18 - Veronica's Big Date", "S02E18 - Veronica's Big Date.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E19 - Veronica's Big Homecoming", "S02E19 - Veronica's Big Homecoming.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E20 - Veronica's Little Ruse", "S02E20 - Veronica's Little Ruse.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E21 - Veronica's Night at the Theater", "S02E21 - Veronica's Night at the Theater.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S02E22 - Veronica Says Goodbye", "S02E22 - Veronica Says Goodbye.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E01 - Veronica's New Boss", "S03E01 - Veronica's New Boss.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E02 - Veronica's June Swoon", "S03E02 - Veronica's June Swoon.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E03 - Veronica's Construction Worker", "S03E03 - Veronica's Construction Worker.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E04 - Veronica's Office - Bigger, Longer and Cuter", "S03E04 - Veronica's Office - Bigger, Longer and Cuter.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E05 - Veronica's New Cat", "S03E05 - Veronica's New Cat.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E06 - Veronica's Long Walk Home", "S03E06 - Veronica's Long Walk Home.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E07 - Veronica's Got All the Right Stuffing", "S03E07 - Veronica's Got All the Right Stuffing.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E08 - Veronica's Sliding Doors", "S03E08 - Veronica's Sliding Doors.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E09 - Veronica's New Year", "S03E09 - Veronica's New Year.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E10 - Veronica's Perfect Man", "S03E10 - Veronica's Perfect Man.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E11 - Veronica's Record", "S03E11 - Veronica's Record.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E12 - Veronica's Tattooed Man", "S03E12 - Veronica's Tattooed Man.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E13 - Veronica's Candy Panties", "S03E13 - Veronica's Candy Panties.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E14 - Veronica's New Bookshelves", "S03E14 - Veronica's New Bookshelves.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E15 - Veronica's Sleepover", "S03E15 - Veronica's Sleepover.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E16 - Veronica's Girls' Night Out", "S03E16 - Veronica's Girls' Night Out.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E17 - Veronica Helps Josh Out", "S03E17 - Veronica Helps Josh Out.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E18 - Veronica Sets Josh Up", "S03E18 - Veronica Sets Josh Up.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E19 - Veronica's Clips", "S03E19 - Veronica's Clips.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E20 - Veronica Loses Her Olive Again", "S03E20 - Veronica Loses Her Olive Again.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E21 - Veronica's Doing the Nasty With Perry", "S03E21 - Veronica's Doing the Nasty With Perry.mp4"],
    ['veronicascloset', "VERONICA'S CLOSET - S03E22 - Veronica Checks Out", "S03E22 - Veronica Checks Out.mp4"],
  ],
  durations: {},
};
