window.SHOW = {
  id: "Jackass",
  title: "Jackass",
  storageProgressKey: "jackass-progress",
  storageSettingsKey: "jackass-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['jackasscompleteseries', "JACKASS - S01E01 - Poo Cocktail",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E01 Poo Cocktail.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E02 - Blind Driver",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E02 Blind Driver.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E03 - Bam Kicking His Dad's Ass All Day Today",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E03 Bam Kicking His Dad's Ass All Day Today.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E04 - Poo Poo Platter",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E04 Poo Poo Platter.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E05 - Mianus",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E05 Mianus.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E06 - Poo Joust",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E06 Poo Joust.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E07 - Casket",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E07 Casket.mp4"],
  ['jackasscompleteseries', "JACKASS - S01E08 - Santa Clonic",
    "Jackass TV series/Jackass Volume 1/Jackass - S01E08 Santa Clonic.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E01 - Cup Test",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E01 Cup Test.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E02 - Jai Alai",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E02 Jai Alai.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E03 - The Loop",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E03 The Loop.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E04 - Wakeboarding",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E04 Wakeboarding.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E05 - Donut",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E05 Donut.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E06 - Slingshot",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E06 Slingshot.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E07 - Eddie's Auto",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E07 Eddie's Auto.mp4"],
  ['jackasscompleteseries', "JACKASS - S02E08 - The Matador",
    "Jackass TV series/Jackass Volume 2/Jackass - S02E08 The Matador.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E01 - Beard Of Leeches",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E01 Beard Of Leeches.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E02 - Spermathon",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E02 Spermathon.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E03 - Office Chairs",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E03 Office Chairs.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E04 - Slip & Slide",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E04 Slip & Slide.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E05 - Bloody Windshield",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E05 Bloody Windshield.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E06 - Playgirl Pontius",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E06 Playgirl Pontius.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E07 - gumball special",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E07 gumball special.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E08 - Bloody Carpet",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E08 Bloody Carpet.mp4"],
  ['jackasscompleteseries', "JACKASS - S03E09 - The Bed Wetter",
    "Jackass TV series/Jackass Volume 3/Jackass - S03E09 The Bed Wetter.mp4"],
],
  durations: {
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E01 Poo Cocktail.mp4": 1255,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E02 Blind Driver.mp4": 1243,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E03 Bam Kicking His Dad's Ass All Day Today.mp4": 1238,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E04 Poo Poo Platter.mp4": 1251,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E05 Mianus.mp4": 1245,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E06 Poo Joust.mp4": 1252,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E07 Casket.mp4": 1235,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 1/Jackass - S01E08 Santa Clonic.mp4": 1251,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E01 Cup Test.mp4": 1228,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E02 Jai Alai.mp4": 1228,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E03 The Loop.mp4": 1234,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E04 Wakeboarding.mp4": 1223,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E05 Donut.mp4": 1230,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E06 Slingshot.mp4": 1222,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E07 Eddie's Auto.mp4": 1235,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 2/Jackass - S02E08 The Matador.mp4": 1230,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E01 Beard Of Leeches.mp4": 1226,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E02 Spermathon.mp4": 1233,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E03 Office Chairs.mp4": 1225,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E04 Slip & Slide.mp4": 1231,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E05 Bloody Windshield.mp4": 1231,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E06 Playgirl Pontius.mp4": 1234,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E07 gumball special.mp4": 2480,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E08 Bloody Carpet.mp4": 1223,
  "jackasscompleteseries::Jackass TV series/Jackass Volume 3/Jackass - S03E09 The Bed Wetter.mp4": 1223,
},
};
