window.SHOW = {
  id: "SaluteYourShorts",
  title: "Salute Your Shorts",
  storageProgressKey: "saluteyourshorts-progress",
  storageSettingsKey: "saluteyourshorts-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E01 - Michael Comes to Camp",
    "Salute Your Shorts S01E01 - Michael Comes to Camp.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E02 - Zeke The Plumber",
    "Salute Your Shorts S01E02 - Zeke The Plumber.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E03 - The Treasure of Sarah Madre",
    "Salute Your Shorts S01E03 - The Treasure of Sarah Madre.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E04 - Donkeylips Crush on Dina",
    "Salute Your Shorts S01E04 - Donkeylips Crush on Dina.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E05 - Brownies for Thud Mackie",
    "Salute Your Shorts S01E05 - Brownies for Thud Mackie.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E06 - Bunk Chief Elections",
    "Salute Your Shorts S01E06 - Bunk Chief Elections.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E07 - Toilet Seat Basketball",
    "Salute Your Shorts S01E07 - Toilet Seat Basketball.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E08 - Sponge vs. The DJ",
    "Salute Your Shorts S01E08 - Sponge vs. The DJ.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E09 - Donkeylips and Sponge Weigh In",
    "Salute Your Shorts S01E09 - Donkeylips and Sponge Weigh In.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E10 - Budnick and Michael Fake Being Sick",
    "Salute Your Shorts S01E10 - Budnick and Michael Fake Being Sick.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E11 - Cinderella Play",
    "Salute Your Shorts S01E11 - Cinderella Play.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E12 - Mail Carrier Mona",
    "Salute Your Shorts S01E12 - Mail Carrier Mona.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S01E13 - The Environmental Party",
    "Salute Your Shorts S01E13 - The Environmental Party.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E01 - Telly and the Tennis Match",
    "Salute Your Shorts S02E01 - Telly and the Tennis Match.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E02 - Goodbye Michael, Hello Pinsky",
    "Salute Your Shorts S02E02 - Goodbye Michael, Hello Pinsky.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E03 - Counselor Budnick",
    "Salute Your Shorts S02E03 - Counselor Budnick.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E04 - Dina and the Rock Star",
    "Salute Your Shorts S02E04 - Dina and the Rock Star.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E05 - The Cursed Skull",
    "Salute Your Shorts S02E05 - The Cursed Skull.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E06 - Budnick Loves Dina (Part 1)",
    "Salute Your Shorts S02E06 - Budnick Loves Dina (Part 1).mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E07 - Budnick Loves Dina (Part 2)",
    "Salute Your Shorts S02E07 - Budnick Loves Dina (Part 2).mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E08 - Sponge's Night Out",
    "Salute Your Shorts S02E08 - Sponge's Night Out.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E09 - The Pinsky-Sponge Gazette",
    "Salute Your Shorts S02E09 - The Pinsky-Sponge Gazette.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E10 - Capture the Flag",
    "Salute Your Shorts S02E10 - Capture the Flag.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E11 - Park Ranger Mona",
    "Salute Your Shorts S02E11 - Park Ranger Mona.mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E12 - The Wrath of Kahn, Jr.",
    "Salute Your Shorts S02E12 - The Wrath of Kahn, Jr..mp4"],
  ['salute-your-shorts-complete', "SALUTE YOUR SHORTS - S02E13 - Anawanna Incorporated",
    "Salute Your Shorts S02E13 - Anawanna Incorporated.mp4"],
],
  durations: {
  "salute-your-shorts-complete::Salute Your Shorts S01E01 - Michael Comes to Camp.mp4": 1511,
  "salute-your-shorts-complete::Salute Your Shorts S01E02 - Zeke The Plumber.mp4": 1513,
  "salute-your-shorts-complete::Salute Your Shorts S01E03 - The Treasure of Sarah Madre.mp4": 1454,
  "salute-your-shorts-complete::Salute Your Shorts S01E04 - Donkeylips Crush on Dina.mp4": 1450,
  "salute-your-shorts-complete::Salute Your Shorts S01E05 - Brownies for Thud Mackie.mp4": 1510,
  "salute-your-shorts-complete::Salute Your Shorts S01E06 - Bunk Chief Elections.mp4": 1452,
  "salute-your-shorts-complete::Salute Your Shorts S01E07 - Toilet Seat Basketball.mp4": 1512,
  "salute-your-shorts-complete::Salute Your Shorts S01E08 - Sponge vs. The DJ.mp4": 1454,
  "salute-your-shorts-complete::Salute Your Shorts S01E09 - Donkeylips and Sponge Weigh In.mp4": 1496,
  "salute-your-shorts-complete::Salute Your Shorts S01E10 - Budnick and Michael Fake Being Sick.mp4": 1448,
  "salute-your-shorts-complete::Salute Your Shorts S01E11 - Cinderella Play.mp4": 1506,
  "salute-your-shorts-complete::Salute Your Shorts S01E12 - Mail Carrier Mona.mp4": 1451,
  "salute-your-shorts-complete::Salute Your Shorts S01E13 - The Environmental Party.mp4": 1452,
  "salute-your-shorts-complete::Salute Your Shorts S02E01 - Telly and the Tennis Match.mp4": 1450,
  "salute-your-shorts-complete::Salute Your Shorts S02E02 - Goodbye Michael, Hello Pinsky.mp4": 1452,
  "salute-your-shorts-complete::Salute Your Shorts S02E03 - Counselor Budnick.mp4": 1435,
  "salute-your-shorts-complete::Salute Your Shorts S02E04 - Dina and the Rock Star.mp4": 1445,
  "salute-your-shorts-complete::Salute Your Shorts S02E05 - The Cursed Skull.mp4": 1450,
  "salute-your-shorts-complete::Salute Your Shorts S02E06 - Budnick Loves Dina (Part 1).mp4": 1451,
  "salute-your-shorts-complete::Salute Your Shorts S02E07 - Budnick Loves Dina (Part 2).mp4": 1454,
  "salute-your-shorts-complete::Salute Your Shorts S02E08 - Sponge's Night Out.mp4": 1450,
  "salute-your-shorts-complete::Salute Your Shorts S02E09 - The Pinsky-Sponge Gazette.mp4": 1450,
  "salute-your-shorts-complete::Salute Your Shorts S02E10 - Capture the Flag.mp4": 1449,
  "salute-your-shorts-complete::Salute Your Shorts S02E11 - Park Ranger Mona.mp4": 1451,
  "salute-your-shorts-complete::Salute Your Shorts S02E12 - The Wrath of Kahn, Jr..mp4": 1455,
  "salute-your-shorts-complete::Salute Your Shorts S02E13 - Anawanna Incorporated.mp4": 1453,
},
};
