window.SHOW = {
  id: "GreenAcres",
  title: "Green Acres",
  art: "GreenAcres.jpg",
  storageProgressKey: "greenacres-progress",
  storageSettingsKey: "greenacres-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E01 - Oliver Buys a Farm",
    "Green Acres Season 1/Green Acres - 001 - Oliver Buys A Farm.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E02 - Lisa's First Day on the Farm",
    "Green Acres Season 1/Green Acres - 002 - Lisa's First Day on the Farm.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E03 - The Decorator",
    "Green Acres Season 1/Green Acres - 003 - The Decorator.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E04 - The Best Laid Plans",
    "Green Acres Season 1/Green Acres - 004 - The Best Laid Plans - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E05 - My Husband, the Rooster Renter",
    "Green Acres Season 1/Green Acres - 005 - My Husband, The Rooster Renter.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E06 - Furniture, Furniture, Who's Got the Furniture?",
    "Green Acres Season 1/Green Acres - 006 - Furniture, Furniture, Who's Got the Furniture.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E07 - Neighborliness",
    "Green Acres Season 1/Green Acres - 007 - Neighborliness - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E08 - Lisa the Helpmate",
    "Green Acres Season 1/Green Acres - 008 - Lisa, The Helpmate - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E09 - You Can't Plug in a 2 with a 6",
    "Green Acres Season 1/Green Acres - 009 - You Can't Plug In A 2 with a 6.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E10 - Don't Call Us, We'll Call You",
    "Green Acres Season 1/Green Acres - 010 - Don't Call Us, We'll Call You.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E11 - Parity Begins at Home",
    "Green Acres Season 1/Green Acres - 011 - Parity Begins At Home - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E12 - Lisa Has a Calf",
    "Green Acres Season 1/Green Acres - 012 - Lisa Has a Calf.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E13 - The Wedding Anniversary",
    "Green Acres Season 1/Green Acres - 013 - The Wedding Anniversary - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E14 - What Happened in Scranton?",
    "Green Acres Season 1/Green Acres - 014 - What Happened In Scranton - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E15 - How to Enlarge a Bedroom",
    "Green Acres Season 1/Green Acres - 015 - How to Enlarge a Bedroom.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E16 - Give Me Land, Lots of Land",
    "Green Acres Season 1/Green Acres - 016 - Give Me Land, Lots Of Land.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E17 - I Didn't Raise My Husband to Be a Fireman",
    "Green Acres Season 1/Green Acres - 017 - I Didn't Raise My Husband to Be a Fireman.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E18 - Lisa Bakes a Cake",
    "Green Acres Season 1/Green Acres - 018 - Lisa Bakes A Cake - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E19 - Sprained Ankle, Country Style",
    "Green Acres Season 1/Green Acres - 019 - Sprained Ankle Country Style - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E20 - The Price of Apples",
    "Green Acres Season 1/Green Acres - 020 - The Price of Apples.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E21 - What's in a Name?",
    "Green Acres Season 1/Green Acres - 021 - What's In A Name - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E22 - The Day of Decision",
    "Green Acres Season 1/Green Acres - 022 - The Day Of Decision - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E23 - A Pig in a Poke",
    "Green Acres Season 1/Green Acres - 023 - A Pig In a Poke.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E24 - The Deputy",
    "Green Acres Season 1/Green Acres - 025 - The Deputy - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E25 - Double Drick",
    "Green Acres Season 1/Green Acres - 026 - Double Drick - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E26 - The Ballad of Molly Turgiss",
    "Green Acres Season 1/Green Acres - 024 - The Ballard Of Molly Turgess - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E27 - Never Look a Gift Tractor in the Mouth",
    "Green Acres Season 1/Green Acres - 028 - Never Look A Gift Tractor In The Mouth.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E29 - Horse? What Horse?",
    "Green Acres Season 1/Green Acres - 029 - Horse - What Horse.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E30 - The Rains Came",
    "Green Acres Season 1/Green Acres - 031 - The Rain Came - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E31 - Culture",
    "Green Acres Season 1/Green Acres - 030 - Culture.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S01E32 - Uncle Ollie",
    "Green Acres Season 1/Green Acres - 032 - Uncle Ollie.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E01 - Wings Over Hooterville",
    "Green Acres Season 2/Green Acres - 033 - Wings Over Hooterville - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E02 - Water, Water Everywhere",
    "Green Acres Season 2/Green Acres - 035 - Water, Water Everywhere - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E03 - I Didn't Raise My Pig to Be a Soldier",
    "Green Acres Season 2/Green Acres - 037 - I Didn't Raise My Pig To Be A Soldier - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E04 - How to See South America By Bus",
    "Green Acres Season 2/Green Acres - 036 - How To See South America By Bus - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E05 - The Ugly Duckling",
    "Green Acres Season 2/Green Acres - 034 - The Ugly Duckling - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E06 - One of Our Assemblymen is Missing",
    "Green Acres Season 2/Green Acres - 038 - One Of Our Assemblymen Is Missing - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E07 - The Good Old Days",
    "Green Acres Season 2/Green Acres - 039 - The Good Old Days - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E08 - Eb Discovers the Birds and the Bees",
    "Green Acres Season 2/Green Acres - 040 - Eb Discovers The Birds & The Bees - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E09 - The Hooterville Image",
    "Green Acres Season 2/Green Acres - 041 - The Hooterville Image - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E10 - You Ought to Be in Pictures",
    "Green Acres Season 2/Green Acres - 042 - You Ought To Be In Pictures - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E11 - A Home Isn't Built in a Day",
    "Green Acres Season 2/Green Acres - 043 - A Home Isn't Built In A Day - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E12 - A Square is Not Round",
    "Green Acres Season 2/Green Acres - 044 - A Square Is Not A Round - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E13 - An Old-fashioned Christmas",
    "Green Acres Season 2/Green Acres - 046 - An Old Fashion Christmas - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E14 - Never Trust a Little Old Lady",
    "Green Acres Season 2/Green Acres - 048 - Never Trust A Little Old Lady - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E15 - School Days",
    "Green Acres Season 2/Green Acres - 049 - School Days - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E16 - His Honor",
    "Green Acres Season 2/Green Acres - 047 - His Honor - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E17 - It's So Peaceful in the Country",
    "Green Acres Season 2/Green Acres - 045 - It's So Peaceful In The Country - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E18 - Exodus to Bleedswell",
    "Green Acres Season 2/Green Acres - 050 - Exodus To Bleedswell - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E19 - It's Human to be Humane",
    "Green Acres Season 2/Green Acres - 051 - It's Human To Be Humane - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E20 - Never Take Your Wife to a Convention",
    "Green Acres Season 2/Green Acres - 052 - Never Take Your Wife To A Convention - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E21 - The Computer Age",
    "Green Acres Season 2/Green Acres - 054 - The Computer Age - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E22 - Never Start Talking Unless Your Voice Comes Out",
    "Green Acres Season 2/Green Acres - 053 - Never Start Talking Unless Your Voice Comes Out - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E23 - The Beverly Hillbillies",
    "Green Acres Season 2/Green Acres - 055 - The Beverly Hillbillies - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E24 - Lisa's Vegetable Garden",
    "Green Acres Season 2/Green Acres - 056 - Lisa's Vegetable Garden - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E25 - The Saucer Season",
    "Green Acres Season 2/Green Acres - 057 - The Saucer Season - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E26 - Getting Even With Haney",
    "Green Acres Season 2/Green Acres - 059 - Getting Even With Mr. Haney - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E27 - Kimball Gets Fired",
    "Green Acres Season 2/Green Acres - 060 - Kimble Get's Fired - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E28 - The Vulgar Ring Story",
    "Green Acres Season 2/Green Acres - 058 - The Vugar Ring - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E29 - Who's Lisa?",
    "Green Acres Season 2/Green Acres - 061 - Who's Lisa - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S02E30 - Music to Milk By",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 063 - Music To Milk By - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E01 - The Man For the Job",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 064 - The Man For The Job - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E02 - Lisa's Jam Session",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 066 - Lisa's Jam Session - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E03 - Love Comes to Arnold Ziffel",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 065 - Love Comes To Arnold Ziffel - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E04 - Oliver vs. the Phone Company",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 067 - Oliver vs The Phone Company - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E05 - Oliver Takes Over the Phone Company",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 068 - Oliver Takes Over the Phone Company.mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E06 - Don't Count Your Tomatoes Before They're Picked",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 069 - Don't Count Your Tomatoes Before They're Picked - (CT).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E07 - A Kind Word For the President",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 070 - A Kind Word For The President - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E08 - Eb Elopes",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 072 - Eb Elopes - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E09 - The Thing",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 073 - The Thing - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E10 - Das Lumpen",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 074 - Das Lumpen - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E11 - Won't You Come Home, Arnold Ziffel?",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 075 - Won't You Come Home, Arnold Ziffel - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E12 - Jealousy, English Style",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 076 - Jealousy, English Style - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E13 - Haney's New Image",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 077 - Haney's New Image - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E14 - Alf and Ralph Break Up",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 079 - Alf & Ralph Break Up - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E15 - No Trespassing",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 078 - No Trespassing - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E16 - Eb Returns",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 080 - Eb Returns - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E17 - Not Guilty",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 071 - Not Guilty - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E18 - Home is Where You Run Away From",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 081 - Home Is Where You Run Away From - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E19 - How to Succeed in Television Without Really Trying",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 083 - How To Succeed In Telvision Without Trying - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E20 - Arnold Ziffel, Boy Hero",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 084 - Arnold, Boy Hero - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E21 - Flight to Nowhere",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 082 - Flight To Nowhere - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E22 - My Mother, the Countess",
    "Green Acres Season 2/Green Acres - 062 - My Mother, The Countess - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E23 - The Spring Festival",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 085 - Spring Festival - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E24 - Our Son, the Barber",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 086 - Our Son, The Barber - (CT).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E25 - Oliver's Jaded Past",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 087 - Oliver's Jaded Past - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E26 - The Hungarian Curse",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 088 - The Hungarian Curse - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E27 - The Rutabaga Story",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 089 - The Rutabaga Story - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E28 - Instant Family",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 090 - Instant Family - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E29 - A Star Named Arnold is Born, Part 1",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 091 - A Star Named Arnold Is Born (pt1) - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S03E30 - A Star Named Arnold is Born, Part 2",
    "Green Acres Season 3/Green Acres Season 3/Green Acres - 092 - A Star Named Arnold Is Born (pt2) - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E01 - Guess Who's Not Going to the Luau?",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 093 - Guess Who's Not Coming To Lulu - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E02 - The Rummage Sale",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 094 - The Rummage Sale - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E03 - Hail to the Fire Chief",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 095 - Hail To The Fire Chief - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E04 - Eb's Romance",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 096 - Eb's Romance - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E05 - The Candidate",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 097 - The Candidate - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E06 - Handy Lessons",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 098 - Handy Lessions - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E07 - A Husband For Eleanor",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 099 - A Husband For Eleanor - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E08 - Old Mail Day",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 100 - Old Mail Day - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E09 - The Agricultural Student",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 101 - The Agricultural Student - (CT).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E10 - How Hooterville was Floundered",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 102 - How Hooterville Was Floundered - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E11 - The Blue Feather",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 103 - The Blue Feather - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E12 - How to Get from Hooterville to Pixley Without Moving",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 106 - How To Get From Hooterville To Pixley Without Moving - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E13 - The Birthday Gift",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 104 - The Birthday Gift - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E14 - Everywhere a Chick Chick",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 105 - Everywhere A Chick Chick - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E15 - The Marital Vacation",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 107 - The Martial Vacation - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E16 - A Prize in Every Package",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 108 - A Prize In Every Package - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E17 - Law Partners",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 109 - Law Partners - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E18 - A Day in the Life of Oliver Wendell Holmes",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 110 - A Day In The Life Of Oliver Wendell Holmes - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E19 - Economy Flight to Washington",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 111 - Economy Flight To Washington - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E20 - Retreat From Washington",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 112 - Retreat From Washington - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E21 - A Hunting We Won't Go",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 113 - A Hunting We Will Go - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E22 - Oh, Promise Me",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 114 - Oh, Promise Me - (TV Rip) .mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E23 - Eb Uses His Ingenuity",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 115 - Eb Uses His Ingenuity - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E24 - The Old Trunk",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 116 - The Old Trunk - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E25 - The Milk Maker",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 117 - The Milk Maker - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S04E26 - The Reincarnation of Eb",
    "Green Acres Season 4/Green Acres Season 4/Green Acres - 118 - The Reincarnation Of Eb - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E01 - Lisa's Mudder Comes for a Visit",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 122 - Lisa's Mudder Comes For A Visit - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E02 - Everybody Tries to Love a Countess",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 123 - Everybody Tries To Love A Countess - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E03 - Where There's a Will",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 119 - Where There's A Will - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E04 - A Tale of a Tail",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 120 - A Tale Of A Tail - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E05 - You and Your Big Shrunken Head",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 121 - You And Your Shrunken Head - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E06 - The Road",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 128 - The Road - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E07 - Four of Spades",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 127 - Four Of Spades - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E08 - The Youth Center",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 129 - The Youth Center - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E09 - The Special Delivery Letter",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 132 - The Special Delivery Letter - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E10 - Oliver's Schoolgirl Crush",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 126 - Oliver's Schoolgirl Crush - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E11 - Ralph's Nuptials",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 133 - Ralph's Nuptials - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E12 - Oliver and the Cornstalk",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 124 - Oliver & The Cornstalk - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E13 - Beauty is Skin Deep",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 125 - Beauty Is Skin Deep - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E14 - The Wish-Book",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 131 - The Wish Book - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E15 - Rest and Relaxation",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 135 - Rest & Relaxation - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E16 - Trapped",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 136 - Trapped - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E17 - Bundle of Joy",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 134 - Bundle Of Joy - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E18 - The Ex-Con",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 130 - The Ex-Con - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E19 - The Cow Killer",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 137 - The Cow Killer - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E20 - The Confrontation",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 138 - The Confrontation - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E21 - The Case of the Hooterville Refund Fraud",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 139 - The Case Of The Hooterville Refund Fraud - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E22 - The Picnic",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 140 - The Picnic - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E23 - The Beeping Rock",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 141 - The Beeping Rock - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E24 - Uncle Fedor",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 143 - Uncle Fedor - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E25 - The Wealthy Landowner",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 142 - The Wealthy Landowner - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S05E26 - Happy Birthday",
    "Green Acres Season 5/Green Acres Season 5/Green Acres - 144 - Happy Birthday - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E01 - The City Kids",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 146 - The City Kids - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E02 - The Coming-Out Party",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 147 - The Coming Out Party - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E03 - Jealousy",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 145 - Jealousy - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E04 - A Royal Love Story",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 149 - A Royal Story - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E05 - Oliver Goes Broke",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 150 - Oliver Goes Broke - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E06 - The Great Mayoralty Campaign",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 156 - The Great Mayoralty Campaign - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E07 - Eb's Double Trouble",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 148 - Eb's Double Trouble - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E08 - Apple-Picking Time",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 151 - Apple Picking Time - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E09 - Enterprising Eb",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 152 - Enterprising Eb - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E10 - Oliver's Double",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 153 - Oliver's Double - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E11 - The High Cost of Loving",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 154 - The High Cost Of Living - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E12 - The Liberation Movement",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 155 - The Liberation Movement - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E13 - Charlie, Homer and Natasha",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 157 - Charlie, Homer, & Natasha - (TV Rip) .mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E14 - The Engagement Ring",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 158 - The Engagememnt Ring - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E15 - The Free Paint Job",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 159 - The Free Paint Job - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E16 - Son of Drobny",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 160 - Son Of Drobny - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E17 - The Wedding Deal",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 164 - The Wedding Deal - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E18 - Star Witness",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 163 - Star Wittness - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E19 - The Spot Remover",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 166 - The Spot Remover - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E20 - King Oliver I",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 169 - King Oliver - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E21 - A Girl for Drobny",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 167 - A Girl For Drobny - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E22 - The Carpenter's Ball",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 162 - The Carpenter's Ball - (TV Rip) .mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E23 - The Hole in the Porch",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 168 - The Hole In The Porch - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E24 - Lisa the Psychologist",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 161 - Lisa The Psychologist - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E25 - Hawaiian Honeymoon",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 165 - Hawaiian Honeymoon - (TV Rip).mp4"],
  ['GreenAcresCompleteSeries', "GREEN ACRES - S06E26 - The Ex-Secretary",
    "Green Acres Season 6/Green Acres Season 6/Green Acres - 170 - Ex Secretary - (TV Rip).mp4"],
],
  durations: {
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 001 - Oliver Buys A Farm.mp4": 1520,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 002 - Lisa's First Day on the Farm.mp4": 1538,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 003 - The Decorator.mp4": 1612,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 004 - The Best Laid Plans - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 005 - My Husband, The Rooster Renter.mp4": 1534,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 006 - Furniture, Furniture, Who's Got the Furniture.mp4": 1524,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 007 - Neighborliness - (TV Rip).mp4": 1303,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 008 - Lisa, The Helpmate - (TV Rip).mp4": 1304,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 009 - You Can't Plug In A 2 with a 6.mp4": 1524,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 010 - Don't Call Us, We'll Call You.mp4": 1508,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 011 - Parity Begins At Home - (TV Rip).mp4": 1284,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 012 - Lisa Has a Calf.mp4": 1518,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 013 - The Wedding Anniversary - (TV Rip).mp4": 1289,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 014 - What Happened In Scranton - (TV Rip).mp4": 1296,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 015 - How to Enlarge a Bedroom.mp4": 1517,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 016 - Give Me Land, Lots Of Land.mp4": 1283,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 017 - I Didn't Raise My Husband to Be a Fireman.mp4": 1520,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 018 - Lisa Bakes A Cake - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 019 - Sprained Ankle Country Style - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 020 - The Price of Apples.mp4": 1518,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 021 - What's In A Name - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 022 - The Day Of Decision - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 023 - A Pig In a Poke.mp4": 1518,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 025 - The Deputy - (TV Rip).mp4": 1284,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 026 - Double Drick - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 024 - The Ballard Of Molly Turgess - (TV Rip).mp4": 1304,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 028 - Never Look A Gift Tractor In The Mouth.mp4": 1516,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 029 - Horse - What Horse.mp4": 1512,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 031 - The Rain Came - (TV Rip).mp4": 1325,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 030 - Culture.mp4": 1520,
  "GreenAcresCompleteSeries::Green Acres Season 1/Green Acres - 032 - Uncle Ollie.mp4": 1527,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 033 - Wings Over Hooterville - (TV Rip).mp4": 1282,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 035 - Water, Water Everywhere - (TV Rip).mp4": 1292,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 037 - I Didn't Raise My Pig To Be A Soldier - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 036 - How To See South America By Bus - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 034 - The Ugly Duckling - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 038 - One Of Our Assemblymen Is Missing - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 039 - The Good Old Days - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 040 - Eb Discovers The Birds & The Bees - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 041 - The Hooterville Image - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 042 - You Ought To Be In Pictures - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 043 - A Home Isn't Built In A Day - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 044 - A Square Is Not A Round - (TV Rip).mp4": 1305,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 046 - An Old Fashion Christmas - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 048 - Never Trust A Little Old Lady - (TV Rip).mp4": 1304,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 049 - School Days - (TV Rip).mp4": 1294,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 047 - His Honor - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 045 - It's So Peaceful In The Country - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 050 - Exodus To Bleedswell - (TV Rip).mp4": 1292,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 051 - It's Human To Be Humane - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 052 - Never Take Your Wife To A Convention - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 054 - The Computer Age - (TV Rip).mp4": 1305,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 053 - Never Start Talking Unless Your Voice Comes Out - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 055 - The Beverly Hillbillies - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 056 - Lisa's Vegetable Garden - (TV Rip).mp4": 1283,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 057 - The Saucer Season - (TV Rip).mp4": 1290,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 059 - Getting Even With Mr. Haney - (TV Rip).mp4": 1305,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 060 - Kimble Get's Fired - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 058 - The Vugar Ring - (TV Rip).mp4": 1304,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 061 - Who's Lisa - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 063 - Music To Milk By - (TV Rip).mp4": 1305,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 064 - The Man For The Job - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 066 - Lisa's Jam Session - (TV Rip).mp4": 1285,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 065 - Love Comes To Arnold Ziffel - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 067 - Oliver vs The Phone Company - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 068 - Oliver Takes Over the Phone Company.mp4": 1317,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 069 - Don't Count Your Tomatoes Before They're Picked - (CT).mp4": 1315,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 070 - A Kind Word For The President - (TV Rip).mp4": 1283,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 072 - Eb Elopes - (TV Rip).mp4": 1286,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 073 - The Thing - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 074 - Das Lumpen - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 075 - Won't You Come Home, Arnold Ziffel - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 076 - Jealousy, English Style - (TV Rip).mp4": 1303,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 077 - Haney's New Image - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 079 - Alf & Ralph Break Up - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 078 - No Trespassing - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 080 - Eb Returns - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 071 - Not Guilty - (TV Rip).mp4": 1296,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 081 - Home Is Where You Run Away From - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 083 - How To Succeed In Telvision Without Trying - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 084 - Arnold, Boy Hero - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 082 - Flight To Nowhere - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 2/Green Acres - 062 - My Mother, The Countess - (TV Rip).mp4": 1294,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 085 - Spring Festival - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 086 - Our Son, The Barber - (CT).mp4": 1313,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 087 - Oliver's Jaded Past - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 088 - The Hungarian Curse - (TV Rip).mp4": 1287,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 089 - The Rutabaga Story - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 090 - Instant Family - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 091 - A Star Named Arnold Is Born (pt1) - (TV Rip).mp4": 1296,
  "GreenAcresCompleteSeries::Green Acres Season 3/Green Acres Season 3/Green Acres - 092 - A Star Named Arnold Is Born (pt2) - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 093 - Guess Who's Not Coming To Lulu - (TV Rip).mp4": 1303,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 094 - The Rummage Sale - (TV Rip).mp4": 1287,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 095 - Hail To The Fire Chief - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 096 - Eb's Romance - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 097 - The Candidate - (TV Rip).mp4": 1287,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 098 - Handy Lessions - (TV Rip).mp4": 1296,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 099 - A Husband For Eleanor - (TV Rip).mp4": 1286,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 100 - Old Mail Day - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 101 - The Agricultural Student - (CT).mp4": 1320,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 102 - How Hooterville Was Floundered - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 103 - The Blue Feather - (TV Rip).mp4": 1303,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 106 - How To Get From Hooterville To Pixley Without Moving - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 104 - The Birthday Gift - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 105 - Everywhere A Chick Chick - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 107 - The Martial Vacation - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 108 - A Prize In Every Package - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 109 - Law Partners - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 110 - A Day In The Life Of Oliver Wendell Holmes - (TV Rip).mp4": 1294,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 111 - Economy Flight To Washington - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 112 - Retreat From Washington - (TV Rip).mp4": 1285,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 113 - A Hunting We Will Go - (TV Rip).mp4": 1286,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 114 - Oh, Promise Me - (TV Rip) .mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 115 - Eb Uses His Ingenuity - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 116 - The Old Trunk - (TV Rip).mp4": 1288,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 117 - The Milk Maker - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 4/Green Acres Season 4/Green Acres - 118 - The Reincarnation Of Eb - (TV Rip).mp4": 1303,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 122 - Lisa's Mudder Comes For A Visit - (TV Rip).mp4": 1294,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 123 - Everybody Tries To Love A Countess - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 119 - Where There's A Will - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 120 - A Tale Of A Tail - (TV Rip).mp4": 1298,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 121 - You And Your Shrunken Head - (TV Rip).mp4": 1303,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 128 - The Road - (TV Rip).mp4": 1293,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 127 - Four Of Spades - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 129 - The Youth Center - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 132 - The Special Delivery Letter - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 126 - Oliver's Schoolgirl Crush - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 133 - Ralph's Nuptials - (TV Rip).mp4": 1294,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 124 - Oliver & The Cornstalk - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 125 - Beauty Is Skin Deep - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 131 - The Wish Book - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 135 - Rest & Relaxation - (TV Rip).mp4": 1296,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 136 - Trapped - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 134 - Bundle Of Joy - (TV Rip).mp4": 1286,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 130 - The Ex-Con - (TV Rip).mp4": 1287,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 137 - The Cow Killer - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 138 - The Confrontation - (TV Rip).mp4": 1296,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 139 - The Case Of The Hooterville Refund Fraud - (TV Rip).mp4": 1290,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 140 - The Picnic - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 141 - The Beeping Rock - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 143 - Uncle Fedor - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 142 - The Wealthy Landowner - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 5/Green Acres Season 5/Green Acres - 144 - Happy Birthday - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 146 - The City Kids - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 147 - The Coming Out Party - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 145 - Jealousy - (TV Rip).mp4": 1295,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 149 - A Royal Story - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 150 - Oliver Goes Broke - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 156 - The Great Mayoralty Campaign - (TV Rip).mp4": 1291,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 148 - Eb's Double Trouble - (TV Rip).mp4": 1294,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 151 - Apple Picking Time - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 152 - Enterprising Eb - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 153 - Oliver's Double - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 154 - The High Cost Of Living - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 155 - The Liberation Movement - (TV Rip).mp4": 1302,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 157 - Charlie, Homer, & Natasha - (TV Rip) .mp4": 1290,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 158 - The Engagememnt Ring - (TV Rip).mp4": 1301,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 159 - The Free Paint Job - (TV Rip).mp4": 1292,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 160 - Son Of Drobny - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 164 - The Wedding Deal - (TV Rip).mp4": 1288,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 163 - Star Wittness - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 166 - The Spot Remover - (TV Rip).mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 169 - King Oliver - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 167 - A Girl For Drobny - (TV Rip).mp4": 1291,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 162 - The Carpenter's Ball - (TV Rip) .mp4": 1299,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 168 - The Hole In The Porch - (TV Rip).mp4": 1291,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 161 - Lisa The Psychologist - (TV Rip).mp4": 1300,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 165 - Hawaiian Honeymoon - (TV Rip).mp4": 1297,
  "GreenAcresCompleteSeries::Green Acres Season 6/Green Acres Season 6/Green Acres - 170 - Ex Secretary - (TV Rip).mp4": 1294,
},
};
