window.SHOW = {
  id: "AdventuresOfSonic",
  title: "Adventures of Sonic the Hedgehog",
  art: "AdventuresOfSonic.png",
  storageProgressKey: "adventuresofsonic-progress",
  storageSettingsKey: "adventuresofsonic-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E01 - The Super Special Son",
    "Adventures of Sonic the Hedgehog E01 - The Super Special Son.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E02 - Subterranean Sonic",
    "Adventures of Sonic the Hedgehog E02 - Subterranean Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E03 - Lovesick Sonic",
    "Adventures of Sonic the Hedgehog E03 -Lovesick Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E04 - Slowwww Going",
    "Adventures of Sonic the Hedgehog E04 - Slowwww Going.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E05 - High Stakes Sonic",
    "Adventures of Sonic the Hedgehog E05 - High Stakes Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E06 - Sonic Breakout",
    "Adventures of Sonic the Hedgehog E06 - Sonic Breakout.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E07 - Trail of the Missing",
    "Adventures of Sonic the Hedgehog E07 - Trail of the Missing.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E08 - Close Encounter of th",
    "Adventures of Sonic the Hedgehog E08 - Close Encounter of th.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E09 - Momma Robotniks Birth",
    "Adventures of Sonic the Hedgehog E09 - Momma Robotniks Birth.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E10 - Big Daddy",
    "Adventures of Sonic the Hedgehog E10 - Big Daddy.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E11 - Sonics Song",
    "Adventures of Sonic the Hedgehog E11 - Sonics Song.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E12 - Birth of a Salesman",
    "Adventures of Sonic the Hedgehog E12 - Birth of a Salesman.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E13 - Best Hedgehog",
    "Adventures of Sonic the Hedgehog E13 - Best Hedgehog.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E14 - The Robotnik Express",
    "Adventures of Sonic the Hedgehog E14 - The Robotnik Express.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E15 - Too Tall Tails",
    "Adventures of Sonic the Hedgehog E15 - Too Tall Tails.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E16 - Tails New Home",
    "Adventures of Sonic the Hedgehog E16 - Tails New Home.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E17 - Over the Hill Hero",
    "Adventures of Sonic the Hedgehog E17 - Over the Hill Hero.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E18 - Blank-Headed Eagle",
    "Adventures of Sonic the Hedgehog E18 - Blank-Headed Eagle.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E19 - The Mystery of the M",
    "Adventures of Sonic the Hedgehog E19 - The Mystery of the M.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E20 - So Long Sucker",
    "Adventures of Sonic the Hedgehog E20 - So Long Sucker.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E21 - Sonic Gets Thrashed",
    "Adventures of Sonic the Hedgehog E21 - Sonic Gets Thrashed.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E22 - Pseudo Sonic",
    "Adventures of Sonic the Hedgehog E22 - Pseudo Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E23 - Grounder the Genius",
    "Adventures of Sonic the Hedgehog E23 - Grounder the Genius.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E24 - Tails in Charge",
    "Adventures of Sonic the Hedgehog E24 - Tails in Charge.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E25 - Sno Problem",
    "Adventures of Sonic the Hedgehog E25 - Sno Problem.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E26 - Submerged Sonic",
    "Adventures of Sonic the Hedgehog E26 - Submerged Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E27 - Boogey-Mania",
    "Adventures of Sonic the Hedgehog E27 - Boogey-Mania.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E28 - Musta Been a Beautif",
    "Adventures of Sonic the Hedgehog E28 - Musta Been a Beautif.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E29 - Robotnik Junior",
    "Adventures of Sonic the Hedgehog E29 - Robotnik Junior.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E30 - Full Tilt Tails",
    "Adventures of Sonic the Hedgehog E30 - Full Tilt Tails.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E31 - MacHopper",
    "Adventures of Sonic the Hedgehog E31 - MacHopper.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E32 - Momma Robotnik Retur",
    "Adventures of Sonic the Hedgehog E32 - Momma Robotnik Retur.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E33 - Spaceman Sonic",
    "Adventures of Sonic the Hedgehog E33 - Spaceman Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E34 - Mad Mike Da Bear War",
    "Adventures of Sonic the Hedgehog E34 - Mad Mike Da Bear War.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E35 - The Last Resort",
    "Adventures of Sonic the Hedgehog E35 - The Last Resort.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E36 - Robotniks Rival",
    "Adventures of Sonic the Hedgehog E36 - Robotniks Rival.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E37 - The Magic Hassle",
    "Adventures of Sonic the Hedgehog E37 - The Magic Hassle.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E38 - Sonic the Matchmaker",
    "Adventures of Sonic the Hedgehog E38 - Sonic the Matchmaker.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E39 - Tails Prevails",
    "Adventures of Sonic the Hedgehog E39 - Tails Prevails.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E40 - Zoobotnik",
    "Adventures of Sonic the Hedgehog E40 - Zoobotnik.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E41 - Attack on the Pinbal",
    "Adventures of Sonic the Hedgehog E41 - Attack on the Pinbal.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E42 - Mass Transit Trouble",
    "Adventures of Sonic the Hedgehog E42 - Mass Transit Trouble.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E43 - Coachnik",
    "Adventures of Sonic the Hedgehog E43 - Coachnik.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E44 - Untouchable Sonic",
    "Adventures of Sonic the Hedgehog E44 - Untouchable Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E45 - Super Robotnik",
    "Adventures of Sonic the Hedgehog E45 - Super Robotnik.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E46 - Robolympics",
    "Adventures of Sonic the Hedgehog E46 - Robolympics.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E47 - Magnificent Sonic",
    "Adventures of Sonic the Hedgehog E47 - Magnificent Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E48 - Blackbot the Pirate",
    "Adventures of Sonic the Hedgehog E48 - Blackbot the Pirate.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E50 - Robotniks Pyramid Sc",
    "Adventures of Sonic the Hedgehog E50 - Robotniks Pyramid Sc.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E51 - Prehistoric Sonic",
    "Adventures of Sonic the Hedgehog E51 - Prehistoric Sonic.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E52 - Baby-Sitter Jitters",
    "Adventures of Sonic the Hedgehog E52 - Baby-Sitter Jitters.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E53 - Honey I Shrunk the H",
    "Adventures of Sonic the Hedgehog E53 - Honey I Shrunk the H.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E54 - Robotnikland",
    "Adventures of Sonic the Hedgehog E54 - Robotnikland.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E55 - The Mobius 5000",
    "Adventures of Sonic the Hedgehog E55 - The Mobius 5000.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E56 - The Little Merhog",
    "Adventures of Sonic the Hedgehog E56 - The Little Merhog.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E57 - Road Hog",
    "Adventures of Sonic the Hedgehog E57 - Road Hog.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E58 - The Robots Robot",
    "Adventures of Sonic the Hedgehog E58 - The Robots Robot.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E59 - Tails Tale",
    "Adventures of Sonic the Hedgehog E59 - Tails Tale.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E60 - Hero of the Year",
    "Adventures of Sonic the Hedgehog E60 - Hero of the Year.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E61 - Fast and Easy",
    "Adventures of Sonic the Hedgehog E61 - Fast and Easy.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E62 - Lifestyles of the Si",
    "Adventures of Sonic the Hedgehog E62 - Lifestyles of the Si.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E63 - Sonic is Running",
    "Adventures of Sonic the Hedgehog E63 - Sonic is Running.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E64 - Robo-Ninjas",
    "Adventures of Sonic the Hedgehog E64 - Robo-Ninjas.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E65 - Sonically Ever After",
    "Adventures of Sonic the Hedgehog E65 - Sonically Ever After.mp4"],
  ['adventures-of-sonic-the-hedgehog_202512', "ADVENTURES OF SONIC THE HEDGEHOG - S01E66 - Sonic Christmas Blas",
    "Adventures of Sonic the Hedgehog E66 - Sonic Christmas Blas.mp4"],
],
  durations: {
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E01 - The Super Special Son.mp4": 1318,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E02 - Subterranean Sonic.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E03 -Lovesick Sonic.mp4": 1311,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E04 - Slowwww Going.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E05 - High Stakes Sonic.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E06 - Sonic Breakout.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E07 - Trail of the Missing.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E08 - Close Encounter of th.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E09 - Momma Robotniks Birth.mp4": 1308,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E10 - Big Daddy.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E11 - Sonics Song.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E12 - Birth of a Salesman.mp4": 1319,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E13 - Best Hedgehog.mp4": 1318,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E14 - The Robotnik Express.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E15 - Too Tall Tails.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E16 - Tails New Home.mp4": 1297,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E17 - Over the Hill Hero.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E18 - Blank-Headed Eagle.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E19 - The Mystery of the M.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E20 - So Long Sucker.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E21 - Sonic Gets Thrashed.mp4": 1311,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E22 - Pseudo Sonic.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E23 - Grounder the Genius.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E24 - Tails in Charge.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E25 - Sno Problem.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E26 - Submerged Sonic.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E27 - Boogey-Mania.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E28 - Musta Been a Beautif.mp4": 1311,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E29 - Robotnik Junior.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E30 - Full Tilt Tails.mp4": 1316,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E31 - MacHopper.mp4": 1316,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E32 - Momma Robotnik Retur.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E33 - Spaceman Sonic.mp4": 1311,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E34 - Mad Mike Da Bear War.mp4": 1308,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E35 - The Last Resort.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E36 - Robotniks Rival.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E37 - The Magic Hassle.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E38 - Sonic the Matchmaker.mp4": 1307,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E39 - Tails Prevails.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E40 - Zoobotnik.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E41 - Attack on the Pinbal.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E42 - Mass Transit Trouble.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E43 - Coachnik.mp4": 1321,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E44 - Untouchable Sonic.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E45 - Super Robotnik.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E46 - Robolympics.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E47 - Magnificent Sonic.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E48 - Blackbot the Pirate.mp4": 1318,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E50 - Robotniks Pyramid Sc.mp4": 1314,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E51 - Prehistoric Sonic.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E52 - Baby-Sitter Jitters.mp4": 1310,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E53 - Honey I Shrunk the H.mp4": 1316,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E54 - Robotnikland.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E55 - The Mobius 5000.mp4": 1316,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E56 - The Little Merhog.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E57 - Road Hog.mp4": 1317,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E58 - The Robots Robot.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E59 - Tails Tale.mp4": 1315,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E60 - Hero of the Year.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E61 - Fast and Easy.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E62 - Lifestyles of the Si.mp4": 1316,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E63 - Sonic is Running.mp4": 1312,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E64 - Robo-Ninjas.mp4": 1316,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E65 - Sonically Ever After.mp4": 1313,
  "adventures-of-sonic-the-hedgehog_202512::Adventures of Sonic the Hedgehog E66 - Sonic Christmas Blas.mp4": 1305,
},
};
