window.SHOW = {
  id: "SchoolhouseRock",
  title: "Schoolhouse Rock",
  art: "SchoolhouseRock.jpg",
  storageProgressKey: "schoolhouserock-progress",
  storageSettingsKey: "schoolhouserock-settings",
  nestedPaths: false,
  grouping: "season",
  segments: "none",
  episodes: [
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E01 - Three Is A Magic Number",
    "01 Three Is A Magic Number.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E02 - My Hero Zero",
    "02 My Hero Zero.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E03 - Elementary My Dear",
    "03 Elementary My Dear.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E04 - The Four Legged Zoo",
    "04 The Four Legged Zoo.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E05 - Ready Or Not Here I Come",
    "05 Ready Or Not Here I Come.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E06 - I Got Six",
    "06 I Got Six.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E07 - Lucky Seven Sampson",
    "07 Lucky Seven Sampson.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E08 - Figure Eight",
    "08 Figure Eight.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E09 - Naughty Number Nine",
    "09 Naughty Number Nine.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E10 - The Good Eleven",
    "10 The Good Eleven.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E11 - Little Twelvetoes",
    "11 Little Twelvetoes.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E12 - A Noun Is A Person Place Or Thing",
    "12 A Noun Is A Person Place Or Thing.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E13 - Verb Thats Whats Happening",
    "13 Verb Thats Whats Happening.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E14 - Conjunction Junction",
    "14 Conjunction Junction.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E15 - Interjections",
    "15 Interjections.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E16 - Unpack Your Adjectives",
    "16 Unpack Your Adjectives.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E17 - Lolly Lolly Lolly Get Your Adverbs Here",
    "17 Lolly Lolly Lolly Get Your Adverbs Here.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E18 - Rufus Xavier Sasparilla",
    "18 Rufus Xavier Sasparilla.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E19 - Busy Prepositions",
    "19 Busy Prepositions.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E20 - The Tale Of Mr Morton",
    "20 The Tale Of Mr Morton.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E21 - No More Kings",
    "21 No More Kings.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E22 - The Shot Heard Round the World",
    "22 The Shot Heard Round the World.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E23 - The Preamble",
    "23 The Preamble.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E24 - Sufferin Till Suffrage",
    "24 Sufferin Till Suffrage.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E25 - Im Just A Bill",
    "25 Im Just A Bill.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E26 - The Great American Melting Pot",
    "26 The Great American Melting Pot.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E27 - Elbow Room",
    "27 Elbow Room.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E28 - Fireworks",
    "28 Fireworks.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E29 - Mother Necessity",
    "29 Mother Necessity.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E30 - Three Ring Government",
    "30 Three Ring Government.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E31 - Im Gonna Send Your Vote To College In Surround",
    "31 Im Gonna Send Your Vote To College In Surround.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E32 - You Earned Your Diploma and Presidential Minute",
    "32 You Earned Your Diploma and Presidential Minute.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E33 - A Victim Of Gravity",
    "33 A Victim Of Gravity.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E34 - Interplanet Janet",
    "34 Interplanet Janet.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E35 - The Body Machine",
    "35 The Body Machine.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E36 - Do The Circulation",
    "36 Do The Circulation.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E37 - The Energy Blues",
    "37 The Energy Blues.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E38 - Them Not So Dry Bones",
    "38 Them Not So Dry Bones.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E39 - Electricity Electricity",
    "39 Electricity Electricity.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E40 - Telegraph Line",
    "40 Telegraph Line.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E41 - The Weather Show",
    "41 The Weather Show.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E42 - Scooter Computer Introduction",
    "42 Scooter Computer Introduction.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E43 - Scooter Computer Hardware",
    "43 Scooter Computer Hardware.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E44 - Scooter Computer Software",
    "44 Scooter Computer Software.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E45 - Scooter Computer Number Cruncher",
    "45 Scooter Computer Number Cruncher.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E46 - Dollars And Sense",
    "46 Dollars And Sense.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E47 - Tax Man Max",
    "47 Tax Man Max.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E48 - Where The Money Goes",
    "48 Where The Money Goes.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E49 - Seven Dollars Fifty Cents Once A Week",
    "49 Seven Dollars Fifty Cents Once A Week.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E50 - Tyrannosaurus Debt",
    "50 Tyrannosaurus Debt.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E51 - This For That",
    "51 This For That.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E52 - Walkin On The Wall Street",
    "52 Walkin On The Wall Street.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E53 - The Checks In The Mail",
    "53 The Checks In The Mail.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E54 - Report from the North Pole",
    "54 Report from the North Pole.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E55 - The Little Things We Do",
    "55 The Little Things We Do.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E56 - The Trash Can Band",
    "56 The Trash Can Band.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E57 - You Oughta Be Savin Water",
    "57 You Oughta Be Savin Water.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E58 - The Rainforest",
    "58 The Rainforest.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E59 - Save the Ocean",
    "59 Save the Ocean.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E60 - Fat Cat Blue - The Clean Rivers Song",
    "60 Fat Cat Blue - The Clean Rivers Song.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E61 - A Tiny Urban Zoo",
    "61 A Tiny Urban Zoo.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E62 - Solar Power to the People",
    "62 Solar Power to the People.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E63 - Windy and the Windmills",
    "63 Windy and the Windmills.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E64 - Don't Be a Carbon Sasquatch",
    "64 Don't Be a Carbon Sasquatch.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E65 - The Three Rs",
    "65 The Three Rs.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E66 - Music Video - Conjunction Junction - Better Than Ezra",
    "66 Music Video - Conjunction Junction - Better Than Ezra.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E67 - Music Video - Electricity Electricity - Goodness",
    "67 Music Video - Electricity Electricity - Goodness.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E68 - Music Video - Im Just a Bill - Deluxe Folk Implosion",
    "68 Music Video - Im Just a Bill - Deluxe Folk Implosion.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E69 - Music Video - My Hero Zero - Lemonheads",
    "69 Music Video - My Hero Zero - Lemonheads.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E70 - The Making Of Im Gonna Send Your Vote To College",
    "70 The Making Of Im Gonna Send Your Vote To College.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E71 - Directors Commentaries",
    "71 Directors Commentaries.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E72 - Emmy Awards Featurette",
    "72 Emmy Awards Featurette.mp4"],
  ['schoolhouse-rock-30th', "SCHOOLHOUSE ROCK - S01E73 - Nike Commercial Three is a Magic Number",
    "73 Nike Commercial Three is a Magic Number.mp4"],
],
  durations: {
  "schoolhouse-rock-30th::01 Three Is A Magic Number.mp4": 182,
  "schoolhouse-rock-30th::02 My Hero Zero.mp4": 182,
  "schoolhouse-rock-30th::03 Elementary My Dear.mp4": 182,
  "schoolhouse-rock-30th::04 The Four Legged Zoo.mp4": 183,
  "schoolhouse-rock-30th::05 Ready Or Not Here I Come.mp4": 184,
  "schoolhouse-rock-30th::06 I Got Six.mp4": 182,
  "schoolhouse-rock-30th::07 Lucky Seven Sampson.mp4": 183,
  "schoolhouse-rock-30th::08 Figure Eight.mp4": 183,
  "schoolhouse-rock-30th::09 Naughty Number Nine.mp4": 184,
  "schoolhouse-rock-30th::10 The Good Eleven.mp4": 182,
  "schoolhouse-rock-30th::11 Little Twelvetoes.mp4": 182,
  "schoolhouse-rock-30th::12 A Noun Is A Person Place Or Thing.mp4": 183,
  "schoolhouse-rock-30th::13 Verb Thats Whats Happening.mp4": 181,
  "schoolhouse-rock-30th::14 Conjunction Junction.mp4": 182,
  "schoolhouse-rock-30th::15 Interjections.mp4": 181,
  "schoolhouse-rock-30th::16 Unpack Your Adjectives.mp4": 183,
  "schoolhouse-rock-30th::17 Lolly Lolly Lolly Get Your Adverbs Here.mp4": 182,
  "schoolhouse-rock-30th::18 Rufus Xavier Sasparilla.mp4": 181,
  "schoolhouse-rock-30th::19 Busy Prepositions.mp4": 183,
  "schoolhouse-rock-30th::20 The Tale Of Mr Morton.mp4": 180,
  "schoolhouse-rock-30th::21 No More Kings.mp4": 182,
  "schoolhouse-rock-30th::22 The Shot Heard Round the World.mp4": 183,
  "schoolhouse-rock-30th::23 The Preamble.mp4": 182,
  "schoolhouse-rock-30th::24 Sufferin Till Suffrage.mp4": 180,
  "schoolhouse-rock-30th::25 Im Just A Bill.mp4": 182,
  "schoolhouse-rock-30th::26 The Great American Melting Pot.mp4": 181,
  "schoolhouse-rock-30th::27 Elbow Room.mp4": 182,
  "schoolhouse-rock-30th::28 Fireworks.mp4": 182,
  "schoolhouse-rock-30th::29 Mother Necessity.mp4": 182,
  "schoolhouse-rock-30th::30 Three Ring Government.mp4": 181,
  "schoolhouse-rock-30th::31 Im Gonna Send Your Vote To College In Surround.mp4": 195,
  "schoolhouse-rock-30th::32 You Earned Your Diploma and Presidential Minute.mp4": 77,
  "schoolhouse-rock-30th::33 A Victim Of Gravity.mp4": 182,
  "schoolhouse-rock-30th::34 Interplanet Janet.mp4": 182,
  "schoolhouse-rock-30th::35 The Body Machine.mp4": 183,
  "schoolhouse-rock-30th::36 Do The Circulation.mp4": 182,
  "schoolhouse-rock-30th::37 The Energy Blues.mp4": 184,
  "schoolhouse-rock-30th::38 Them Not So Dry Bones.mp4": 182,
  "schoolhouse-rock-30th::39 Electricity Electricity.mp4": 181,
  "schoolhouse-rock-30th::40 Telegraph Line.mp4": 182,
  "schoolhouse-rock-30th::41 The Weather Show.mp4": 177,
  "schoolhouse-rock-30th::42 Scooter Computer Introduction.mp4": 203,
  "schoolhouse-rock-30th::43 Scooter Computer Hardware.mp4": 201,
  "schoolhouse-rock-30th::44 Scooter Computer Software.mp4": 202,
  "schoolhouse-rock-30th::45 Scooter Computer Number Cruncher.mp4": 202,
  "schoolhouse-rock-30th::46 Dollars And Sense.mp4": 182,
  "schoolhouse-rock-30th::47 Tax Man Max.mp4": 182,
  "schoolhouse-rock-30th::48 Where The Money Goes.mp4": 183,
  "schoolhouse-rock-30th::49 Seven Dollars Fifty Cents Once A Week.mp4": 182,
  "schoolhouse-rock-30th::50 Tyrannosaurus Debt.mp4": 182,
  "schoolhouse-rock-30th::51 This For That.mp4": 182,
  "schoolhouse-rock-30th::52 Walkin On The Wall Street.mp4": 182,
  "schoolhouse-rock-30th::53 The Checks In The Mail.mp4": 182,
  "schoolhouse-rock-30th::54 Report from the North Pole.mp4": 185,
  "schoolhouse-rock-30th::55 The Little Things We Do.mp4": 184,
  "schoolhouse-rock-30th::56 The Trash Can Band.mp4": 184,
  "schoolhouse-rock-30th::57 You Oughta Be Savin Water.mp4": 184,
  "schoolhouse-rock-30th::58 The Rainforest.mp4": 184,
  "schoolhouse-rock-30th::59 Save the Ocean.mp4": 184,
  "schoolhouse-rock-30th::60 Fat Cat Blue - The Clean Rivers Song.mp4": 184,
  "schoolhouse-rock-30th::61 A Tiny Urban Zoo.mp4": 179,
  "schoolhouse-rock-30th::62 Solar Power to the People.mp4": 184,
  "schoolhouse-rock-30th::63 Windy and the Windmills.mp4": 184,
  "schoolhouse-rock-30th::64 Don't Be a Carbon Sasquatch.mp4": 184,
  "schoolhouse-rock-30th::65 The Three Rs.mp4": 189,
  "schoolhouse-rock-30th::66 Music Video - Conjunction Junction - Better Than Ezra.mp4": 197,
  "schoolhouse-rock-30th::67 Music Video - Electricity Electricity - Goodness.mp4": 206,
  "schoolhouse-rock-30th::68 Music Video - Im Just a Bill - Deluxe Folk Implosion.mp4": 204,
  "schoolhouse-rock-30th::69 Music Video - My Hero Zero - Lemonheads.mp4": 185,
  "schoolhouse-rock-30th::70 The Making Of Im Gonna Send Your Vote To College.mp4": 888,
  "schoolhouse-rock-30th::71 Directors Commentaries.mp4": 1849,
  "schoolhouse-rock-30th::72 Emmy Awards Featurette.mp4": 200,
  "schoolhouse-rock-30th::73 Nike Commercial Three is a Magic Number.mp4": 33,
},
};
