window.SHOW = {
  id: "DragonBallZ",
  title: "Dragon Ball Z",
  art: "DragonBallZ.jpg",
  storageProgressKey: "dragonballz-progress",
  storageSettingsKey: "dragonballz-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['dbzcomplete', "DRAGON BALL Z - S01E01 - The Arrival of Raditz", 
    "8Dragon Ball Z ALL/Dragon Ball Z.001.DBOX.480p.x264-iKaos [v3] [6AFFEF6B].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E02 - The Arrival of Raditz", 
    "8Dragon Ball Z ALL/Dragon Ball Z.002.DBOX.480p.x264-iKaos [v3] [5072B146].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E03 - The World's Strongest Team", 
    "8Dragon Ball Z ALL/Dragon Ball Z.003.DBOX.480p.x264-iKaos [v3] [3B7BB4C8].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E04 - Gohan's Hidden Powers", 
    "8Dragon Ball Z ALL/Dragon Ball Z.004.DBOX.480p.x264-iKaos [v3] [095B81E6].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E05 - Goku's Unusual Journey", 
    "8Dragon Ball Z ALL/Dragon Ball Z.005.DBOX.480p.x264-iKaos [v3] [75AA1943].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E06 - Goku's Unusual Journey", 
    "8Dragon Ball Z ALL/Dragon Ball Z.006.DBOX.480p.x264-iKaos [v3] [3F9382F9].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E07 - Gohan's Metamorphosis", 
    "8Dragon Ball Z ALL/Dragon Ball Z.007.DBOX.480p.x264-iKaos [v3] [A209B7EC].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E08 - Gohan's Metamorphosis", 
    "8Dragon Ball Z ALL/Dragon Ball Z.008.DBOX.480p.x264-iKaos [v3] [B9D6EAEF].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E09 - Gohan Makes a Friend", 
    "8Dragon Ball Z ALL/Dragon Ball Z.009.DBOX.480p.x264-iKaos [v3] [C46F2D46].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E10 - Gohan Makes a Friend", 
    "8Dragon Ball Z ALL/Dragon Ball Z.010.DBOX.480p.x264-iKaos [v3] [D7279875].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E11 - Trouble on Arlia", 
    "8Dragon Ball Z ALL/Dragon Ball Z.011.DBOX.480p.x264-iKaos [v3] [F0B02971].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E12 - Home For Infinite Losers", 
    "8Dragon Ball Z ALL/Dragon Ball Z.012.DBOX.480p.x264-iKaos [v3] [2B2727FA].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E13 - Home For Infinite Losers", 
    "8Dragon Ball Z ALL/Dragon Ball Z.013.DBOX.480p.x264-iKaos [v3] [48E4742F].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E14 - Princess Snake's Hospitality", 
    "8Dragon Ball Z ALL/Dragon Ball Z.014.DBOX.480p.x264-iKaos [v3] [0185019E].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E15 - Escape from Piccolo", 
    "8Dragon Ball Z ALL/Dragon Ball Z.015.DBOX.480p.x264-iKaos [v3] [14B33973].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E16 - Escape from Piccolo", 
    "8Dragon Ball Z ALL/Dragon Ball Z.016.DBOX.480p.x264-iKaos [v3] [256F61B3].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E17 - Showdown in the Past", 
    "8Dragon Ball Z ALL/Dragon Ball Z.017.DBOX.480p.x264-iKaos [v3] [CA1D6934].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E18 - The End of Snake Way", 
    "8Dragon Ball Z ALL/Dragon Ball Z.018.DBOX.480p.x264-iKaos [v3] [EE64FD77].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E19 - A Fight Against Gravity... Catch Bubbles!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.019.DBOX.480p.x264-iKaos [v3] [9E1B53CD].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E20 - The Legend of the Saiyans", 
    "8Dragon Ball Z ALL/Dragon Ball Z.020.DBOX.480p.x264-iKaos [v3] [C52465C3].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E21 - A Black Day for Planet Earth", 
    "8Dragon Ball Z ALL/Dragon Ball Z.021.DBOX.480p.x264-iKaos [v3] [F7EB97E7].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E22 - The Battle Begins... Goku Where Are You?", 
    "8Dragon Ball Z ALL/Dragon Ball Z.022.DBOX.480p.x264-iKaos [v3] [1C26C359].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E23 - The Saibamen Strike", 
    "8Dragon Ball Z ALL/Dragon Ball Z.023.DBOX.480p.x264-iKaos [v3] [2822BAB5].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E24 - Nappa... The Invincible?", 
    "8Dragon Ball Z ALL/Dragon Ball Z.024.DBOX.480p.x264-iKaos [v3] [AB2EDC29].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E25 - Tien Goes All Out!!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.025.DBOX.480p.x264-iKaos [v3] [6AD42C0D].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E26 - Tien Goes All Out!!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.026.DBOX.480p.x264-iKaos [v3] [F0DB2962].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E27 - Time's Up!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.027.DBOX.480p.x264-iKaos [v3] [A30F00AC].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E28 - The Return of Goku", 
    "8Dragon Ball Z ALL/Dragon Ball Z.028.DBOX.480p.x264-iKaos [v3] [8BFCEA5A].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E29 - Goku Strikes Back", 
    "8Dragon Ball Z ALL/Dragon Ball Z.029.DBOX.480p.x264-iKaos [v3] [4B2C1AF6].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E30 - Goku vs. Vegeta... A Saiyan Duel!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.030.DBOX.480p.x264-iKaos [v3] [12E7A463].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E31 - Goku vs. Vegeta... A Saiyan Duel!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.031.DBOX.480p.x264-iKaos [v3] [3977476C].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E32 - Vegeta... Saiyan Style!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.032.DBOX.480p.x264-iKaos [v3] [329F32EA].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E33 - Stop Vegeta Now!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.033.DBOX.480p.x264-iKaos [v3] [E2C76623].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E34 - Stop Vegeta Now!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.034.DBOX.480p.x264-iKaos [v3] [7B25CD2A].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E35 - The Battle Ends", 
    "8Dragon Ball Z ALL/Dragon Ball Z.035.DBOX.480p.x264-iKaos [v3] [BC72F514].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E36 - A New Goal... Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.036.DBOX.480p.x264-iKaos [v3] [741B4BD5].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E37 - A New Goal... Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.037.DBOX.480p.x264-iKaos [v3] [AA8894CF].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E38 - Journey to Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.038.DBOX.480p.x264-iKaos [v3] [DD1D03BF].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S01E39 - Journey to Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.039.DBOX.480p.x264-iKaos [v3] [63172531].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E01 - Friends or Foes?", 
    "8Dragon Ball Z ALL/Dragon Ball Z.040.DBOX.480p.x264-iKaos [v3] [A2E85E86].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E02 - Friends or Foes?", 
    "8Dragon Ball Z ALL/Dragon Ball Z.041.DBOX.480p.x264-iKaos [v3] [46453279].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E03 - Hunt for a Dragon Ball", 
    "8Dragon Ball Z ALL/Dragon Ball Z.042.DBOX.480p.x264-iKaos [v3] [4D8A28F2].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E04 - Who's Who?!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.043.DBOX.480p.x264-iKaos [v3] [553840EE].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E05 - Touchdown on Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.044.DBOX.480p.x264-iKaos [v3] [3FA265AF].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E06 - Face-off on Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.045.DBOX.480p.x264-iKaos [v3] [DEE3ECF2].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E07 - The Ruthless Frieza", 
    "8Dragon Ball Z ALL/Dragon Ball Z.046.DBOX.480p.x264-iKaos [v3] [04F6DEF9].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E08 - The Nameks versus Frieza", 
    "8Dragon Ball Z ALL/Dragon Ball Z.047.DBOX.480p.x264-iKaos [v3] [025124C5].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E09 - Escape from Dodoria", 
    "8Dragon Ball Z ALL/Dragon Ball Z.048.DBOX.480p.x264-iKaos [v3] [ADF31381].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E10 - Secrets Revealed", 
    "8Dragon Ball Z ALL/Dragon Ball Z.049.DBOX.480p.x264-iKaos [v3] [8CDE45AF].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E11 - A Collision Course", 
    "8Dragon Ball Z ALL/Dragon Ball Z.050.DBOX.480p.x264-iKaos [v3] [CAAB8929].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E12 - Stay Away From Frieza", 
    "8Dragon Ball Z ALL/Dragon Ball Z.051.DBOX.480p.x264-iKaos [v3] [4EB6807F].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E13 - Stay Away From Frieza", 
    "8Dragon Ball Z ALL/Dragon Ball Z.052.DBOX.480p.x264-iKaos [v3] [2F0B408D].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E14 - Zarbon Transformed", 
    "8Dragon Ball Z ALL/Dragon Ball Z.053.DBOX.480p.x264-iKaos [v3] [3F909DCB].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E15 - The Eldest Namek", 
    "8Dragon Ball Z ALL/Dragon Ball Z.054.DBOX.480p.x264-iKaos [v3] [0C30262F].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E16 - Get Vegeta!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.055.DBOX.480p.x264-iKaos [v3] [BA28763F].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E17 - Vegeta Revived", 
    "8Dragon Ball Z ALL/Dragon Ball Z.056.DBOX.480p.x264-iKaos [v3] [4D2018E6].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E18 - A Heavy Burden", 
    "8Dragon Ball Z ALL/Dragon Ball Z.057.DBOX.480p.x264-iKaos [v3] [39C3E95B].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E19 - Immortality Denied", 
    "8Dragon Ball Z ALL/Dragon Ball Z.058.DBOX.480p.x264-iKaos [v3] [426DFE16].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E20 - Big Trouble for Bulma", 
    "8Dragon Ball Z ALL/Dragon Ball Z.059.DBOX.480p.x264-iKaos [v3] [D003A267].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E21 - Scramble for the Dragon Balls!", 
    "8Dragon Ball Z ALL/Dragon Ball Z.060.DBOX.480p.x264-iKaos [v3] [01D1989B].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E22 - Arrival of the Ginyu Force", 
    "8Dragon Ball Z ALL/Dragon Ball Z.061.DBOX.480p.x264-iKaos [v3] [18984D6A].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E23 - Elite Fighters of the Universe... The Ginyu Force", 
    "8Dragon Ball Z ALL/Dragon Ball Z.062.DBOX.480p.x264-iKaos [v3] [704D0F32].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E24 - Time Tricks and Body Binds", 
    "8Dragon Ball Z ALL/Dragon Ball Z.063.DBOX.480p.x264-iKaos [v3] [13965EDA].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E25 - No Refuge From Recoome", 
    "8Dragon Ball Z ALL/Dragon Ball Z.064.DBOX.480p.x264-iKaos [v3] [66D6B48E].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E26 - Enter Goku", 
    "8Dragon Ball Z ALL/Dragon Ball Z.065.DBOX.480p.x264-iKaos [v3] [318B49E0].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E27 - Goku... Super Saiyan?", 
    "8Dragon Ball Z ALL/Dragon Ball Z.066.DBOX.480p.x264-iKaos [v3] [97AD84D1].mp4"],
  ['dbzcomplete', "DRAGON BALL Z - S02E28 - Goku... Super Saiyan?", 
    "8Dragon Ball Z ALL/Dragon Ball Z.067.DBOX.480p.x264-iKaos [v3] [90E67167].mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E29 - At Last, a Direct Confrontation!! Captain Ginyu Takes the Field", 
    "068 - Ginyu Assault.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E30 - Incredible Force!! Did You See Goku's Full Power?", 
    "069 - Incredible Force!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E31 - What of the Battle's Outcome!? Freeza's Evil Hand Closes Around the Grand Elder", 
    "070 - Frieza Approaches.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E32 - Surprise!! Goku is Ginyu and Ginyu is Goku", 
    "071 - Goku is Ginyu and Ginyu is Goku.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E33 - Come Forth, Super Shen Long!! Grant Me My Wish", 
    "072 - Calling the Eternal Dragon.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E34 - That Ain't Me! Gohan, Don't Lose Your Nerve, Hit Your Father!!", 
    "073 - Gohan, Defeat Your Dad!!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S02E35 - Whoops!! Ginyu Has Turned Into a Frog", 
    "074 - Captain Ginyu... The Frog.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E01 - Password is Porunga", 
    "075 - Password is Porunga.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E02 - Piccolo's Return", 
    "076 - Piccolo's Return.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E03 - The Fusion", 
    "077 - The Fusion.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E04 - Fighting Power: One Million?", 
    "078 - Fighting Power One Million.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E05 - Gohan Attacks", 
    "079 - Gohan Attacks.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E06 - Piccolo the Super-Namek", 
    "080 - Piccolo the Super-Namek.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E07 - Deja Vu", 
    "081 - Déjà vu.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E08 - Frieza's Second Transformation", 
    "082 - Frieza's Second Transformation.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E09 - Another Transformation?", 
    "083 - Another Transformation.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E10 - Dende's Demise", 
    "084 - Dende's Demise.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E11 - The Renewed Goku", 
    "085 - The Renewed Goku.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E12 - The End of Vegeta", 
    "086 - The End of Vegeta.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E13 - The Ultimate Battle", 
    "087 - The Ultimate Battle.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E14 - Clash of the Super Powers", 
    "088 - Clash of the Super Powers.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E15 - Frieza's Boast", 
    "089 - Frieza's Boast.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E16 - Bold and Fearless", 
    "090 - Bold and Fearless.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E17 - Embodiment of Fire", 
    "091 - Embodiment of Fire.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E18 - Trump Card", 
    "092 - Trump Card.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E19 - Keep the Chance Alive!!", 
    "093 - Keep the Chance Alive.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E20 - Power of the Spirit", 
    "094 - Power of the Spirit.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E21 - Transformed at Last", 
    "095 - Transformed at Last.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E22 - Explosion of Anger", 
    "096 - Explosion of Anger.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E23 - Namek's Destruction?", 
    "097 - Namek's Destruction.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E24 - A Final Attack", 
    "098 - A Final Attack.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E25 - Approaching Destruction", 
    "099 - Approaching Destruction.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E26 - Gohan Returns", 
    "100 - Gohan Returns.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E27 - The Last Wish", 
    "101 - The Last Wish.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E28 - Duel on a Vanishing Planet", 
    "102 - Duel on a Vanishing Planet.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E29 - Pathos of Frieza", 
    "103 - Pathos of Frieza.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E30 - Frieza Defeated!!", 
    "104 - Frieza Defeated!!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E31 - Mighty Blast of Rage", 
    "105 - Mighty Blast of Rage.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E32 - Namek's Explosion... Goku's End?", 
    "106 - Namek's Explosion... Goku's End.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S03E33 - Goku's Alive!!", 
    "107 - Goku's Alive!!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E01 - The Heavens Tremble", 
    "108 - The Heavens Tremble.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E02 - Black Fog of Terror", 
    "109 - Black Fog of Terror.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E03 - Battle in Kami's Lookout", 
    "110 - Battle in Kami's Lookout.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E04 - Fight with Piccolo", 
    "111 - Fight With Piccolo.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E05 - Call for Restoration", 
    "112 - Call For Restoration.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E06 - Suicidal Course", 
    "113 - Suicidal Course.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E07 - Extreme Measures", 
    "114 - Extreme Measures.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E08 - The World Awakens", 
    "115 - The World Awakens.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E09 - Brief Chance for Victory", 
    "116 - Brief Chance for Victory.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E10 - Krillin's Proposal", 
    "117 - Krillin's Proposal.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E11 - Frieza's Counterattack", 
    "118 - Frieza's Counterattack.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E12 - The Mysterious Youth", 
    "119 - The Mysterious Youth.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E13 - Another Super Saiyan?", 
    "120 - Another Super Saiyan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E14 - Welcome Back Goku", 
    "121 - Welcome Back Goku.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E15 - Mystery Revealed", 
    "122 - Mystery Revealed.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E16 - Goku's Special Technique", 
    "123 - Goku's Special Technique.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E17 - Z Warriors Prepare", 
    "124 - Z Warriors Prepare.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E18 - Goku's Ordeal", 
    "125 - Goku's Ordeal.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E19 - The Androids Appear", 
    "126 - The Androids Appear.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E20 - A Handy Trick", 
    "127 - A Handy Trick.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E21 - Double Trouble for Goku", 
    "128 - Double Trouble for Goku.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E22 - Upgrade to Super Saiyan", 
    "129 - Upgrade to Super Saiyan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E23 - The Secret of Dr. Gero", 
    "130 - The Secret of Dr. Gero.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E24 - More Androids?!", 
    "131 - More Androids!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E25 - Follow Dr. Gero", 
    "132 - Follow Dr. Gero.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E26 - Nightmare Comes True", 
    "133 - Nightmare Comes True.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E27 - Goku's Assassin", 
    "134 - Goku's Assassin.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E28 - Deadly Beauty", 
    "135 - Deadly Beauty.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E29 - No Match for the Androids", 
    "136 - No Match for the Androids.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E30 - Last Ditch Effort", 
    "137 - Last Ditch Effort.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E31 - Closing In", 
    "138 - Closing In.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S04E32 - Unwelcome Discovery", 
    "139 - Unwelcome Discovery.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E01 - Seized with Fear", 
    "140 - Seized with Fear.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E02 - The Reunion", 
    "141 - The Reunion.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E03 - Borrowed Powers", 
    "142 - Borrowed Powers.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E04 - His Name is Cell", 
    "143 - His Name is Cell.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E05 - Piccolo's Folly", 
    "144 - Piccolo's Folly.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E06 - Laboratory Basement", 
    "145 - Laboratory Basement.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E07 - Our Hero Awakes", 
    "146 - Our Hero Awakes.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E08 - Time Chamber", 
    "147 - Time Chamber.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E09 - The Monster is Coming", 
    "148 - The Monster is Coming.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E10 - He's Here", 
    "149 - He's Here.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E11 - Up to Piccolo", 
    "150 - Up to Piccolo.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E12 - Silent Warrior", 
    "151 - Silent Warrior.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E13 - Say Goodbye, 17", 
    "152 - Say Goodbye, 17.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E14 - Sacrifice", 
    "153 - Sacrifice.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E15 - Saiyans Emerge", 
    "154 - Saiyans Emerge.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E16 - Super Vegeta", 
    "155 - Super Vegeta.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E17 - Bow to the Prince", 
    "156 - Bow to The Prince.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E18 - Hour of Temptation", 
    "157 - Hour of Temptation.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E19 - Krillin's Decision", 
    "158 - Krillin's Decision.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E20 - The Last Defense", 
    "159 - The Last Defense.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E21 - Cell is Complete", 
    "160 - Cell is Complete.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E22 - Vegeta Must Pay", 
    "161 - Vegeta Must Pay.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E23 - Trunks Ascends", 
    "162 - Trunks Ascends.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E24 - Saving Throw", 
    "163 - Saving Throw.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E25 - Ghosts from Tomorrow", 
    "164 - Ghosts from Tomorrow.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S05E26 - The Cell Games", 
    "165 - The Cell Games.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E01 - What is the Tournament?", 
    "166 - What is the Tournament.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E02 - The Doomsday Broadcast", 
    "167 - The Doomsday Broadcast.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E03 - Meet Me in the Ring", 
    "168 - Meet Me In the Ring.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E04 - No Worries Here", 
    "169 - No Worries Here.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E05 - A Girl Named Lime", 
    "170 - A Girl Named Lime.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E06 - Memories of Gohan", 
    "171 - Memories of Gohan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E07 - A New Guardian", 
    "172 - A New Guardian.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E08 - Dende's Dragon", 
    "173 - Dende's Dragon.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E09 - The Puzzle of General Tao", 
    "174 - The Puzzle of General Tao.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E10 - The Games Begin", 
    "175 - The Games Begin.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E11 - Losers Fight First", 
    "176 - Losers Fight First.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E12 - Goku vs. Cell", 
    "177 - Goku vs. Cell.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E13 - Cell's Bag of Tricks", 
    "178 - Cell's Bag of Tricks.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E14 - No More Rules", 
    "179 - No More Rules.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E15 - The Fight is Over", 
    "180 - The Fight is Over.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E16 - Faith in a Boy", 
    "181 - Faith in a Boy.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E17 - Gohan's Desperate Plea", 
    "182 - Gohan's Plea.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E18 - Android Explosion", 
    "183 - Android Explosion.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E19 - Cell Juniors Attack!", 
    "184 - Cell Juniors Attack!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E20 - The Unleashing", 
    "185 - Awakening.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E21 - The Unstoppable Gohan", 
    "186 - The Unstoppable Gohan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E22 - Cell's Mighty Breakdown", 
    "187 - Cell's Break Down.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E23 - A Hero's Farewell", 
    "188 - A Hero's Farewell.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E24 - Cell Returns!", 
    "189 - Cell Returns!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E25 - The Horror Won't End", 
    "190 - The Horror Won't End.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E26 - Save the World", 
    "191 - Save the World.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E27 - Goku's Decision", 
    "192 - Goku's Decision.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E28 - One More Wish", 
    "193 - One More Wish.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S06E29 - Free the Future", 
    "194 - Free the Future.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E01 - Warriors of the Dead", 
    "195 - Warriors of the Dead.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E02 - Tournament Begins", 
    "196 - Tournament Begins.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E03 - Water Fight", 
    "197 - Water Fight.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E04 - Final Round", 
    "198 - Final Round.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E05 - Goku vs. Pikkon", 
    "199 - Goku vs. Pikkon.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E06 - Gohan Goes to High School", 
    "200 - Gohan Goes to High School.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E07 - I am Saiyaman", 
    "201 - I am Saiyaman.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E08 - Gohan's First Date", 
    "202 - Gohan's First Date.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E09 - Rescue Videl", 
    "203 - Rescue Videl.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E10 - Blackmail", 
    "204 - Blackmail.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E11 - I'll Fight Too!", 
    "205 - I'll Fight Too!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E12 - The Newest Super Saiyan", 
    "206 - The Newest Super Saiyan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E13 - Take Flight Videl", 
    "207 - Take Flight, Videl.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E14 - Gather For the Tournament", 
    "208 - Gather for the Tournament.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E15 - Camera Shy", 
    "209 - Camera Shy.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E16 - The World Tournament", 
    "210 - The World Tournament.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E17 - Trunks vs. Goten", 
    "211 - Trunks vs. Goten.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E18 - Best of the Boys", 
    "212 - Best of the Boys.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E19 - Big Trouble, Little Trunks", 
    "213 - Big Trouble, Little Trunks.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E20 - Who Will Fight Who?", 
    "214 - Who Will Fight Who.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E21 - Forfeit of Piccolo!", 
    "215 - Forfeit of Piccolo.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E22 - A Dark and Secret Power", 
    "216 - A Dark and Secret Power.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E23 - Videl is Crushed", 
    "217 - Videl Is Crushed.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E24 - Identities Revealed", 
    "218 - Identities Revealed.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S07E25 - Energy Drain", 
    "219 - Energy Drain.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E01 - The Wizard's Curse", 
    "220 - The Wizard's Curse.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E02 - King of the Demons", 
    "221 - King of the Demons.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E03 - Vegeta Attacks", 
    "222 - Vegeta Attacks.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E04 - Next Up, Goku", 
    "223 - Next Up, Goku.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E05 - Battle Supreme", 
    "224 - Battle Supreme.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E06 - Eighteen Unmasks", 
    "225 - Eighteen Unmasks.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E07 - Pay to Win", 
    "226 - Pay to Win.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E08 - Heart of a Villain", 
    "227 - Heart of a Villain.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E09 - The Dark Prince Returns", 
    "228 - The Dark Prince Returns.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E10 - Vegeta's Pride", 
    "229 - Vegeta's Pride.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E11 - The Long Awaited Fight", 
    "230 - The Long Awaited Fight.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E12 - Magic Ball of Buu", 
    "231 - Magic Ball of Buu.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E13 - Buu is Hatched!", 
    "232 - Buu is Hatched.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E14 - The Losses Begin", 
    "233 - The Losses Begin.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E15 - The Terror of Majin Buu", 
    "234 - The Terror of Mr. Buu.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E16 - Meal Time", 
    "235 - Meal Time.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E17 - The Warrior's Decision", 
    "236 - The Warrior's Decision.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E18 - Final Atonement", 
    "237 - Final Atonement.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E19 - Evil Lives On", 
    "238 - Evil Lives On.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E20 - Find the Dragon Balls", 
    "239 - Find the Dragon Balls.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E21 - Revival", 
    "240 - Revival.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E22 - Global Announcement", 
    "241 - Global Announcement.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E23 - Learn to Fuse", 
    "242 - Learn to Fuse!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E24 - The Z Sword", 
    "243 - The Z Sword.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E25 - Race to Capsule Corp.", 
    "244 - Race to Capsule Corp..mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E26 - Super Saiyan 3?!", 
    "245 - Super Saiyan 3!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E27 - Buu's Mutiny", 
    "246 - Buu's Mutiny.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E28 - The Fusion Dance", 
    "247 - The Fusion Dance.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E29 - Goku's Time is Up", 
    "248 - Goku's Time Is Up.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E30 - Return to Other World", 
    "249 - Return to Other World.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E31 - Out From the Broken Sword", 
    "250 - Out from the Broken Sword.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E32 - Gotenks is Born", 
    "251 - Gotenks Is Born.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E33 - Unlikely Friendship", 
    "252 - Unlikely Friendship.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S08E34 - I Kill No More", 
    "253 - I Kill No More.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E01 - The Evil of Men", 
    "254 - The Evil of Men.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E02 - Buu Against Buu", 
    "255 - Buu Against Buu.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E03 - Empty Planet", 
    "256 - Empty Planet.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E04 - Time Struggle", 
    "257 - Time Struggle.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E05 - Super Moves of Gotenks", 
    "258 - Super Moves of Gotenks.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E06 - Trapped in Forever", 
    "259 - Trapped in Forever.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E07 - Feeding Frenzy", 
    "260 - Feeding Frenzy.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E08 - Gotenks is Awesome", 
    "261 - Gotenks is Awesome!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E09 - Unlucky Break", 
    "262 - Unlucky Break.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E10 - A Whole New Gohan", 
    "263 - A Whole New Gohan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E11 - Search for Survivors", 
    "264 - Search For Survivors.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E12 - Majin Buu Transforms", 
    "265 - Majin Buu Transforms.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E13 - The Old Kai's Weapon", 
    "266 - The Old Kai's Weapon.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E14 - Ready to Fuse?", 
    "267 - Ready to Fuse.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E15 - Union of Rivals", 
    "268 - Union of Rivals.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E16 - Meet Vegito", 
    "269 - Meet Vegito.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E17 - Rip in the Universe", 
    "270 - Rip in the Universe.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E18 - Vegito...Downsized", 
    "271 - Vegito... Downsized.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E19 - The Incredible Fighting Candy", 
    "272 - The Incredible Fighting Candy.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E20 - The Innards of Buu", 
    "273 - The Innards of Buu.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E21 - Mind Trap", 
    "274 - Mind Trap.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E22 - Deadly Vision", 
    "275 - Deadly Vision.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E23 - Evil Kid Buu!", 
    "276 - Evil Kid Buu!.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E24 - End of Earth", 
    "277 - End of Earth.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E25 - True Saiyans Fight Alone", 
    "278 - True Saiyans Fight Alone.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E26 - Battle for the Universe Begins", 
    "279 - Battle for the Universe Begins.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E27 - Vegeta's Respect", 
    "280 - Vegeta's Respect.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E28 - Minute of Desperation", 
    "281 - Minute of Desperation.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E29 - Old Buu Emerges", 
    "282 - Old Buu Emerges.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E30 - Earth Reborn", 
    "283 - Earth Reborn.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E31 - Call to Action", 
    "284 - Call to Action.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E32 - People of Earth Unite", 
    "285 - People of Earth Unite.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E33 - Spirit Bomb Triumphant", 
    "286 - Spirit Bomb Triumphant.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E34 - Celebrations with Majin Buu", 
    "287 - Celebrations with Majin Buu.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E35 - He's Always Late", 
    "288 - He's Always Late.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E36 - Granddaughter Pan", 
    "289 - Granddaughter Pan.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E37 - Buu's Reincarnation", 
    "290 - Buu's Reincarnation.mp4"],
  ['dragon-ball-z-funimation-faulconer-score', "DRAGON BALL Z - S09E38 - Goku's Next Journey", 
    "291 - Goku's Next Journey.mp4"],
],
  durations: {
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.001.DBOX.480p.x264-iKaos [v3] [6AFFEF6B].mp4": 1477,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.002.DBOX.480p.x264-iKaos [v3] [5072B146].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.003.DBOX.480p.x264-iKaos [v3] [3B7BB4C8].mp4": 1477,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.004.DBOX.480p.x264-iKaos [v3] [095B81E6].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.005.DBOX.480p.x264-iKaos [v3] [75AA1943].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.006.DBOX.480p.x264-iKaos [v3] [3F9382F9].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.007.DBOX.480p.x264-iKaos [v3] [A209B7EC].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.008.DBOX.480p.x264-iKaos [v3] [B9D6EAEF].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.009.DBOX.480p.x264-iKaos [v3] [C46F2D46].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.010.DBOX.480p.x264-iKaos [v3] [D7279875].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.011.DBOX.480p.x264-iKaos [v3] [F0B02971].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.012.DBOX.480p.x264-iKaos [v3] [2B2727FA].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.013.DBOX.480p.x264-iKaos [v3] [48E4742F].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.014.DBOX.480p.x264-iKaos [v3] [0185019E].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.015.DBOX.480p.x264-iKaos [v3] [14B33973].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.016.DBOX.480p.x264-iKaos [v3] [256F61B3].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.017.DBOX.480p.x264-iKaos [v3] [CA1D6934].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.018.DBOX.480p.x264-iKaos [v3] [EE64FD77].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.019.DBOX.480p.x264-iKaos [v3] [9E1B53CD].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.020.DBOX.480p.x264-iKaos [v3] [C52465C3].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.021.DBOX.480p.x264-iKaos [v3] [F7EB97E7].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.022.DBOX.480p.x264-iKaos [v3] [1C26C359].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.023.DBOX.480p.x264-iKaos [v3] [2822BAB5].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.024.DBOX.480p.x264-iKaos [v3] [AB2EDC29].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.025.DBOX.480p.x264-iKaos [v3] [6AD42C0D].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.026.DBOX.480p.x264-iKaos [v3] [F0DB2962].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.027.DBOX.480p.x264-iKaos [v3] [A30F00AC].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.028.DBOX.480p.x264-iKaos [v3] [8BFCEA5A].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.029.DBOX.480p.x264-iKaos [v3] [4B2C1AF6].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.030.DBOX.480p.x264-iKaos [v3] [12E7A463].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.031.DBOX.480p.x264-iKaos [v3] [3977476C].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.032.DBOX.480p.x264-iKaos [v3] [329F32EA].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.033.DBOX.480p.x264-iKaos [v3] [E2C76623].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.034.DBOX.480p.x264-iKaos [v3] [7B25CD2A].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.035.DBOX.480p.x264-iKaos [v3] [BC72F514].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.036.DBOX.480p.x264-iKaos [v3] [741B4BD5].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.037.DBOX.480p.x264-iKaos [v3] [AA8894CF].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.038.DBOX.480p.x264-iKaos [v3] [DD1D03BF].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.039.DBOX.480p.x264-iKaos [v3] [63172531].mp4": 1477,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.040.DBOX.480p.x264-iKaos [v3] [A2E85E86].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.041.DBOX.480p.x264-iKaos [v3] [46453279].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.042.DBOX.480p.x264-iKaos [v3] [4D8A28F2].mp4": 1478,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.043.DBOX.480p.x264-iKaos [v3] [553840EE].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.044.DBOX.480p.x264-iKaos [v3] [3FA265AF].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.045.DBOX.480p.x264-iKaos [v3] [DEE3ECF2].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.046.DBOX.480p.x264-iKaos [v3] [04F6DEF9].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.047.DBOX.480p.x264-iKaos [v3] [025124C5].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.048.DBOX.480p.x264-iKaos [v3] [ADF31381].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.049.DBOX.480p.x264-iKaos [v3] [8CDE45AF].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.050.DBOX.480p.x264-iKaos [v3] [CAAB8929].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.051.DBOX.480p.x264-iKaos [v3] [4EB6807F].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.052.DBOX.480p.x264-iKaos [v3] [2F0B408D].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.053.DBOX.480p.x264-iKaos [v3] [3F909DCB].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.054.DBOX.480p.x264-iKaos [v3] [0C30262F].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.055.DBOX.480p.x264-iKaos [v3] [BA28763F].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.056.DBOX.480p.x264-iKaos [v3] [4D2018E6].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.057.DBOX.480p.x264-iKaos [v3] [39C3E95B].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.058.DBOX.480p.x264-iKaos [v3] [426DFE16].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.059.DBOX.480p.x264-iKaos [v3] [D003A267].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.060.DBOX.480p.x264-iKaos [v3] [01D1989B].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.061.DBOX.480p.x264-iKaos [v3] [18984D6A].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.062.DBOX.480p.x264-iKaos [v3] [704D0F32].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.063.DBOX.480p.x264-iKaos [v3] [13965EDA].mp4": 1479,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.064.DBOX.480p.x264-iKaos [v3] [66D6B48E].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.065.DBOX.480p.x264-iKaos [v3] [318B49E0].mp4": 1481,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.066.DBOX.480p.x264-iKaos [v3] [97AD84D1].mp4": 1480,
  "dbzcomplete::8Dragon Ball Z ALL/Dragon Ball Z.067.DBOX.480p.x264-iKaos [v3] [90E67167].mp4": 1479,
  "dragon-ball-z-funimation-faulconer-score::068 - Ginyu Assault.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::069 - Incredible Force!.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::070 - Frieza Approaches.mp4": 1197,
  "dragon-ball-z-funimation-faulconer-score::071 - Goku is Ginyu and Ginyu is Goku.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::072 - Calling the Eternal Dragon.mp4": 1165,
  "dragon-ball-z-funimation-faulconer-score::073 - Gohan, Defeat Your Dad!!.mp4": 1161,
  "dragon-ball-z-funimation-faulconer-score::074 - Captain Ginyu... The Frog.mp4": 1179,
  "dragon-ball-z-funimation-faulconer-score::075 - Password is Porunga.mp4": 1146,
  "dragon-ball-z-funimation-faulconer-score::076 - Piccolo's Return.mp4": 1206,
  "dragon-ball-z-funimation-faulconer-score::077 - The Fusion.mp4": 1145,
  "dragon-ball-z-funimation-faulconer-score::078 - Fighting Power One Million.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::079 - Gohan Attacks.mp4": 1129,
  "dragon-ball-z-funimation-faulconer-score::080 - Piccolo the Super-Namek.mp4": 1170,
  "dragon-ball-z-funimation-faulconer-score::081 - Déjà vu.mp4": 1197,
  "dragon-ball-z-funimation-faulconer-score::082 - Frieza's Second Transformation.mp4": 1153,
  "dragon-ball-z-funimation-faulconer-score::083 - Another Transformation.mp4": 1182,
  "dragon-ball-z-funimation-faulconer-score::084 - Dende's Demise.mp4": 1165,
  "dragon-ball-z-funimation-faulconer-score::085 - The Renewed Goku.mp4": 1158,
  "dragon-ball-z-funimation-faulconer-score::086 - The End of Vegeta.mp4": 1185,
  "dragon-ball-z-funimation-faulconer-score::087 - The Ultimate Battle.mp4": 1137,
  "dragon-ball-z-funimation-faulconer-score::088 - Clash of the Super Powers.mp4": 1145,
  "dragon-ball-z-funimation-faulconer-score::089 - Frieza's Boast.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::090 - Bold and Fearless.mp4": 1157,
  "dragon-ball-z-funimation-faulconer-score::091 - Embodiment of Fire.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::092 - Trump Card.mp4": 1148,
  "dragon-ball-z-funimation-faulconer-score::093 - Keep the Chance Alive.mp4": 1169,
  "dragon-ball-z-funimation-faulconer-score::094 - Power of the Spirit.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::095 - Transformed at Last.mp4": 1186,
  "dragon-ball-z-funimation-faulconer-score::096 - Explosion of Anger.mp4": 1120,
  "dragon-ball-z-funimation-faulconer-score::097 - Namek's Destruction.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::098 - A Final Attack.mp4": 1178,
  "dragon-ball-z-funimation-faulconer-score::099 - Approaching Destruction.mp4": 1122,
  "dragon-ball-z-funimation-faulconer-score::100 - Gohan Returns.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::101 - The Last Wish.mp4": 1180,
  "dragon-ball-z-funimation-faulconer-score::102 - Duel on a Vanishing Planet.mp4": 1193,
  "dragon-ball-z-funimation-faulconer-score::103 - Pathos of Frieza.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::104 - Frieza Defeated!!.mp4": 1128,
  "dragon-ball-z-funimation-faulconer-score::105 - Mighty Blast of Rage.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::106 - Namek's Explosion... Goku's End.mp4": 1182,
  "dragon-ball-z-funimation-faulconer-score::107 - Goku's Alive!!.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::108 - The Heavens Tremble.mp4": 1154,
  "dragon-ball-z-funimation-faulconer-score::109 - Black Fog of Terror.mp4": 1149,
  "dragon-ball-z-funimation-faulconer-score::110 - Battle in Kami's Lookout.mp4": 1125,
  "dragon-ball-z-funimation-faulconer-score::111 - Fight With Piccolo.mp4": 1177,
  "dragon-ball-z-funimation-faulconer-score::112 - Call For Restoration.mp4": 1145,
  "dragon-ball-z-funimation-faulconer-score::113 - Suicidal Course.mp4": 1169,
  "dragon-ball-z-funimation-faulconer-score::114 - Extreme Measures.mp4": 1122,
  "dragon-ball-z-funimation-faulconer-score::115 - The World Awakens.mp4": 1185,
  "dragon-ball-z-funimation-faulconer-score::116 - Brief Chance for Victory.mp4": 1161,
  "dragon-ball-z-funimation-faulconer-score::117 - Krillin's Proposal.mp4": 1225,
  "dragon-ball-z-funimation-faulconer-score::118 - Frieza's Counterattack.mp4": 1227,
  "dragon-ball-z-funimation-faulconer-score::119 - The Mysterious Youth.mp4": 1177,
  "dragon-ball-z-funimation-faulconer-score::120 - Another Super Saiyan.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::121 - Welcome Back Goku.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::122 - Mystery Revealed.mp4": 1182,
  "dragon-ball-z-funimation-faulconer-score::123 - Goku's Special Technique.mp4": 1178,
  "dragon-ball-z-funimation-faulconer-score::124 - Z Warriors Prepare.mp4": 1173,
  "dragon-ball-z-funimation-faulconer-score::125 - Goku's Ordeal.mp4": 1178,
  "dragon-ball-z-funimation-faulconer-score::126 - The Androids Appear.mp4": 1173,
  "dragon-ball-z-funimation-faulconer-score::127 - A Handy Trick.mp4": 1145,
  "dragon-ball-z-funimation-faulconer-score::128 - Double Trouble for Goku.mp4": 1161,
  "dragon-ball-z-funimation-faulconer-score::129 - Upgrade to Super Saiyan.mp4": 1189,
  "dragon-ball-z-funimation-faulconer-score::130 - The Secret of Dr. Gero.mp4": 1169,
  "dragon-ball-z-funimation-faulconer-score::131 - More Androids!.mp4": 1154,
  "dragon-ball-z-funimation-faulconer-score::132 - Follow Dr. Gero.mp4": 1146,
  "dragon-ball-z-funimation-faulconer-score::133 - Nightmare Comes True.mp4": 1170,
  "dragon-ball-z-funimation-faulconer-score::134 - Goku's Assassin.mp4": 1180,
  "dragon-ball-z-funimation-faulconer-score::135 - Deadly Beauty.mp4": 1173,
  "dragon-ball-z-funimation-faulconer-score::136 - No Match for the Androids.mp4": 1097,
  "dragon-ball-z-funimation-faulconer-score::137 - Last Ditch Effort.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::138 - Closing In.mp4": 1173,
  "dragon-ball-z-funimation-faulconer-score::139 - Unwelcome Discovery.mp4": 1189,
  "dragon-ball-z-funimation-faulconer-score::140 - Seized with Fear.mp4": 1188,
  "dragon-ball-z-funimation-faulconer-score::141 - The Reunion.mp4": 1181,
  "dragon-ball-z-funimation-faulconer-score::142 - Borrowed Powers.mp4": 1137,
  "dragon-ball-z-funimation-faulconer-score::143 - His Name is Cell.mp4": 1149,
  "dragon-ball-z-funimation-faulconer-score::144 - Piccolo's Folly.mp4": 1152,
  "dragon-ball-z-funimation-faulconer-score::145 - Laboratory Basement.mp4": 1155,
  "dragon-ball-z-funimation-faulconer-score::146 - Our Hero Awakes.mp4": 1165,
  "dragon-ball-z-funimation-faulconer-score::147 - Time Chamber.mp4": 1177,
  "dragon-ball-z-funimation-faulconer-score::148 - The Monster is Coming.mp4": 1144,
  "dragon-ball-z-funimation-faulconer-score::149 - He's Here.mp4": 1165,
  "dragon-ball-z-funimation-faulconer-score::150 - Up to Piccolo.mp4": 1152,
  "dragon-ball-z-funimation-faulconer-score::151 - Silent Warrior.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::152 - Say Goodbye, 17.mp4": 1174,
  "dragon-ball-z-funimation-faulconer-score::153 - Sacrifice.mp4": 1149,
  "dragon-ball-z-funimation-faulconer-score::154 - Saiyans Emerge.mp4": 1145,
  "dragon-ball-z-funimation-faulconer-score::155 - Super Vegeta.mp4": 1158,
  "dragon-ball-z-funimation-faulconer-score::156 - Bow to The Prince.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::157 - Hour of Temptation.mp4": 1172,
  "dragon-ball-z-funimation-faulconer-score::158 - Krillin's Decision.mp4": 1153,
  "dragon-ball-z-funimation-faulconer-score::159 - The Last Defense.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::160 - Cell is Complete.mp4": 1180,
  "dragon-ball-z-funimation-faulconer-score::161 - Vegeta Must Pay.mp4": 1093,
  "dragon-ball-z-funimation-faulconer-score::162 - Trunks Ascends.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::163 - Saving Throw.mp4": 1153,
  "dragon-ball-z-funimation-faulconer-score::164 - Ghosts from Tomorrow.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::165 - The Cell Games.mp4": 1128,
  "dragon-ball-z-funimation-faulconer-score::166 - What is the Tournament.mp4": 1180,
  "dragon-ball-z-funimation-faulconer-score::167 - The Doomsday Broadcast.mp4": 1159,
  "dragon-ball-z-funimation-faulconer-score::168 - Meet Me In the Ring.mp4": 1209,
  "dragon-ball-z-funimation-faulconer-score::169 - No Worries Here.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::170 - A Girl Named Lime.mp4": 1177,
  "dragon-ball-z-funimation-faulconer-score::171 - Memories of Gohan.mp4": 1160,
  "dragon-ball-z-funimation-faulconer-score::172 - A New Guardian.mp4": 1180,
  "dragon-ball-z-funimation-faulconer-score::173 - Dende's Dragon.mp4": 1155,
  "dragon-ball-z-funimation-faulconer-score::174 - The Puzzle of General Tao.mp4": 1184,
  "dragon-ball-z-funimation-faulconer-score::175 - The Games Begin.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::176 - Losers Fight First.mp4": 1157,
  "dragon-ball-z-funimation-faulconer-score::177 - Goku vs. Cell.mp4": 1125,
  "dragon-ball-z-funimation-faulconer-score::178 - Cell's Bag of Tricks.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::179 - No More Rules.mp4": 1112,
  "dragon-ball-z-funimation-faulconer-score::180 - The Fight is Over.mp4": 1137,
  "dragon-ball-z-funimation-faulconer-score::181 - Faith in a Boy.mp4": 1157,
  "dragon-ball-z-funimation-faulconer-score::182 - Gohan's Plea.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::183 - Android Explosion.mp4": 1113,
  "dragon-ball-z-funimation-faulconer-score::184 - Cell Juniors Attack!.mp4": 1116,
  "dragon-ball-z-funimation-faulconer-score::185 - Awakening.mp4": 1104,
  "dragon-ball-z-funimation-faulconer-score::186 - The Unstoppable Gohan.mp4": 1132,
  "dragon-ball-z-funimation-faulconer-score::187 - Cell's Break Down.mp4": 1153,
  "dragon-ball-z-funimation-faulconer-score::188 - A Hero's Farewell.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::189 - Cell Returns!.mp4": 1113,
  "dragon-ball-z-funimation-faulconer-score::190 - The Horror Won't End.mp4": 1132,
  "dragon-ball-z-funimation-faulconer-score::191 - Save the World.mp4": 1157,
  "dragon-ball-z-funimation-faulconer-score::192 - Goku's Decision.mp4": 1184,
  "dragon-ball-z-funimation-faulconer-score::193 - One More Wish.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::194 - Free the Future.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::195 - Warriors of the Dead.mp4": 1133,
  "dragon-ball-z-funimation-faulconer-score::196 - Tournament Begins.mp4": 1168,
  "dragon-ball-z-funimation-faulconer-score::197 - Water Fight.mp4": 1160,
  "dragon-ball-z-funimation-faulconer-score::198 - Final Round.mp4": 1120,
  "dragon-ball-z-funimation-faulconer-score::199 - Goku vs. Pikkon.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::200 - Gohan Goes to High School.mp4": 1072,
  "dragon-ball-z-funimation-faulconer-score::201 - I am Saiyaman.mp4": 1153,
  "dragon-ball-z-funimation-faulconer-score::202 - Gohan's First Date.mp4": 1193,
  "dragon-ball-z-funimation-faulconer-score::203 - Rescue Videl.mp4": 1109,
  "dragon-ball-z-funimation-faulconer-score::204 - Blackmail.mp4": 1169,
  "dragon-ball-z-funimation-faulconer-score::205 - I'll Fight Too!.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::206 - The Newest Super Saiyan.mp4": 1148,
  "dragon-ball-z-funimation-faulconer-score::207 - Take Flight, Videl.mp4": 1174,
  "dragon-ball-z-funimation-faulconer-score::208 - Gather for the Tournament.mp4": 1166,
  "dragon-ball-z-funimation-faulconer-score::209 - Camera Shy.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::210 - The World Tournament.mp4": 1128,
  "dragon-ball-z-funimation-faulconer-score::211 - Trunks vs. Goten.mp4": 1156,
  "dragon-ball-z-funimation-faulconer-score::212 - Best of the Boys.mp4": 1114,
  "dragon-ball-z-funimation-faulconer-score::213 - Big Trouble, Little Trunks.mp4": 1156,
  "dragon-ball-z-funimation-faulconer-score::214 - Who Will Fight Who.mp4": 1175,
  "dragon-ball-z-funimation-faulconer-score::215 - Forfeit of Piccolo.mp4": 1166,
  "dragon-ball-z-funimation-faulconer-score::216 - A Dark and Secret Power.mp4": 1136,
  "dragon-ball-z-funimation-faulconer-score::217 - Videl Is Crushed.mp4": 1159,
  "dragon-ball-z-funimation-faulconer-score::218 - Identities Revealed.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::219 - Energy Drain.mp4": 1175,
  "dragon-ball-z-funimation-faulconer-score::220 - The Wizard's Curse.mp4": 1185,
  "dragon-ball-z-funimation-faulconer-score::221 - King of the Demons.mp4": 1158,
  "dragon-ball-z-funimation-faulconer-score::222 - Vegeta Attacks.mp4": 1112,
  "dragon-ball-z-funimation-faulconer-score::223 - Next Up, Goku.mp4": 1154,
  "dragon-ball-z-funimation-faulconer-score::224 - Battle Supreme.mp4": 1144,
  "dragon-ball-z-funimation-faulconer-score::225 - Eighteen Unmasks.mp4": 1134,
  "dragon-ball-z-funimation-faulconer-score::226 - Pay to Win.mp4": 1144,
  "dragon-ball-z-funimation-faulconer-score::227 - Heart of a Villain.mp4": 1133,
  "dragon-ball-z-funimation-faulconer-score::228 - The Dark Prince Returns.mp4": 1166,
  "dragon-ball-z-funimation-faulconer-score::229 - Vegeta's Pride.mp4": 1140,
  "dragon-ball-z-funimation-faulconer-score::230 - The Long Awaited Fight.mp4": 1136,
  "dragon-ball-z-funimation-faulconer-score::231 - Magic Ball of Buu.mp4": 1187,
  "dragon-ball-z-funimation-faulconer-score::232 - Buu is Hatched.mp4": 1146,
  "dragon-ball-z-funimation-faulconer-score::233 - The Losses Begin.mp4": 1122,
  "dragon-ball-z-funimation-faulconer-score::234 - The Terror of Mr. Buu.mp4": 1135,
  "dragon-ball-z-funimation-faulconer-score::235 - Meal Time.mp4": 1177,
  "dragon-ball-z-funimation-faulconer-score::236 - The Warrior's Decision.mp4": 1114,
  "dragon-ball-z-funimation-faulconer-score::237 - Final Atonement.mp4": 1116,
  "dragon-ball-z-funimation-faulconer-score::238 - Evil Lives On.mp4": 1155,
  "dragon-ball-z-funimation-faulconer-score::239 - Find the Dragon Balls.mp4": 1142,
  "dragon-ball-z-funimation-faulconer-score::240 - Revival.mp4": 1156,
  "dragon-ball-z-funimation-faulconer-score::241 - Global Announcement.mp4": 1148,
  "dragon-ball-z-funimation-faulconer-score::242 - Learn to Fuse!.mp4": 1173,
  "dragon-ball-z-funimation-faulconer-score::243 - The Z Sword.mp4": 1134,
  "dragon-ball-z-funimation-faulconer-score::244 - Race to Capsule Corp..mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::245 - Super Saiyan 3!.mp4": 1130,
  "dragon-ball-z-funimation-faulconer-score::246 - Buu's Mutiny.mp4": 1099,
  "dragon-ball-z-funimation-faulconer-score::247 - The Fusion Dance.mp4": 1128,
  "dragon-ball-z-funimation-faulconer-score::248 - Goku's Time Is Up.mp4": 1164,
  "dragon-ball-z-funimation-faulconer-score::249 - Return to Other World.mp4": 1156,
  "dragon-ball-z-funimation-faulconer-score::250 - Out from the Broken Sword.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::251 - Gotenks Is Born.mp4": 1174,
  "dragon-ball-z-funimation-faulconer-score::252 - Unlikely Friendship.mp4": 1130,
  "dragon-ball-z-funimation-faulconer-score::253 - I Kill No More.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::254 - The Evil of Men.mp4": 1163,
  "dragon-ball-z-funimation-faulconer-score::255 - Buu Against Buu.mp4": 1146,
  "dragon-ball-z-funimation-faulconer-score::256 - Empty Planet.mp4": 1141,
  "dragon-ball-z-funimation-faulconer-score::257 - Time Struggle.mp4": 1163,
  "dragon-ball-z-funimation-faulconer-score::258 - Super Moves of Gotenks.mp4": 1166,
  "dragon-ball-z-funimation-faulconer-score::259 - Trapped in Forever.mp4": 1120,
  "dragon-ball-z-funimation-faulconer-score::260 - Feeding Frenzy.mp4": 1175,
  "dragon-ball-z-funimation-faulconer-score::261 - Gotenks is Awesome!.mp4": 1127,
  "dragon-ball-z-funimation-faulconer-score::262 - Unlucky Break.mp4": 1146,
  "dragon-ball-z-funimation-faulconer-score::263 - A Whole New Gohan.mp4": 1148,
  "dragon-ball-z-funimation-faulconer-score::264 - Search For Survivors.mp4": 1165,
  "dragon-ball-z-funimation-faulconer-score::265 - Majin Buu Transforms.mp4": 1150,
  "dragon-ball-z-funimation-faulconer-score::266 - The Old Kai's Weapon.mp4": 1117,
  "dragon-ball-z-funimation-faulconer-score::267 - Ready to Fuse.mp4": 1147,
  "dragon-ball-z-funimation-faulconer-score::268 - Union of Rivals.mp4": 1128,
  "dragon-ball-z-funimation-faulconer-score::269 - Meet Vegito.mp4": 1150,
  "dragon-ball-z-funimation-faulconer-score::270 - Rip in the Universe.mp4": 1148,
  "dragon-ball-z-funimation-faulconer-score::271 - Vegito... Downsized.mp4": 1120,
  "dragon-ball-z-funimation-faulconer-score::272 - The Incredible Fighting Candy.mp4": 1094,
  "dragon-ball-z-funimation-faulconer-score::273 - The Innards of Buu.mp4": 1170,
  "dragon-ball-z-funimation-faulconer-score::274 - Mind Trap.mp4": 1144,
  "dragon-ball-z-funimation-faulconer-score::275 - Deadly Vision.mp4": 1134,
  "dragon-ball-z-funimation-faulconer-score::276 - Evil Kid Buu!.mp4": 1111,
  "dragon-ball-z-funimation-faulconer-score::277 - End of Earth.mp4": 1116,
  "dragon-ball-z-funimation-faulconer-score::278 - True Saiyans Fight Alone.mp4": 1160,
  "dragon-ball-z-funimation-faulconer-score::279 - Battle for the Universe Begins.mp4": 1195,
  "dragon-ball-z-funimation-faulconer-score::280 - Vegeta's Respect.mp4": 1183,
  "dragon-ball-z-funimation-faulconer-score::281 - Minute of Desperation.mp4": 1169,
  "dragon-ball-z-funimation-faulconer-score::282 - Old Buu Emerges.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::283 - Earth Reborn.mp4": 1169,
  "dragon-ball-z-funimation-faulconer-score::284 - Call to Action.mp4": 1149,
  "dragon-ball-z-funimation-faulconer-score::285 - People of Earth Unite.mp4": 1167,
  "dragon-ball-z-funimation-faulconer-score::286 - Spirit Bomb Triumphant.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::287 - Celebrations with Majin Buu.mp4": 1168,
  "dragon-ball-z-funimation-faulconer-score::288 - He's Always Late.mp4": 1159,
  "dragon-ball-z-funimation-faulconer-score::289 - Granddaughter Pan.mp4": 1176,
  "dragon-ball-z-funimation-faulconer-score::290 - Buu's Reincarnation.mp4": 1196,
  "dragon-ball-z-funimation-faulconer-score::291 - Goku's Next Journey.mp4": 1182,
},
};
