window.SHOW = {
  id: "DragonBallSuper",
  title: "Dragon Ball Super",
  art: "DragonBallSuper.jpg",
  storageProgressKey: "dragonballsuper-progress",
  storageSettingsKey: "dragonballsuper-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E01 - A Peacetime Reward: Who Gets the 100,000,000 Zeni?!", 
    "5DargonBallSuper/Dragon Ball Super 01.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E02 - To the Promised Resort! Vegeta Takes a Family Trip!", 
    "5DargonBallSuper/Dragon Ball Super 02.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E03 - Where Does the Dream Pick Up? Find the Super Saiyan God!", 
    "5DargonBallSuper/Dragon Ball Super 03.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E04 - Bid for the Dragon Balls! Pilaf and Crew's Impossible Mission!", 
    "5DargonBallSuper/Dragon Ball Super 04.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E05 - Showdown on King Kai's World! Goku vs. Beerus the Destroyer!", 
    "5DargonBallSuper/Dragon Ball Super 05.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E06 - Don't Anger the Destroyer! A Heart-Pounding Birthday Party", 
    "5DargonBallSuper/Dragon Ball Super 06.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E07 - How Dare You Do That To My Bulma! Vegeta's Metamorphosis of Fury?", 
    "5DargonBallSuper/Dragon Ball Super 07.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E08 - Goku Makes an Entrance! A Last Chance from Lord Beerus?", 
    "5DargonBallSuper/Dragon Ball Super 08.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E09 - Thanks For Waiting, Lord Beerus! A Super Saiyan God is Born At Last!", 
    "5DargonBallSuper/Dragon Ball Super 09.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E10 - Show Us, Goku! The Power of a Super Saiyan God!", 
    "5DargonBallSuper/Dragon Ball Super 10.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E11 - Let's Keep Going, Lord Beerus! The Battle of Gods!", 
    "5DargonBallSuper/Dragon Ball Super 11.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E12 - The Universe Will Shatter? Clash! Destroyer vs. Super Saiyan God!", 
    "5DargonBallSuper/Dragon Ball Super 12.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E13 - Goku, Surpass Super Saiyan God!", 
    "5DargonBallSuper/Dragon Ball Super 13.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E14 - This is All the Power I've Got! A Settlement Between Gods", 
    "5DargonBallSuper/Dragon Ball Super 14.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E15 - Valiant Mr. Satan, Work a Miracle! A Challenge from Outer Space!", 
    "5DargonBallSuper/Dragon Ball Super 15.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E16 - Vegeta Becomes a Student?! Win Over Whis!", 
    "5DargonBallSuper/Dragon Ball Super 16.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E17 - Pan is Born! And Goku Goes on a Training Journey?!", 
    "5DargonBallSuper/Dragon Ball Super 17.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S01E18 - I'm Here, Too! Training Commences on Beerus' World", 
    "5DargonBallSuper/Dragon Ball Super 18.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E01 - Despair Redux! The Return of the Evil Emperor, Frieza!", 
    "5DargonBallSuper/Dragon Ball Super 19.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E02 - A Warning from Jaco! Frieza and 1,000 Soldiers Close In", 
    "5DargonBallSuper/Dragon Ball Super 20.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E03 - The Start of Vengeance! The Frieza Force's Malice Strikes Gohan!", 
    "5DargonBallSuper/Dragon Ball Super 21.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E04 - Change! An Unexpected Return! His Name is Ginyu!!", 
    "5DargonBallSuper/Dragon Ball Super 22.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E05 - Earth! Gohan! Both on the Ropes! Hurry and Get Here, Goku!!", 
    "5DargonBallSuper/Dragon Ball Super 23.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E06 - Clash! Frieza vs. Goku! This is the Result of My Training!", 
    "5DargonBallSuper/Dragon Ball Super 24.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E07 - A Full-Throttle Battle! The Vengeful Golden Frieza", 
    "5DargonBallSuper/Dragon Ball Super 25.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E08 - A Chance Appears in a Tight Spot! Launch a Counteroffensive, Goku!", 
    "5DargonBallSuper/Dragon Ball Super 26.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S02E09 - The Earth Explodes? A Decisive Kamehameha!", 
    "5DargonBallSuper/Dragon Ball Super 27.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E01 - The 6th Universe's Destroyer! His Name is Champa!", 
    "5DargonBallSuper/Dragon Ball Super 28.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E02 - Combat Matches Are a Go! The Captain Is Someone Stronger Than Goku", 
    "5DargonBallSuper/Dragon Ball Super 29.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E03 - A Run-Through For the Competition! Who Are the Last Two Members?", 
    "5DargonBallSuper/Dragon Ball Super 30.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E04 - Off to See Master Zuno! Find Out Where the Super Dragon Balls Are!", 
    "5DargonBallSuper/Dragon Ball Super 31.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E05 - The Matches Begin! We're All Off to the Planet with No Name!", 
    "5DargonBallSuper/Dragon Ball Super 32.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E06 - Surprise, 6th Universe! This is Super Saiyan Goku!", 
    "5DargonBallSuper/Dragon Ball Super 33.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E07 - Piccolo vs Frost! Stake it All on the Special Beam Cannon!", 
    "5DargonBallSuper/Dragon Ball Super 34.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S03E08 - Turn Your Anger into Strength! Vegeta's Full-Bore Battle", 
    "5DargonBallSuper/Dragon Ball Super 35.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E21 - With New Hope in His Heart - Farewell, Trunks", 
    "5DargonBallSuper/Dragon Ball Super 067 With New Hope in His Heart - Farewell, Trunks.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E22 - Come Forth, Shenron! Whose Wish Will Be Granted?", 
    "5DargonBallSuper/Dragon Ball Super 068 Come Forth, Shenron! - Whose Wish Will Be Granted.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E23 - Goku vs. Arale! An Off-the-Wall Battle Spells the End of the Earth?", 
    "5DargonBallSuper/Dragon Ball Super 069 Goku vs. Arale! - An Off-the-Wall Battle Spells the End of the Earth.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E24 - A Challenge From Champa! This Time, a Baseball Game!", 
    "5DargonBallSuper/Dragon Ball Super 070 A Challenge From Champa! - This Time, a Baseball Game!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E25 - Goku Dies! An Assassination That Must Be Executed!", 
    "5DargonBallSuper/Dragon Ball Super 071 Goku Dies! - An Assassination That Must Be Executed.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E26 - Will He Strike Back? The Unseen Killing Technique!", 
    "5DargonBallSuper/Dragon Ball Super 072 Will He Strike Back - The Unseen Killing Technique!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E27 - Gohan's Plight! The Preposterous Great Saiyaman Film Adaptation?!", 
    "5DargonBallSuper/Dragon Ball Super 073 Gohan's Plight! - The Preposterous Great Saiyaman Film Adaptation!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E28 - For My Beloved Ones! The Indomitable Great Saiyaman!", 
    "5DargonBallSuper/Dragon Ball Super 074 For My Beloved Ones! - The Indomitable Great Saiyaman!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E29 - Goku and Krillin! Back to the Old Familiar Training Ground!", 
    "5DargonBallSuper/Dragon Ball Super 075 Goku and Krillin - Back to the Old Familiar Training Ground!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S04E30 - Conquer the Terrifying Foes! Krillin's Fighting Spirit Rebounds!", 
    "5DargonBallSuper/Dragon Ball Super 076 Conquer the Terrifying Foes! - Krillin's Fighting Spirit Rebounds!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E01 - Let's Do It, Grand Zeno! The Universes' Best Tournament!!", 
    "5DargonBallSuper/Dragon Ball Super 077 Let's Do It, Grand Zeno! - The Universes' Best Tournament!!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E02 - Even the Universes' Gods are Appalled?! The Lose-and-Perish Tournament of Power", 
    "5DargonBallSuper/Dragon Ball Super 078 Even the Universes' Gods are Appalled! - The Lose-and-Perish Tournament of Power.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E03 - The 9th Universe's Kicking Basil vs. the 7th Universe's Majin Buu!!", 
    "5DargonBallSuper/Dragon Ball Super 079 The 9th Universe's Kicking Basil - vs - The 7th Universe's Majin Buu!!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E04 - Awaken Your Dormant Fighting Spirit! Gohan's Fight!", 
    "5DargonBallSuper/Dragon Ball Super 080 Awaken Your Dormant Fighting Spirit! - Gohan's Fight!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E05 - Bergamo the Crusher vs. Goku! Whose Strength Reaches the Wild Blue Yonder?", 
    "5DargonBallSuper/Dragon Ball Super 081 Bergamo the Crusher vs. Goku! - Whose Strength Reaches the Wild Blue Yonder.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E06 - Goku Must Pay! The Warrior of Justice Top Barges In!", 
    "5DargonBallSuper/Dragon Ball Super 082 Goku Must Pay - The Warrior of Justice Top Barges In!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E07 - Field The All-7th-Universe Team! Who Are The Mighty Ten?", 
    "5DargonBallSuper/Dragon Ball Super 083 Field The All-7th-Universe Team! - Who Are The Mighty Ten.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E08 - Goku the Talent Scout Recruit Krillin and Android 18", 
    "5DargonBallSuper/Dragon Ball Super 084 Goku the Talent Scout - Recruit Krillin and Android 18.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E09 - The Universes Go Into Action - Each With Their Own Motives", 
    "5DargonBallSuper/Dragon Ball Super 085 The Universes Go Into Action - Each With Their Own Motives.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E10 - First Time Exchanging Blows! Android 17 vs. Goku!!", 
    "5DargonBallSuper/Dragon Ball Super 086 First Time Exchanging Blows! - Android 17 vs. Goku!!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E11 - Hunt the Poaching Ring! Goku and Android 17's Joint Struggle!", 
    "5DargonBallSuper/Dragon Ball Super 087 Hunt the Poaching Ring! - Goku and Android 17's Joint Struggle!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E12 - Gohan and Piccolo Master and Pupil Clash in Max Training!", 
    "5DargonBallSuper/Dragon Ball Super 088 Gohan and Piccolo - Master and Pupil Clash in Max Training!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E13 - A Mysterious Beauty Appears! The Enigma of the Tien Shin-Style Dojo?", 
    "5DargonBallSuper/Dragon Ball Super 089 A Mysterious Beauty Appears! - The Enigma of the Tien Shin-Style Dojo.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E14 - Staring Down the Wall to be Overcome Goku vs. Gohan", 
    "5DargonBallSuper/Dragon Ball Super 090 Staring Down the Wall to be Overcome! - Goku vs. Gohan.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E15 - Which Universe Will Win Their Place? The Mighty Warriors Gradually Assemble!", 
    "5DargonBallSuper/Dragon Ball Super 091 Which Universe Will Win Their Place - The Mighty Warriors Gradually Assemble!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E16 - A State of Emergency! Failure to Reach Ten Members!!", 
    "5DargonBallSuper/Dragon Ball Super 092 A State of Emergency! - Failure to Reach Ten Members!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E17 - You're Our Tenth Warrior! Goku Approaches Frieza!!", 
    "5DargonBallSuper/Dragon Ball Super 093 You're Our Tenth Warrior! - Goku Approaches Frieza!!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E18 - The Evil Emperor Returns! A Reception from Mysterious Assassins?", 
    "5DargonBallSuper/Dragon Ball Super 094 The Evil Emperor Returns! - A Reception from Mysterious Assassins.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E19 - Most Heinous! Most Evil! Frieza's Wild Rampage!", 
    "5DargonBallSuper/Dragon Ball Super 095 Most Heinous! Most Evil! - Frieza's Wild Rampage!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E20 - The Time Has Come! To the Null Realm with the Universes on the Line!", 
    "5DargonBallSuper/Dragon Ball Super 096 The Time Has Come! - To the Null Realm with the Universes on the Line!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E21 - Survive! The Tournament of Power Begins at Last!!", 
    "5DargonBallSuper/Dragon Ball Super 097 Survive! - The Tournament of Power Begins at Last!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E22 - Ah, the Uncertainty! A Universe Despairs!", 
    "5DargonBallSuper/Dragon Ball Super 098 Ah, the Uncertainty! - A Universe Despairs!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E23 - Show Them! Krillin's Underlying Strength!", 
    "5DargonBallSuper/Dragon Ball Super 099 Show Them! - Krillin's Underlying Strength!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E24 - Rampage! A Crazed Warrior's Savagery Awakens!", 
    "5DargonBallSuper/Dragon Ball Super 100 Rampage! - A Crazed Warrior's Savagery Awakens!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E25 - Warriors of Justice Close In! The Pride Troopers!", 
    "5DargonBallSuper/Dragon Ball Super 101 Warriors of Justice Close In! - The Pride Troopers!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E26 - The Power of Love Explodes? The 2nd Universe's Witchy Warriors!", 
    "5DargonBallSuper/Dragon Ball Super 102 The Power of Love Explodes - The 2nd Universe's Witchy Warriors!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E27 - Gohan, Get Ruthless! Showdown with the 10th Universe!", 
    "5DargonBallSuper/Dragon Ball Super 103 Gohan, Get Ruthless! - Showdown with the 10th Universe!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E28 - A Transcendent Light-Speed Battle Erupts! Goku and Hit's United Front!", 
    "5DargonBallSuper/Dragon Ball Super 104 A Transcendent Light-Speed Battle Erupts! - Goku and Hit's United Front!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E29 - A Valiant Fight! Master Roshi's Blaze of Glory!", 
    "5DargonBallSuper/Dragon Ball Super 105 A Valiant Fight! - Master Roshi's Blaze of Glory!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E30 - Find them Out! Deathmatch with a Furtive Attacker!", 
    "5DargonBallSuper/Dragon Ball Super 106 Find them Out! - Deathmatch with a Furtive Attacker!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E31 - Revenge", 
    "5DargonBallSuper/Dragon Ball Super 107 Revenge F! - A Cunning Trap is Set.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E32 - Frieza and Frost! A Mutual Malevolence?", 
    "5DargonBallSuper/Dragon Ball Super 108 Frieza and Frost! - A Mutual Malevolence.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E33 - The Mightiest Enemy Zeroes in on Goku! Launch the Knockout Spirit Bomb Now!", 
    "5DargonBallSuper/Dragon Ball Super 109 The Mightiest Enemy Zeroes in on Goku! - Launch the Knockout Spirit Bomb Now!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E34 - Goku Enkindled! The Awakened One's New Ultra Instinct!", 
    "5DargonBallSuper/Dragon Ball Super 110 Goku Enkindled! - The Awakened One's New Ultra Instinct!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E35 - An Extra-Dimensional Ultimate Battle! Hit vs. Jiren!", 
    "5DargonBallSuper/Dragon Ball Super 111 An Extra-Dimensional Ultimate Battle! - Hit vs. Jiren!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E36 - A Saiyan Oath! Vegeta's Resolve!", 
    "5DargonBallSuper/Dragon Ball Super 112 A Saiyan Oath! - Vegeta's Resolve!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E37 - With Great Joy! The Fighting Freak Saiyans' Battle Rejoined!", 
    "5DargonBallSuper/Dragon Ball Super 113 With Great Joy! - The Fighting Freak Saiyans' Battle Rejoined!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E38 - Bloodcurdling! The Explosive Birth of a New Super Warrior!", 
    "5DargonBallSuper/Dragon Ball Super 114 Bloodcurdling! - The Explosive Birth of a New Super Warrior!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E39 - Goku vs. Kefla! Super Saiyan Blue Beaten?!", 
    "5DargonBallSuper/Dragon Ball Super 115 Goku vs. Kefla! - Super Saiyan Blue Beaten.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E40 - Signs of a Turnabout! The Autonomous Ultra Instinct Erupts!", 
    "5DargonBallSuper/Dragon Ball Super 116 Signs of a Turnabout! - The Autonomous Ultra Instinct Erupts!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E41 - Showdown of Love! The Androids vs the 2nd Universe!", 
    "5DargonBallSuper/Dragon Ball Super 117 Showdown of Love! - The Androids vs the 2nd Universe!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E42 - Accelerating Tragedy - Vanishing Universes", 
    "5DargonBallSuper/Dragon Ball Super 118 Accelerating Tragedy - Vanishing Universes.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E43 - Unavoidable? The Ferocity of a Stealth Attack!", 
    "5DargonBallSuper/Dragon Ball Super 119 Unavoidable - The Ferocity of a Stealth Attack!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E44 - A Perfect Survival Strategy! The 3rd Universe's Menacing Assassin!", 
    "5DargonBallSuper/Dragon Ball Super 120 A Perfect Survival Strategy! - The 3rd Universe's Menacing Assassin!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E45 - All-Out War! The Ultimate Four-Fold Union vs. the 7th Universe's Total Offensive!", 
    "5DargonBallSuper/Dragon Ball Super 121 All-Out War! - The Ultimate Four-Fold Union vs. the 7th Universe's Total Offensive!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E46 - With His Pride on the Line! Vegeta's Challenge to Be the Strongest!", 
    "5DargonBallSuper/Dragon Ball Super 122 With His Pride on the Line! - Vegeta's Challenge to Be the Strongest!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E47 - Body, Soul and Power Unleashed! Goku and Vegeta!", 
    "5DargonBallSuper/Dragon Ball Super 123 Body, Soul and Power Unleashed! - Goku and Vegeta!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E48 - A Storm-and-Stress Assault! Gohan's Last Stand!", 
    "5DargonBallSuper/Dragon Ball Super 124 A Storm-and-Stress Assault! - Gohan's Last Stand!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E49 - A Commanding Presence! The Advent of Top the Destroyer!", 
    "5DargonBallSuper/Dragon Ball Super 125 A Commanding Presence! - The Advent of Top the Destroyer!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E50 - Surpass Even a God! Vegeta's Sacrifice Strike!", 
    "5DargonBallSuper/Dragon Ball Super 126 Surpass Even a God! - Vegeta's Sacrifice Strike!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E51 - The Approaching Wall! A Hopeful Final Barrier!", 
    "5DargonBallSuper/Dragon Ball Super 127 The Approaching Wall! - A Hopeful Final Barrier.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E52 - To the Noble, Proud End! Vegeta Falls!", 
    "5DargonBallSuper/Dragon Ball Super 128 To the Noble, Proud End! - Vegeta Falls!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E53 - A Transcendent Limit Break! Autonomous Ultra Instinct Mastered!", 
    "5DargonBallSuper/Dragon Ball Super 129 A Transcendent Limit Break! - Autonomous Ultra Instinct Mastered!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E54 - The Greatest Showdown of All Time! The Ultimate Survival Battle!", 
    "5DargonBallSuper/Dragon Ball Super 130 The Greatest Showdown of All Time! - The Ultimate Survival Battle!.mp4"],
  ['dragonballsuperdubb', "DRAGON BALL SUPER - S05E55 - A Miraculous Conclusion! Farewell, Goku! Until We Meet Again!", 
    "5DargonBallSuper/Dragon Ball Super 131 The Miraculous Conclusion! - Farewell Goku! Until We Meet Again!.mp4"],
],
  durations: {
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 01.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 02.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 03.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 04.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 05.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 06.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 07.mp4": 1398,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 08.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 09.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 10.mp4": 1398,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 11.mp4": 1407,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 12.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 13.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 14.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 15.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 16.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 17.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 18.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 19.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 20.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 21.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 22.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 23.mp4": 1407,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 24.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 25.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 26.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 27.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 28.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 29.mp4": 1407,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 30.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 31.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 32.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 33.mp4": 1392,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 34.mp4": 1387,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 35.mp4": 1398,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 067 With New Hope in His Heart - Farewell, Trunks.mp4": 1364,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 068 Come Forth, Shenron! - Whose Wish Will Be Granted.mp4": 1364,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 069 Goku vs. Arale! - An Off-the-Wall Battle Spells the End of the Earth.mp4": 1364,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 070 A Challenge From Champa! - This Time, a Baseball Game!.mp4": 1364,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 071 Goku Dies! - An Assassination That Must Be Executed.mp4": 1364,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 072 Will He Strike Back - The Unseen Killing Technique!.mp4": 1364,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 073 Gohan's Plight! - The Preposterous Great Saiyaman Film Adaptation!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 074 For My Beloved Ones! - The Indomitable Great Saiyaman!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 075 Goku and Krillin - Back to the Old Familiar Training Ground!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 076 Conquer the Terrifying Foes! - Krillin's Fighting Spirit Rebounds!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 077 Let's Do It, Grand Zeno! - The Universes' Best Tournament!!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 078 Even the Universes' Gods are Appalled! - The Lose-and-Perish Tournament of Power.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 079 The 9th Universe's Kicking Basil - vs - The 7th Universe's Majin Buu!!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 080 Awaken Your Dormant Fighting Spirit! - Gohan's Fight!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 081 Bergamo the Crusher vs. Goku! - Whose Strength Reaches the Wild Blue Yonder.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 082 Goku Must Pay - The Warrior of Justice Top Barges In!.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 083 Field The All-7th-Universe Team! - Who Are The Mighty Ten.mp4": 1368,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 084 Goku the Talent Scout - Recruit Krillin and Android 18.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 085 The Universes Go Into Action - Each With Their Own Motives.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 086 First Time Exchanging Blows! - Android 17 vs. Goku!!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 087 Hunt the Poaching Ring! - Goku and Android 17's Joint Struggle!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 088 Gohan and Piccolo - Master and Pupil Clash in Max Training!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 089 A Mysterious Beauty Appears! - The Enigma of the Tien Shin-Style Dojo.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 090 Staring Down the Wall to be Overcome! - Goku vs. Gohan.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 091 Which Universe Will Win Their Place - The Mighty Warriors Gradually Assemble!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 092 A State of Emergency! - Failure to Reach Ten Members!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 093 You're Our Tenth Warrior! - Goku Approaches Frieza!!.mp4": 1359,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 094 The Evil Emperor Returns! - A Reception from Mysterious Assassins.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 095 Most Heinous! Most Evil! - Frieza's Wild Rampage!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 096 The Time Has Come! - To the Null Realm with the Universes on the Line!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 097 Survive! - The Tournament of Power Begins at Last!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 098 Ah, the Uncertainty! - A Universe Despairs!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 099 Show Them! - Krillin's Underlying Strength!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 100 Rampage! - A Crazed Warrior's Savagery Awakens!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 101 Warriors of Justice Close In! - The Pride Troopers!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 102 The Power of Love Explodes - The 2nd Universe's Witchy Warriors!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 103 Gohan, Get Ruthless! - Showdown with the 10th Universe!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 104 A Transcendent Light-Speed Battle Erupts! - Goku and Hit's United Front!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 105 A Valiant Fight! - Master Roshi's Blaze of Glory!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 106 Find them Out! - Deathmatch with a Furtive Attacker!.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 107 Revenge F! - A Cunning Trap is Set.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 108 Frieza and Frost! - A Mutual Malevolence.mp4": 1363,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 109 The Mightiest Enemy Zeroes in on Goku! - Launch the Knockout Spirit Bomb Now!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 110 Goku Enkindled! - The Awakened One's New Ultra Instinct!.mp4": 1355,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 111 An Extra-Dimensional Ultimate Battle! - Hit vs. Jiren!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 112 A Saiyan Oath! - Vegeta's Resolve!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 113 With Great Joy! - The Fighting Freak Saiyans' Battle Rejoined!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 114 Bloodcurdling! - The Explosive Birth of a New Super Warrior!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 115 Goku vs. Kefla! - Super Saiyan Blue Beaten.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 116 Signs of a Turnabout! - The Autonomous Ultra Instinct Erupts!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 117 Showdown of Love! - The Androids vs the 2nd Universe!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 118 Accelerating Tragedy - Vanishing Universes.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 119 Unavoidable - The Ferocity of a Stealth Attack!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 120 A Perfect Survival Strategy! - The 3rd Universe's Menacing Assassin!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 121 All-Out War! - The Ultimate Four-Fold Union vs. the 7th Universe's Total Offensive!.mp4": 1356,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 122 With His Pride on the Line! - Vegeta's Challenge to Be the Strongest!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 123 Body, Soul and Power Unleashed! - Goku and Vegeta!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 124 A Storm-and-Stress Assault! - Gohan's Last Stand!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 125 A Commanding Presence! - The Advent of Top the Destroyer!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 126 Surpass Even a God! - Vegeta's Sacrifice Strike!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 127 The Approaching Wall! - A Hopeful Final Barrier.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 128 To the Noble, Proud End! - Vegeta Falls!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 129 A Transcendent Limit Break! - Autonomous Ultra Instinct Mastered!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 130 The Greatest Showdown of All Time! - The Ultimate Survival Battle!.mp4": 1348,
  "dragonballsuperdubb::5DargonBallSuper/Dragon Ball Super 131 The Miraculous Conclusion! - Farewell Goku! Until We Meet Again!.mp4": 1433,
},
};
