window.SHOW = {
  id: "AlfredHitchcockPresents",
  title: "Alfred Hitchcock Presents",
  storageProgressKey: "alfredhitchcockpresents-progress",
  storageSettingsKey: "alfredhitchcockpresents-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E01",
    "alfred hitchcock presents-s1e1-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E02",
    "alfred hitchcock presents-s1e2-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E03",
    "alfred hitchcock presents-s1e3-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E04",
    "alfred hitchcock presents-s1e4-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E05",
    "alfred hitchcock presents-s1e5-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E06",
    "alfred hitchcock presents-s1e6-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E07",
    "alfred hitchcock presents-s1e7-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E08",
    "alfred hitchcock presents-s1e8-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E10",
    "alfred hitchcock presents-s1e10-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E11",
    "alfred hitchcock presents-s1e11-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E12",
    "alfred hitchcock presents-s1e12-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E13",
    "alfred hitchcock presents-s1e13-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E14",
    "alfred hitchcock presents-s1e14-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E15",
    "alfred hitchcock presents-s1e15-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E16",
    "alfred hitchcock presents-s1e16-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E17",
    "alfred hitchcock presents-s1e17-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E18",
    "alfred hitchcock presents-s1e18-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E19",
    "alfred hitchcock presents-s1e19-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E20",
    "alfred hitchcock presents-s1e20-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E21",
    "alfred hitchcock presents-s1e21-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E22",
    "alfred hitchcock presents-s1e22-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E23",
    "alfred hitchcock presents-s1e23-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E24",
    "alfred hitchcock presents-s1e24-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E25",
    "alfred hitchcock presents-s1e25-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E26",
    "alfred hitchcock presents-s1e26-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E27",
    "alfred hitchcock presents-s1e27-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E28",
    "alfred hitchcock presents-s1e28-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E29",
    "alfred hitchcock presents-s1e29-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E30",
    "alfred hitchcock presents-s1e30-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E31",
    "alfred hitchcock presents-s1e31-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E32",
    "alfred hitchcock presents-s1e32-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E33",
    "alfred hitchcock presents-s1e33-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E34",
    "alfred hitchcock presents-s1e34-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E35",
    "alfred hitchcock presents-s1e35-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E36",
    "alfred hitchcock presents-s1e36-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E37",
    "alfred hitchcock presents-s1e37-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E38",
    "alfred hitchcock presents-s1e38-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-1e-1-colorized-720p-hd', "ALFRED HITCHCOCK PRESENTS - S01E39",
    "alfred hitchcock presents-s1e39-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E01",
    "alfred hitchcock presents-s2e1-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E02",
    "alfred hitchcock presents-s2e2-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E03",
    "alfred hitchcock presents-s2e3-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E04",
    "alfred hitchcock presents-s2e4-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E05",
    "alfred hitchcock presents-s2e5-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E06",
    "alfred hitchcock presents-s2e6-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E07",
    "alfred hitchcock presents-s2e7-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E08",
    "alfred hitchcock presents-s2e8-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E09",
    "alfred hitchcock presents-s2e9-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E10",
    "alfred hitchcock presents-s2e10-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E11",
    "alfred hitchcock presents-s2e11-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E12",
    "alfred hitchcock presents-s2e12-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E13",
    "alfred hitchcock presents-s2e13-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E14",
    "alfred hitchcock presents-s2e14-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E15",
    "alfred hitchcock presents-s2e15-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E16",
    "alfred hitchcock presents-s2e16-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E17",
    "alfred hitchcock presents-s2e17-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E18",
    "alfred hitchcock presents-s2e18-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E19",
    "alfred hitchcock presents-s2e19-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E20",
    "alfred hitchcock presents-s2e20-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E21",
    "alfred hitchcock presents-s2e21-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E22",
    "alfred hitchcock presents-s2e22-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E23",
    "alfred hitchcock presents-s2e23-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E24",
    "alfred hitchcock presents-s2e24-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E25",
    "alfred hitchcock presents-s2e25-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E26",
    "alfred hitchcock presents-s2e26-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E27",
    "alfred hitchcock presents-s2e27-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E28",
    "alfred hitchcock presents-s2e28-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E29",
    "alfred hitchcock presents-s2e29-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E30",
    "alfred hitchcock presents-s2e30-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E31",
    "alfred hitchcock presents-s2e31-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E32",
    "alfred hitchcock presents-s2e32-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E33",
    "alfred hitchcock presents-s2e33-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E34",
    "alfred hitchcock presents-s2e34-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E35",
    "alfred hitchcock presents-s2e35-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E36",
    "alfred hitchcock presents-s2e36-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E37",
    "alfred hitchcock presents-s2e37-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E38",
    "alfred hitchcock presents-s2e38-colorized-720p-hd.mp4"],
  ['alfred-hitchcock-presents-s-2e-13-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S02E39",
    "alfred hitchcock presents-s2e39-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E01",
    "alfred hitchcock presents-s3e1-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E02",
    "alfred hitchcock presents-s3e2-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E03",
    "alfred hitchcock presents-s3e3-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E04",
    "alfred hitchcock presents-s3e4-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E05",
    "alfred hitchcock presents-s3e5-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E06",
    "alfred hitchcock presents-s3e6-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E07",
    "alfred hitchcock presents-s3e7-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E08",
    "alfred hitchcock presents-s3e8-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E09",
    "alfred hitchcock presents-s3e9-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E10",
    "alfred hitchcock presents-s3e10-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E11",
    "alfred hitchcock presents-s3e11-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E12",
    "alfred hitchcock presents-s3e12-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E13",
    "alfred hitchcock presents-s3e13-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E14",
    "alfred hitchcock presents-s3e14-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E15",
    "alfred hitchcock presents-s3e15-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E16",
    "alfred hitchcock presents-s3e16-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E17",
    "alfred hitchcock presents-s3e17-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E18",
    "alfred hitchcock presents-s3e18-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E19",
    "alfred hitchcock presents-s3e19-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E20",
    "alfred hitchcock presents-s3e20-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E21",
    "alfred hitchcock presents-s3e21-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E22",
    "alfred hitchcock presents-s3e22-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E23",
    "alfred hitchcock presents-s3e23-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E24",
    "alfred hitchcock presents-s3e24-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E25",
    "alfred hitchcock presents-s3e25-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E26",
    "alfred hitchcock presents-s3e26-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E27",
    "alfred hitchcock presents-s3e27-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E28",
    "alfred hitchcock presents-s3e28-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E29",
    "alfred hitchcock presents-s3e29-colorized-576p-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E30",
    "alfred hitchcock presents-s3e30-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E31",
    "alfred hitchcock presents-s3e31-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E32",
    "alfred hitchcock presents-s3e32-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E33",
    "alfred hitchcock presents-s3e33-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E34",
    "alfred hitchcock presents-s3e34-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E35",
    "alfred hitchcock presents-s3e35-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E36",
    "alfred hitchcock presents-s3e36-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E37",
    "alfred hitchcock presents-s3e37-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E38",
    "alfred hitchcock presents-s3e38-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-3e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S03E39",
    "alfred hitchcock presents-s3e39-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E01",
    "alfred hitchcock presents-s4e1-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E02",
    "alfred hitchcock presents-s4e2-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E03",
    "alfred hitchcock presents-s4e3-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E04",
    "alfred hitchcock presents-s4e4-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E05",
    "alfred hitchcock presents-s4e5-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E06",
    "alfred hitchcock presents-s4e6-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E07",
    "alfred hitchcock presents-s4e7-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E08",
    "alfred hitchcock presents-s4e8-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E09",
    "alfred hitchcock presents-s4e9-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E10",
    "alfred hitchcock presents-s4e10-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E11",
    "alfred hitchcock presents-s4e11-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E12",
    "alfred hitchcock presents-s4e12-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E13",
    "alfred hitchcock presents-s4e13-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E14",
    "alfred hitchcock presents-s4e14-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E15",
    "alfred hitchcock presents-s4e15-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E16",
    "alfred hitchcock presents-s4e16-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E17",
    "alfred hitchcock presents-s4e17-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E19",
    "alfred hitchcock presents-s4e19-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E20",
    "alfred hitchcock presents-s4e20-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E21",
    "alfred hitchcock presents-s4e21-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E22",
    "alfred hitchcock presents-s4e22-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E23",
    "alfred hitchcock presents-s4e23-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E24",
    "alfred hitchcock presents-s4e24-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E25",
    "alfred hitchcock presents-s4e25-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E26",
    "alfred hitchcock presents-s4e26-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E27",
    "alfred hitchcock presents-s4e27-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E28",
    "alfred hitchcock presents-s4e28-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E29",
    "alfred hitchcock presents-s4e29-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E30",
    "alfred hitchcock presents-s4e30-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E31",
    "alfred hitchcock presents-s4e31-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E32",
    "alfred hitchcock presents-s4e32-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E33",
    "alfred hitchcock presents-s4e33-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E34",
    "alfred hitchcock presents-s4e34-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E35",
    "alfred hitchcock presents-s4e35-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-4e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S04E36",
    "alfred hitchcock presents-s4e36-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E01",
    "alfred hitchcock presents-1959-s5e1-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E02",
    "alfred hitchcock presents-1959-s5e2-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E03",
    "alfred hitchcock presents-1959-s5e3-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E04",
    "alfred hitchcock presents-1959-s5e4-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E05",
    "alfred hitchcock presents-1959-s5e5-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E06",
    "alfred hitchcock presents-1959-s5e6-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E07",
    "alfred hitchcock presents-1959-s5e7-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E08",
    "alfred hitchcock presents-1959-s5e8-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E09",
    "alfred hitchcock presents-1959-s5e9-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E10",
    "alfred hitchcock presents-1959-s5e10-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E11",
    "alfred hitchcock presents-1959-s5e11-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E12",
    "alfred hitchcock presents-1959-s5e12-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E13",
    "alfred hitchcock presents-1959-s5e13-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E14",
    "alfred hitchcock presents-1959-s5e14-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E15",
    "alfred hitchcock presents-1959-s5e15-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E16",
    "alfred hitchcock presents-1959-s5e16-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E17",
    "alfred hitchcock presents-1959-s5e17-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E18",
    "alfred hitchcock presents-1959-s5e18-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E19",
    "alfred hitchcock presents-1959-s5e19-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E20",
    "alfred hitchcock presents-1959-s5e20-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E21",
    "alfred hitchcock presents-1959-s5e21-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E22",
    "alfred hitchcock presents-1959-s5e22-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E23",
    "alfred hitchcock presents-1959-s5e23-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E24",
    "alfred hitchcock presents-1959-s5e24-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E25",
    "alfred hitchcock presents-1959-s5e25-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E26",
    "alfred hitchcock presents-1959-s5e26-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E27",
    "alfred hitchcock presents-1959-s5e27-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E28",
    "alfred hitchcock presents-1959-s5e28-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E29",
    "alfred hitchcock presents-1959-s5e29-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E30",
    "alfred hitchcock presents-1959-s5e30-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E31",
    "alfred hitchcock presents-1959-s5e31-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E32",
    "alfred hitchcock presents-1959-s5e32-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E33",
    "alfred hitchcock presents-1959-s5e33-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E35",
    "alfred hitchcock presents-1959-s5e35-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E36",
    "alfred hitchcock presents-1959-s5e36-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E37",
    "alfred hitchcock presents-1959-s5e37-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-1959-s-5e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S05E38",
    "alfred hitchcock presents-1959-s5e38-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E01",
    "alfred hitchcock presents-s6e1-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E02",
    "alfred hitchcock presents-s6e2-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E03",
    "alfred hitchcock presents-s6e3-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E04",
    "alfred hitchcock presents-s6e4-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E06",
    "alfred hitchcock presents-s6e6-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E07",
    "alfred hitchcock presents-s6e7-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E08",
    "alfred hitchcock presents-s6e8-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E09",
    "alfred hitchcock presents-s6e9-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E10",
    "alfred hitchcock presents-s6e10-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E11",
    "alfred hitchcock presents-s6e11-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E12",
    "alfred hitchcock presents-s6e12-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E13",
    "alfred hitchcock presents-s6e13-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E14",
    "alfred hitchcock presents-s6e14-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E15",
    "alfred hitchcock presents-s6e15-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E16",
    "alfred hitchcock presents-s6e16-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E17",
    "alfred hitchcock presents-s6e17-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E18",
    "alfred hitchcock presents-s6e18-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E19",
    "alfred hitchcock presents-s6e19-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E20",
    "alfred hitchcock presents-s6e20-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E21",
    "alfred hitchcock presents-s6e21-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E22",
    "alfred hitchcock presents-s6e22-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E23",
    "alfred hitchcock presents-s6e23-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E24",
    "alfred hitchcock presents-s6e24-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E25",
    "alfred hitchcock presents-s6e25-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E26",
    "alfred hitchcock presents-s6e26-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E28",
    "alfred hitchcock presents-s6e28-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E29",
    "alfred hitchcock presents-s6e29-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E30",
    "alfred hitchcock presents-s6e30-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E31",
    "alfred hitchcock presents-s6e31-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E32",
    "alfred hitchcock presents-s6e32-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E33",
    "alfred hitchcock presents-s6e33-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E34",
    "alfred hitchcock presents-s6e34-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E36",
    "alfred hitchcock presents-s6e36-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E37",
    "alfred hitchcock presents-s6e37-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-6e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S06E38",
    "alfred hitchcock presents-s6e38-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E01",
    "alfred hitchcock presents-s7e1-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E02",
    "alfred hitchcock presents-s7e2-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E03",
    "alfred hitchcock presents-s7e3-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E04",
    "alfred hitchcock presents-s7e4-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E05",
    "alfred hitchcock presents-s7e5-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E06",
    "alfred hitchcock presents-s7e6-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E07",
    "alfred hitchcock presents-s7e7-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E08",
    "alfred hitchcock presents-s7e8-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E09",
    "alfred hitchcock presents-s7e9-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E10",
    "alfred hitchcock presents-s7e10-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E11",
    "alfred hitchcock presents-s7e11-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E12",
    "alfred hitchcock presents-s7e12-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E13",
    "alfred hitchcock presents-s7e13-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E14",
    "alfred hitchcock presents-s7e14shrt-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E15",
    "alfred hitchcock presents-s7e15-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E16",
    "alfred hitchcock presents-s7e16-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E17",
    "alfred hitchcock presents-s7e17-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E18",
    "alfred hitchcock presents-s7e18-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E19",
    "alfred hitchcock presents-s7e19-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E20",
    "alfred hitchcock presents-s7e20-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E21",
    "alfred hitchcock presents-s7e21-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E22",
    "alfred hitchcock presents-s7e22-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E23",
    "alfred hitchcock presents-s7e23-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E24",
    "alfred hitchcock presents-s7e24-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E25",
    "alfred hitchcock presents-s7e25-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E26",
    "alfred hitchcock presents-s7e26-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E27",
    "alfred hitchcock presents-s7e27-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E28",
    "alfred hitchcock presents-s7e28-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E29",
    "alfred hitchcock presents-s7e29-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E30",
    "alfred hitchcock presents-s7e30-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E31",
    "alfred hitchcock presents-s7e31-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E32",
    "alfred hitchcock presents-s7e32-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E33",
    "alfred hitchcock presents-s7e33-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E35",
    "alfred hitchcock presents-s7e35-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E36",
    "alfred hitchcock presents-s7e36-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E37",
    "alfred hitchcock presents-s7e37-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E38",
    "alfred hitchcock presents-s7e38-colorized-sd.mp4"],
  ['alfred-hitchcock-presents-s-7e-1-colorized-sd', "ALFRED HITCHCOCK PRESENTS - S07E39",
    "alfred hitchcock presents-s7e39pd-colorized-sd.mp4"],
],
  durations: {
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e1-colorized-720p-hd.mp4": 1638,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e2-colorized-720p-hd.mp4": 1628,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e3-colorized-720p-hd.mp4": 1628,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e4-colorized-720p-hd.mp4": 1626,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e5-colorized-720p-hd.mp4": 1618,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e6-colorized-720p-hd.mp4": 1596,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e7-colorized-720p-hd.mp4": 1612,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e8-colorized-720p-hd.mp4": 1598,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e10-colorized-720p-hd.mp4": 1618,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e11-colorized-720p-hd.mp4": 1585,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e12-colorized-720p-hd.mp4": 1608,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e13-colorized-720p-hd.mp4": 1582,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e14-colorized-720p-hd.mp4": 1585,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e15-colorized-576p-sd.mp4": 1616,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e16-colorized-720p-hd.mp4": 1601,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e17-colorized-720p-hd.mp4": 1609,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e18-colorized-720p-hd.mp4": 1593,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e19-colorized-720p-hd.mp4": 1563,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e20-colorized-720p-hd.mp4": 1584,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e21-colorized-576p-sd.mp4": 1707,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e22-colorized-576p-sd.mp4": 1606,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e23-colorized-720p-hd.mp4": 1579,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e24-colorized-720p-hd.mp4": 1596,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e25-colorized-720p-hd.mp4": 1622,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e26-colorized-720p-hd.mp4": 1593,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e27-colorized-720p-hd.mp4": 1616,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e28-colorized-576p-sd.mp4": 1615,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e29-colorized-576p-sd.mp4": 1619,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e30-colorized-576p-sd.mp4": 1576,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e31-colorized-576p-sd.mp4": 1612,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e32-colorized-576p-sd.mp4": 1611,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e33-colorized-576p-sd.mp4": 1616,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e34-colorized-576p-sd.mp4": 1617,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e35-colorized-576p-sd.mp4": 1620,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e36-colorized-576p-sd.mp4": 2244,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e37-colorized-576p-sd.mp4": 1575,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e38-colorized-576p-sd.mp4": 1589,
  "alfred-hitchcock-presents-s-1e-1-colorized-720p-hd::alfred hitchcock presents-s1e39-colorized-576p-sd.mp4": 1561,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e1-colorized-576p-sd.mp4": 1568,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e2-colorized-576p-sd.mp4": 1576,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e3-colorized-576p-sd.mp4": 1527,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e4-colorized-576p-sd.mp4": 1525,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e5-colorized-576p-sd.mp4": 1576,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e6-colorized-sd.mp4": 1465,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e7-colorized-576p-sd.mp4": 1543,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e8-colorized-720p-hd.mp4": 1484,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e9-colorized-576p-sd.mp4": 1537,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e10-colorized-576p-sd.mp4": 1532,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e11-colorized-576p-sd.mp4": 1522,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e12-colorized-sd.mp4": 1478,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e13-colorized-sd.mp4": 1479,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e14-colorized-sd.mp4": 1438,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e15-colorized-576p-sd.mp4": 1547,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e16-colorized-576p-sd.mp4": 1578,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e17-colorized-sd.mp4": 1446,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e18-colorized-sd.mp4": 1454,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e19-colorized-576p-sd.mp4": 1537,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e20-colorized-576p-sd.mp4": 1510,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e21-colorized-576p-sd.mp4": 1521,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e22-colorized-sd.mp4": 1474,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e23-colorized-sd.mp4": 1451,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e24-colorized-576p-sd.mp4": 1551,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e25-colorized-576p-sd.mp4": 1584,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e26-colorized-sd.mp4": 1469,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e27-colorized-576p-sd.mp4": 1848,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e28-colorized-sd.mp4": 1449,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e29-colorized-576p-sd.mp4": 1526,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e30-colorized-sd.mp4": 1469,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e31-colorized-576p-sd.mp4": 1510,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e32-colorized-sd.mp4": 1488,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e33-colorized-sd.mp4": 1520,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e34-colorized-sd.mp4": 1554,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e35-colorized-sd.mp4": 1473,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e36-colorized-576p-sd.mp4": 1546,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e37-colorized-sd.mp4": 1459,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e38-colorized-720p-hd.mp4": 1566,
  "alfred-hitchcock-presents-s-2e-13-colorized-sd::alfred hitchcock presents-s2e39-colorized-576p-sd.mp4": 1534,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e1-colorized-sd.mp4": 1600,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e2-colorized-sd.mp4": 1587,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e3-colorized-sd.mp4": 1541,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e4-colorized-sd.mp4": 1640,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e5-colorized-sd.mp4": 1591,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e6-colorized-sd.mp4": 1599,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e7-colorized-sd.mp4": 1594,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e8-colorized-sd.mp4": 1576,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e9-colorized-sd.mp4": 1622,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e10-colorized-sd.mp4": 1573,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e11-colorized-sd.mp4": 1609,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e12-colorized-576p-sd.mp4": 1573,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e13-colorized-sd.mp4": 1600,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e14-colorized-sd.mp4": 1608,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e15-colorized-sd.mp4": 1580,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e16-colorized-sd.mp4": 1535,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e17-colorized-sd.mp4": 1599,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e18-colorized-sd.mp4": 1607,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e19-colorized-sd.mp4": 1616,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e20-colorized-sd.mp4": 1619,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e21-colorized-sd.mp4": 1600,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e22-colorized-576p-sd.mp4": 1567,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e23-colorized-sd.mp4": 1617,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e24-colorized-sd.mp4": 1572,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e25-colorized-sd.mp4": 1553,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e26-colorized-576p-sd.mp4": 1569,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e27-colorized-sd.mp4": 1624,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e28-colorized-sd.mp4": 1621,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e29-colorized-576p-sd.mp4": 1622,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e30-colorized-sd.mp4": 1620,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e31-colorized-sd.mp4": 1627,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e32-colorized-sd.mp4": 1617,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e33-colorized-sd.mp4": 1565,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e34-colorized-sd.mp4": 1623,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e35-colorized-sd.mp4": 1622,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e36-colorized-sd.mp4": 1550,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e37-colorized-sd.mp4": 1570,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e38-colorized-sd.mp4": 1609,
  "alfred-hitchcock-presents-s-3e-1-colorized-sd::alfred hitchcock presents-s3e39-colorized-sd.mp4": 1609,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e1-colorized-sd.mp4": 1620,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e2-colorized-sd.mp4": 1613,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e3-colorized-sd.mp4": 1600,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e4-colorized-sd.mp4": 1630,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e5-colorized-sd.mp4": 1621,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e6-colorized-sd.mp4": 1601,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e7-colorized-sd.mp4": 1614,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e8-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e9-colorized-sd.mp4": 1567,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e10-colorized-sd.mp4": 1557,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e11-colorized-sd.mp4": 1559,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e12-colorized-sd.mp4": 1617,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e13-colorized-sd.mp4": 1559,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e14-colorized-sd.mp4": 1617,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e15-colorized-sd.mp4": 1619,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e16-colorized-sd.mp4": 1616,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e17-colorized-sd.mp4": 1624,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e19-colorized-sd.mp4": 1618,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e20-colorized-sd.mp4": 1623,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e21-colorized-sd.mp4": 1618,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e22-colorized-sd.mp4": 1600,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e23-colorized-sd.mp4": 1628,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e24-colorized-sd.mp4": 1595,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e25-colorized-sd.mp4": 1619,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e26-colorized-sd.mp4": 1620,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e27-colorized-sd.mp4": 1558,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e28-colorized-sd.mp4": 1621,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e29-colorized-sd.mp4": 1548,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e30-colorized-sd.mp4": 1622,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e31-colorized-sd.mp4": 1527,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e32-colorized-sd.mp4": 1619,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e33-colorized-sd.mp4": 1618,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e34-colorized-sd.mp4": 1618,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e35-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-s-4e-1-colorized-sd::alfred hitchcock presents-s4e36-colorized-sd.mp4": 1620,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e1-colorized-sd.mp4": 1616,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e2-colorized-sd.mp4": 1891,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e3-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e4-colorized-sd.mp4": 1593,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e5-colorized-sd.mp4": 1615,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e6-colorized-sd.mp4": 1606,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e7-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e8-colorized-sd.mp4": 1597,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e9-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e10-colorized-sd.mp4": 1605,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e11-colorized-sd.mp4": 1609,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e12-colorized-sd.mp4": 1541,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e13-colorized-sd.mp4": 1382,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e14-colorized-sd.mp4": 1604,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e15-colorized-sd.mp4": 1603,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e16-colorized-sd.mp4": 1589,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e17-colorized-sd.mp4": 1610,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e18-colorized-sd.mp4": 1556,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e19-colorized-sd.mp4": 1587,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e20-colorized-sd.mp4": 1575,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e21-colorized-sd.mp4": 1569,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e22-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e23-colorized-sd.mp4": 1613,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e24-colorized-sd.mp4": 1629,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e25-colorized-sd.mp4": 1551,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e26-colorized-sd.mp4": 1594,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e27-colorized-sd.mp4": 1539,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e28-colorized-sd.mp4": 1614,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e29-colorized-sd.mp4": 1585,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e30-colorized-sd.mp4": 1606,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e31-colorized-sd.mp4": 1622,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e32-colorized-sd.mp4": 1612,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e33-colorized-sd.mp4": 1586,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e35-colorized-sd.mp4": 1589,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e36-colorized-sd.mp4": 1603,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e37-colorized-sd.mp4": 1663,
  "alfred-hitchcock-presents-1959-s-5e-1-colorized-sd::alfred hitchcock presents-1959-s5e38-colorized-sd.mp4": 1614,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e1-colorized-sd.mp4": 1600,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e2-colorized-sd.mp4": 1583,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e3-colorized-sd.mp4": 1586,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e4-colorized-sd.mp4": 1574,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e6-colorized-sd.mp4": 1577,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e7-colorized-sd.mp4": 1560,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e8-colorized-sd.mp4": 1585,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e9-colorized-sd.mp4": 1575,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e10-colorized-sd.mp4": 1573,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e11-colorized-sd.mp4": 1570,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e12-colorized-sd.mp4": 1561,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e13-colorized-sd.mp4": 1582,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e14-colorized-sd.mp4": 1563,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e15-colorized-sd.mp4": 1569,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e16-colorized-sd.mp4": 1585,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e17-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e18-colorized-sd.mp4": 1634,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e19-colorized-sd.mp4": 1582,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e20-colorized-sd.mp4": 1579,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e21-colorized-sd.mp4": 1573,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e22-colorized-sd.mp4": 1583,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e23-colorized-sd.mp4": 1569,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e24-colorized-sd.mp4": 1568,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e25-colorized-sd.mp4": 1507,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e26-colorized-sd.mp4": 1587,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e28-colorized-sd.mp4": 1594,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e29-colorized-sd.mp4": 1590,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e30-colorized-sd.mp4": 1537,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e31-colorized-sd.mp4": 1585,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e32-colorized-sd.mp4": 1594,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e33-colorized-sd.mp4": 1516,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e34-colorized-sd.mp4": 1528,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e36-colorized-sd.mp4": 1517,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e37-colorized-sd.mp4": 1531,
  "alfred-hitchcock-presents-s-6e-1-colorized-sd::alfred hitchcock presents-s6e38-colorized-sd.mp4": 1564,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e1-colorized-sd.mp4": 1579,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e2-colorized-sd.mp4": 1579,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e3-colorized-sd.mp4": 1566,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e4-colorized-sd.mp4": 1574,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e5-colorized-sd.mp4": 1536,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e6-colorized-sd.mp4": 1574,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e7-colorized-sd.mp4": 1567,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e8-colorized-sd.mp4": 1589,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e9-colorized-sd.mp4": 1474,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e10-colorized-sd.mp4": 1578,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e11-colorized-sd.mp4": 1570,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e12-colorized-sd.mp4": 1565,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e13-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e14shrt-colorized-sd.mp4": 974,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e15-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e16-colorized-sd.mp4": 1567,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e17-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e18-colorized-sd.mp4": 1566,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e19-colorized-sd.mp4": 1572,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e20-colorized-sd.mp4": 1564,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e21-colorized-sd.mp4": 1563,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e22-colorized-sd.mp4": 1603,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e23-colorized-sd.mp4": 1566,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e24-colorized-sd.mp4": 1576,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e25-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e26-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e27-colorized-sd.mp4": 1465,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e28-colorized-sd.mp4": 1567,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e29-colorized-sd.mp4": 1577,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e30-colorized-sd.mp4": 1573,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e31-colorized-sd.mp4": 1575,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e32-colorized-sd.mp4": 1583,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e33-colorized-sd.mp4": 1566,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e35-colorized-sd.mp4": 1566,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e36-colorized-sd.mp4": 1571,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e37-colorized-sd.mp4": 1564,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e38-colorized-sd.mp4": 1568,
  "alfred-hitchcock-presents-s-7e-1-colorized-sd::alfred hitchcock presents-s7e39pd-colorized-sd.mp4": 1561,
},
  introSkipSeconds: 54,
  // this rip frames the real picture inside a black surround with a vertical
  // watermark panel down the left. crop trims it back to the true video.
  // fractions of the full frame { x, y, w, h }; keyed by season because each
  // season is a separate archive item and may be framed differently — measured
  // per season before being added here (seasons not listed are left uncropped).
  cropBySeason: {
    1: { x: 0.1499, y: 0.0354, w: 0.7084, h: 0.9229 },
    2: { x: 0.1522, y: 0.0208, w: 0.7178, h: 0.9563 },
    3: { x: 0.1440, y: 0.0167, w: 0.7155, h: 0.9625 },
    4: { x: 0.1487, y: 0.0250, w: 0.7026, h: 0.9458 },
    5: { x: 0.1464, y: 0.0208, w: 0.7307, h: 0.9521 },
    6: { x: 0.1405, y: 0.0146, w: 0.7447, h: 0.9688 },
    7: { x: 0.1382, y: 0.0208, w: 0.7295, h: 0.9542 },
  },
};
