window.SHOW = {
  id: "SciFiAnime",
  title: "Sci-Fi Saturday Anime",
  art: "SciFiAnime.png",
  storageProgressKey: "scifianime-progress",
  storageSettingsKey: "scifianime-settings",
  nestedPaths: false,
  grouping: "flat",
  segments: "film",
  episodes: [
  ['gall-force-scifi-rip', 'SCI-FI ANIME - 11/09/1996'],
  ['venuswarsscifichannel', 'SCI-FI ANIME - 07/13/1996'],
  ['lodosswarscifichannel', 'SCI-FI ANIME - 11/23/1996'],
  ['scifi-saturday-anime-project-ako', 'SCI-FI ANIME - 01/04/1997'],
  ['vampire-hunter-d-sci-fi-channel-05-17-1997', 'SCI-FI ANIME - 05/17/1997'],
  // this archive.org item bundles 2 separate recordings of the same movie —
  // one has an exact date buried in its own filename, the other doesn't
  ['odin-photon-space-sailer-starlight-sci-fi-channel-saturday-anime', 'SCI-FI ANIME - 05/31/1997',
    'SciFi Channel Saturday Anime - _Odin_ Photon Space Sailor Starlight_ 05_31_1997 09_00 EST.mp4'],
  ['odin-photon-space-sailer-starlight-sci-fi-channel-saturday-anime', 'SCI-FI ANIME - Undated',
    'Odin - Photon Space Sailer Starlight (Sci-Fi Channel Saturday Anime).mp4'],
  ['galaxy-express-999-sci-fi-channel-vhs-rip', 'SCI-FI ANIME - Undated',
    'Galaxy Express 999 Sci-Fi Channel VHS rip with commercials(720P_60FPS).ia.mp4'],
  ['rinse-repeat-yu-yu-hakusho-the-movie-sci-fi-channel', 'SCI-FI ANIME - Recreation (undated)'],
  ['myopic-vhs-no-05', 'SCI-FI ANIME - VHS Tape #5 (undated, multi-show)'],
  ['myopic-vhs-no-08', 'SCI-FI ANIME - VHS Tape #8 (undated, multi-show)'],
  ['myopic-vhs-no-09', 'SCI-FI ANIME - VHS Tape #9 (undated, multi-show)'],
],
  durations: {
  "gall-force-scifi-rip": 7156,
  "venuswarsscifichannel": 6920,
  "lodosswarscifichannel": 5060,
  "scifi-saturday-anime-project-ako": 6947,
  "vampire-hunter-d-sci-fi-channel-05-17-1997": 7162,
  "odin-photon-space-sailer-starlight-sci-fi-channel-saturday-anime::SciFi Channel Saturday Anime - _Odin_ Photon Space Sailor Starlight_ 05_31_1997 09_00 EST.mp4": 7209,
  "odin-photon-space-sailer-starlight-sci-fi-channel-saturday-anime::Odin - Photon Space Sailer Starlight (Sci-Fi Channel Saturday Anime).mp4": 7240,
  "galaxy-express-999-sci-fi-channel-vhs-rip::Galaxy Express 999 Sci-Fi Channel VHS rip with commercials(720P_60FPS).ia.mp4": 7123,
  "rinse-repeat-yu-yu-hakusho-the-movie-sci-fi-channel": 7272,
  "myopic-vhs-no-05": 25119,
  "myopic-vhs-no-08": 27728,
  "myopic-vhs-no-09": 26971,
},
  film: {
  'gall-force-scifi-rip': 'Gall Force: Eternal Story',
  'venuswarsscifichannel': 'Venus Wars',
  'lodosswarscifichannel': 'Record of Lodoss War (eps. 1-3)',
  'vampire-hunter-d-sci-fi-channel-05-17-1997': 'Vampire Hunter D',
  'scifi-saturday-anime-project-ako': 'Project A-ko',
  'odin-photon-space-sailer-starlight-sci-fi-channel-saturday-anime::SciFi Channel Saturday Anime - _Odin_ Photon Space Sailor Starlight_ 05_31_1997 09_00 EST.mp4': 'Odin: Photon Space Sailer Starlight',
  'odin-photon-space-sailer-starlight-sci-fi-channel-saturday-anime::Odin - Photon Space Sailer Starlight (Sci-Fi Channel Saturday Anime).mp4': 'Odin: Photon Space Sailer Starlight',
  'galaxy-express-999-sci-fi-channel-vhs-rip::Galaxy Express 999 Sci-Fi Channel VHS rip with commercials(720P_60FPS).ia.mp4': 'Galaxy Express 999',
  'rinse-repeat-yu-yu-hakusho-the-movie-sci-fi-channel': 'Yu Yu Hakusho: The Movie',
},
  shows: {
  'myopic-vhs-no-05': ['Casshan: Robot Hunter', 'Outlaw Star', 'Tenchi Muyo!', 'Beast Wars'],
  'myopic-vhs-no-08': ['Roujin Z', 'Project A-Ko', 'Outlaw Star'],
  'myopic-vhs-no-09': ['Dominion Tank Police', 'Dragon Ball Z', 'Tenchi Muyo!'],
},
};
