window.SHOW = {
  id: "Newhart",
  title: "Newhart",
  art: "Newhart.jpg",
  storageProgressKey: "newhart-progress",
  storageSettingsKey: "newhart-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['NewhartSeries', "NEWHART - S01E01 - In the Beginning",
    "Newhart - 101 - In the Beginning.mp4"],
  ['NewhartSeries', "NEWHART - S01E02 - Mrs. Newton's Body Lies A'Mould'ring in the Grave",
    "Newhart - 102 - Mrs. Newton's Body Lies A'Mould'ring in the Grave.mp4"],
  ['NewhartSeries', "NEWHART - S01E03 - Hail to the Councilman",
    "Newhart - 103 - Hail to the Councilman.mp4"],
  ['NewhartSeries', "NEWHART - S01E04 - Shall We Gather at the River",
    "Newhart - 104 - Shall We Gather at the River.mp4"],
  ['NewhartSeries', "NEWHART - S01E05 - This Probably is Condemned",
    "Newhart - 105 - This Probably is Condemned.mp4"],
  ['NewhartSeries', "NEWHART - S01E06 - No Tigers at the Circus",
    "Newhart - 106 - No Tigers at the Circus.mp4"],
  ['NewhartSeries', "NEWHART - S01E07 - The Perfect Match",
    "Newhart - 107 - The Perfect Match.mp4"],
  ['NewhartSeries', "NEWHART - S01E08 - Some are Born Writers...Others Have Writers Thrust Upon Them",
    "Newhart - 108 - Some are Born Writers...Others Have Writers Thrust Upon Them.mp4"],
  ['NewhartSeries', "NEWHART - S01E09 - No Room at the Inn",
    "Newhart - 109 - No Room at the Inn.mp4"],
  ['NewhartSeries', "NEWHART - S01E10 - The Senator's Wife Was Indiscreet",
    "Newhart - 110 - The Senator's Wife Was Indiscreet.mp4"],
  ['NewhartSeries', "NEWHART - S01E11 - Sprained Dreams",
    "Newhart - 111 - Sprained Dreams.mp4"],
  ['NewhartSeries', "NEWHART - S01E12 - The Way We Thought We Were",
    "Newhart - 112 - The Way We Thought We Were.mp4"],
  ['NewhartSeries', "NEWHART - S01E13 - The Visitors",
    "Newhart - 113 - The Visitors.mp4"],
  ['NewhartSeries', "NEWHART - S01E14 - What is This Thing Called Lust",
    "Newhart - 114 - What is This Thing Called Lust.mp4"],
  ['NewhartSeries', "NEWHART - S01E15 - Breakfast Theater",
    "Newhart - 115 - Breakfast Theater.mp4"],
  ['NewhartSeries', "NEWHART - S01E16 - Ricky Nelson, Up Your Nose",
    "Newhart - 116 - Ricky Nelson, Up Your Nose.mp4"],
  ['NewhartSeries', "NEWHART - S01E17 - A View from the Bench",
    "Newhart - 117 - A View from the Bench.mp4"],
  ['NewhartSeries', "NEWHART - S01E18 - The Boy Who Cried Goat",
    "Newhart - 118 - The Boy Who Cried Goat.mp4"],
  ['NewhartSeries', "NEWHART - S01E19 - Heaven Knows Mr. Utley",
    "Newhart - 119 - Heaven Knows Mr. Utley.mp4"],
  ['NewhartSeries', "NEWHART - S01E20 - You're Homebody 'til Somebody Loves You",
    "Newhart - 120 - You're Homebody 'til Somebody Loves You.mp4"],
  ['NewhartSeries', "NEWHART - S01E21 - Grandma, What a Big Mouth You Have",
    "Newhart - 121 - Grandma, What a Big Mouth You Have.mp4"],
  ['NewhartSeries', "NEWHART - S01E22 - I Enjoy Being a Guy",
    "Newhart - 122 - I Enjoy Being a Guy.mp4"],
  ['NewhartSeries2', "NEWHART - S02E01 - It Happened One Afternoon 1",
    "Newhart - 201 - It Happened One Afternoon 1.mp4"],
  ['NewhartSeries2', "NEWHART - S02E02 - It Happened One Afternoon 2",
    "Newhart - 202 - It Happened One Afternoon 2.mp4"],
  ['NewhartSeries2', "NEWHART - S02E03 - Animal Attractions",
    "Newhart - 203 - Animal Attractions.mp4"],
  ['NewhartSeries2', "NEWHART - S02E04 - The Stratford Wives",
    "Newhart - 204 - The Stratford Wives.mp4"],
  ['NewhartSeries2', "NEWHART - S02E05 - The Girl From Manhattan",
    "Newhart - 205 - The Girl From Manhattan.mp4"],
  ['NewhartSeries2', "NEWHART - S02E06 - Dont Rain On My Parade",
    "Newhart - 206 - Dont Rain On My Parade.mp4"],
  ['NewhartSeries2', "NEWHART - S02E07 - Lady And The Tramps",
    "Newhart - 207 - Lady And The Tramps.mp4"],
  ['NewhartSeries2', "NEWHART - S02E08 - The Man Who Came Forever",
    "Newhart - 208 - The Man Who Came Forever.mp4"],
  ['NewhartSeries2', "NEWHART - S02E09 - The Looks Of Love",
    "Newhart - 209 - The Looks Of Love.mp4"],
  ['NewhartSeries2', "NEWHART - S02E10 - Kirk Goes For The Juggler",
    "Newhart - 210 - Kirk Goes For The Juggler.mp4"],
  ['NewhartSeries2', "NEWHART - S02E11 - A Jug of Wine, a Loaf of Bread and POW",
    "Newhart - 211 - A Jug Of Wine.mp4"],
  ['NewhartSeries2', "NEWHART - S02E12 - Cats",
    "Newhart - 212 - Cats.mp4"],
  ['NewhartSeries2', "NEWHART - S02E13 - Curious George At The Firehouse",
    "Newhart - 213 - Curious George At The Firehouse.mp4"],
  ['NewhartSeries2', "NEWHART - S02E14 - Book Beat",
    "Newhart - 214 - Book Beat.mp4"],
  ['NewhartSeries2', "NEWHART - S02E15 - Kirk Pops The Question",
    "Newhart - 215 - Kirk Pops The Question.mp4"],
  ['NewhartSeries2', "NEWHART - S02E16 - Best Friends",
    "Newhart - 216 - Best Friends.mp4"],
  ['NewhartSeries2', "NEWHART - S02E17 - Kirk Ties One On",
    "Newhart - 217 - Kirk Ties One On.mp4"],
  ['NewhartSeries2', "NEWHART - S02E18 - Go Grandma Go",
    "Newhart - 218 - Go Grandma Go.mp4"],
  ['NewhartSeries2', "NEWHART - S02E19 - Leave It To The Beavers",
    "Newhart - 219 - Leave It To The Beavers.mp4"],
  ['NewhartSeries2', "NEWHART - S02E20 - Vermont Today",
    "Newhart - 220 - Vermont Today.mp4"],
  ['NewhartSeries2', "NEWHART - S02E21 - Send Her Ella",
    "Newhart - 221 - Send Her Ella.mp4"],
  ['NewhartSeries2', "NEWHART - S02E22 - New Faces Of 1951",
    "Newhart - 222 - New Faces Of 1951.mp4"],
  ['NewhartSeries3', "NEWHART - S03E01 - Tell A Lie Get A Check",
    "Newhart - 301 - Tell A Lie Get A Check.mp4"],
  ['NewhartSeries3', "NEWHART - S03E02 - Twenty Year Itch",
    "Newhart - 302 - Twenty Year Itch.mp4"],
  ['NewhartSeries3', "NEWHART - S03E03 - A Hunting We Will Go",
    "Newhart - 303 - A Hunting We Will Go.mp4"],
  ['NewhartSeries3', "NEWHART - S03E04 - Miss Stephanie",
    "Newhart - 304 - Miss Stephanie.mp4"],
  ['NewhartSeries3', "NEWHART - S03E05 - But Seriously Beavers",
    "Newhart - 305 - But Seriously Beavers.mp4"],
  ['NewhartSeries3', "NEWHART - S03E06 - Tickets Please",
    "Newhart - 306 - Tickets Please.mp4"],
  ['NewhartSeries3', "NEWHART - S03E07 - Poor Reception",
    "Newhart - 307 - Poor Reception.mp4"],
  ['NewhartSeries3', "NEWHART - S03E08 - The Fan",
    "Newhart - 308 - The Fan.mp4"],
  ['NewhartSeries3', "NEWHART - S03E09 - Happy Trails To You",
    "Newhart - 309 - Happy Trails To You.mp4"],
  ['NewhartSeries3', "NEWHART - S03E10 - Georgies Girl",
    "Newhart - 310 - Georgies Girl.mp4"],
  ['NewhartSeries3', "NEWHART - S03E11 - Pillow Fight",
    "Newhart - 311 - Pillow Fight.mp4"],
  ['NewhartSeries3', "NEWHART - S03E12 - Local Hero",
    "Newhart - 312 - Local Hero.mp4"],
  ['NewhartSeries3', "NEWHART - S03E13 - Dick Gets Larrys Goat",
    "Newhart - 313 - Dick Gets Larrys Goat.mp4"],
  ['NewhartSeries3', "NEWHART - S03E14 - Once I Had A Secret Love",
    "Newhart - 314 - Once I Had A Secret Love.mp4"],
  ['NewhartSeries3', "NEWHART - S03E15 - Lady In Wading",
    "Newhart - 315 - Lady In Wading.mp4"],
  ['NewhartSeries3', "NEWHART - S03E16 - Look Homeward Stephanie",
    "Newhart - 316 - Look Homeward Stephanie.mp4"],
  ['NewhartSeries3', "NEWHART - S03E17 - My Fair Larry",
    "Newhart - 317 - My Fair Larry.mp4"],
  ['NewhartSeries3', "NEWHART - S03E18 - Youre Nobody Til Somebody Hires You",
    "Newhart - 318 - Youre Nobody Til Somebody Hires You.mp4"],
  ['NewhartSeries3', "NEWHART - S03E19 - Out With The New Inn With The Old",
    "Newhart - 319 - Out With The New Inn With The Old.mp4"],
  ['NewhartSeries3', "NEWHART - S03E20 - R.I.P. Off",
    "Newhart - 320 - R.I.P. Off.mp4"],
  ['NewhartSeries3', "NEWHART - S03E21 - The Prodigal Darryl",
    "Newhart - 321 - The Prodigal Darryl.mp4"],
  ['NewhartSeries3', "NEWHART - S03E22 - What Makes Dick Run",
    "Newhart - 322 - What Makes Dick Run.mp4"],
  ['NewhartSeries4', "NEWHART - S04E01 - Pirate Pete",
    "Newhart - 401 - Pirate Pete.mp4"],
  ['NewhartSeries4', "NEWHART - S04E02 - The Way We Ought To Be",
    "Newhart - 402 - The Way We Ought To Be.mp4"],
  ['NewhartSeries4', "NEWHART - S04E03 - Summa Cum Larry",
    "Newhart - 403 - Summa Cum Larry.mp4"],
  ['NewhartSeries4', "NEWHART - S04E04 - Oh That Morocco",
    "Newhart - 404 - Oh That Morocco.mp4"],
  ['NewhartSeries4', "NEWHART - S04E05 - Candidate Larry",
    "Newhart - 405 - Candidate Larry.mp4"],
  ['NewhartSeries4', "NEWHART - S04E06 - Locks Stocks & Noodlehead",
    "Newhart - 406 - Locks Stocks & Noodlehead.mp4"],
  ['NewhartSeries4', "NEWHART - S04E07 - The Geezers In The Band",
    "Newhart - 407 - The Geezers In The Band.mp4"],
  ['NewhartSeries4', "NEWHART - S04E08 - The Shape Of Things",
    "Newhart - 408 - The Shape Of Things.mp4"],
  ['NewhartSeries4', "NEWHART - S04E09 - Write To Privacy",
    "Newhart - 409 - Write To Privacy.mp4"],
  ['NewhartSeries4', "NEWHART - S04E10 - Still The Beavers",
    "Newhart - 410 - Still The Beavers.mp4"],
  ['NewhartSeries4', "NEWHART - S04E11 - Much Ado About Mitch",
    "Newhart - 411 - Much Ado About Mitch.mp4"],
  ['NewhartSeries4', "NEWHART - S04E12 - Look Ma No Talent",
    "Newhart - 412 - Look Ma No Talent.mp4"],
  ['NewhartSeries4', "NEWHART - S04E13 - Larrys Dead Long Live Larry",
    "Newhart - 413 - Larrys Dead Long Live Larry.mp4"],
  ['NewhartSeries4', "NEWHART - S04E14 - Stephanie Nightingale",
    "Newhart - 414 - Stephanie Nightingale.mp4"],
  ['NewhartSeries4', "NEWHART - S04E15 - Stratford Horror Picture Show",
    "Newhart - 415 - Stratford Horror Picture Show.mp4"],
  ['NewhartSeries4', "NEWHART - S04E16 - I Do Okay",
    "Newhart - 416 - I Do Okay.mp4"],
  ['NewhartSeries4', "NEWHART - S04E17 - The Snowman Cometh",
    "Newhart - 417 - The Snowman Cometh.mp4"],
  ['NewhartSeries4', "NEWHART - S04E18 - Will The Real Dick Loudon",
    "Newhart - 418 - Will The Real Dick Loudon.mp4"],
  ['NewhartSeries4', "NEWHART - S04E19 - He Aint Human Hes My Cousin",
    "Newhart - 419 - He Aint Human Hes My Cousin.mp4"],
  ['NewhartSeries4', "NEWHART - S04E20 - Dwight SchmidlappIs Not A Quitter",
    "Newhart - 420 - Dwight SchmidlappIs Not A Quitter.mp4"],
  ['NewhartSeries4', "NEWHART - S04E21 - Torn Between Three Brothers",
    "Newhart - 421 - Torn Between Three Brothers.mp4"],
  ['NewhartSeries4', "NEWHART - S04E22 - Baby Im Your Handyman",
    "Newhart - 422 - Baby Im Your Handyman.mp4"],
  ['NewhartSeries4', "NEWHART - S04E23 - Replaceable You",
    "Newhart - 423 - Replaceable You.mp4"],
  ['NewhartSeries4', "NEWHART - S04E24 - Pre-Nups",
    "Newhart - 424 - Pre-Nups.mp4"],
  ['NewhartSeries5', "NEWHART - S05E01 - Co-Hostess Twinkie",
    "Newhart - 501 - Co-Hostess Twinkie.mp4"],
  ['NewhartSeries5', "NEWHART - S05E02 - Camp Stephanie",
    "Newhart - 502 - Camp Stephanie.mp4"],
  ['NewhartSeries5', "NEWHART - S05E03 - Dick The Kid",
    "Newhart - 503 - Dick The Kid.mp4"],
  ['NewhartSeries5', "NEWHART - S05E04 - High Fidelity",
    "Newhart - 504 - High Fidelity.mp4"],
  ['NewhartSeries5', "NEWHART - S05E05 - Desperately Desiring Susan 1",
    "Newhart - 505 - Desperately Desiring Susan 1.mp4"],
  ['NewhartSeries5', "NEWHART - S05E06 - Desperately Desiring Susan 2",
    "Newhart - 506 - Desperately Desiring Susan 2.mp4"],
  ['NewhartSeries5', "NEWHART - S05E07 - My Two And Only",
    "Newhart - 507 - My Two And Only.mp4"],
  ['NewhartSeries5', "NEWHART - S05E08 - Thanksgiving For The Memories",
    "Newhart - 508 - Thanksgiving For The Memories.mp4"],
  ['NewhartSeries5', "NEWHART - S05E09 - Utley Can You Spend A Dime",
    "Newhart - 509 - Utley Can You Spend A Dime.mp4"],
  ['NewhartSeries5', "NEWHART - S05E10 - Sweet And Sour Charity",
    "Newhart - 510 - Sweet And Sour Charity.mp4"],
  ['NewhartSeries5', "NEWHART - S05E11 - Everybody Ought To Have A Maid",
    "Newhart - 511 - Everybody Ought To Have A Maid.mp4"],
  ['NewhartSeries5', "NEWHART - S05E12 - Saturday In New York With George",
    "Newhart - 512 - Saturday In New York With George.mp4"],
  ['NewhartSeries5', "NEWHART - S05E13 - Love Letters In The Mud",
    "Newhart - 513 - Love Letters In The Mud.mp4"],
  ['NewhartSeries5', "NEWHART - S05E14 - First Of The Belles",
    "Newhart - 514 - First Of The Belles.mp4"],
  ['NewhartSeries5', "NEWHART - S05E15 - Its My Party And Ill Die If I Want To",
    "Newhart - 515 - Its My Party And Ill Die If I Want To.mp4"],
  ['NewhartSeries5', "NEWHART - S05E16 - Chimes They Are A Changin",
    "Newhart - 516 - Chimes They Are A Changin.mp4"],
  ['NewhartSeries5', "NEWHART - S05E17 - Unfriendly Persuasion",
    "Newhart - 517 - Unfriendly Persuasion.mp4"],
  ['NewhartSeries5', "NEWHART - S05E18 - Jail Jail The Gangs All Here",
    "Newhart - 518 - Jail Jail The Gangs All Here.mp4"],
  ['NewhartSeries5', "NEWHART - S05E19 - Dr Jekyll And Mr Loudon",
    "Newhart - 519 - Dr Jekyll And Mr Loudon.mp4"],
  ['NewhartSeries5', "NEWHART - S05E20 - Fun With Dick And Joanna",
    "Newhart - 520 - Fun With Dick And Joanna.mp4"],
  ['NewhartSeries5', "NEWHART - S05E21 - Night Moves",
    "Newhart - 521 - Night Moves.mp4"],
  ['NewhartSeries5', "NEWHART - S05E22 - Harris Ankles PIV for Web Post",
    "Newhart - 522 - Harris Ankles PIV for Web Post.mp4"],
  ['NewhartSeries5', "NEWHART - S05E23 - Good Bye And Good Riddance",
    "Newhart - 523 - Good Bye And Good Riddance.mp4"],
  ['NewhartSeries5', "NEWHART - S05E24 - Much To Do Without Muffin",
    "Newhart - 524 - Much To Do Without Muffin.mp4"],
  ['NewhartSeries6', "NEWHART - S06E01 - Heres To You Mrs Loudon",
    "Newhart - 601 - Heres To You Mrs Loudon.mp4"],
  ['NewhartSeries6', "NEWHART - S06E02 - Prima Darryl",
    "Newhart - 602 - Prima Darryl.mp4"],
  ['NewhartSeries6', "NEWHART - S06E03 - Inn This Corner",
    "Newhart - 603 - Inn This Corner.mp4"],
  ['NewhartSeries6', "NEWHART - S06E04 - Me And My Gayle",
    "Newhart - 604 - Me And My Gayle.mp4"],
  ['NewhartSeries6', "NEWHART - S06E05 - Reading Writing And Rating Points",
    "Newhart - 605 - Reading Writing And Rating Points.mp4"],
  ['NewhartSeries6', "NEWHART - S06E06 - Vintage Stephanie",
    "Newhart - 606 - Vintage Stephanie.mp4"],
  ['NewhartSeries6', "NEWHART - S06E07 - Take Me To Your Loudon",
    "Newhart - 607 - Take Me To Your Loudon.mp4"],
  ['NewhartSeries6', "NEWHART - S06E08 - Till Depth Do Us Part 1",
    "Newhart - 608 - Till Depth Do Us Part 1.mp4"],
  ['NewhartSeries6', "NEWHART - S06E09 - Till Depth Do Us Part 2",
    "Newhart - 609 - Till Depth Do Us Part 2.mp4"],
  ['NewhartSeries6', "NEWHART - S06E10 - Telethon Man",
    "Newhart - 610 - Telethon Man.mp4"],
  ['NewhartSeries6', "NEWHART - S06E11 - Laugh At My Wife Please",
    "Newhart - 611 - Laugh At My Wife Please.mp4"],
  ['NewhartSeries6', "NEWHART - S06E12 - Support Your Local Shifflet",
    "Newhart - 612 - Support Your Local Shifflet.mp4"],
  ['NewhartSeries6', "NEWHART - S06E13 - My Three Dads",
    "Newhart - 613 - My Three Dads.mp4"],
  ['NewhartSeries6', "NEWHART - S06E14 - A Friendship That Will Last",
    "Newhart - 614 - A Friendship That Will Last.mp4"],
  ['NewhartSeries6', "NEWHART - S06E15 - Presence Of Malice",
    "Newhart - 615 - Presence Of Malice.mp4"],
  ['NewhartSeries6', "NEWHART - S06E16 - Would You Buy A Used Car",
    "Newhart - 616 - Would You Buy A Used Car.mp4"],
  ['NewhartSeries6', "NEWHART - S06E17 - The Buck Stops Here",
    "Newhart - 617 - The Buck Stops Here.mp4"],
  ['NewhartSeries6', "NEWHART - S06E18 - Attention WPIV Shoppers",
    "Newhart - 618 - Attention WPIV Shoppers.mp4"],
  ['NewhartSeries6', "NEWHART - S06E19 - The Big Uneasy",
    "Newhart - 619 - The Big Uneasy.mp4"],
  ['NewhartSeries6', "NEWHART - S06E20 - Draw Partner",
    "Newhart - 620 - Draw Partner.mp4"],
  ['NewhartSeries6', "NEWHART - S06E21 - A Midseasons Night Dream",
    "Newhart - 621 - A Midseasons Night Dream.mp4"],
  ['NewhartSeries6', "NEWHART - S06E22 - Newsstruck",
    "Newhart - 622 - Newsstruck.mp4"],
  ['NewhartSeries6', "NEWHART - S06E23 - The Gleeless Club",
    "Newhart - 623 - The Gleeless Club.mp4"],
  ['NewhartSeries6', "NEWHART - S06E24 - Courtin Disaster",
    "Newhart - 624 - Courtin Disaster.mp4"],
  ['NewhartSeries7', "NEWHART - S07E01 - Town Without Pity",
    "Newhart - 701 - Town Without Pity.mp4"],
  ['NewhartSeries7', "NEWHART - S07E02 - Apples Apples Apples",
    "Newhart - 702 - Apples Apples Apples.mp4"],
  ['NewhartSeries7', "NEWHART - S07E03 - This Bloods For You",
    "Newhart - 703 - This Bloods For You.mp4"],
  ['NewhartSeries7', "NEWHART - S07E04 - I Married Dick",
    "Newhart - 704 - I Married Dick.mp4"],
  ['NewhartSeries7', "NEWHART - S07E05 - Goonstruck",
    "Newhart - 705 - Goonstruck.mp4"],
  ['NewhartSeries7', "NEWHART - S07E06 - I Came I Saw I Sat",
    "Newhart - 706 - I Came I Saw I Sat.mp4"],
  ['NewhartSeries7', "NEWHART - S07E07 - Twelve Annoyed Men And Women",
    "Newhart - 707 - Twelve Annoyed Men And Women.mp4"],
  ['NewhartSeries7', "NEWHART - S07E08 - Home For The Holidays",
    "Newhart - 708 - Home For The Holidays.mp4"],
  ['NewhartSeries7', "NEWHART - S07E09 - Shoe Business Is My Life",
    "Newhart - 709 - Shoe Business Is My Life.mp4"],
  ['NewhartSeries7', "NEWHART - S07E10 - George And The Old Maid",
    "Newhart - 710 - George And The Old Maid.mp4"],
  ['NewhartSeries7', "NEWHART - S07E11 - Hi, Society",
    "Newhart - 711 - Hi, Society.mp4"],
  ['NewhartSeries7', "NEWHART - S07E12 - Cupcake On My Back",
    "Newhart - 712 - Cupcake On My Back.mp4"],
  ['NewhartSeries7', "NEWHART - S07E13 - Another Saturday Night",
    "Newhart - 713 - Another Saturday Night.mp4"],
  ['NewhartSeries7', "NEWHART - S07E14 - The Nice Man Cometh",
    "Newhart - 714 - The Nice Man Cometh.mp4"],
  ['NewhartSeries7', "NEWHART - S07E15 - One And A Half Million Dollar Man",
    "Newhart - 715 - One And A Half Million Dollar Man.mp4"],
  ['NewhartSeries7', "NEWHART - S07E16 - The Little Match Girl",
    "Newhart - 716 - The Little Match Girl.mp4"],
  ['NewhartSeries7', "NEWHART - S07E17 - Buy Buy Blues",
    "Newhart - 717 - Buy Buy Blues.mp4"],
  ['NewhartSeries7', "NEWHART - S07E18 - Message from Michael",
    "Newhart - 718 - Message from Michael.mp4"],
  ['NewhartSeries7', "NEWHART - S07E19 - Homes And Jo-Jo",
    "Newhart - 719 - Homes And Jo-Jo.mp4"],
  ['NewhartSeries7', "NEWHART - S07E20 - Georgie & Bess",
    "Newhart - 720 - Georgie & Bess.mp4"],
  ['NewhartSeries7', "NEWHART - S07E21 - Murder At The Stratley",
    "Newhart - 721 - Murder At The Stratley.mp4"],
  ['NewhartSeries7', "NEWHART - S07E22 - Malling In Love Again",
    "Newhart - 722 - Malling In Love Again.mp4"],
  ['NewhartSeries8', "NEWHART - S08E01 - Don't Worry Be Pregnant",
    "Newhart - 801 - Don't Worry Be Pregnant.mp4"],
  ['NewhartSeries8', "NEWHART - S08E02 - Get Dick",
    "Newhart - 802 - Get Dick.mp4"],
  ['NewhartSeries8', "NEWHART - S08E03 - Poetry and Pastries",
    "Newhart - 803 - Poetry and Pastries.mp4"],
  ['NewhartSeries8', "NEWHART - S08E04 - Utley Exposed",
    "Newhart - 804 - Utley Exposed.mp4"],
  ['NewhartSeries8', "NEWHART - S08E05 - Ramblin' Michael Harris",
    "Newhart - 805 - Ramblin' Michael Harris.mp4"],
  ['NewhartSeries8', "NEWHART - S08E06 - Meet Michael Vanderkellen",
    "Newhart - 806 - Meet Michael Vanderkellen.mp4"],
  ['NewhartSeries8', "NEWHART - S08E07 - Good Lord Loudon",
    "Newhart - 807 - Good Lord Loudon.mp4"],
  ['NewhartSeries8', "NEWHART - S08E08 - Cupcake in a Cage",
    "Newhart - 808 - Cupcake in a Cage.mp4"],
  ['NewhartSeries8', "NEWHART - S08E09 - Attack of the Killer Aunt",
    "Newhart - 809 - Attack of the Killer Aunt.mp4"],
  ['NewhartSeries8', "NEWHART - S08E10 - I Like You, Butt",
    "Newhart - 810 - I Like You, Butt.mp4"],
  ['NewhartSeries8', "NEWHART - S08E11 - Jumpin' George",
    "Newhart - 811 - Jumpin' George.mp4"],
  ['NewhartSeries8', "NEWHART - S08E12 - Lights, Camera, Contractions!",
    "Newhart - 812 - Lights, Camera, Contractions!.mp4"],
  ['NewhartSeries8', "NEWHART - S08E13 - Beauty and the Pest",
    "Newhart - 813 - Beauty and the Pest.mp4"],
  ['NewhartSeries8', "NEWHART - S08E14 - Good Neighbor Sam",
    "Newhart - 814 - Good Neighbor Sam.mp4"],
  ['NewhartSeries8', "NEWHART - S08E15 - Child In Charge",
    "Newhart - 815 - Child In Charge.mp4"],
  ['NewhartSeries8', "NEWHART - S08E16 - Seein' Double",
    "Newhart - 816 - Seein' Double.mp4"],
  ['NewhartSeries8', "NEWHART - S08E17 - Born to Be Mild",
    "Newhart - 817 - Born to Be Mild.mp4"],
  ['NewhartSeries8', "NEWHART - S08E18 - Daddy's Little Girl",
    "Newhart - 818 - Daddy's Little Girl.mp4"],
  ['NewhartSeries8', "NEWHART - S08E19 - Georgie and Grace",
    "Newhart - 819 - Georgie and Grace.mp4"],
  ['NewhartSeries8', "NEWHART - S08E20 - Handymania",
    "Newhart - 820 - Handymania.mp4"],
  ['NewhartSeries8', "NEWHART - S08E21 - Dick and Tim",
    "Newhart - 821 - Dick and Tim.mp4"],
  ['NewhartSeries8', "NEWHART - S08E22 - Father Goose",
    "Newhart - 822 - Father Goose.mp4"],
  ['NewhartSeries8', "NEWHART - S08E23 - My Husband, My Peasant",
    "Newhart - 823 - My Husband, My Peasant.mp4"],
  ['NewhartSeries8', "NEWHART - S08E24 - The Last Newhart",
    "Newhart - 824 - The Last Newhart.mp4"],
],
  durations: {
  "NewhartSeries::Newhart - 101 - In the Beginning.mp4": 1569,
  "NewhartSeries::Newhart - 102 - Mrs. Newton's Body Lies A'Mould'ring in the Grave.mp4": 1480,
  "NewhartSeries::Newhart - 103 - Hail to the Councilman.mp4": 1499,
  "NewhartSeries::Newhart - 104 - Shall We Gather at the River.mp4": 1496,
  "NewhartSeries::Newhart - 105 - This Probably is Condemned.mp4": 1494,
  "NewhartSeries::Newhart - 106 - No Tigers at the Circus.mp4": 1499,
  "NewhartSeries::Newhart - 107 - The Perfect Match.mp4": 1494,
  "NewhartSeries::Newhart - 108 - Some are Born Writers...Others Have Writers Thrust Upon Them.mp4": 1498,
  "NewhartSeries::Newhart - 109 - No Room at the Inn.mp4": 1468,
  "NewhartSeries::Newhart - 110 - The Senator's Wife Was Indiscreet.mp4": 1487,
  "NewhartSeries::Newhart - 111 - Sprained Dreams.mp4": 1498,
  "NewhartSeries::Newhart - 112 - The Way We Thought We Were.mp4": 1495,
  "NewhartSeries::Newhart - 113 - The Visitors.mp4": 1476,
  "NewhartSeries::Newhart - 114 - What is This Thing Called Lust.mp4": 1496,
  "NewhartSeries::Newhart - 115 - Breakfast Theater.mp4": 1428,
  "NewhartSeries::Newhart - 116 - Ricky Nelson, Up Your Nose.mp4": 1497,
  "NewhartSeries::Newhart - 117 - A View from the Bench.mp4": 1498,
  "NewhartSeries::Newhart - 118 - The Boy Who Cried Goat.mp4": 1496,
  "NewhartSeries::Newhart - 119 - Heaven Knows Mr. Utley.mp4": 1497,
  "NewhartSeries::Newhart - 120 - You're Homebody 'til Somebody Loves You.mp4": 1496,
  "NewhartSeries::Newhart - 121 - Grandma, What a Big Mouth You Have.mp4": 1499,
  "NewhartSeries::Newhart - 122 - I Enjoy Being a Guy.mp4": 1464,
  "NewhartSeries2::Newhart - 201 - It Happened One Afternoon 1.mp4": 1341,
  "NewhartSeries2::Newhart - 202 - It Happened One Afternoon 2.mp4": 1335,
  "NewhartSeries2::Newhart - 203 - Animal Attractions.mp4": 1333,
  "NewhartSeries2::Newhart - 204 - The Stratford Wives.mp4": 1338,
  "NewhartSeries2::Newhart - 205 - The Girl From Manhattan.mp4": 1472,
  "NewhartSeries2::Newhart - 206 - Dont Rain On My Parade.mp4": 1452,
  "NewhartSeries2::Newhart - 207 - Lady And The Tramps.mp4": 1457,
  "NewhartSeries2::Newhart - 208 - The Man Who Came Forever.mp4": 1433,
  "NewhartSeries2::Newhart - 209 - The Looks Of Love.mp4": 1464,
  "NewhartSeries2::Newhart - 210 - Kirk Goes For The Juggler.mp4": 1474,
  "NewhartSeries2::Newhart - 211 - A Jug Of Wine.mp4": 1467,
  "NewhartSeries2::Newhart - 212 - Cats.mp4": 1475,
  "NewhartSeries2::Newhart - 213 - Curious George At The Firehouse.mp4": 1403,
  "NewhartSeries2::Newhart - 214 - Book Beat.mp4": 1346,
  "NewhartSeries2::Newhart - 215 - Kirk Pops The Question.mp4": 1343,
  "NewhartSeries2::Newhart - 216 - Best Friends.mp4": 1341,
  "NewhartSeries2::Newhart - 217 - Kirk Ties One On.mp4": 1444,
  "NewhartSeries2::Newhart - 218 - Go Grandma Go.mp4": 1445,
  "NewhartSeries2::Newhart - 219 - Leave It To The Beavers.mp4": 1443,
  "NewhartSeries2::Newhart - 220 - Vermont Today.mp4": 1444,
  "NewhartSeries2::Newhart - 221 - Send Her Ella.mp4": 1338,
  "NewhartSeries2::Newhart - 222 - New Faces Of 1951.mp4": 1435,
  "NewhartSeries3::Newhart - 301 - Tell A Lie Get A Check.mp4": 1342,
  "NewhartSeries3::Newhart - 302 - Twenty Year Itch.mp4": 1341,
  "NewhartSeries3::Newhart - 303 - A Hunting We Will Go.mp4": 1390,
  "NewhartSeries3::Newhart - 304 - Miss Stephanie.mp4": 1343,
  "NewhartSeries3::Newhart - 305 - But Seriously Beavers.mp4": 1366,
  "NewhartSeries3::Newhart - 306 - Tickets Please.mp4": 1408,
  "NewhartSeries3::Newhart - 307 - Poor Reception.mp4": 1408,
  "NewhartSeries3::Newhart - 308 - The Fan.mp4": 1399,
  "NewhartSeries3::Newhart - 309 - Happy Trails To You.mp4": 1408,
  "NewhartSeries3::Newhart - 310 - Georgies Girl.mp4": 1395,
  "NewhartSeries3::Newhart - 311 - Pillow Fight.mp4": 1408,
  "NewhartSeries3::Newhart - 312 - Local Hero.mp4": 1396,
  "NewhartSeries3::Newhart - 313 - Dick Gets Larrys Goat.mp4": 1391,
  "NewhartSeries3::Newhart - 314 - Once I Had A Secret Love.mp4": 1409,
  "NewhartSeries3::Newhart - 315 - Lady In Wading.mp4": 1393,
  "NewhartSeries3::Newhart - 316 - Look Homeward Stephanie.mp4": 1407,
  "NewhartSeries3::Newhart - 317 - My Fair Larry.mp4": 1409,
  "NewhartSeries3::Newhart - 318 - Youre Nobody Til Somebody Hires You.mp4": 1409,
  "NewhartSeries3::Newhart - 319 - Out With The New Inn With The Old.mp4": 1408,
  "NewhartSeries3::Newhart - 320 - R.I.P. Off.mp4": 1342,
  "NewhartSeries3::Newhart - 321 - The Prodigal Darryl.mp4": 1407,
  "NewhartSeries3::Newhart - 322 - What Makes Dick Run.mp4": 1406,
  "NewhartSeries4::Newhart - 401 - Pirate Pete.mp4": 1335,
  "NewhartSeries4::Newhart - 402 - The Way We Ought To Be.mp4": 1399,
  "NewhartSeries4::Newhart - 403 - Summa Cum Larry.mp4": 1343,
  "NewhartSeries4::Newhart - 404 - Oh That Morocco.mp4": 1347,
  "NewhartSeries4::Newhart - 405 - Candidate Larry.mp4": 1391,
  "NewhartSeries4::Newhart - 406 - Locks Stocks & Noodlehead.mp4": 1404,
  "NewhartSeries4::Newhart - 407 - The Geezers In The Band.mp4": 1340,
  "NewhartSeries4::Newhart - 408 - The Shape Of Things.mp4": 1340,
  "NewhartSeries4::Newhart - 409 - Write To Privacy.mp4": 1330,
  "NewhartSeries4::Newhart - 410 - Still The Beavers.mp4": 1334,
  "NewhartSeries4::Newhart - 411 - Much Ado About Mitch.mp4": 1340,
  "NewhartSeries4::Newhart - 412 - Look Ma No Talent.mp4": 1340,
  "NewhartSeries4::Newhart - 413 - Larrys Dead Long Live Larry.mp4": 1332,
  "NewhartSeries4::Newhart - 414 - Stephanie Nightingale.mp4": 1342,
  "NewhartSeries4::Newhart - 415 - Stratford Horror Picture Show.mp4": 1340,
  "NewhartSeries4::Newhart - 416 - I Do Okay.mp4": 1339,
  "NewhartSeries4::Newhart - 417 - The Snowman Cometh.mp4": 1333,
  "NewhartSeries4::Newhart - 418 - Will The Real Dick Loudon.mp4": 1342,
  "NewhartSeries4::Newhart - 419 - He Aint Human Hes My Cousin.mp4": 1394,
  "NewhartSeries4::Newhart - 420 - Dwight SchmidlappIs Not A Quitter.mp4": 1341,
  "NewhartSeries4::Newhart - 421 - Torn Between Three Brothers.mp4": 1339,
  "NewhartSeries4::Newhart - 422 - Baby Im Your Handyman.mp4": 1336,
  "NewhartSeries4::Newhart - 423 - Replaceable You.mp4": 1401,
  "NewhartSeries4::Newhart - 424 - Pre-Nups.mp4": 1318,
  "NewhartSeries5::Newhart - 501 - Co-Hostess Twinkie.mp4": 1446,
  "NewhartSeries5::Newhart - 502 - Camp Stephanie.mp4": 1446,
  "NewhartSeries5::Newhart - 503 - Dick The Kid.mp4": 1447,
  "NewhartSeries5::Newhart - 504 - High Fidelity.mp4": 1443,
  "NewhartSeries5::Newhart - 505 - Desperately Desiring Susan 1.mp4": 1451,
  "NewhartSeries5::Newhart - 506 - Desperately Desiring Susan 2.mp4": 1472,
  "NewhartSeries5::Newhart - 507 - My Two And Only.mp4": 1446,
  "NewhartSeries5::Newhart - 508 - Thanksgiving For The Memories.mp4": 1450,
  "NewhartSeries5::Newhart - 509 - Utley Can You Spend A Dime.mp4": 1446,
  "NewhartSeries5::Newhart - 510 - Sweet And Sour Charity.mp4": 1318,
  "NewhartSeries5::Newhart - 511 - Everybody Ought To Have A Maid.mp4": 1452,
  "NewhartSeries5::Newhart - 512 - Saturday In New York With George.mp4": 1446,
  "NewhartSeries5::Newhart - 513 - Love Letters In The Mud.mp4": 1422,
  "NewhartSeries5::Newhart - 514 - First Of The Belles.mp4": 1450,
  "NewhartSeries5::Newhart - 515 - Its My Party And Ill Die If I Want To.mp4": 1445,
  "NewhartSeries5::Newhart - 516 - Chimes They Are A Changin.mp4": 1451,
  "NewhartSeries5::Newhart - 517 - Unfriendly Persuasion.mp4": 1451,
  "NewhartSeries5::Newhart - 518 - Jail Jail The Gangs All Here.mp4": 1443,
  "NewhartSeries5::Newhart - 519 - Dr Jekyll And Mr Loudon.mp4": 1450,
  "NewhartSeries5::Newhart - 520 - Fun With Dick And Joanna.mp4": 1318,
  "NewhartSeries5::Newhart - 521 - Night Moves.mp4": 1317,
  "NewhartSeries5::Newhart - 522 - Harris Ankles PIV for Web Post.mp4": 1319,
  "NewhartSeries5::Newhart - 523 - Good Bye And Good Riddance.mp4": 1319,
  "NewhartSeries5::Newhart - 524 - Much To Do Without Muffin.mp4": 1319,
  "NewhartSeries6::Newhart - 601 - Heres To You Mrs Loudon.mp4": 1317,
  "NewhartSeries6::Newhart - 602 - Prima Darryl.mp4": 1430,
  "NewhartSeries6::Newhart - 603 - Inn This Corner.mp4": 1429,
  "NewhartSeries6::Newhart - 604 - Me And My Gayle.mp4": 1430,
  "NewhartSeries6::Newhart - 605 - Reading Writing And Rating Points.mp4": 1317,
  "NewhartSeries6::Newhart - 606 - Vintage Stephanie.mp4": 1317,
  "NewhartSeries6::Newhart - 607 - Take Me To Your Loudon.mp4": 1430,
  "NewhartSeries6::Newhart - 608 - Till Depth Do Us Part 1.mp4": 1429,
  "NewhartSeries6::Newhart - 609 - Till Depth Do Us Part 2.mp4": 1451,
  "NewhartSeries6::Newhart - 610 - Telethon Man.mp4": 1430,
  "NewhartSeries6::Newhart - 611 - Laugh At My Wife Please.mp4": 1430,
  "NewhartSeries6::Newhart - 612 - Support Your Local Shifflet.mp4": 1430,
  "NewhartSeries6::Newhart - 613 - My Three Dads.mp4": 1432,
  "NewhartSeries6::Newhart - 614 - A Friendship That Will Last.mp4": 1429,
  "NewhartSeries6::Newhart - 615 - Presence Of Malice.mp4": 1426,
  "NewhartSeries6::Newhart - 616 - Would You Buy A Used Car.mp4": 1431,
  "NewhartSeries6::Newhart - 617 - The Buck Stops Here.mp4": 1430,
  "NewhartSeries6::Newhart - 618 - Attention WPIV Shoppers.mp4": 1426,
  "NewhartSeries6::Newhart - 619 - The Big Uneasy.mp4": 1431,
  "NewhartSeries6::Newhart - 620 - Draw Partner.mp4": 1424,
  "NewhartSeries6::Newhart - 621 - A Midseasons Night Dream.mp4": 1318,
  "NewhartSeries6::Newhart - 622 - Newsstruck.mp4": 1431,
  "NewhartSeries6::Newhart - 623 - The Gleeless Club.mp4": 1431,
  "NewhartSeries6::Newhart - 624 - Courtin Disaster.mp4": 1426,
  "NewhartSeries7::Newhart - 701 - Town Without Pity.mp4": 1435,
  "NewhartSeries7::Newhart - 702 - Apples Apples Apples.mp4": 1441,
  "NewhartSeries7::Newhart - 703 - This Bloods For You.mp4": 1441,
  "NewhartSeries7::Newhart - 704 - I Married Dick.mp4": 1440,
  "NewhartSeries7::Newhart - 705 - Goonstruck.mp4": 1435,
  "NewhartSeries7::Newhart - 706 - I Came I Saw I Sat.mp4": 1318,
  "NewhartSeries7::Newhart - 707 - Twelve Annoyed Men And Women.mp4": 1318,
  "NewhartSeries7::Newhart - 708 - Home For The Holidays.mp4": 1317,
  "NewhartSeries7::Newhart - 709 - Shoe Business Is My Life.mp4": 1319,
  "NewhartSeries7::Newhart - 710 - George And The Old Maid.mp4": 1315,
  "NewhartSeries7::Newhart - 711 - Hi, Society.mp4": 1443,
  "NewhartSeries7::Newhart - 712 - Cupcake On My Back.mp4": 1441,
  "NewhartSeries7::Newhart - 713 - Another Saturday Night.mp4": 1440,
  "NewhartSeries7::Newhart - 714 - The Nice Man Cometh.mp4": 1426,
  "NewhartSeries7::Newhart - 715 - One And A Half Million Dollar Man.mp4": 1441,
  "NewhartSeries7::Newhart - 716 - The Little Match Girl.mp4": 1319,
  "NewhartSeries7::Newhart - 717 - Buy Buy Blues.mp4": 1422,
  "NewhartSeries7::Newhart - 718 - Message from Michael.mp4": 1443,
  "NewhartSeries7::Newhart - 719 - Homes And Jo-Jo.mp4": 1436,
  "NewhartSeries7::Newhart - 720 - Georgie & Bess.mp4": 1440,
  "NewhartSeries7::Newhart - 721 - Murder At The Stratley.mp4": 1441,
  "NewhartSeries7::Newhart - 722 - Malling In Love Again.mp4": 1439,
  "NewhartSeries8::Newhart - 801 - Don't Worry Be Pregnant.mp4": 1349,
  "NewhartSeries8::Newhart - 802 - Get Dick.mp4": 1317,
  "NewhartSeries8::Newhart - 803 - Poetry and Pastries.mp4": 1344,
  "NewhartSeries8::Newhart - 804 - Utley Exposed.mp4": 1345,
  "NewhartSeries8::Newhart - 805 - Ramblin' Michael Harris.mp4": 1420,
  "NewhartSeries8::Newhart - 806 - Meet Michael Vanderkellen.mp4": 1396,
  "NewhartSeries8::Newhart - 807 - Good Lord Loudon.mp4": 1345,
  "NewhartSeries8::Newhart - 808 - Cupcake in a Cage.mp4": 1391,
  "NewhartSeries8::Newhart - 809 - Attack of the Killer Aunt.mp4": 1395,
  "NewhartSeries8::Newhart - 810 - I Like You, Butt.mp4": 1344,
  "NewhartSeries8::Newhart - 811 - Jumpin' George.mp4": 2454,
  "NewhartSeries8::Newhart - 812 - Lights, Camera, Contractions!.mp4": 1346,
  "NewhartSeries8::Newhart - 813 - Beauty and the Pest.mp4": 1396,
  "NewhartSeries8::Newhart - 814 - Good Neighbor Sam.mp4": 1345,
  "NewhartSeries8::Newhart - 815 - Child In Charge.mp4": 1347,
  "NewhartSeries8::Newhart - 816 - Seein' Double.mp4": 1318,
  "NewhartSeries8::Newhart - 817 - Born to Be Mild.mp4": 1395,
  "NewhartSeries8::Newhart - 818 - Daddy's Little Girl.mp4": 1345,
  "NewhartSeries8::Newhart - 819 - Georgie and Grace.mp4": 1345,
  "NewhartSeries8::Newhart - 820 - Handymania.mp4": 1317,
  "NewhartSeries8::Newhart - 821 - Dick and Tim.mp4": 1346,
  "NewhartSeries8::Newhart - 822 - Father Goose.mp4": 1345,
  "NewhartSeries8::Newhart - 823 - My Husband, My Peasant.mp4": 1346,
  "NewhartSeries8::Newhart - 824 - The Last Newhart.mp4": 1345,
},
};
