window.SHOW = {
  id: "Duckman",
  title: "Duckman",
  art: "Duckman.jpg",
  storageProgressKey: "duckman-progress",
  storageSettingsKey: "duckman-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['DuckmanComplete', "DUCKMAN - S01E01 - I, Duckman",
    "Duckman/Season 1/Duckman S01E01 I, Duckman (Pilot).mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E02 - T.V. or Not to Be",
    "Duckman/Season 1/Duckman S01E02 T.V. or Not to Be.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E03 - Gripes of Wrath",
    "Duckman/Season 1/Duckman S01E03 Gripes of Wrath.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E04 - Psyche",
    "Duckman/Season 1/Duckman S01E04 Psyche.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E05 - Gland of Opportunity",
    "Duckman/Season 1/Duckman S01E05 Gland of Opportunity.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E06 - Ride the High School",
    "Duckman/Season 1/Duckman S01E06 Ride the High School.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E07 - A Civil War",
    "Duckman/Season 1/Duckman S01E07 A Civil War.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E08 - Not So Easy Riders",
    "Duckman/Season 1/DuckmanS01E08 Not so Easy Riders.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E09 - It's the Thing of the Principal",
    "Duckman/Season 1/DuckmanS01E09 It's the Thing of the Principal.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E10 - Cellar Beware",
    "Duckman/Season 1/DuckmanS01E10 Cellar Beware.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E11 - American Dicks",
    "Duckman/Season 1/DuckmanS01E11 American Dicks.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E12 - About Face",
    "Duckman/Season 1/DuckmanS01E12 About Face.mkv"],
  ['DuckmanComplete', "DUCKMAN - S01E13 - Joking the Chicken",
    "Duckman/Season 1/DuckmanS01E13 Joking the Chicken.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E01 - Papa Oom M.O.W. M.O.W.",
    "Duckman/Season 2/DuckmanS02E01 Papa Oom M.O.W. M.O.W. .mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E02 - Married Alive",
    "Duckman/Season 2/DuckmanS02E02 Married Alive.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E03 - Days of Whining and Neurosis",
    "Duckman/Season 2/DuckmanS02E03 Days of Whining and Neurosis.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E04 - Inherit the Judgement: The Dope's Trial",
    "Duckman/Season 2/DuckmanS02E04 Inherit the Judgement - The Dope's Trial.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E05 - America the Beautiful",
    "Duckman/Season 2/DuckmanS02E05 America the Beautiful.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E06 - The Germ Turns",
    "Duckman/Season 2/DuckmanS02E06 The Germ Turns.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E07 - In the Nam of the Father",
    "Duckman/Season 2/DuckmanS02E07 In the Nam of the Father.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E08 - Research and Destroy",
    "Duckman/Season 2/DuckmanS02E08 Research and Destroy.mkv"],
  ['DuckmanComplete', "DUCKMAN - S02E09 - Clip Job",
    "Duckman/Season 2/DuckmanS02E09 Clip Job.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E01 - Noir Gang",
    "Duckman/Season 3/Duckman S03E01 Noir Gang.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E02 - Forbidden Fruit",
    "Duckman/Season 3/Duckman S03E02 Forbidden Fruit.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E03 - Grandma-ma's Flatulent Adventure",
    "Duckman/Season 3/Duckman S03E03 Grandma-ma's Flatulent Adventure.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E04 - Color of Naught",
    "Duckman/Season 3/Duckman S03E04 Color of Naught.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E05 - Sperms of Endearment",
    "Duckman/Season 3/Duckman S03E05 Sperms of Endearment.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E06 - A Room with a Bellevue",
    "Duckman/Season 3/Duckman S03E06 A Room with a Bellevue.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E07 - Apocalypse Not",
    "Duckman/Season 3/Duckman S03E07 Apocalypse Not.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E08 - Clear and Presidente Danger",
    "Duckman/Season 3/Duckman S03E08 Clear and Presidente Danger.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E09 - The Girls of Route Canal",
    "Duckman/Season 3/Duckman S03E09 The Girls of Route Canal.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E10 - The Mallardian Candidate",
    "Duckman/Season 3/Duckman S03E10 The Mallardian Candidate.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E11 - Pig Amok",
    "Duckman/Season 3/Duckman S03E11 Pig Amok.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E12 - The Once and Future Duck",
    "Duckman/Season 3/Duckman S03E12 The Once and Future Duck.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E13 - The One with Lisa Kudrow in a Small Role",
    "Duckman/Season 3/Duckman S03E13 The One with Lisa Kudrow in a Small Role.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E14 - Aged Heat",
    "Duckman/Season 3/Duckman S03E14 Aged Heat.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E15 - They Craved Duckman's Brain!",
    "Duckman/Season 3/Duckman S03E15 They Craved Duckman's Brain.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E16 - The Road to Dendron",
    "Duckman/Season 3/Duckman S03E16 The Road to Dendron.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E17 - Exile in Guyville",
    "Duckman/Season 3/Duckman S03E17 Exile in Guyville.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E18 - The Longest Weekend",
    "Duckman/Season 3/Duckman S03E18 The Longest Weekend.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E19 - The Amazing Colossal Duckman",
    "Duckman/Season 3/Duckman S03E19 The Amazing Colossal Duckman.mkv"],
  ['DuckmanComplete', "DUCKMAN - S03E20 - Cock Tales for Four",
    "Duckman/Season 3/Duckman S03E20 Cock Tales for Four.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E01 - Dammit, Hollywood",
    "Duckman/Season 4/Duckman S04E01 Damnit, Hollywood.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E02 - Coolio Runnings",
    "Duckman/Season 4/Duckman S04E02 Coolio Runnings.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E03 - Aged Heat 2: Women in Heat",
    "Duckman/Season 4/Duckman S04E03 Aged Heat 2 Women in Heat.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E04 - All About Elliott",
    "Duckman/Season 4/Duckman S04E04 All About Elliott.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E05 - From Brad to Worse",
    "Duckman/Season 4/Duckman S04E05 From Brad to Worse.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E06 - Bonfire of the Panties",
    "Duckman/Season 4/Duckman S04E06 Bonfire of Panties.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E07 - Role with It",
    "Duckman/Season 4/Duckman S04E07 Role With It.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E08 - Ajax & Ajaxer",
    "Duckman/Season 4/Duckman S04E08 Ajax & Ajaxer.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E09 - With Friends Like These",
    "Duckman/Season 4/Duckman S04E09 With Friends Like These.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E10 - A Trophied Duck",
    "Duckman/Season 4/Duckman S04E10 A Trophied Duck.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E11 - A Star Is Abhorred",
    "Duckman/Season 4/Duckman S04E11 A Star is Abhorred.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E12 - Bev Takes a Holiday",
    "Duckman/Season 4/Duckman S04E12 Bev Takes a Holiday.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E13 - Love! Anger! Kvetching!",
    "Duckman/Season 4/Duckman S04E13 Love! Anger! Kvetching!.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E14 - Haunted Society Plumbers",
    "Duckman/Season 4/Duckman S04E14 Haunted Society Plumbers.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E15 - Ebony, Baby",
    "Duckman/Season 4/Duckman S04E15 Ebony, Baby.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E16 - Vuuck, as in Duck",
    "Duckman/Season 4/Duckman S04E16 Vuuck, as in Duck.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E17 - Crime, Punishment, War, Peace, and the Idiot",
    "Duckman/Season 4/Duckman S04E17 Crime, Punishment, War, Peace, and the Idiot.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E18 - Kidney, Popsicle, and Nuts",
    "Duckman/Season 4/Duckman S04E18 Kidney, Popsicle and Nuts.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E19 - The Tami Show",
    "Duckman/Season 4/Duckman S04E19 The Tami Show.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E20 - My Feral Lady",
    "Duckman/Season 4/Duckman S04E20 My Feral Lady.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E21 - Westward, No!",
    "Duckman/Season 4/Duckman S04E21 Westward, No!.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E22 - Short, Plush and Deadly",
    "Duckman/Season 4/Duckman S04E22 Short, Plush and Deadly.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E23 - How to Suck in Business Without Really Trying",
    "Duckman/Season 4/Duckman S04E23 How to Suck in Business Without Really Trying.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E24 - You've Come a Wrong Way, Baby",
    "Duckman/Season 4/Duckman S04E24 You've Come a Wrong Way, Baby.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E25 - Hamlet 2: This Time It's Personal",
    "Duckman/Season 4/Duckman S04E25 Hamlet 2 This Time it's Personal.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E26 - Das Sub",
    "Duckman/Season 4/Duckman S04E26 Das Sub.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E27 - Where No Duckman Has Gone Before",
    "Duckman/Season 4/Duckman S04E27 Where No Duckman Has Gone Before.mkv"],
  ['DuckmanComplete', "DUCKMAN - S04E28 - Four Weddings Inconceivable",
    "Duckman/Season 4/Duckman S04E28 Four Weddings Inconceivable.mkv"],
],
  durations: {
  "DuckmanComplete::Duckman/Season 1/Duckman S01E01 I, Duckman (Pilot).mkv": 1362,
  "DuckmanComplete::Duckman/Season 1/Duckman S01E02 T.V. or Not to Be.mkv": 1362,
  "DuckmanComplete::Duckman/Season 1/Duckman S01E03 Gripes of Wrath.mkv": 1363,
  "DuckmanComplete::Duckman/Season 1/Duckman S01E04 Psyche.mkv": 1361,
  "DuckmanComplete::Duckman/Season 1/Duckman S01E05 Gland of Opportunity.mkv": 1364,
  "DuckmanComplete::Duckman/Season 1/Duckman S01E06 Ride the High School.mkv": 1365,
  "DuckmanComplete::Duckman/Season 1/Duckman S01E07 A Civil War.mkv": 1345,
  "DuckmanComplete::Duckman/Season 1/DuckmanS01E08 Not so Easy Riders.mkv": 1338,
  "DuckmanComplete::Duckman/Season 1/DuckmanS01E09 It's the Thing of the Principal.mkv": 1363,
  "DuckmanComplete::Duckman/Season 1/DuckmanS01E10 Cellar Beware.mkv": 1352,
  "DuckmanComplete::Duckman/Season 1/DuckmanS01E11 American Dicks.mkv": 1362,
  "DuckmanComplete::Duckman/Season 1/DuckmanS01E12 About Face.mkv": 1364,
  "DuckmanComplete::Duckman/Season 1/DuckmanS01E13 Joking the Chicken.mkv": 1362,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E01 Papa Oom M.O.W. M.O.W. .mkv": 1353,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E02 Married Alive.mkv": 1362,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E03 Days of Whining and Neurosis.mkv": 1361,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E04 Inherit the Judgement - The Dope's Trial.mkv": 1362,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E05 America the Beautiful.mkv": 1362,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E06 The Germ Turns.mkv": 1361,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E07 In the Nam of the Father.mkv": 1361,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E08 Research and Destroy.mkv": 1361,
  "DuckmanComplete::Duckman/Season 2/DuckmanS02E09 Clip Job.mkv": 1367,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E01 Noir Gang.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E02 Forbidden Fruit.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E03 Grandma-ma's Flatulent Adventure.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E04 Color of Naught.mkv": 1361,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E05 Sperms of Endearment.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E06 A Room with a Bellevue.mkv": 1363,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E07 Apocalypse Not.mkv": 1363,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E08 Clear and Presidente Danger.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E09 The Girls of Route Canal.mkv": 1363,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E10 The Mallardian Candidate.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E11 Pig Amok.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E12 The Once and Future Duck.mkv": 1363,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E13 The One with Lisa Kudrow in a Small Role.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E14 Aged Heat.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E15 They Craved Duckman's Brain.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E16 The Road to Dendron.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E17 Exile in Guyville.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E18 The Longest Weekend.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E19 The Amazing Colossal Duckman.mkv": 1362,
  "DuckmanComplete::Duckman/Season 3/Duckman S03E20 Cock Tales for Four.mkv": 1362,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E01 Damnit, Hollywood.mkv": 1362,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E02 Coolio Runnings.mkv": 1362,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E03 Aged Heat 2 Women in Heat.mkv": 1363,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E04 All About Elliott.mkv": 1362,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E05 From Brad to Worse.mkv": 1364,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E06 Bonfire of Panties.mkv": 1362,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E07 Role With It.mkv": 1304,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E08 Ajax & Ajaxer.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E09 With Friends Like These.mkv": 1333,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E10 A Trophied Duck.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E11 A Star is Abhorred.mkv": 1331,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E12 Bev Takes a Holiday.mkv": 1328,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E13 Love! Anger! Kvetching!.mkv": 1325,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E14 Haunted Society Plumbers.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E15 Ebony, Baby.mkv": 1321,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E16 Vuuck, as in Duck.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E17 Crime, Punishment, War, Peace, and the Idiot.mkv": 1331,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E18 Kidney, Popsicle and Nuts.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E19 The Tami Show.mkv": 1330,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E20 My Feral Lady.mkv": 1330,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E21 Westward, No!.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E22 Short, Plush and Deadly.mkv": 1306,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E23 How to Suck in Business Without Really Trying.mkv": 1332,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E24 You've Come a Wrong Way, Baby.mkv": 1331,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E25 Hamlet 2 This Time it's Personal.mkv": 1331,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E26 Das Sub.mkv": 1333,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E27 Where No Duckman Has Gone Before.mkv": 1308,
  "DuckmanComplete::Duckman/Season 4/Duckman S04E28 Four Weddings Inconceivable.mkv": 1332,
},
};
